Repository makeplane/plane, pull requests merged in 2023-12, with the labels that each got.

#2953 chore: removed django settings module
  ENV_SETUP.md
  deploy/coolify/coolify-docker-compose.yml
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: 🐛bug, ⚙️backend

#2959 fix: upgrading space application to nextjs 14
  space/components/accounts/email-reset-password-form.tsx
  space/components/issues/filters-render/state/filter-state-block.tsx
  space/components/issues/navbar/index.tsx
  space/components/issues/navbar/issue-board-view.tsx
  space/components/issues/navbar/issue-view.tsx
  space/components/issues/navbar/search.tsx
  space/components/issues/peek-overview/full-screen-peek-view.tsx
  space/components/issues/peek-overview/issue-activity.tsx
  space/components/issues/peek-overview/layout.tsx
  space/components/ui/tooltip.tsx
  space/components/views/login.tsx
  space/components/views/project-details.tsx
  space/lib/mobx/store-init.tsx
  space/package.json
  space/pages/_app.tsx
  space/pages/_document.tsx
  yarn.lock
Labels: 🌐frontend, 🌟improvement

#2956 [FED-868] fix: create view modal overlapping
  web/components/command-palette/command-pallette.tsx
  web/components/headers/project-views.tsx
  web/store/command-palette.store.ts
Labels: 🐛bug, 🌐frontend

#2960 [FED-862] fix: create issue modal improvement
  web/components/issues/select/cycle.tsx
  web/components/issues/select/module.tsx
Labels: 🌐frontend

#2963 [FED-924] chore: profile issue display filters content updated
  web/constants/issue.ts
Labels: 🌐frontend

#2964 chore: workspace global issues
  web/components/headers/global-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/index.ts
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
  web/components/issues/issue-layouts/roots/index.ts
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/onboarding/onboarding-sidebar.tsx
  web/components/page-views/signin.tsx
  web/components/workspace/views/header.tsx
  web/constants/issue.ts
  web/layouts/settings-layout/profile/sidebar.tsx
  web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
  web/pages/[workspaceSlug]/workspace-views/all-issues.tsx
  web/pages/[workspaceSlug]/workspace-views/assigned.tsx
  web/pages/[workspaceSlug]/workspace-views/created.tsx
  web/pages/[workspaceSlug]/workspace-views/subscribed.tsx
  web/pages/accounts/password.tsx
  web/services/workspace.service.ts
  web/store/global-view/global_view_issues.store.ts
  web/store/issues/global/filter.store.ts
  web/store/issues/global/issue.store.ts
  web/store/issues/profile/filter.store.ts
Labels: 🌐frontend, 🧹chore

#2958 fix: create workspace form validation
  web/components/account/sign-in-forms/unique-code.tsx
  web/components/onboarding/join-workspaces.tsx
  web/components/onboarding/workspace.tsx
Labels: 🐛bug, 🌐frontend

#2962 style: updated the UI of the instance admin setup and the sign in workflow
  web/components/account/sign-in-forms/create-password.tsx
  web/components/account/sign-in-forms/email-form.tsx
  web/components/account/sign-in-forms/optional-set-password.tsx
  web/components/account/sign-in-forms/password.tsx
  web/components/account/sign-in-forms/root.tsx
  web/components/account/sign-in-forms/set-password-link.tsx
  web/components/account/sign-in-forms/unique-code.tsx
  web/components/common/latest-feature-block.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/inbox/issue-card.tsx
  web/components/instance/help-section.tsx
  web/components/instance/instance-admin-restriction.tsx
  web/components/instance/not-ready-view.tsx
  web/components/instance/setup-done-view.tsx
  web/components/instance/setup-form/email-code-form.tsx
  web/components/instance/setup-form/email-form.tsx
  web/components/instance/setup-form/password-form.tsx
  web/components/instance/setup-form/root.tsx
  web/components/instance/setup-view.tsx
  web/components/instance/sidebar-menu.tsx
  web/components/issues/attachment/attachments.tsx
  web/components/issues/main-content.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/page-views/signin.tsx
  web/components/pages/pages-list/list-item.tsx
  web/components/views/view-list-item.tsx
  web/components/workspace/views/default-view-list-item.tsx
  web/components/workspace/views/view-list-item.tsx
  web/layouts/admin-layout/layout.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/layouts/instance-layout/index.tsx
  web/layouts/settings-layout/profile/sidebar.tsx
  web/layouts/settings-layout/project/sidebar.tsx
  web/pages/accounts/password.tsx
  web/public/onboarding/onboarding-pages.svg
  web/services/auth.service.ts
  web/store/instance/instance.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2966 fix: corrected rendering of workspace-level labels, members, and states in project view
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
Labels: 🌐frontend

#2968 fix: V3 release blocker bugs
  web/components/issues/form.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/views/modal.tsx
  web/store/command-palette.store.ts
  web/store/issues/project-issues/base-issue.store.ts
Labels: 🌐frontend, 🌐web

#2974 fix: global issues properties updation issue resolved
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
Labels: 🌐frontend

#2973 chore: update instance admin sign in service
  web/services/auth.service.ts
Labels: 🐛bug, 🌐frontend

#2972 fix: sub display filter params for fetching issues
  web/store/issues/global/filter.store.ts
  web/store/issues/profile/filter.store.ts
  web/store/issues/project-issues/archived/filter.store.ts
  web/store/issues/project-issues/cycle/filter.store.ts
  web/store/issues/project-issues/draft/filter.store.ts
  web/store/issues/project-issues/module/filter.store.ts
  web/store/issues/project-issues/project-view/filter.store.ts
  web/store/issues/project-issues/project/filter.store.ts
  web/store/issues/project-issues/utils.ts
Labels: 🌐frontend, 🌐web

#2969 refactor: custom hook for sign in redirection
  web/components/account/sign-in-forms/email-form.tsx
  web/components/account/sign-in-forms/password.tsx
  web/components/account/sign-in-forms/root.tsx
  web/components/account/sign-in-forms/set-password-link.tsx
  web/components/page-views/signin.tsx
  web/hooks/use-sign-in-redirection.ts
  web/pages/accounts/password.tsx
  web/public/onboarding/onboarding-pages.svg
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#2978 fix: Permission levels for project settings
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/inbox/actions-header.tsx
  web/components/inbox/main-content.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/main-content.tsx
  web/components/issues/sidebar.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/modules/sidebar.tsx
  web/components/pages/pages-list/list-item.tsx
  web/components/project/member-list-item.tsx
  web/components/project/project-settings-member-defaults.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/project/settings/features-list.tsx
  web/helpers/user.helper.ts
  web/layouts/settings-layout/project/layout.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/store/inbox/inbox_filters.store.ts
Labels: 🌐frontend, 🌐web

#2970 chore: html validation
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/serializers/state.py
  apiserver/plane/api/views/state.py
  apiserver/plane/app/views/state.py
  apiserver/plane/bgtasks/webhook_task.py
  apiserver/plane/utils/issue_filters.py
  apiserver/requirements/base.txt
Labels: ⚙️backend, 🌟improvement

#2986 [FED-790] chore: module and cycle sidebar date mutation fix
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
Labels: 🌐frontend, 🌟improvement

#2982 chore: draft issue layout and permission validation
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/store/issues/project-issues/draft/issue.store.ts
Labels: 🐛bug, 🌐frontend

#2981 fix: sentry error
  apiserver/plane/settings/common.py
Labels: ⚙️backend, 🐳docker

#2976 fix: leave project mutation
  web/components/project/member-list-item.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/settings/members-list-item.tsx
Labels: 🌐frontend, 🌟improvement

#2985 chore: issue update status in peekview & detail
  web/components/inbox/main-content.tsx
  web/components/issues/description-form.tsx
  web/components/issues/index.ts
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/components/issues/issue-update-status.tsx
  web/components/issues/main-content.tsx
  web/components/issues/sidebar.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2988 style: image picker, spreadsheet view title, icons
  web/components/core/image-picker-popover.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/sidebar.tsx
  web/constants/spreadsheet.ts
Labels: 🎨UI / UX

#2965 chore: email invite accept validation
  web/components/onboarding/invitations.tsx
  web/pages/invitations/index.tsx
  web/pages/onboarding/index.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#2980 chore: space ui component revamp and bug fixes
  space/components/accounts/email-code-form.tsx
  space/components/accounts/email-password-form.tsx
  space/components/accounts/email-reset-password-form.tsx
  space/components/accounts/onboarding-form.tsx
  space/components/issues/navbar/index.tsx
  space/components/issues/peek-overview/comment/comment-reactions.tsx
  space/components/issues/peek-overview/full-screen-peek-view.tsx
  space/components/issues/peek-overview/issue-activity.tsx
  space/components/issues/peek-overview/issue-emoji-reactions.tsx
  space/components/issues/peek-overview/issue-vote-reactions.tsx
  space/components/issues/peek-overview/side-peek-view.tsx
  space/components/ui/index.ts
  space/components/ui/input.tsx
  space/components/ui/loader.tsx
  space/components/ui/primary-button.tsx
  space/components/ui/secondary-button.tsx
  space/components/ui/tooltip.tsx
  web/components/profile/navbar.tsx
Labels: 🌐frontend, 🎨UI / UX

#2991 chore: implemented filters in plane deploy
  space/components/issues/board-views/kanban/block.tsx
  space/components/issues/board-views/kanban/header.tsx
  space/components/issues/board-views/kanban/index.tsx
  space/components/issues/filters-render/index.tsx
  space/components/issues/filters-render/label/filter-label-block.tsx
  space/components/issues/filters-render/label/index.tsx
  space/components/issues/filters-render/priority/filter-priority-block.tsx
  space/components/issues/filters-render/priority/index.tsx
  space/components/issues/filters-render/state/filter-state-block.tsx
  space/components/issues/filters-render/state/index.tsx
  space/components/issues/filters/applied-filters/filters-list.tsx
  space/components/issues/filters/applied-filters/label.tsx
  space/components/issues/filters/applied-filters/priority.tsx
  space/components/issues/filters/applied-filters/root.tsx
  space/components/issues/filters/applied-filters/state.tsx
  space/components/issues/filters/helpers/dropdown.tsx
  space/components/issues/filters/helpers/filter-header.tsx
  space/components/issues/filters/helpers/filter-option.tsx
  space/components/issues/filters/helpers/index.ts
  space/components/issues/filters/index.ts
  space/components/issues/filters/labels.tsx
  space/components/issues/filters/priority.tsx
  space/components/issues/filters/root.tsx
  space/components/issues/filters/selection.tsx
  space/components/issues/filters/state.tsx
  space/components/issues/navbar/index.tsx
  space/components/issues/navbar/issue-board-view.tsx
  space/components/issues/navbar/issue-filter.tsx
  space/components/views/project-details.tsx
  space/layouts/project-layout.tsx
  space/store/issue.ts
  space/store/issues/base-issue-filter.store.ts
  space/store/issues/helpers.ts
  space/store/issues/issue-filters.store.ts
  space/store/issues/types.ts
  space/store/project.ts
  space/store/root.ts
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/modal.tsx
  web/components/profile/profile-issues.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/store/issues/base-issue-kanban-helper.store.ts
  web/store/issues/profile/issue.store.ts
Labels: 🌐frontend, 🧹chore

#2995 fix: bugs related to issues
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/modal.tsx
  web/components/issues/sidebar-select/cycle.tsx
  web/components/issues/sidebar-select/module.tsx
  web/components/profile/profile-issues.tsx
  web/store/issues/profile/issue.store.ts
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
Labels: 🌐frontend, 🌐web

#2996 fix: Image Resizing and PR
  packages/editor/core/src/index.ts
  packages/editor/core/src/ui/extensions/image/image-resize.tsx
  packages/editor/core/src/ui/hooks/use-editor.tsx
  packages/editor/core/src/ui/hooks/use-read-only-editor.tsx
  packages/editor/core/src/ui/hooks/useInitializedContent.tsx
  packages/editor/core/src/ui/index.tsx
  packages/editor/extensions/src/extensions/drag-drop.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  space/styles/editor.css
  web/components/inbox/main-content.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/styles/editor.css
Labels: 🐛bug, ✍️editor

#2992 fix: bug fixes and improvement
  web/components/headers/project-settings.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/modules/sidebar.tsx
  web/components/ui/datepicker.tsx
  web/layouts/settings-layout/project/layout.tsx
Labels: 🐛bug, 🌐frontend

#3002 fix: removed labels in the filters and handled redirection issue from peek overview and ui changes
  space/components/issues/board-views/kanban/block.tsx
  space/components/issues/board-views/list/block.tsx
  space/components/issues/filters/applied-filters/filters-list.tsx
  space/components/issues/filters/helpers/dropdown.tsx
  space/components/issues/filters/root.tsx
  space/components/issues/filters/selection.tsx
  space/components/issues/navbar/index.tsx
  space/components/issues/peek-overview/layout.tsx
Labels: 🌐frontend

#3004 dev: modified docker image repo names
  .github/workflows/build-branch.yml
  .github/workflows/update-docker-images.yml
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install-private.sh
Labels: 🚀CI/CD

#1452 feat: add CodeQL workflow
  .github/workflows/codeql.yml
Labels: 🔄workflows

#2989 chore: posthog event for workspace invite
  apiserver/plane/app/views/workspace.py
  apiserver/plane/bgtasks/event_tracking_task.py
  web/components/headers/workspace-dashboard.tsx
  web/components/inbox/issue-activity.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/inbox/modals/delete-issue-modal.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/main-content.tsx
  web/components/issues/modal.tsx
  web/components/modules/delete-module-modal.tsx
  web/components/modules/modal.tsx
  web/components/onboarding/invitations.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/create-update-page-modal.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/delete-project-modal.tsx
  web/components/project/form.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/workspace/create-workspace-form.tsx
  web/components/workspace/delete-workspace-modal.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/pages/invitations/index.tsx
  web/pages/onboarding/index.tsx
  web/store/event-tracker.store.ts
Labels: 🌐frontend, ⚙️backend

#3009 dev: remove unused packages
  Dockerfile
  apiserver/Dockerfile.api
  apiserver/file.txt
  apiserver/gunicorn.config.py
  apiserver/plane/settings/common.py
  apiserver/requirements/base.txt
  apiserver/requirements/production.txt
Labels: 📦dependencies, ⚙️backend

#3000 dev: management command to reset user password
  apiserver/plane/db/management/commands/reset_password.py
Labels: ⚙️backend

#3010 fix: bug fixes
  web/components/headers/project-views.tsx
  web/components/issues/select/label.tsx
  web/components/issues/sidebar-select/label.tsx
Labels: 🐛bug, 🌐frontend

#3008 chore: plane logo without text
  space/components/views/login.tsx
  space/pages/accounts/password.tsx
  space/public/plane-logos/blue-without-text-new.png
Labels: 🌐frontend

#3003 fix: custom analytic grouped bar tooltip value as ID
  web/components/analytics/custom-analytics/graph/custom-tooltip.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2987 fix: kanban board block's menu & drop delete.
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/list-view-types.d.ts
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/store/issues/base-issue-kanban-helper.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3007 chore: remove unused fields from the god mode
  web/components/instance/email-form.tsx
  web/pages/god-mode/authorization.tsx
Labels: 🌐frontend, 🧹chore

#3011 chore: Page auth and other improvements
  apiserver/plane/api/views/inbox.py
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/page.py
  apiserver/plane/app/views/project.py
Labels: ⚙️backend, 🌟improvement

#3012 fix: issue layouts bugs and ui fixes
  web/components/headers/project-view-issues.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/save-filter-view.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/root.tsx
Labels: 🌐frontend

#3013 fix: frontend build warnings
  space/components/issues/filters/applied-filters/filters-list.tsx
  space/components/issues/filters/helpers/dropdown.tsx
  space/components/issues/filters/selection.tsx
  space/components/issues/navbar/index.tsx
  space/lib/mobx/store-init.tsx
  web/components/command-palette/command-pallette.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/description-form.tsx
  web/components/issues/form.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/extra-options.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/list/headers/empty-group.tsx
  web/components/issues/issue-layouts/list/headers/priority.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/quick-add-issue-form.tsx
  web/components/issues/modal.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/onboarding/index.tsx
Labels: 🌐frontend, 🛠️refactor

#3016 fix: spreadsheet layout bugs
  web/components/issues/issue-layouts/empty-states/project.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/view-select/due-date.tsx
  web/components/issues/view-select/start-date.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2920 [ FEATURE ] New Issue Widget for displaying issues inside `document-editor`
  packages/editor/core/src/ui/hooks/use-editor.tsx
  packages/editor/core/src/ui/hooks/use-read-only-editor.tsx
  packages/editor/document-editor/package.json
  packages/editor/document-editor/src/ui/components/content-browser.tsx
  packages/editor/document-editor/src/ui/components/editor-header.tsx
  packages/editor/document-editor/src/ui/components/heading-component.tsx
  packages/editor/document-editor/src/ui/components/info-popover.tsx
  packages/editor/document-editor/src/ui/components/page-renderer.tsx
  packages/editor/document-editor/src/ui/components/vertical-dropdown-menu.tsx
  packages/editor/document-editor/src/ui/extensions/index.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedSuggestionList/index.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedSuggestionList/issue-suggestion-extension.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedSuggestionList/issue-suggestion-items.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedSuggestionList/issue-suggestion-renderer.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedWidget/index.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedWidget/issue-widget-card.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedWidget/issue-widget-node.tsx
  packages/editor/document-editor/src/ui/extensions/widgets/IssueEmbedWidget/types.ts
  packages/editor/document-editor/src/ui/hooks/use-editor-markings.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/document-editor/src/ui/readonly/index.tsx
  packages/editor/document-editor/src/ui/utils/menu-options.ts
  packages/editor/extensions/src/extensions/slash-commands.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  packages/editor/types/package.json
  packages/editor/types/src/index.ts
  packages/editor/types/src/types/slash-commands-suggestion.ts
  web/components/inbox/issue-activity.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/services/page.service.ts
  yarn.lock
Labels: ✨feature, ✍️editor, pages

#3017 Chore: Minify build for plane packages
  packages/editor/core/package.json
  packages/editor/document-editor/package.json
  packages/editor/extensions/package.json
  packages/editor/lite-text-editor/package.json
  packages/editor/rich-text-editor/package.json
  packages/editor/types/package.json
  packages/ui/package.json
Labels: 🌐frontend

#3015 dev: instance refactor
  apiserver/bin/takeoff
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/urls/workspace.py
  apiserver/plane/app/views/auth_extended.py
  apiserver/plane/app/views/authentication.py
  apiserver/plane/app/views/config.py
  apiserver/plane/app/views/external.py
  apiserver/plane/app/views/oauth.py
  apiserver/plane/app/views/workspace.py
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/event_tracking_task.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/magic_link_code_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
  apiserver/plane/celery.py
  apiserver/plane/license/bgtasks/instance_verification_task.py
  apiserver/plane/license/management/commands/register_instance.py
  apiserver/plane/license/utils/instance_value.py
  apiserver/plane/settings/common.py
  web/components/workspace/settings/members-list-item.tsx
  web/services/workspace.service.ts
  web/store/workspace/workspace-member.store.ts
Labels: ⚙️backend, 🧹chore

#3021 chore: public images
  .github/workflows/build-branch.yml
  deploy/selfhost/docker-compose.yml
Labels: 🐳docker

#3001 refactor: issue peek overview
  web/components/inbox/issue-activity.tsx
  web/components/inbox/main-content.tsx
  web/components/issues/activity.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/roots/module-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/list/roots/project-root.tsx
  web/components/issues/issue-layouts/list/roots/project-view-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/index.ts
  web/components/issues/issue-reaction.tsx
  web/components/issues/main-content.tsx
  web/components/issues/peek-overview/activity/card.tsx
  web/components/issues/peek-overview/activity/comment-card.tsx
  web/components/issues/peek-overview/activity/comment-editor.tsx
  web/components/issues/peek-overview/activity/comment-reaction.tsx
  web/components/issues/peek-overview/activity/index.ts
  web/components/issues/peek-overview/activity/view.tsx
  web/components/issues/peek-overview/index.ts
  web/components/issues/peek-overview/issue-detail.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/peek-overview/reactions/index.ts
  web/components/issues/peek-overview/reactions/preview.tsx
  web/components/issues/peek-overview/reactions/root.tsx
  web/components/issues/peek-overview/reactions/selector.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/services/issue/issue_comment.service.ts
  web/services/issue/issue_reaction.service.ts
  web/store/archived-issues/issue_detail.store.ts
  web/store/event-tracker.store.ts
  web/store/issue/issue_detail.store.ts
  web/types/issues.d.ts
  web/types/reaction.d.ts
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#3034 [FED-1116] bug: cycle and module change not working from the peek overview
  web/components/issues/peek-overview/properties.tsx
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3037 [FED-1116] bug: cycle and module change not working from the peek overview
  web/components/issues/peek-overview/properties.tsx
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3038 chore: release version update
  apiserver/package.json
  package.json
  packages/editor/core/package.json
  packages/editor/document-editor/package.json
  packages/editor/extensions/package.json
  packages/editor/lite-text-editor/package.json
  packages/editor/rich-text-editor/package.json
  packages/editor/types/package.json
  packages/eslint-config-custom/package.json
  packages/tailwind-config-custom/package.json
  packages/tsconfig/package.json
  packages/ui/package.json
  space/package.json
  web/package.json
Labels: 🧹chore

#3042 fix: handled undefined issue_id in list layout
  web/components/issues/issue-layouts/list/blocks-list.tsx
Labels: 🌐frontend, 🧹chore

#3040 [REGRESSION]: peek overview rerendering on typing fixed
  web/components/issues/description-form.tsx
  web/components/issues/peek-overview/issue-detail.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🌐frontend

#3059 chore: configurations
  ENV_SETUP.md
  apiserver/plane/app/views/oauth.py
  apiserver/plane/license/utils/encryption.py
  deploy/coolify/coolify-docker-compose.yml
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
  space/.env.example
  turbo.json
  web/.env.example
Labels: 🧹chore, ⚙️config changes

#3060 chore: error handling for user permission while issue drag & drop
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/roots/module-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/store/issues/base-issue-calendar-helper.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3062 fix: oauth configuration check
  apiserver/plane/app/views/oauth.py
Labels: 🐛bug, ⚙️backend

#3063 fix: issue with GPT assistant response not updating on new requests.
  web/components/core/modals/gpt-assistant-modal.tsx
Labels: 🐛bug, 🌐frontend

#3064 fix: spreadsheet layout sub issues overlapping
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
Labels: 🐛bug, 🎨UI / UX

#3066 chore: user permission related fix
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/pages/pages-list/list-item.tsx
Labels: 🐛bug, 🌐frontend

#3067 chore: access restriction for lower roles
  web/components/cycles/modal.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/modal.tsx
  web/components/modules/modal.tsx
  web/components/pages/create-update-page-modal.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3068 chore: profile setting bug fixes
  web/pages/profile/activity.tsx
  web/pages/profile/change-password.tsx
Labels: 🐛bug, 🌐frontend

#3069 fix: disable label combining for labels inside a group
  web/components/labels/project-setting-label-group.tsx
  web/components/labels/project-setting-label-list.tsx
Labels: 🐛bug

#3081 fix: issue with clear filter option not working for filter groups in create view modal.
  web/components/views/form.tsx
Labels: 🐛bug, 🌐frontend

#3080 fix: spreadsheet layout alignment
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
Labels: 🌐frontend, 🎨UI / UX

#3079 fix: delete issue mutation & toast
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/pages/profile/activity.tsx
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
  web/store/issues/project-issues/project/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3070 fix: pre-fill cycle and module details when editing an issue
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
Labels: 🐛bug, 🌐frontend

#3071 chore: set an expiry of 30 days for the access and refresh tokens
  web/services/api.service.ts
Labels: 🌐frontend, 🌟improvement

#3072 chore: issue link mobx integration
  web/components/core/modals/link-modal.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sidebar.tsx
  web/services/issue/issue.service.ts
  web/services/module.service.ts
  web/store/issue/issue_detail.store.ts
  web/store/module/modules.store.ts
Labels: 🌐frontend, 🌟improvement

#3075 fix: gantt issues not getting updated
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
Labels: 🐛bug, 🌐frontend

#3076 style: cycle and module sidebar improvement
  web/components/cycles/sidebar.tsx
  web/components/issues/attachment/attachment-upload.tsx
  web/components/modules/sidebar.tsx
Labels: 🌐frontend, 🎨UI / UX

#3082 [FED-1185] fix: analytics modal's size not changing when switching between modes
  web/components/analytics/project-modal/modal.tsx
Labels: 🐛bug, 🌐frontend

#3085 fix: debug tool bar import
  apiserver/plane/urls.py
Labels: 🐛bug, ⚙️backend

#3091 chore: guest and viewer can leave project
  apiserver/plane/app/views/project.py
  web/components/project/member-list-item.tsx
Labels: 🐛bug, 🌐frontend, ⚙️backend

#3086 chore: issue layout quick add issue button permission validation
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
Labels: 🌐frontend, 🌟improvement

#3096 chore: update self hosted sign in form cta in the web and space apps
  space/components/accounts/sign-in-forms/self-hosted-sign-in.tsx
  web/components/account/sign-in-forms/self-hosted-sign-in.tsx
Labels: 🌐frontend

#3119 chore: analytics permission validation added
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/workspace/sidebar-menu.tsx
  web/components/workspace/sidebar-quick-action.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3117 chore: issue details related bug fixes and improvement
  web/components/inbox/main-content.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/main-content.tsx
  web/components/issues/sidebar-select/parent.tsx
  web/components/issues/sub-issues/properties.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3111 chore: calendar layout improvement
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
Labels: 🌐frontend, 🌟improvement

#3107 chore: image file update, icon consistency, bug fixes and code refactor
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/modules/sidebar.tsx
  web/components/onboarding/user-details.tsx
  web/components/workspace/views/default-view-list-item.tsx
  web/pages/profile/activity.tsx
  web/public/instance-not-ready.svg
  web/public/instance-not-ready.webp
  web/public/onboarding/cycles.svg
  web/public/onboarding/cycles.webp
  web/public/onboarding/issues.svg
  web/public/onboarding/issues.webp
  web/public/onboarding/modules.svg
  web/public/onboarding/modules.webp
  web/public/onboarding/onboarding-issues.svg
  web/public/onboarding/onboarding-issues.webp
  web/public/onboarding/pages.svg
  web/public/onboarding/pages.webp
  web/public/onboarding/sign-in.svg
  web/public/onboarding/sign-in.webp
  web/public/onboarding/views.svg
  web/public/onboarding/views.webp
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3098 chore: issue sidebar and project view improvement and validation
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/issues/sidebar-select/assignee.tsx
  web/components/issues/sidebar.tsx
  web/components/views/view-list-item.tsx
Labels: 🌐frontend, 🌟improvement

#3095 chore: cycle and module sidebar validation
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
Labels: 🌐frontend, 🌟improvement

#3094 chore: empty state action button validation
  web/components/issues/issue-layouts/empty-states/project.tsx
  web/components/modules/modules-list-view.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/list-view.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/components/project/card-list.tsx
  web/components/views/views-list.tsx
  web/pages/[workspaceSlug]/analytics.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🌐frontend, 🌟improvement

#3088 fix: cycle delete & active cycle loading
  web/components/cycles/active-cycle-details.tsx
  web/store/cycle/cycles.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3110 fix: spreadsheet layout sub-issues property update
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/hooks/use-sub-issue.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3128 fix: build error
  web/components/headers/project-view-issues.tsx
Labels: 🧹chore

#3114 chore: resolved the email-use-tls error
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/magic_link_code_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
Labels: 🐛bug, ⚙️backend, 🐳docker

#3112 chore: workspace project reinvite
  apiserver/plane/app/views/project.py
  apiserver/plane/app/views/workspace.py
Labels: 🐛bug, ⚙️backend

#3087 chore: project member list
  apiserver/plane/app/views/project.py
Labels: ⚙️backend, 🌟improvement

#3105 fix: environment file missing for space
  CONTRIBUTING.md
  apiserver/Dockerfile.dev
  apiserver/bin/takeoff.local
  docker-compose-local.yml
  nginx/Dockerfile.dev
  nginx/nginx-single-docker-image.conf
  nginx/nginx.conf.dev
  setup.sh
  space/Dockerfile.dev
  web/Dockerfile.dev
Labels: 🐛bug, 🐳docker

#3127 fix: cycle & module sidebar date range picker
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar-select/select-members.tsx
  web/components/modules/sidebar.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3126 chore: `add new or existing issues` validation for guest & viewers in cycles and modules empty state.
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
Labels: 🐛bug, 🌐frontend

#3130 chore: state ordering sequence in kanban and list layout
  web/constants/project.ts
  web/helpers/state.helper.ts
  web/store/project/project-state.store.ts
Labels: 🌐frontend, 🧹chore

#3113 chore: filter edit operation in views is disabled for lower roles
  web/components/headers/project-view-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/label.tsx
  web/components/issues/issue-layouts/filters/applied-filters/members.tsx
  web/components/issues/issue-layouts/filters/applied-filters/priority.tsx
  web/components/issues/issue-layouts/filters/applied-filters/project.tsx
  web/components/issues/issue-layouts/filters/applied-filters/state.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/views/modal.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3133 chore: sidebar quick action improvement
  web/components/workspace/sidebar-quick-action.tsx
Labels: 🌐frontend, 🎨UI / UX

#3135 fix: remove get requests from the catch block
  web/constants/swr-config.ts
  web/lib/app-provider.tsx
  web/store/issues/project-issues/cycle/filter.store.ts
  web/store/issues/project-issues/module/filter.store.ts
  web/store/issues/project-issues/project-view/filter.store.ts
Labels: 🐛bug, 🌐frontend

#3147 chore: link modal validation
  web/components/core/modals/link-modal.tsx
Labels: 🌐frontend, 🌟improvement

#3141 chore: priority sorting order
  web/constants/issue.ts
Labels: 🌐frontend, 🧹chore

#3092 feat: workspace and project members endpoint
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/urls/workspace.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/project.py
  apiserver/plane/app/views/workspace.py
Labels: ⚙️backend, 🌟improvement

#3163 fix: unnecessary overflow in the profile settings layout
  web/pages/profile/activity.tsx
  web/pages/profile/change-password.tsx
  web/pages/profile/index.tsx
  web/pages/profile/preferences.tsx
Labels: 🌐frontend, 🎨UI / UX

#3131 fix: create issue modal project deselecting
  web/components/issues/form.tsx
Labels: 🐛bug, 🌐frontend

#3142 fix: issue with `cycle` and `module` sidebar filter implementation.
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#3144 chore: disable API calls for un-authorized users
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/store/archived-issues/issue.store.ts
  web/store/cycle/cycle_issue.store.ts
  web/store/issue/issue.store.ts
  web/store/issues/project-issues/archived/issue.store.ts
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/draft/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
  web/store/issues/project-issues/project-view/issue.store.ts
  web/store/issues/project-issues/project/issue.store.ts
  web/store/module/module_issue.store.ts
  web/store/profile-issues/issue_filters.store.ts
Labels: 🌐frontend, 🌟improvement

#3145 fix: project members fetch fix
  web/components/issues/issue-layouts/properties/assignee.tsx
Labels: 🐛bug, 🌐frontend

#3146 chore: role restriction to issue detail & peek-overview
  web/components/core/sidebar/links-list.tsx
  web/components/issues/attachment/attachments.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/main-content.tsx
  web/components/issues/peek-overview/issue-detail.tsx
Labels: 🌐frontend, 🧹chore

#3148 chore: made project-identifier rule consistent
  web/components/project/create-project-modal.tsx
  web/components/project/form.tsx
Labels: 🐛bug, 🎨UI / UX

#3121 Fix .vertical-lr in Firefox
  web/styles/globals.css
Labels: 🎨UI / UX

#3157 chore: issue click & peek overview improvement
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/properties/date.tsx
  web/components/issues/issue-layouts/properties/estimates.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue.tsx
  web/components/project/priority-select.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3134 fix: issue peek-overview delete functionality
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
  web/components/issues/issue-layouts/gantt/project-root.tsx
  web/components/issues/issue-layouts/gantt/project-view-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/sub-issues/issue.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/root.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🐛bug, 🌐frontend

#3136 fix: typo in install.sh
  deploy/selfhost/install.sh
Labels: 🧹chore

#3168 fix: project cover endpoint
  apiserver/plane/app/views/project.py
Labels: 🐛bug, ⚙️backend

#3167 User role validation across workspace and projects.
  web/components/common/new-empty-state.tsx
  web/components/issues/issue-layouts/empty-states/project.tsx
  web/components/modules/modules-list-view.tsx
  web/components/modules/sidebar.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/list-view.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/components/project/card-list.tsx
  web/components/views/views-list.tsx
  web/components/workspace/views/header.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🐛bug, 🌐frontend

#3100 fix: issue with peek view properties not editable and options not being shown in `all workspace issues`.
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/sidebar-select/assignee.tsx
  web/components/issues/sidebar-select/cycle.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/issues/sidebar-select/module.tsx
  web/components/issues/sidebar-select/parent.tsx
  web/components/issues/sidebar-select/state.tsx
  web/components/issues/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#3159 fix: bug fixes & improvements
  web/components/issues/select/cycle.tsx
  web/store/issues/global/issue.store.ts
  web/store/issues/project-issues/cycle/issue.store.ts
  web/store/issues/project-issues/draft/issue.store.ts
  web/store/issues/project-issues/module/issue.store.ts
  web/store/issues/project-issues/project-view/issue.store.ts
  web/store/issues/project-issues/project/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3170 sync: moving contributions from preview to develop
  apiserver/requirements/base.txt
  deploy/selfhost/install.sh
  web/styles/globals.css
Labels: 📢promote

#3174 chore: cycle and module sidebar mutation fix
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/roots/module-root.tsx
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/cycle-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/module-root.tsx
  web/components/issues/modal.tsx
Labels: 🐛bug, 🌐frontend

#3179 refactor: projects & inbox store instances
  web/components/estimates/estimates-list.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/inbox/actions-header.tsx
  web/components/inbox/filters-dropdown.tsx
  web/components/inbox/filters-list.tsx
  web/components/inbox/issue-card.tsx
  web/components/inbox/issues-list-sidebar.tsx
  web/components/inbox/main-content.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/inbox/modals/delete-issue-modal.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/project.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/list/roots/project-view-root.tsx
  web/components/issues/issue-layouts/properties/estimates.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/components/workspace/views/form.tsx
  web/hooks/store/index.ts
  web/hooks/store/use-inbox-filters.ts
  web/hooks/store/use-inbox-issues.ts
  web/hooks/store/use-inbox.ts
  web/layouts/auth-layout/project-wrapper.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
  web/store/inbox/inbox_issue.store.ts
Labels: 🌟improvement, 🧹chore

#3182 dev: branch build custom docker repo with suffix
  .github/workflows/build-branch.yml
Labels: 🚀CI/CD

#3204 fix: role authorization for create project button in project empty state
  web/components/page-views/workspace-dashboard.tsx
  web/components/project/card-list.tsx
Labels: 🐛bug, 🌐frontend

#3132 dev: segway intgegration
  .gitignore
  apiserver/Procfile
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/app/views/importer.py
  apiserver/plane/bgtasks/__init__.py
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/event_tracking_task.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
  apiserver/plane/bgtasks/file_asset_task.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/bgtasks/issue_sync_task.py
  apiserver/plane/bgtasks/magic_link_code_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/user_welcome_task.py
  apiserver/plane/bgtasks/webhook_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
  apiserver/plane/celery.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/state.py
  apiserver/plane/settings/common.py
  packages/tsconfig/express.json
  segway/.env.example
  segway/Dockerfile.segway
  segway/README.md
  segway/package.json
  segway/src/controller/github.controller.ts
  segway/src/controller/index.ts
  segway/src/controller/jira.controller.ts
  segway/src/controller/slack.controller.ts
  segway/src/db/singleton.ts
  segway/src/middleware/authkey.middleware.ts
  segway/src/middleware/logger.middleware.ts
  segway/src/mq/singleton.ts
  segway/src/server.ts
  segway/src/start.ts
  segway/src/utils/logger.ts
  segway/src/worker/base.worker.ts
  segway/tsconfig.json
  segway/yarn.lock
  yarn.lock
Labels: ⚙️backend, 🔗integrations

#3205 dev: github importer
  apiserver/plane/app/views/importer.py
  apiserver/plane/app/views/integration/base.py
  apiserver/plane/app/views/integration/github.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/db/migrations/0051_cycle_external_id_cycle_external_source_and_more.py
  apiserver/plane/db/models/base.py
  apiserver/plane/db/models/importer.py
  segway/.env.example
  segway/combined.log
  segway/package.json
  segway/src/controller/github.controller.ts
  segway/src/controller/jira.controller.ts
  segway/src/utils/github.authentication.ts
  segway/src/utils/paginator.ts
  segway/yarn.lock
Labels: ⚙️backend, 🔗integrations

#3186 style: instance admin email settings ui & ux update.
  web/components/instance/email-form.tsx
Labels: 🌐frontend, 🎨UI / UX

#3215 refactor: use-user-auth hook
  web/components/exporter/export-modal.tsx
  web/components/exporter/guide.tsx
  web/components/integration/delete-import-modal.tsx
  web/components/integration/github/root.tsx
  web/components/integration/guide.tsx
  web/components/integration/jira/root.tsx
  web/components/issues/sidebar.tsx
  web/hooks/use-issue-notification-subscription.tsx
  web/hooks/use-user-auth.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/accounts/sign-up.tsx
  web/pages/onboarding/index.tsx
  web/pages/profile/index.tsx
  web/store/user/index.ts
Labels: 🛠️refactor

#3207 refactor: project-view & application related stores
  web/components/headers/project-view-issues.tsx
  web/components/views/views-list.tsx
  web/store/application/app-config.store.ts
  web/store/application/command-palette.store.ts
  web/store/application/event-tracker.store.ts
  web/store/application/instance.store.ts
  web/store/application/router.store.ts
  web/store/application/theme.store.ts
  web/store/project-view.store.ts
Labels: 🛠️refactor

#3218 chore: bug fixes & improvement
  web/components/common/new-empty-state.tsx
  web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/components/issues/modal.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3189 fix: bugs & improvements
  web/components/profile/sidebar.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
Labels: 🐛bug, 🎨UI / UX

#3206 style: email placeholder changed across the platform
  space/components/accounts/sign-in-forms/create-password.tsx
  space/components/accounts/sign-in-forms/email-form.tsx
  space/components/accounts/sign-in-forms/optional-set-password.tsx
  space/components/accounts/sign-in-forms/password.tsx
  space/components/accounts/sign-in-forms/self-hosted-sign-in.tsx
  space/components/accounts/sign-in-forms/set-password-link.tsx
  space/components/accounts/sign-in-forms/unique-code.tsx
  space/pages/accounts/password.tsx
  web/components/account/sign-in-forms/create-password.tsx
  web/components/account/sign-in-forms/email-form.tsx
  web/components/account/sign-in-forms/optional-set-password.tsx
  web/components/account/sign-in-forms/password.tsx
  web/components/account/sign-in-forms/self-hosted-sign-in.tsx
  web/components/account/sign-in-forms/set-password-link.tsx
  web/components/account/sign-in-forms/unique-code.tsx
  web/components/instance/setup-form/sign-in-form.tsx
  web/components/onboarding/invite-members.tsx
  web/pages/accounts/password.tsx
Labels: 🌐frontend, 🎨UI / UX

#3221 fix: optimistic update for instant operations
  web/store/page.store.ts
  web/store/state.store.ts
  web/store/workspace/api-token.store.ts
  web/store/workspace/index.ts
  web/store/workspace/webhook.store.ts
Labels: 🧹chore

#3226 chore: allow non-latin characters to project identifier
  web/components/project/create-project-modal.tsx
Labels: 🌟improvement, 🧹chore

#3220 fix: posthog events trigger in staging
  web/lib/wrappers/posthog-wrapper.tsx
Labels: 🌐frontend, event tracking

#3246 fix: custom theme validation added
  web/helpers/theme.helper.ts
Labels: 🐛bug, 🌐frontend

#3223 style: create webhook page to modal
  web/components/web-hooks/create-webhook-modal.tsx
  web/components/web-hooks/empty-state.tsx
  web/components/web-hooks/form/form.tsx
  web/components/web-hooks/form/secret-key.tsx
  web/components/web-hooks/generated-hook-details.tsx
  web/components/web-hooks/index.ts
  web/pages/[workspaceSlug]/settings/webhooks/[webhookId].tsx
  web/pages/[workspaceSlug]/settings/webhooks/create.tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3251 chore: cycle & module sidebar improvement
  web/components/cycles/sidebar.tsx
  web/components/modules/select/lead.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar.tsx
  web/components/project/sidebar-list.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#3259 fix: external api serializer
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/serializers/module.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
Labels: 🐛bug, ⚙️backend

#3188 chore: estimates and issue parent id fixes
  apiserver/plane/app/serializers/estimate.py
  apiserver/plane/app/views/estimate.py
  apiserver/plane/app/views/search.py
  apiserver/plane/bgtasks/issue_activites_task.py
  web/components/estimates/create-update-estimate-modal.tsx
Labels: 🐛bug, 🌐frontend, ⚙️backend

#3263 fix: replacing onclick redirections with link tag.
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/issues-stats.tsx
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🎨UI / UX

#3269 Style/UI improvements
  web/components/headers/global-issues.tsx
  web/components/issues/peek-overview/activity/card.tsx
Labels: 🌐frontend, 🎨UI / UX

#3250 fix: onboarding redirection loop and bug fixes
  web/components/auth-screens/not-authorized-view.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/hooks/use-sign-in-redirection.ts
  web/hooks/use-user-auth.tsx
  web/hooks/use-user.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/pages/onboarding/index.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3267 fix: issue parent select
  web/components/issues/sidebar-select/parent.tsx
Labels: 🐛bug, 🌐frontend

#3270 chore: cycle current status
  apiserver/plane/app/serializers/cycle.py
  apiserver/plane/app/views/cycle.py
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/gantt-chart/blocks.tsx
  web/components/cycles/sidebar.tsx
  web/components/cycles/transfer-issues-modal.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/helpers/date-time.helper.ts
  web/store/cycle/cycles.store.ts
  web/types/cycles.d.ts
Labels: 🌐frontend, ⚙️backend, 🌟improvement, 🧹chore

#3277 feat: external identifiers
  apiserver/plane/db/migrations/0051_cycle_external_id_cycle_external_source_and_more.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/inbox.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/state.py
Labels: ⚙️backend, 🔄migrations

#3260 Chore/user role validation
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/properties/date.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/issues/view-select/due-date.tsx
  web/components/issues/view-select/start-date.tsx
Labels: 🌐frontend, 🎨UI / UX

#3284 Style: custom theme UI fixes
  web/components/core/theme/theme-switch.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
Labels: 🌐frontend, 🎨UI / UX
