Repository makeplane/plane, pull requests merged in 2023-09, with the labels that each got.

#2041 chore: cycle endpoint to return display name as well in the assignee distribution
  apiserver/plane/api/views/cycle.py
Labels: Backend

#2024 fix: Gantt chart bugs
  apps/app/components/gantt-chart/helpers/draggable.tsx
Labels: bug, frontend

#2044 dev: migrations for v0.12 release
  apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0042_alter_issuevote_unique_together_alter_issuevote_vote_and_more.py
Labels: Backend

#2043 fix: peek overview bugs
  apps/app/components/issues/delete-issue-modal.tsx
  apps/app/components/issues/peek-overview/issue-properties.tsx
  apps/app/components/issues/peek-overview/layout.tsx
  apps/app/components/issues/sidebar-select/assignee.tsx
  apps/app/components/issues/sidebar-select/priority.tsx
  apps/app/components/ui/dropdowns/custom-select.tsx
  apps/app/store/issues.ts
Labels: bug, frontend

#2048 fix: migration error
  apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
Labels: Backend

#2049 chore: updates project invite placeholder
  apps/app/components/project/send-project-invitation-modal.tsx
Labels: frontend, improvement

#2042 feat: leave project and workspace endpoint
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/workspace.py
Labels: Backend

#2047 chore: vote actor details
  apiserver/plane/api/serializers/issue.py
Labels: Backend

#2051 chore: remove theme store from Plane deploy
  apps/space/components/issues/navbar/theme.tsx
  apps/space/lib/mobx/store-init.tsx
  apps/space/pages/_app.tsx
  apps/space/store/root.ts
  apps/space/store/theme.ts
Labels: frontend

#2036 chore: bug fixes and ui/ux enhancements
  apps/app/components/command-palette/shortcuts-modal.tsx
  apps/app/components/core/activity.tsx
  apps/app/components/core/filters/issues-view-filter.tsx
  apps/app/components/core/image-picker-popover.tsx
  apps/app/components/core/views/board-view/board-header.tsx
  apps/app/components/core/views/board-view/single-board.tsx
  apps/app/components/core/views/board-view/single-issue.tsx
  apps/app/components/core/views/list-view/single-issue.tsx
  apps/app/components/core/views/list-view/single-list.tsx
  apps/app/components/core/views/spreadsheet-view/single-issue.tsx
  apps/app/components/cycles/active-cycle-details.tsx
  apps/app/components/emoji-icon-picker/index.tsx
  apps/app/components/emoji-icon-picker/types.d.ts
  apps/app/components/issues/delete-issue-modal.tsx
  apps/app/components/issues/label.tsx
  apps/app/components/issues/modal.tsx
  apps/app/components/issues/my-issues/my-issues-view-options.tsx
  apps/app/components/issues/my-issues/my-issues-view.tsx
  apps/app/components/profile/profile-issues-view-options.tsx
  apps/app/components/profile/profile-issues-view.tsx
  apps/app/components/workspace/issues-stats.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  apps/app/pages/[workspaceSlug]/settings/index.tsx
Labels: frontend

#2054 chore: sign in options added
  apps/space/components/issues/navbar/index.tsx
  apps/space/components/issues/peek-overview/issue-activity.tsx
  apps/space/pages/index.tsx
  apps/space/store/user.ts
Labels: frontend

#2055 style: sign in page bg color
  apps/space/components/issues/board-views/kanban/index.tsx
  apps/space/pages/_document.tsx
  apps/space/pages/index.tsx
Labels: frontend, UI

#2057 fix: issue vote constraints
  apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/issue.py
Labels: Backend

#2056 fix: sidebar cycle and module select
  apps/app/components/issues/sidebar-select/blocked.tsx
  apps/app/components/issues/sidebar-select/blocker.tsx
  apps/app/components/issues/sidebar-select/cycle.tsx
  apps/app/components/issues/sidebar-select/module.tsx
Labels: bug, frontend

#2062 dev: updated error handling for project deploy board attributes
  apiserver/plane/api/views/issue.py
Labels: bug, Backend

#2064 fix: peek overview layout switch
  apps/app/components/issues/peek-overview/layout.tsx
  apps/space/components/issues/peek-overview/layout.tsx
Labels: bug, frontend

#2072 fix: state group icon not rendering correct color
  space/components/icons/index.ts
  space/components/icons/state-group/backlog-state-icon.tsx
  space/components/icons/state-group/cancelled-state-icon.tsx
  space/components/icons/state-group/completed-state-icon.tsx
  space/components/icons/state-group/index.ts
  space/components/icons/state-group/started-state-icon.tsx
  space/components/icons/state-group/state-group-icon.tsx
  space/components/icons/state-group/unstarted-state-icon.tsx
  space/components/issues/board-views/kanban/header.tsx
  space/components/issues/board-views/list/block.tsx
  space/components/issues/board-views/list/header.tsx
  space/components/issues/board-views/list/index.tsx
  space/components/views/project-details.tsx
Labels: bug, frontend

#2074 chore: add authorization to the gantt chart
  web/components/cycles/gantt-chart/cycle-issues-layout.tsx
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/issues/gantt-chart/layout.tsx
  web/components/modules/gantt-chart/module-issues-layout.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/components/views/gantt-chart.tsx
Labels: frontend, improvement

#2070 chore: cycle update errors
  apiserver/plane/api/views/cycle.py
Labels: Backend

#2073 fix: state ordering for project public boards
  apiserver/plane/api/views/issue.py
Labels: bug, Backend

#2075 fix: copy link button not working on the peek overview
  space/components/issues/peek-overview/header.tsx
  space/components/issues/peek-overview/issue-properties.tsx
  space/components/issues/peek-overview/layout.tsx
  space/layouts/project-layout.tsx
  web/components/issues/peek-overview/issue-properties.tsx
Labels: bug, frontend

#2077 fix: favicon path on Plane space
  space/pages/_app.tsx
  space/public/site.webmanifest.json
Labels: bug, frontend

#2080 fix: project invite modal members filter function
  web/components/project/send-project-invitation-modal.tsx
Labels: bug, frontend

#2081 feat: landing page after logging in
  space/components/accounts/index.ts
  space/components/accounts/sign-in.tsx
  space/components/accounts/user-logged-in.tsx
  space/components/views/home.tsx
  space/components/views/index.ts
  space/components/views/project-details.tsx
  space/pages/index.tsx
  space/public/user-logged-in.svg
Labels: frontend, improvement

#2082 chore: invalid URL screen
  space/components/views/project-details.tsx
  space/public/something-went-wrong.svg
Labels: frontend, improvement

#2087 dev: docker environment deploy fixes
  docker-compose-hub.yml
  docker-compose.yml
  space/Dockerfile.space
  space/package.json
  web/Dockerfile.web
Labels: docker

#2089 fix: show profile time according to the user's timezone
  web/components/profile/sidebar.tsx
Labels: bug, frontend

#2094 fix: validation in automation task
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: Backend, improvement

#2096 fix: redirection after signing in on space
  space/components/accounts/sign-in.tsx
  space/store/user.ts
Labels: bug, frontend

#2100 feat: plane space comment reactions
  space/components/issues/peek-overview/comment/add-comment.tsx
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/components/issues/peek-overview/comment/comment-reactions.tsx
  space/components/issues/peek-overview/comment/index.ts
  space/components/issues/peek-overview/header.tsx
  space/components/issues/peek-overview/index.ts
  space/components/issues/peek-overview/issue-emoji-reactions.tsx
  space/components/ui/reaction-selector.tsx
  space/services/issue.service.ts
  space/store/issue_details.ts
  space/types/issue.ts
  web/components/core/reaction-selector.tsx
Labels: feature, frontend

#2101 fix: don't render invalid dated blocks on the gantt chart
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/gantt-chart/helpers/block-structure.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
Labels: frontend, improvement

#2102 fix: issue object for filtering
  apiserver/plane/api/views/workspace.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/utils/analytics_plot.py
Labels: Backend

#2099 fix: public issue list endpoint n+1
  apiserver/plane/api/views/issue.py
Labels: Backend, n+1

#2109 fix: edit issue comment mutation on Plane deploy
  space/store/issue_details.ts
Labels: bug, frontend

#2092 fix: Improved Image Deletion Logic, Image ID Issue in Modals and Performance Optimization in Editor
  web/components/tiptap/extensions/index.tsx
  web/components/tiptap/plugins/delete-image.tsx
  web/components/tiptap/plugins/upload-image.tsx
Labels: bug, enhancement, UI, Editor

#2114 chore: render specific icons for due dates
  space/components/issues/board-views/block-due-date.tsx
  space/components/issues/peek-overview/issue-properties.tsx
  space/constants/helpers.ts
  space/helpers/date-time.helper.ts
Labels: frontend, improvement

#2116 chore: option to switch access of a comment
  web/components/inbox/inbox-issue-activity.tsx
  web/components/issues/activity.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/main-content.tsx
  web/components/issues/peek-overview/issue-activity.tsx
  web/services/issues.service.ts
Labels: frontend, improvement

#2095 dev: update python packages
  apiserver/requirements/base.txt
  apiserver/requirements/production.txt
Labels: Backend

#2108 fix: issue comment ordering for public boards
  apiserver/plane/api/views/issue.py
Labels: Backend

#2110 fix: remove triage issue status from public boards
  apiserver/plane/api/views/issue.py
Labels: Backend

#2117 fix: onboarding role select dropdown text color
  space/components/accounts/onboarding-form.tsx
Labels: frontend, UI

#2118 fix: update plane logo
  space/components/accounts/sign-in.tsx
  space/pages/onboarding/index.tsx
  space/public/plane-logos/blue-without-text.png
  space/public/plane-logos/blue-without-text.svg
Labels: frontend, UI

#2123 fix: custom date filters not working on my issues and profile issues
  web/components/core/filters/date-filter-modal.tsx
  web/components/issues/my-issues/my-issues-select-filters.tsx
  web/components/views/select-filters.tsx
Labels: 🐛bug, frontend

#2124 fix: handleClose function of the export modal
  web/components/exporter/guide.tsx
Labels: 🐛bug, frontend

#2126 chore: update state icons and colors
  space/components/issues/peek-overview/issue-properties.tsx
  web/components/analytics/scope-and-demand/demand.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/command-palette/issue/change-issue-state.tsx
  web/components/core/filters/filters-list.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/core/views/board-view/all-boards.tsx
  web/components/core/views/board-view/board-header.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/icons/backlog-state-icon.tsx
  web/components/icons/cancelled-state-icon.tsx
  web/components/icons/completed-state-icon.tsx
  web/components/icons/index.ts
  web/components/icons/started-state-icon.tsx
  web/components/icons/state-group-icon.tsx
  web/components/icons/state/backlog.tsx
  web/components/icons/state/cancelled.tsx
  web/components/icons/state/completed.tsx
  web/components/icons/state/index.ts
  web/components/icons/state/started.tsx
  web/components/icons/state/state-group-icon.tsx
  web/components/icons/state/unstarted.tsx
  web/components/icons/unstarted-state-icon.tsx
  web/components/issues/gantt-chart/blocks.tsx
  web/components/issues/my-issues/my-issues-select-filters.tsx
  web/components/issues/peek-overview/issue-properties.tsx
  web/components/issues/select/state.tsx
  web/components/issues/sidebar-select/state.tsx
  web/components/issues/view-select/state.tsx
  web/components/states/single-state.tsx
  web/components/views/select-filters.tsx
  web/components/web-view/select-state.tsx
  web/components/workspace/issues-pie-chart.tsx
  web/constants/state.ts
  web/helpers/analytics.helper.ts
Labels: enhancement, frontend

#2130 chore: remove `getServerSideProps`
  space/pages/[workspace_slug]/[project_slug]/index.tsx
  web/pages/installations/[provider]/index.tsx
Labels: frontend, 🧹chore

#2132 refactor: priority icon component
  web/components/analytics/custom-analytics/table.tsx
  web/components/command-palette/issue/change-issue-priority.tsx
  web/components/core/filters/filters-list.tsx
  web/components/core/views/board-view/board-header.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/icons/priority-icon.tsx
  web/components/inbox/filters-dropdown.tsx
  web/components/inbox/filters-list.tsx
  web/components/inbox/inbox-issue-card.tsx
  web/components/inbox/inbox-main-content.tsx
  web/components/issues/my-issues/my-issues-select-filters.tsx
  web/components/issues/my-issues/my-issues-view.tsx
  web/components/issues/peek-overview/issue-properties.tsx
  web/components/issues/select/priority.tsx
  web/components/issues/sidebar-select/priority.tsx
  web/components/issues/sidebar.tsx
  web/components/issues/view-select/priority.tsx
  web/components/profile/profile-issues-view.tsx
  web/components/views/select-filters.tsx
  web/components/web-view/issue-properties-detail.tsx
  web/components/web-view/select-priority.tsx
  web/constants/project.ts
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/types/issues.d.ts
Labels: frontend, refactor

#2142 chore: changed issue priority from NULL to none
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/workspace.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/utils/issue_filters.py
Labels: Backend, 🌟improvement, 🔄migrations

#2148 feat: users can select timezone during onboarding
  web/components/onboarding/user-details.tsx
  web/helpers/date-time.helper.ts
Labels: frontend

#2135 [chore] Updated web and deploy backend configuration for reverse proxy & decoupled Plane Deploy URL generation for web
  docker-compose.yml
  setup.sh
  space/Dockerfile.space
  space/helpers/common.helper.ts
  space/services/authentication.service.ts
  space/services/file.service.ts
  space/services/issue.service.ts
  space/services/project.service.ts
  space/services/user.service.ts
  web/.env.example
  web/Dockerfile.web
  web/components/project/publish-project/modal.tsx
  web/helpers/common.helper.ts
  web/layouts/app-layout/app-header.tsx
  web/lib/auth.ts
  web/services/ai.service.ts
  web/services/analytics.service.ts
  web/services/app-installations.service.ts
  web/services/authentication.service.ts
  web/services/cycles.service.ts
  web/services/estimates.service.ts
  web/services/file.service.ts
  web/services/inbox.service.ts
  web/services/integration/csv.services.ts
  web/services/integration/github.service.ts
  web/services/integration/index.ts
  web/services/integration/jira.service.ts
  web/services/issues.service.ts
  web/services/modules.service.ts
  web/services/notifications.service.ts
  web/services/pages.service.ts
  web/services/project-publish.service.ts
  web/services/project.service.ts
  web/services/reaction.service.ts
  web/services/state.service.ts
  web/services/user.service.ts
  web/services/views.service.ts
  web/services/workspace.service.ts
Labels: 🐳docker

#2157 release: self hosting fixes
  .env.example
  replace-env-vars.sh
  space/additional.d.ts
  space/components/accounts/sign-in.tsx
  space/next.config.js
  space/package.json
  space/pages/onboarding/index.tsx
  space/tsconfig.json
Labels: 🏠self-hosted, 🚀release, 🐳docker, ⚙️config changes

#2159 refactor: view props structure
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/core/views/all-views.tsx
  web/components/core/views/board-view/all-boards.tsx
  web/components/core/views/board-view/board-header.tsx
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/calendar-view/calendar.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/all-lists.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-columns.tsx
  web/components/cycles/gantt-chart/cycle-issues-layout.tsx
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/gantt-chart/layout.tsx
  web/components/issues/modal.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/issues/my-issues/my-issues-view.tsx
  web/components/issues/view-select/due-date.tsx
  web/components/issues/view-select/start-date.tsx
  web/components/modules/gantt-chart/module-issues-layout.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/components/profile/profile-issues-view.tsx
  web/contexts/issue-view.context.tsx
  web/contexts/profile-issues-context.tsx
  web/hooks/gantt-chart/cycle-issues-view.tsx
  web/hooks/gantt-chart/issue-view.tsx
  web/hooks/gantt-chart/module-issues-view.tsx
  web/hooks/my-issues/use-my-issues-filter.tsx
  web/hooks/my-issues/use-my-issues.tsx
  web/hooks/use-calendar-issues-view.tsx
  web/hooks/use-issues-view.tsx
  web/hooks/use-profile-issues.tsx
  web/hooks/use-spreadsheet-issues-view.tsx
  web/pages/[workspaceSlug]/me/my-issues.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
  web/services/issues.service.ts
  web/services/modules.service.ts
  web/services/project.service.ts
  web/types/index.d.ts
  web/types/issues.d.ts
  web/types/projects.d.ts
  web/types/view-props.d.ts
  web/types/workspace.d.ts
Labels: frontend, refactor

#2160 fix: handle undefined view props
  web/components/profile/profile-issues-view-options.tsx
  web/components/profile/profile-issues-view.tsx
  web/contexts/issue-view.context.tsx
  web/contexts/profile-issues-context.tsx
  web/hooks/my-issues/use-my-issues-filter.tsx
  web/hooks/use-profile-issues.tsx
  web/types/view-props.d.ts
Labels: 🐛bug, frontend

#2162 chore: priority migration
  apiserver/plane/db/migrations/0043_auto_20230912_1733.py
Labels: Backend, 🔄migrations

#2161 feat: issue drafts
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/migrations/0043_issue_is_draft_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/issue.py
Labels: ✨feature, Backend, 🔄migrations

#2146 chore: changed view props
  apiserver/plane/db/migrations/0043_auto_20230911_1655.py
Labels: Backend, 🌟improvement, 🔄migrations

#1995 feat: add a relation to an issue
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/search.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/db/migrations/0043_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/issue.py
Labels: enhancement, Backend

#2166 refactor: switched priority null -> 'none'
  web/components/issues/form.tsx
  web/components/issues/select/priority.tsx
  web/components/web-view/select-priority.tsx
  web/constants/project.ts
  web/types/issues.d.ts
Labels: frontend, refactor

#2169 fix: migration files
  apiserver/plane/db/migrations/0043_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0043_auto_20230912_1733.py
  apiserver/plane/db/migrations/0043_issue_is_draft_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0044_auto_20230913_0709.py
Labels: Backend, 🔄migrations

#2173 feat: changed payload for swimlanes
  apiserver/plane/api/views/issue.py
  apiserver/plane/utils/grouper.py
Labels: ✨feature, Backend

#2175 chore: changed default props for workspace and project members
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/workspace.py
Labels: Backend, 🌟improvement

#2172 chore: peek overview for issue view and my issue view
  space/components/accounts/sign-in.tsx
  space/pages/onboarding/index.tsx
  web/components/core/views/all-views.tsx
  web/components/core/views/board-view/all-boards.tsx
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/calendar-view/calendar.tsx
  web/components/core/views/calendar-view/single-issue.tsx
  web/components/core/views/gantt-chart-view/index.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/all-lists.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/cycles/gantt-chart/cycle-issues-layout.tsx
  web/components/issues/form.tsx
  web/components/issues/gantt-chart/blocks.tsx
  web/components/issues/gantt-chart/layout.tsx
  web/components/issues/my-issues/my-issues-view.tsx
  web/components/modules/gantt-chart/module-issues-layout.tsx
  web/components/views/gantt-chart.tsx
  web/hooks/use-calendar-issues-view.tsx
Labels: ✨feature, frontend

#2176 fix: sub groups in cycle module and my issues
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
Labels: Backend, 🌟improvement

#2177 style: project setting ui revamp
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/core/image-picker-popover.tsx
  web/components/emoji-icon-picker/index.tsx
  web/components/estimates/single-estimate.tsx
  web/components/icons/index.ts
  web/components/icons/module-icon.tsx
  web/components/integration/github/select-repository.tsx
  web/components/integration/slack/select-channel.tsx
  web/components/labels/create-update-label-inline.tsx
  web/components/labels/single-label-group.tsx
  web/components/labels/single-label.tsx
  web/components/project/index.ts
  web/components/project/member-select.tsx
  web/components/project/settings-header.tsx
  web/components/project/settings-sidebar.tsx
  web/components/project/single-integration-card.tsx
  web/components/states/single-state.tsx
  web/components/ui/integration-and-import-export-banner.tsx
  web/components/ui/toggle-switch.tsx
  web/package.json
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/control.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/services/modules.service.ts
Labels: frontend, 🎨UI / UX

#2184 fix: track events issue and env variables fixes
  turbo.json
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-menu.tsx
  web/components/workspace/single-invitation.tsx
  web/lib/mobx/store-init.tsx
  web/next.config.js
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/api/slack-redirect.ts
  web/pages/api/track-event.ts
  web/pages/api/unsplash.ts
  web/services/ai.service.ts
  web/services/cycles.service.ts
  web/services/estimates.service.ts
  web/services/inbox.service.ts
  web/services/integration/csv.services.ts
  web/services/integration/github.service.ts
  web/services/integration/index.ts
  web/services/integration/jira.service.ts
  web/services/issues.service.ts
  web/services/modules.service.ts
  web/services/pages.service.ts
  web/services/project-publish.service.ts
  web/services/project.service.ts
  web/services/reaction.service.ts
  web/services/state.service.ts
  web/services/track-event.service.ts
  web/services/user.service.ts
  web/services/views.service.ts
  web/services/workspace.service.ts
  yarn.lock
Labels: ⚙️config changes

#2186 feat: posthog integration
  turbo.json
  web/package.json
  web/pages/_app.tsx
  web/pages/_document.tsx
  yarn.lock
Labels: frontend, ⚙️config changes

#2190 fix: edit/delete for draft issue
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/views/all-views.tsx
  web/components/core/views/board-view/all-boards.tsx
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/all-lists.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/issues/delete-draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/index.ts
  web/components/workspace/sidebar-quick-action.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx
Labels: ✨feature, frontend, refactor

#2192 chore: changed issue relation history logs
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
Labels: Backend, 🌟improvement, 🔄migrations

#2194 chore: changed old values in issue relation logs
  apiserver/plane/bgtasks/issue_activites_task.py
Labels: Backend

#2193 style: workspace and profile setting revamp
  web/components/automation/auto-close-automation.tsx
  web/components/core/activity.tsx
  web/components/core/modals/image-upload-modal.tsx
  web/components/exporter/guide.tsx
  web/components/exporter/single-export.tsx
  web/components/integration/guide.tsx
  web/components/integration/single-import.tsx
  web/components/integration/single-integration-card.tsx
  web/components/labels/create-update-label-inline.tsx
  web/components/labels/single-label.tsx
  web/components/project/confirm-project-member-remove.tsx
  web/components/project/member-select.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/project/settings-sidebar.tsx
  web/components/states/single-state.tsx
  web/components/ui/integration-and-import-export-banner.tsx
  web/components/web-view/activity-message.tsx
  web/components/workspace/confirm-workspace-member-remove.tsx
  web/components/workspace/index.ts
  web/components/workspace/settings-header.tsx
  web/layouts/settings-navbar.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/public/theme-mode/custom-mode.svg
  web/public/theme-mode/custom-theme-banner.svg
  web/public/theme-mode/dark-high-contrast.svg
  web/public/theme-mode/dark-mode.svg
  web/public/theme-mode/light-high-contrast.svg
  web/public/theme-mode/light-mode.svg
Labels: frontend, 🎨UI / UX

#2199 fix: hydration error and draft issue workflow
  web/components/command-palette/command-pallette.tsx
  web/components/core/views/issues-view.tsx
  web/components/issues/delete-draft-issue-modal.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/modal.tsx
  web/components/ui/buttons/type.d.ts
  web/components/workspace/sidebar-quick-action.tsx
  web/services/issues.service.ts
  web/store/draft-issue.ts
  web/store/root.ts
Labels: frontend, refactor

#2189 fix: activity not coming for blocking/blocked, 'related to' and duplicate
  web/components/core/activity.tsx
  web/components/issues/sidebar-select/blocked.tsx
  web/components/issues/sidebar-select/blocker.tsx
  web/components/issues/sidebar-select/duplicate.tsx
  web/components/issues/sidebar-select/relates-to.tsx
  web/components/issues/sidebar.tsx
  web/components/web-view/activity-message.tsx
  web/components/web-view/issue-properties-detail.tsx
  web/services/issues.service.ts
  web/types/issues.d.ts
Labels: frontend, refactor

#2005 feat: workspace views
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/view.py
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/view.py
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/view.py
Labels: ✨feature, Backend, 🔄migrations

#2213 fix: tracking logs for issue activity
  apiserver/plane/bgtasks/issue_activites_task.py
Labels: 🐛bug, Backend

#2215 fix: migration files
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
  apiserver/plane/db/migrations/0045_issueactivity_epoch_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0046_auto_20230919_1421.py
Labels: Backend, 🔄migrations

#2217 fix: changed time to timestamp
  apiserver/plane/api/views/issue.py
Labels: 🐛bug, Backend

#2138 chore: dynamic position dropdown
  web/components/core/views/board-view/board-header.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/calendar-view/single-issue.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/spreadsheet-view/single-issue.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-view.tsx
  web/components/icons/module/cancelled.tsx
  web/components/icons/module/paused.tsx
  web/components/icons/state/backlog.tsx
  web/components/icons/state/cancelled.tsx
  web/components/icons/state/started.tsx
  web/components/icons/state/unstarted.tsx
  web/components/issues/view-select/index.ts
  web/components/issues/view-select/state.tsx
  web/components/project/index.ts
  web/components/project/label-select.tsx
  web/components/project/members-select.tsx
  web/components/project/priority-select.tsx
  web/components/states/index.ts
  web/components/states/state-select.tsx
  web/hooks/use-dynamic-dropdown.tsx
Labels: frontend, 🎨UI / UX

#2212 fix: fields not getting selected in the create issue form
  web/components/core/views/issues-view.tsx
  web/components/issues/confirm-issue-discard.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/modal.tsx
  web/components/workspace/sidebar-quick-action.tsx
Labels: 🐛bug, frontend, 🎨UI / UX, 🧹chore

#2221 chore: sub issues count in individual issue
  apiserver/plane/api/views/issue.py
Labels: Backend, 🌟improvement

#2233 Implemented nested issues in the sub issues section in issue detail page
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/index.ts
  web/components/issues/main-content.tsx
  web/components/issues/sub-issues-list.tsx
  web/components/issues/sub-issues/index.ts
  web/components/issues/sub-issues/issue.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/progressbar.tsx
  web/components/issues/sub-issues/properties.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/project/members-select.tsx
Labels: ✨feature, frontend, 🎨UI / UX

#2225 refactor: product updates modal layout
  web/components/ui/product-updates-modal.tsx
Labels: frontend, 🌟improvement

#2226 fix: helper function to handle array with no elements
  web/components/analytics/custom-analytics/graph/index.tsx
  web/helpers/array.helper.ts
Labels: 🐛bug, frontend

#2227 fix: label color in the activity logs coming as black
  web/components/core/activity.tsx
Labels: 🐛bug, frontend

#2228 fix: profile issues layout switch
  web/components/core/views/board-view/all-boards.tsx
  web/components/profile/profile-issues-view.tsx
  web/contexts/profile-issues-context.tsx
Labels: 🐛bug, frontend, 🎨UI / UX

#2239 chore: updated docker naming conventions
  docker-compose-hub.yml
  docker-compose.yml
  nginx/nginx.conf.template
  space/.env.example
  web/.env.example
Labels: 🐳docker, 🧹chore

#2241 chore: added state and priority order in workspace user profile
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, 🧹chore

#2229 fix: changed priority from None to none
  apiserver/plane/api/views/importer.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/db/migrations/0047_auto_20230921_0758.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/workspace.py
  apiserver/plane/utils/analytics_plot.py
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend, 🌟improvement, 🔄migrations

#2185 fix: cycle and module stats when issues are archived
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/workspace.py
Labels: 🐛bug, ⚙️backend

#2240 feat: quick add
  web/components/core/views/board-view/index.ts
  web/components/core/views/board-view/inline-create-issue-form.tsx
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/calendar-view/index.ts
  web/components/core/views/calendar-view/inline-create-issue-form.tsx
  web/components/core/views/calendar-view/single-date.tsx
  web/components/core/views/gantt-chart-view/inline-create-issue-form.tsx
  web/components/core/views/index.ts
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/core/views/list-view/index.ts
  web/components/core/views/list-view/inline-create-issue-form.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/gantt-chart/sidebar.tsx
  web/helpers/string.helper.ts
  web/hooks/gantt-chart/issue-view.tsx
  web/hooks/use-keypress.tsx
Labels: ✨feature, 🌐frontend, 🎨UI / UX

#2244 chore: added epoch in draft
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: 🐛bug, ⚙️backend

#2211 style: settings page improvement
  web/components/ui/toggle-switch.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
Labels: 🌐frontend, 🎨UI / UX

#2253 chore: changed priority props in workspace and project
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/workspace.py
Labels: 🐛bug, ⚙️backend

#2246 fix: bug fix related to fetching dropdown options for the profile issue
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/calendar-view/single-date.tsx
  web/components/core/views/calendar-view/single-issue.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/single-issue.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-issues.tsx
  web/components/project/label-select.tsx
  web/components/project/members-select.tsx
  web/components/states/state-select.tsx
Labels: 🐛bug, 🌐frontend

#2254 fix: sub issue state and member select build error
  web/components/issues/sub-issues/properties.tsx
Labels: 🐛bug, 🌐frontend

#2256 feat: project issues topbar
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/views/board-view/all-boards.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/headers/index.ts
  web/components/headers/project-issues.tsx
  web/components/issue-layouts/display-filters/display-filters-selection.tsx
  web/components/issue-layouts/display-filters/display-properties.tsx
  web/components/issue-layouts/display-filters/extra-options.tsx
  web/components/issue-layouts/display-filters/group-by.tsx
  web/components/issue-layouts/display-filters/index.ts
  web/components/issue-layouts/display-filters/index.tsx
  web/components/issue-layouts/display-filters/issue-type.tsx
  web/components/issue-layouts/display-filters/order-by.tsx
  web/components/issue-layouts/filters/assignees.tsx
  web/components/issue-layouts/filters/created-by.tsx
  web/components/issue-layouts/filters/filter-selection.tsx
  web/components/issue-layouts/filters/index.ts
  web/components/issue-layouts/filters/index.tsx
  web/components/issue-layouts/filters/labels.tsx
  web/components/issue-layouts/filters/priority.tsx
  web/components/issue-layouts/filters/start-date.tsx
  web/components/issue-layouts/filters/state-group.tsx
  web/components/issue-layouts/filters/state.tsx
  web/components/issue-layouts/filters/target-date.tsx
  web/components/issue-layouts/helpers/dropdown.tsx
  web/components/issue-layouts/helpers/filter-header.tsx
  web/components/issue-layouts/helpers/filter-option.tsx
  web/components/issue-layouts/helpers/index.ts
  web/components/issue-layouts/index.ts
  web/components/issue-layouts/layout-selection.tsx
  web/components/issue-layouts/root.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/constants/issue.ts
  web/helpers/issue.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/store/issue_filters.ts
  web/store/project.ts
  web/types/issues.d.ts
  web/types/projects.d.ts
  web/types/view-props.d.ts
  web/types/workspace.d.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2255 chore: renamed all the issues view tooltips content from View to Layout
  web/components/core/filters/issues-view-filter.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#2250 fix: bug fixes and ui improvement
  web/components/cycles/single-cycle-list.tsx
  web/components/labels/single-label.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
Labels: 🐛bug, 🌐frontend

#2259 feat: quick-add placement in spreadsheet and gantt
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/core/views/list-view/inline-create-issue-form.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/gantt-chart/sidebar.tsx
  web/components/profile/profile-issues-view.tsx
  web/layouts/app-layout/app-sidebar.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
Labels: 🌐frontend, 🎨UI / UX

#2249 fix: draft issue delete not working
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/issues/delete-draft-issue-modal.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2263 feat: Add peek overview in sub issues and updated UI for empty states.
  web/components/issues/sub-issues/issue.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/root.tsx
Labels: 🌐frontend

#2235 chore: add tooltip to show full time on activity logs
  web/components/issues/activity.tsx
Labels: 🌐frontend, 🌟improvement

#2208 fix: issue automation iterable error
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: 🐛bug, ⚙️backend

#2257 fix: n+1 queries for cycle list and project member endpoints
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/views/project.py
Labels: ⚙️backend, ⚡performance

#2262 Implemented swimlanes and kanban view
  web/components/core/views/all-views.tsx
  web/components/issues/issue-layouts/calandar/index.ts
  web/components/issues/issue-layouts/calandar/root.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/assignee.tsx
  web/components/issues/issue-layouts/kanban/headers/card.tsx
  web/components/issues/issue-layouts/kanban/headers/created_by.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-root.tsx
  web/components/issues/issue-layouts/kanban/headers/label.tsx
  web/components/issues/issue-layouts/kanban/headers/priority.tsx
  web/components/issues/issue-layouts/kanban/headers/state-group.tsx
  web/components/issues/issue-layouts/kanban/headers/state.tsx
  web/components/issues/issue-layouts/kanban/headers/sub-group-by-root.tsx
  web/components/issues/issue-layouts/kanban/index.ts
  web/components/issues/issue-layouts/kanban/root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/constants/issue.ts
  web/package.json
  web/store/issue.ts
  web/store/kanban_view.ts
  web/styles/globals.css
  yarn.lock
Labels: 🌐frontend, 🌟improvement

#2266 dev: migration for 0.13
  apiserver/plane/db/migrations/0044_auto_20230913_0709.py
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
  apiserver/plane/db/migrations/0046_auto_20230919_1421.py
  apiserver/plane/db/migrations/0047_auto_20230921_0758.py
Labels: ⚙️backend, 🔄migrations

#2268 dev: re-split migrations into two different files
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
  apiserver/plane/db/migrations/0046_auto_20230926_1015.py
  apiserver/plane/db/migrations/0047_auto_20230926_1029.py
Labels: ⚙️backend, 🔄migrations

#2267 fix: user dashboard greeting timezone
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/views/board-view/board-header.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/pages/[workspaceSlug]/index.tsx
Labels: 🐛bug, 🌐frontend

#2272 style: gantt layout quick-add padding
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/views/board-view/inline-create-issue-form.tsx
  web/components/core/views/calendar-view/calendar.tsx
  web/components/core/views/calendar-view/inline-create-issue-form.tsx
  web/components/core/views/calendar-view/single-date.tsx
  web/components/core/views/gantt-chart-view/inline-create-issue-form.tsx
  web/components/core/views/list-view/inline-create-issue-form.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#2275 fix: gantt block getting clicked while moving the block
  web/components/gantt-chart/helpers/draggable.tsx
Labels: 🐛bug, 🌐frontend

#2277 chore: handle calendar date range in frontend
  web/components/core/views/calendar-view/calendar-header.tsx
  web/components/core/views/calendar-view/calendar.tsx
  web/components/core/views/calendar-view/single-date.tsx
  web/contexts/issue-view.context.tsx
  web/helpers/calendar.helper.ts
  web/hooks/use-calendar-issues-view.tsx
  web/types/view-props.d.ts
Labels: 🐛bug, 🌐frontend

#2279 chore: gantt chart empty state
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/sidebar.tsx
  web/components/issues/gantt-chart/blocks.tsx
Labels: 🌐frontend, 🌟improvement

#2280 style: calender quick-add same width as single date
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/calendar-view/inline-create-issue-form.tsx
  web/components/core/views/calendar-view/single-date.tsx
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
Labels: 🐛bug, 🌐frontend

#2278 chore: updated created at in draft issue
  apiserver/plane/api/views/issue.py
Labels: ⚙️backend, 🌟improvement

#2276 chore: make target dates inclusive when filtering
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend, 🧹chore

#2283 chore: sort order and issue props for global views
  apiserver/plane/db/migrations/0048_globalview_sort_order_workspacemember_issue_props_and_more.py
  apiserver/plane/db/models/view.py
  apiserver/plane/db/models/workspace.py
Labels: ⚙️backend, 🌟improvement

#2284 chore: removed project filter in global views
  apiserver/plane/db/models/view.py
Labels: 🐛bug, ⚙️backend

#2290 fix: inbox issue deletes
  apiserver/plane/api/views/inbox.py
Labels: 🐛bug, ⚙️backend

#2288 chore: views
  apiserver/plane/api/permissions/workspace.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/view.py
Labels: ⚙️backend, 🧹chore

#2282 chore: fetch issues from previous, current and next month in the calendar view
  web/hooks/use-calendar-issues-view.tsx
Labels: 🌐frontend, 🌟improvement

#2281 fix: issue activity estimate value bug fix
  web/components/core/activity.tsx
  web/hooks/use-estimate-option.tsx
Labels: 🌐frontend, 🎨UI / UX

#2289 fix: ui and bugs
  web/components/core/activity.tsx
  web/components/core/filters/filters-list.tsx
  web/components/core/filters/issues-view-filter.tsx
  web/components/core/views/board-view/inline-create-issue-form.tsx
  web/components/core/views/calendar-view/inline-create-issue-form.tsx
  web/components/core/views/gantt-chart-view/inline-create-issue-form.tsx
  web/components/core/views/issues-view.tsx
  web/components/core/views/list-view/inline-create-issue-form.tsx
  web/components/core/views/list-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/assignee-column/assignee-column.tsx
  web/components/core/views/spreadsheet-view/created-on-column/created-on-column.tsx
  web/components/core/views/spreadsheet-view/due-date-column/due-date-column.tsx
  web/components/core/views/spreadsheet-view/estimate-column/estimate-column.tsx
  web/components/core/views/spreadsheet-view/issue-column/issue-column.tsx
  web/components/core/views/spreadsheet-view/label-column/label-column.tsx
  web/components/core/views/spreadsheet-view/priority-column/priority-column.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/core/views/spreadsheet-view/start-date-column/start-date-column.tsx
  web/components/core/views/spreadsheet-view/state-column/state-column.tsx
  web/components/core/views/spreadsheet-view/updated-on-column/updated-on-column.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/onboarding/invite-members.tsx
  web/components/onboarding/user-details.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/constants/fetch-keys.ts
  web/hooks/use-issues-view.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2293 dev: calendar view layout revamp
  web/components/analytics/scope-and-demand/year-wise-issues.tsx
  web/components/core/views/all-views.tsx
  web/components/issue-layouts/filters/filter-selection.tsx
  web/components/issue-layouts/filters/filters-selection.tsx
  web/components/issue-layouts/layout-selection.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/calandar/index.ts
  web/components/issues/issue-layouts/calandar/root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/index.ts
  web/components/issues/issue-layouts/calendar/dropdowns/months-dropdown.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
  web/components/issues/issue-layouts/calendar/header.tsx
  web/components/issues/issue-layouts/calendar/index.ts
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/root.tsx
  web/components/issues/issue-layouts/calendar/types.d.ts
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
  web/components/issues/issue-layouts/index.ts
  web/constants/calendar.ts
  web/constants/issue.ts
  web/contexts/issue-view.context.tsx
  web/helpers/calendar.helper.ts
  web/helpers/date-time.helper.ts
  web/helpers/issue.helper.ts
  web/hooks/use-calendar-issues-view.tsx
  web/pages/calendar.tsx
  web/store/calendar.ts
  web/store/issue.ts
  web/store/issue_filters.ts
  web/store/root.ts
  web/types/view-props.d.ts
Labels: 🌐frontend, 🌟improvement

#2292 fix: notifications for created by me and assigned to me
  apiserver/plane/bgtasks/issue_activites_task.py
Labels: 🐛bug, ⚙️backend

#2299 chore: handle error when creating label with the same name
  apiserver/plane/api/views/issue.py
Labels: ⚙️backend, 🧹chore

#2294 chore: issues grouped kanban and swimlanes UI and functionality
  web/components/gantt-chart/contexts/index.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/assignee.tsx
  web/components/issues/issue-layouts/kanban/headers/card.tsx
  web/components/issues/issue-layouts/kanban/headers/created_by.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-root.tsx
  web/components/issues/issue-layouts/kanban/headers/label.tsx
  web/components/issues/issue-layouts/kanban/headers/priority.tsx
  web/components/issues/issue-layouts/kanban/headers/state-group.tsx
  web/components/issues/issue-layouts/kanban/headers/state.tsx
  web/components/issues/issue-layouts/kanban/headers/sub-group-by-card.tsx
  web/components/issues/issue-layouts/kanban/headers/sub-group-by-root.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/kanban/root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/constants/issue.ts
  web/store/issue.ts
  web/store/issue_detail.ts
  web/store/kanban_view.ts
  web/store/project.ts
Labels: 🌐frontend, 🎨UI / UX

#2300 chore: global issues ui improvement and bug fixes
  web/components/core/views/spreadsheet-view/issue-column/issue-column.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/issues/workspace-views/workpace-view-issues.tsx
  web/components/issues/workspace-views/workspace-all-issue.tsx
  web/components/views/single-view-item.tsx
  web/components/workspace/sidebar-menu.tsx
  web/components/workspace/views/modal.tsx
  web/components/workspace/views/workpace-view-navigation.tsx
  web/contexts/workspace-view-context.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/workspace-views/issues.tsx
Labels: 🌐frontend, 🎨UI / UX

#2297 refactor: filter components, constants and helper functions
  web/components/core/filters/date-filter-modal.tsx
  web/components/headers/project-issues.tsx
  web/components/issue-layouts/display-filters/display-filters-selection.tsx
  web/components/issue-layouts/display-filters/extra-options.tsx
  web/components/issue-layouts/display-filters/group-by.tsx
  web/components/issue-layouts/display-filters/issue-type.tsx
  web/components/issue-layouts/display-filters/order-by.tsx
  web/components/issue-layouts/display-filters/sub-group-by.tsx
  web/components/issue-layouts/filters/filters-selection.tsx
  web/components/issue-layouts/filters/start-date.tsx
  web/components/issue-layouts/filters/state-group.tsx
  web/components/issue-layouts/filters/target-date.tsx
  web/components/issue-layouts/helpers/dropdown.tsx
  web/components/issue-layouts/index.ts
  web/components/issue-layouts/root.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/months-dropdown.tsx
  web/components/issues/issue-layouts/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/header/display-filters/display-properties.tsx
  web/components/issues/issue-layouts/header/display-filters/extra-options.tsx
  web/components/issues/issue-layouts/header/display-filters/group-by.tsx
  web/components/issues/issue-layouts/header/display-filters/index.ts
  web/components/issues/issue-layouts/header/display-filters/issue-type.tsx
  web/components/issues/issue-layouts/header/display-filters/order-by.tsx
  web/components/issues/issue-layouts/header/display-filters/sub-group-by.tsx
  web/components/issues/issue-layouts/header/filters/assignees.tsx
  web/components/issues/issue-layouts/header/filters/created-by.tsx
  web/components/issues/issue-layouts/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/header/filters/index.ts
  web/components/issues/issue-layouts/header/filters/labels.tsx
  web/components/issues/issue-layouts/header/filters/priority.tsx
  web/components/issues/issue-layouts/header/filters/start-date.tsx
  web/components/issues/issue-layouts/header/filters/state-group.tsx
  web/components/issues/issue-layouts/header/filters/state.tsx
  web/components/issues/issue-layouts/header/filters/target-date.tsx
  web/components/issues/issue-layouts/header/helpers/dropdown.tsx
  web/components/issues/issue-layouts/header/helpers/filter-header.tsx
  web/components/issues/issue-layouts/header/helpers/filter-option.tsx
  web/components/issues/issue-layouts/header/helpers/index.ts
  web/components/issues/issue-layouts/header/index.ts
  web/components/issues/issue-layouts/header/layout-selection.tsx
  web/components/issues/issue-layouts/index.ts
  web/constants/filters.ts
  web/constants/issue.ts
  web/helpers/issue.helper.ts
  web/store/issue_filters.ts
  web/types/view-props.d.ts
Labels: 🌐frontend, 🌟improvement

#2302 dev: gantt chart implementation using MobX
  web/components/core/views/all-views.tsx
  web/components/cycles/gantt-chart/cycle-issues-layout.tsx
  web/components/gantt-chart/hooks/block-update.tsx
  web/components/headers/project-issues.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/gantt/index.ts
  web/components/issues/issue-layouts/gantt/root.tsx
  web/components/issues/issue-layouts/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/header/layout-selection.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/peek-overview/layout.tsx
  web/components/modules/gantt-chart/module-issues-layout.tsx
  web/components/views/gantt-chart.tsx
  web/constants/issue.ts
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/store/issue_filters.ts
Labels: 🌐frontend, 🌟improvement

#2301 chore: workspace view mutation fix ,bug fixes and code refactor
  web/components/core/views/spreadsheet-view/issue-column/issue-column.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/issues/workspace-views/workpace-view-issues.tsx
  web/components/issues/workspace-views/workspace-all-issue.tsx
  web/components/issues/workspace-views/workspace-assigned-issue.tsx
  web/components/issues/workspace-views/workspace-issue-view-option.tsx
  web/components/views/single-view-item.tsx
  web/components/workspace/views/workpace-view-navigation.tsx
  web/constants/fetch-keys.ts
  web/contexts/workspace-view-context.tsx
  web/pages/[workspaceSlug]/workspace-views/all-issues.tsx
  web/types/view-props.d.ts
Labels: 🌐frontend, 🎨UI / UX

#2303 chore: workspace view order by removed
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
Labels: 🌐frontend, 🎨UI / UX

#2305 dev: updated migrations for 0.13-dev
  apiserver/plane/db/migrations/0043_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0045_auto_20230915_0655.py
  apiserver/plane/db/migrations/0045_issueactivity_epoch_workspacemember_issue_props_and_more.py
  apiserver/plane/db/migrations/0046_auto_20230926_1015.py
  apiserver/plane/db/migrations/0047_auto_20230926_1029.py
  apiserver/plane/db/migrations/0048_globalview_sort_order_workspacemember_issue_props_and_more.py
Labels: ⚙️backend, 🔄migrations

#2306 dev: spreadsheet layout implementation using MobX
  web/components/core/views/all-views.tsx
  web/components/core/views/spreadsheet-view/single-issue.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-columns.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-issues.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-layouts/gantt/root.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/spreadsheet/index.ts
  web/components/issues/issue-layouts/spreadsheet/root.tsx
  web/components/issues/modal.tsx
  web/hooks/gantt-chart/issue-view.tsx
  web/hooks/use-spreadsheet-issues-view.tsx
Labels: 🌐frontend, 🌟improvement

#2307 fix: workspace view filters count fix
  web/components/core/filters/workspace-filters-list.tsx
  web/components/views/single-view-item.tsx
  web/components/workspace/views/single-workspace-view-item.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
  web/pages/[workspaceSlug]/workspace-views/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#2314 fix: workspace view redirection fix, style: spreadsheet view shadow scroll fix
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/workspace/views/modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2315 fix: update build workflow for the deploy app
  .github/workflows/Update_Docker_Images.yml
Labels: 🐛bug, 🐳docker

#2316 promote: develop to stage release
  .github/workflows/Update_Docker_Images.yml
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/workspace/views/modal.tsx
Labels: 📢promote

#2317 fix: workspace view add issue mutation fix
  web/components/issues/modal.tsx
Labels: 🐛bug, 🌐frontend
