Repository makeplane/plane, pull requests merged in 2023-10, with the labels that each got.

#2325 dev: applied filters list implementation using MobX
  web/components/core/views/all-views.tsx
  web/components/issue-layouts/root.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/months-dropdown.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/filters/applied-filters/date.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/index.ts
  web/components/issues/issue-layouts/filters/applied-filters/label.tsx
  web/components/issues/issue-layouts/filters/applied-filters/members.tsx
  web/components/issues/issue-layouts/filters/applied-filters/priority.tsx
  web/components/issues/issue-layouts/filters/applied-filters/state-group.tsx
  web/components/issues/issue-layouts/filters/applied-filters/state.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/extra-options.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/group-by.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/index.ts
  web/components/issues/issue-layouts/filters/header/display-filters/issue-type.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/order-by.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/sub-group-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/index.ts
  web/components/issues/issue-layouts/filters/header/filters/labels.tsx
  web/components/issues/issue-layouts/filters/header/filters/priority.tsx
  web/components/issues/issue-layouts/filters/header/filters/start-date.tsx
  web/components/issues/issue-layouts/filters/header/filters/state-group.tsx
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/components/issues/issue-layouts/filters/header/filters/target-date.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/issues/issue-layouts/filters/header/helpers/filter-header.tsx
  web/components/issues/issue-layouts/filters/header/helpers/filter-option.tsx
  web/components/issues/issue-layouts/filters/header/helpers/index.ts
  web/components/issues/issue-layouts/filters/header/index.ts
  web/components/issues/issue-layouts/filters/header/layout-selection.tsx
  web/components/issues/issue-layouts/filters/index.ts
  web/components/issues/issue-layouts/index.ts
  web/store/issue_filters.ts
Labels: 🌐frontend, 🌟improvement

#2333 dev: create action to sync PR changes to the repo
  .github/workflows/create-sync-pr.yml
Labels: 🔄workflows

#2346 dev: update sync workflow to run only when the source repo is configured
  .github/workflows/build-test-pull-request.yml
  .github/workflows/create-sync-pr.yml
  .github/workflows/update-docker-images.yml
Labels: 🚀CI/CD

#2359 refactor: filter components
  web/components/core/views/all-views.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/months-dropdown.tsx
  web/components/issues/issue-layouts/calendar/header.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/index.ts
  web/components/issues/issue-layouts/filters/applied-filters/root.tsx
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/labels.tsx
  web/components/issues/issue-layouts/filters/header/filters/start-date.tsx
  web/components/issues/issue-layouts/filters/header/filters/state-group.tsx
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/components/issues/issue-layouts/filters/header/filters/target-date.tsx
Labels: 🌐frontend, 🛠️refactor

#2340 fix: issue relation mutation and draft issue
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/emoji-icon-picker/index.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/sidebar-select/blocked.tsx
  web/components/issues/sidebar-select/blocker.tsx
  web/components/issues/sidebar-select/duplicate.tsx
  web/components/issues/sidebar-select/relates-to.tsx
  web/components/issues/sidebar.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2365 fix: sync workflow fixes
  .github/workflows/create-sync-pr.yml
Labels: 🚀CI/CD

#2366 fix: sync job pr description escaped values fix
  .github/workflows/create-sync-pr.yml
Labels: 🚀CI/CD

#2348 dev: update apiserver configuration files
  apiserver/.env.example
  apiserver/plane/settings/production.py
Labels: ⚙️backend, ⚙️config changes

#2350 fix: themening validation in store init.
  web/lib/mobx/store-init.tsx
Labels: 🐛bug, 🌐frontend

#2368 chore: removed the issue draft log from my profile
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, 🧹chore

#2351 chore: layout access validation and switch in plane deploy issues route
  space/components/issues/navbar/index.tsx
Labels: 🌐frontend, 🧹chore

#2354 fix: table options menu positioning
  web/components/tiptap/index.tsx
  web/components/tiptap/table-menu/index.tsx
Labels: 🐛bug, 🌐frontend

#2355 dev: configuration endpoint for frontend client
  apiserver/.env.example
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/config.py
  apiserver/plane/api/views/external.py
  apiserver/plane/api/views/release.py
  apiserver/plane/settings/local.py
  apiserver/plane/settings/production.py
  apiserver/plane/settings/selfhosted.py
  apiserver/plane/settings/staging.py
Labels: ⚙️backend, ⚙️config changes

#2349 fix: 404 when redirecting user clicks on Sign In button
  space/components/accounts/sign-in.tsx
  space/components/issues/navbar/index.tsx
  space/components/views/login.tsx
  space/lib/mobx/store-init.tsx
  space/pages/index.tsx
  space/pages/login/index.tsx
  space/store/user.ts
Labels: 🐛bug, 🌐frontend, 🚀space

#2369 fix: project setting member role validation
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/project/member-select.tsx
  web/components/ui/dropdowns/custom-menu.tsx
  web/components/ui/empty-state.tsx
  web/components/ui/toggle-switch.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
Labels: 🐛bug, 🌐frontend

#2370 chore: project covers endpoint
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/project.py
Labels: ⚙️backend, 🧹chore

#2375 feat: default project cover images tab on the change cover popover
  space/services/file.service.ts
  turbo.json
  web/components/core/image-picker-popover.tsx
  web/components/project/create-project-modal.tsx
  web/next.config.js
  web/services/file.service.ts
Labels: ✨feature, 🌐frontend

#2378 chore: remove unnecessary OAuth envs
  space/components/accounts/github-login-button.tsx
  space/components/accounts/google-login.tsx
  space/components/accounts/sign-in.tsx
  space/services/app-config.service.ts
  turbo.json
  web/pages/index.tsx
Labels: 🐛bug, 🌐frontend

#2380 fix: added user store variables in Mobx store observable
  space/store/user.ts
Labels: 🐛bug, 🌐frontend

#2381 fix: backlog and started state group icons
  web/components/icons/state/backlog.tsx
  web/components/icons/state/started.tsx
Labels: 🌐frontend, 🌟improvement

#2382 fix: removed default theme setting in the index page
  web/pages/index.tsx
Labels: 🐛bug, 🌐frontend

#2383 refactor: change naming convention of the module filter store
  web/components/headers/module-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/module-root.tsx
  web/components/issues/issue-layouts/module-all-layouts.tsx
  web/constants/issue.ts
  web/store/module_filters.ts
  web/store/modules.ts
Labels: 🌐frontend, 🛠️refactor

#2398 chore: integrate popper js
  web/components/automation/auto-archive-automation.tsx
  web/components/core/theme/theme-switch.tsx
  web/components/core/views/board-view/single-board.tsx
  web/components/core/views/board-view/single-issue.tsx
  web/components/core/views/list-view/single-list.tsx
  web/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  web/components/integration/github/select-repository.tsx
  web/components/integration/jira/give-details.tsx
  web/components/issues/main-content.tsx
  web/components/issues/peek-overview/header.tsx
  web/components/issues/select/estimate.tsx
  web/components/issues/sidebar-select/cycle.tsx
  web/components/issues/sidebar-select/estimate.tsx
  web/components/issues/sidebar-select/module.tsx
  web/components/issues/sidebar-select/priority.tsx
  web/components/issues/sidebar-select/state.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/issues/view-select/assignee.tsx
  web/components/issues/view-select/estimate.tsx
  web/components/issues/view-select/label.tsx
  web/components/issues/view-select/priority.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar-select/select-members.tsx
  web/components/notifications/notification-card.tsx
  web/components/onboarding/user-details.tsx
  web/components/pages/single-page-block.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/label-select.tsx
  web/components/project/member-select.tsx
  web/components/project/members-select.tsx
  web/components/project/priority-select.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/states/state-select.tsx
  web/components/ui/dropdowns/custom-menu.tsx
  web/components/ui/dropdowns/custom-search-select.tsx
  web/components/ui/dropdowns/custom-select.tsx
  web/components/ui/dropdowns/types.d.ts
  web/package.json
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  yarn.lock
Labels: 🌐frontend

#2412 chore: implement new worksapace wrapper for global views
  packages/ui/dist/index.d.ts
  packages/ui/dist/index.js
  packages/ui/dist/index.mjs
  web/components/headers/global-issues.tsx
  web/components/views/view-list-item.tsx
  web/components/views/views-list.tsx
  web/components/workspace/views/header.tsx
  web/components/workspace/views/view-list-item.tsx
  web/components/workspace/views/views-list.tsx
  web/helpers/analytics.helper.ts
  web/layouts/app-layout/layout.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
  web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
  web/pages/[workspaceSlug]/workspace-views/all-issues.tsx
  web/pages/[workspaceSlug]/workspace-views/assigned.tsx
  web/pages/[workspaceSlug]/workspace-views/created.tsx
  web/pages/[workspaceSlug]/workspace-views/index.tsx
  web/pages/[workspaceSlug]/workspace-views/subscribed.tsx
Labels: 🌐frontend

#2356 fix: web-view action permission, logs, archive issue, and more
  web/components/issues/comment/comment-reaction.tsx
  web/components/issues/sidebar-select/cycle.tsx
  web/components/web-view/activity-message.tsx
  web/components/web-view/commend-card.tsx
  web/components/web-view/confirm-delete.tsx
  web/components/web-view/date-selector.tsx
  web/components/web-view/index.ts
  web/components/web-view/issue-activity.tsx
  web/components/web-view/issue-attachments.tsx
  web/components/web-view/issue-link-list.tsx
  web/components/web-view/issue-properties-detail.tsx
  web/components/web-view/issue-web-view-form.tsx
  web/components/web-view/issues-select-bottom-sheet.tsx
  web/components/web-view/select-assignee.tsx
  web/components/web-view/select-blocked-by.tsx
  web/components/web-view/select-blocked.tsx
  web/components/web-view/select-blocker-to.tsx
  web/components/web-view/select-blocker.tsx
  web/components/web-view/select-cycle.tsx
  web/components/web-view/select-duplicate.tsx
  web/components/web-view/select-module.tsx
  web/components/web-view/select-parent.tsx
  web/components/web-view/select-priority.tsx
  web/components/web-view/select-relates-to.tsx
  web/components/web-view/select-state.tsx
  web/components/web-view/spinner.tsx
  web/components/web-view/sub-issues.tsx
  web/components/web-view/web-view-modal.tsx
  web/layouts/web-view-layout/index.tsx
  web/pages/m/[workspaceSlug]/editor.tsx
  web/pages/m/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/public/web-view-spinner.png
  web/styles/globals.css
Labels: 🐛bug, 🌐frontend

#2416 chore: project card revamp and refactor
  web/components/project/card.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2411 [bug]: fix recent page hiding last item on scroll #1468
  web/components/pages/pages-list/recent-pages-list.tsx
Labels: 🌐frontend, 🎨UI / UX

#2376 dev: hub compose file update
  docker-compose-hub.yml
  web/components/pages/pages-list/recent-pages-list.tsx
Labels: 🐳docker, devops

#2444 stage: hub compose file update (#2376)
  docker-compose-hub.yml
  web/components/pages/pages-list/recent-pages-list.tsx
Labels: 🐳docker

#2407 chore: api endpoints
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/base.py
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/serializers/user.py
  apiserver/plane/api/serializers/workspace.py
  apiserver/plane/api/urls/__init__.py
  apiserver/plane/api/urls/analytic.py
  apiserver/plane/api/urls/asset.py
  apiserver/plane/api/urls/authentication.py
  apiserver/plane/api/urls/configuration.py
  apiserver/plane/api/urls/cycle.py
  apiserver/plane/api/urls/estimate.py
  apiserver/plane/api/urls/gpt.py
  apiserver/plane/api/urls/importer.py
  apiserver/plane/api/urls/inbox.py
  apiserver/plane/api/urls/integration.py
  apiserver/plane/api/urls/issue.py
  apiserver/plane/api/urls/module.py
  apiserver/plane/api/urls/notification.py
  apiserver/plane/api/urls/page.py
  apiserver/plane/api/urls/project.py
  apiserver/plane/api/urls/public_board.py
  apiserver/plane/api/urls/release_note.py
  apiserver/plane/api/urls/search.py
  apiserver/plane/api/urls/state.py
  apiserver/plane/api/urls/unsplash.py
  apiserver/plane/api/urls/user.py
  apiserver/plane/api/urls/views.py
  apiserver/plane/api/urls/workspace.py
  apiserver/plane/api/urls_deprecated.py
  apiserver/plane/api/views/analytic.py
  apiserver/plane/api/views/auth_extended.py
  apiserver/plane/api/views/authentication.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/notification.py
  apiserver/plane/api/views/oauth.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/user.py
  apiserver/plane/api/views/workspace.py
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/utils/analytics_plot.py
  apiserver/runtime.txt
Labels: ⚙️backend, 🧹chore

#2451 chore: scale down tailwind spacing and font sizes to 90% of default
  packages/tailwind-config-custom/tailwind.config.js
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2448 style: project card revamp
  web/components/headers/projects.tsx
  web/components/project/card.tsx
  web/types/projects.d.ts
Labels: 🌐frontend, 🎨UI / UX

#2449 fix: profile pic dimension bug fix
  web/components/issues/activity.tsx
  web/components/profile/sidebar.tsx
  web/components/web-view/issue-activity.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2452 fix: sidebar collapse state not working
  web/components/project/sidebar-list-item.tsx
  web/components/project/sidebar-list.tsx
  web/components/workspace/help-section.tsx
Labels: 🐛bug, 🌐frontend

#2450 chore: ui package code refactor
  packages/ui/package.json
  packages/ui/src/button/button.tsx
  packages/ui/src/tooltip/tooltip.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2455 fix: project layout added and theming fixes
  packages/ui/package.json
  packages/ui/src/form-fields/index.tsx
  packages/ui/src/form-fields/input-color-picker.tsx
  web/components/command-palette/change-interface-theme.tsx
  web/components/core/theme/color-picker-input.tsx
  web/components/core/theme/custom-theme-selector.tsx
  web/components/core/theme/theme-switch.tsx
  web/components/headers/cycles.tsx
  web/components/headers/index.ts
  web/components/headers/modules.tsx
  web/components/headers/profile-preferences.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-views.tsx
  web/components/icons/module-icon.tsx
  web/constants/themes.ts
  web/layouts/app-layout/layout.tsx
  web/layouts/auth-layout/index.ts
  web/layouts/auth-layout/project-wrapper.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/lib/mobx/store-init.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
  web/store/project/project.store.ts
  web/store/user.store.ts
  web/types/users.d.ts
Labels: 🎨UI / UX

#2426 chore: removed notification for draft issues
  apiserver/plane/bgtasks/issue_activites_task.py
Labels: ⚙️backend, 🌟improvement

#2454 refactor: exception handling
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/views/analytic.py
  apiserver/plane/api/views/api_token.py
  apiserver/plane/api/views/asset.py
  apiserver/plane/api/views/auth_extended.py
  apiserver/plane/api/views/authentication.py
  apiserver/plane/api/views/base.py
  apiserver/plane/api/views/config.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/estimate.py
  apiserver/plane/api/views/exporter.py
  apiserver/plane/api/views/external.py
  apiserver/plane/api/views/importer.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/integration/base.py
  apiserver/plane/api/views/integration/github.py
  apiserver/plane/api/views/integration/slack.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/notification.py
  apiserver/plane/api/views/oauth.py
  apiserver/plane/api/views/page.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/search.py
  apiserver/plane/api/views/state.py
  apiserver/plane/api/views/user.py
  apiserver/plane/api/views/view.py
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, 🛠️refactor

#2456 chore: icon improvement
  web/components/command-palette/shortcuts-modal.tsx
  web/components/issues/issue-layouts/filters/header/layout-selection.tsx
  web/components/notifications/notification-card.tsx
  web/components/notifications/notification-popover.tsx
  web/components/profile/profile-issues-view-options.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/project/sidebar-list.tsx
  web/components/ui/multi-level-dropdown.tsx
  web/components/workspace/help-section.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-menu.tsx
Labels: 🌐frontend, 🎨UI / UX

#2460 chore: color picker popperjs integration
  packages/ui/package.json
  packages/ui/src/form-fields/input-color-picker.tsx
  yarn.lock
Labels: 🌐frontend, 🎨UI / UX

#2459 fix: wrap the project auth wrapper with observer
  web/layouts/auth-layout/project-wrapper.tsx
Labels: 🐛bug, 🌐frontend

#2461 fix: font sizes and sidebar icons
  packages/tailwind-config-custom/tailwind.config.js
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/labels/single-label-group.tsx
  web/components/notifications/notification-popover.tsx
  web/components/pages/single-page-block.tsx
  web/components/project/publish-project/modal.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/project/sidebar-list.tsx
  web/components/web-view/issue-attachments.tsx
  web/components/web-view/issue-link-list.tsx
  web/components/web-view/sub-issues.tsx
  web/components/workspace/sidebar-menu.tsx
  web/pages/[workspaceSlug]/workspace-views/issues.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2458 chore: breadcrumbs ui component
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  packages/ui/src/breadcrumbs/index.tsx
  packages/ui/src/index.tsx
  web/components/headers/cycles.tsx
  web/components/headers/modules.tsx
  web/components/headers/profile-preferences.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/headers/workspace-analytics.tsx
  web/layouts/profile-layout.tsx
  web/pages/[workspaceSlug]/me/my-issues.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
Labels: 🌐frontend, 🛠️refactor

#2464 style: project page ui improvement
  web/components/project/card.tsx
  web/components/project/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#2453 style: create/update issue modal ui improvement
  web/components/issues/form.tsx
  web/components/issues/modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2465 fix: command paletter mobx implementation
  web/components/command-palette/command-modal.tsx
  web/components/command-palette/command-pallette.tsx
  web/components/command-palette/index.ts
  web/components/command-palette/shortcuts-modal.tsx
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/cycles/modal.tsx
  web/components/cycles/select.tsx
  web/components/headers/project-views.tsx
  web/components/modules/modal.tsx
  web/components/pages/create-update-page-modal.tsx
  web/components/pages/pages-view.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/sidebar-list.tsx
  web/components/views/modal.tsx
  web/layouts/app-layout/layout.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/store/command-palette.store.ts
  web/store/root.ts
  web/store/theme.store.ts
  web/store/user.store.ts
Labels: 🎨UI / UX

#2469 fix: global view filters dropdown overflow issue
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/profile/profile-issues-filter.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2472 chore: add emoji to projects list
  web/components/issues/select/project.tsx
Labels: 🌐frontend, 🎨UI / UX

#2475 fix: svg icon properties naming convention fix
  packages/ui/src/icons/admin-profile-icon.tsx
  packages/ui/src/icons/archive-icon.tsx
  packages/ui/src/icons/contrast-icon.tsx
  packages/ui/src/icons/copy-icon.tsx
  packages/ui/src/icons/create-icon.tsx
  packages/ui/src/icons/dice-icon.tsx
  packages/ui/src/icons/external-link-icon.tsx
  packages/ui/src/icons/layer-stack.tsx
  packages/ui/src/icons/layers-icon.tsx
  packages/ui/src/icons/modal-peek-icon.tsx
  packages/ui/src/icons/panel-center-icon.tsx
  packages/ui/src/icons/photo-filter-icon.tsx
  packages/ui/src/icons/related-icon.tsx
  packages/ui/src/icons/side-peek-icon.tsx
  packages/ui/src/icons/subscribe-icon.tsx
  packages/ui/src/icons/user-group-icon.tsx
  web/components/icons/module-icon.tsx
Labels: 🌐frontend, 🧹chore

#2474 refactor: remove unused hooks
  web/components/core/image-picker-popover.tsx
  web/components/core/modals/image-upload-modal.tsx
  web/components/exporter/export-modal.tsx
  web/components/exporter/guide.tsx
  web/components/integration/github/import-data.tsx
  web/components/integration/jira/give-details.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/modal.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/hooks/use-projects.tsx
  web/hooks/use-theme.tsx
  web/hooks/use-workspace-details.tsx
  web/hooks/use-workspaces.tsx
  web/layouts/app-layout-legacy/app-sidebar.tsx
  web/pages/onboarding/index.tsx
Labels: 🌐frontend, 🛠️refactor

#2477 chore: settings page refactoring
  web/components/common/empty-state.tsx
  web/components/headers/index.ts
  web/components/headers/project-settings.tsx
  web/components/headers/workspace-settings.tsx
  web/components/notifications/notification-popover.tsx
  web/components/project/delete-project-section.tsx
  web/components/project/index.ts
  web/layouts/setting-layout/project-setting-layout/index.tsx
  web/layouts/setting-layout/project-setting-layout/layout.tsx
  web/layouts/setting-layout/project-setting-layout/sidebar.tsx
  web/layouts/setting-layout/workspace-setting-layout/index.tsx
  web/layouts/setting-layout/workspace-setting-layout/layout.tsx
  web/layouts/setting-layout/workspace-setting-layout/sidebar.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2478 refactor: spreadsheet layout
  web/components/issues/issue-layouts/spreadsheet/assignee-column/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/assignee-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/columns-list.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/index.ts
  web/components/issues/issue-layouts/spreadsheet/columns/issue/index.ts
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/created-on-column/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/created-on-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/due-date-column/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/due-date-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/estimate-column/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/estimate-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/index.ts
  web/components/issues/issue-layouts/spreadsheet/label-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/label-column/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/priority-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/priority-column/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-layouts/spreadsheet/start-date-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/start-date-column/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/state-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/state-column/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/updated-on-column/index.ts
  web/components/issues/issue-layouts/spreadsheet/updated-on-column/updated-on-column.tsx
  web/components/issues/view-select/start-date.tsx
  web/styles/command-pallette.css
Labels: 🌐frontend, 🛠️refactor

#2479 chore: fetch cycles, modules and views in the project wrapper
  web/layouts/auth-layout/project-wrapper.tsx
Labels: 🌐frontend

#2483 fix: modal alignment fix
  web/components/core/modals/bulk-delete-issues-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2485 fix: issues mutation on changing filters
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/gantt-chart/sidebar.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/issue-layouts/kanban/headers/priority.tsx
  web/components/issues/issue-layouts/list/headers/priority.tsx
  web/components/issues/modal.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/lib/mobx/store-init.tsx
  web/services/issue/issue.service.ts
  web/store/cycle/cycle_issue.store.ts
  web/store/global-view/global_view_issues.store.ts
  web/store/issue/issue.store.ts
  web/store/issue/issue_detail.store.ts
  web/store/module/module_issue.store.ts
  web/store/project-view/project_view_issues.store.ts
Labels: 🐛bug, 🌐frontend

#2491 style: project select dropdown & modals ui improvement
  packages/ui/src/form-fields/input.tsx
  packages/ui/src/form-fields/textarea.tsx
  web/components/cycles/cycle-create-edit-modal.tsx
  web/components/cycles/form.tsx
  web/components/cycles/modal.tsx
  web/components/issues/select/project.tsx
  web/components/modules/form.tsx
  web/components/modules/modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2493 fix: workspaces list not being fetched, display properties endpoint updated
  web/components/workspace/sidebar-dropdown.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/services/issue/issue.service.ts
  web/store/issue/issue_filters.store.ts
Labels: 🐛bug, 🌐frontend

#2494 chore: project page link error
  web/components/project/card.tsx
Labels: 🐛bug, 🌐frontend

#2495 chore: create workspace ui improvement
  web/components/workspace/create-workspace-form.tsx
  web/pages/create-workspace/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#2498 chore: implemented store for issue reaction, comments, and comment reactions. Implemented ui and components for issue reactions in issue peek overview
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/reactions/index.ts
  web/components/issues/issue-peek-overview/reactions/preview.tsx
  web/components/issues/issue-peek-overview/reactions/root.tsx
  web/components/issues/issue-peek-overview/reactions/selector.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/constants/issue.ts
  web/store/issue/issue_detail.store.ts
Labels: 🌐frontend, 🧹chore

#2501 chore: sign in page ui improvement and redirection fix
  web/components/account/email-code-form.tsx
  web/components/account/email-forgot-password-form.tsx
  web/components/account/email-password-form.tsx
  web/components/account/email-signup-form.tsx
  web/pages/accounts/sign-up.tsx
Labels: 🌐frontend, 🎨UI / UX

#2504 chore: redirection validation and create workspace form fix
  web/components/page-views/signin.tsx
  web/components/workspace/create-workspace-form.tsx
Labels: 🌐frontend, 🎨UI / UX

#2506 chore: removed heroicons package
  space/components/accounts/onboarding-form.tsx
  space/components/issues/navbar/issue-filter.tsx
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/components/ui/dropdown.tsx
  space/components/ui/toast-alert.tsx
  space/package.json
  web/components/command-palette/command-modal.tsx
  web/package.json
  yarn.lock
Labels: 🌐frontend, 🧹chore

#2507 chore: issue peek overview issue comments and comment reactions
  web/components/issues/issue-peek-overview/activity/card.tsx
  web/components/issues/issue-peek-overview/activity/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
  web/components/issues/issue-peek-overview/activity/comment-reaction.tsx
  web/components/issues/issue-peek-overview/activity/index.ts
  web/components/issues/issue-peek-overview/activity/view.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/reactions/root.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/store/issue/issue_detail.store.ts
Labels: 🌐frontend, 🧹chore

#2514 refactor: publish project modal
  web/components/headers/project-issues.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/project/index.ts
  web/components/project/publish-project/modal.tsx
  web/components/project/sidebar-list-item.tsx
  web/store/project/project.store.ts
  web/store/project/project_publish.store.ts
Labels: 🌐frontend, 🛠️refactor

#2516 fix: Gantt chart blocks drag and resize logic
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
  web/components/issues/issue-layouts/gantt/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/root.tsx
  web/store/cycle/cycle_issue.store.ts
  web/store/issue/issue.store.ts
  web/store/module/module_issue.store.ts
  web/store/project-view/project_view_issues.store.ts
Labels: 🐛bug, 🌐frontend

#2517 refactor: cycle, module and view layout roots
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
Labels: 🌐frontend, 🛠️refactor

#2518 chore: removed material icons package
  space/components/issues/peek-overview/header.tsx
  space/package.json
  web/package.json
  yarn.lock
Labels: 🌐frontend, 🧹chore

#2484 dev: Self Hosting simplified with shell script
  .gitignore
  deploy/heroku/Dockerfile
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install.sh
  deploy/selfhost/variables.env
  docker-compose-hub.yml
  web/components/pages/pages-list/recent-pages-list.tsx
Labels: 🏠self-hosted, 🐳docker, ⚙️config changes

#2523 fix: command palette fix
  web/store/command-palette.store.ts
Labels: 🐛bug, 🌐frontend

#2525 fix: extend custom tailwind variables instead of overwriting
  packages/tailwind-config-custom/tailwind.config.js
Labels: 🐛bug, 🌐frontend

#2526 style: command modal style
  web/styles/command-pallette.css
Labels: 🌐frontend, 🎨UI / UX

#2527 chore: sidebar fix and ui improvement
  web/components/cycles/sidebar.tsx
  web/components/issues/sidebar-select/duplicate.tsx
  web/components/issues/sidebar-select/relates-to.tsx
Labels: 🌐frontend, 🎨UI / UX

#2528 fix: cycle modal redundant component fix
  web/components/command-palette/command-pallette.tsx
  web/components/cycles/cycle-create-edit-modal.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/delete-modal.tsx
  web/components/cycles/form.tsx
  web/components/cycles/index.ts
  web/components/cycles/modal.tsx
  web/components/cycles/select.tsx
  web/components/cycles/sidebar.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/store/cycle/cycles.store.ts
Labels: 🌐frontend

#2521 refactor: modules list page
  web/components/headers/index.ts
  web/components/headers/modules-list.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/modal.tsx
  web/components/modules/delete-module-modal.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/components/modules/index.ts
  web/components/modules/modal.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/modules-list-view.tsx
  web/components/modules/sidebar.tsx
  web/components/project/sidebar-list-item.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/services/module.service.ts
  web/store/issue/issue_detail.store.ts
  web/store/module/module_filters.store.ts
  web/store/module/modules.store.ts
Labels: 🌐frontend, 🛠️refactor

#2532 chore: layout refactor
  web/components/headers/index.ts
  web/components/headers/user-profile.tsx
  web/components/profile/navbar.tsx
  web/layouts/app-layout-legacy/app-header.tsx
  web/layouts/app-layout-legacy/app-sidebar.tsx
  web/layouts/app-layout-legacy/layout.tsx
  web/layouts/auth-layout-legacy/index.ts
  web/layouts/auth-layout-legacy/project-authorization-wrapper.tsx
  web/layouts/auth-layout-legacy/user-authorization-wrapper.tsx
  web/layouts/auth-layout-legacy/workspace-authorization-wrapper.tsx
  web/layouts/profile-layout.tsx
  web/layouts/profile-layout/index.ts
  web/layouts/profile-layout/layout.tsx
  web/layouts/setting-layout/index.ts
  web/layouts/setting-layout/project-setting-layout/layout.tsx
  web/layouts/setting-layout/workspace-setting-layout/layout.tsx
  web/pages/[workspaceSlug]/me/my-issues.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/index.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/index.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/pages/[workspaceSlug]/workspace-views/issues.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2535 chore: implemented drag and drop between dates for project issues, cycle, module, and project views for calendar layout
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/roots/module-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/store/cycle/cycle_issue_calendar_view.store.ts
  web/store/cycle/index.ts
  web/store/issue/index.ts
  web/store/issue/issue_calendar_view.store.ts
  web/store/module/index.ts
  web/store/module/module_issue_calendar_view.store.ts
  web/store/project-view/index.ts
  web/store/project-view/project_view_issue_calendar_view.store.ts
  web/store/project-view/project_view_issues.store.ts
  web/store/root.ts
Labels: 🌐frontend, 🧹chore

#2537 chore: issue comment reaction workflow and mutation update
  web/components/issues/issue-peek-overview/activity/card.tsx
  web/components/issues/issue-peek-overview/activity/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/comment-reaction.tsx
  web/components/issues/issue-peek-overview/activity/view.tsx
  web/components/issues/issue-peek-overview/reactions/root.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/store/issue/issue_detail.store.ts
Labels: 🌐frontend, 🧹chore

#2540 [fix] `docker-compose` failing to build images
  packages/editor/core/package.json
  packages/ui/package.json
  space/package.json
Labels: 🐳docker

#2533 chore: implement MobX in project features settings
  web/components/project/delete-project-modal.tsx
  web/components/project/index.ts
  web/components/project/settings-sidebar.tsx
  web/components/project/settings/features-list.tsx
  web/components/project/settings/index.ts
  web/components/project/settings/single-label.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/project/sidebar-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/services/track_event.service.ts
  web/store/project/project.store.ts
  web/store/user.store.ts
Labels: 🐛bug, 🌐frontend

#2547 fix: enabling the nextjs static site generation for web and space
  .gitignore
  space/next.config.js
  space/package.json
  web/next.config.js
  web/package.json
Labels: 🌐frontend, ⚙️config changes

#2534 chore: total issues count for issue listing endpoint
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/base.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/view.py
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, 🧹chore

#2524 chore: make module create and list endpoint response structure similar
  apiserver/plane/api/views/module.py
Labels: ⚙️backend, 🧹chore

#2258 chore: user issue display properties
  apiserver/plane/api/urls/issue.py
  apiserver/plane/api/urls_deprecated.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/project.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/db/migrations/0046_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/issue.py
Labels: ⚙️backend, 🔄migrations, 🧹chore

#2417 fix: issue filters validation
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend, 🌟improvement

#2418 chore: removed duplicate issues for multiple assignees or labels
  apiserver/plane/api/views/issue.py
Labels: 🐛bug, ⚙️backend

#2503 refactor: issue activity
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/notification_task.py
Labels: ⚙️backend, 🧹chore, 🛠️refactor

#2548 style: module ui revamp
  packages/tailwind-config-custom/tailwind.config.js
  packages/ui/src/progress/circular-progress-indicator.tsx
  packages/ui/src/progress/index.tsx
  web/components/core/sidebar/links-list.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/core/sidebar/single-progress-stats.tsx
  web/components/headers/modules-list.tsx
  web/components/modules/index.ts
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/module-peek-overview.tsx
  web/components/modules/modules-list-view.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar-select/select-members.tsx
  web/components/modules/sidebar.tsx
  web/components/ui/avatar.tsx
  web/constants/module.ts
  web/helpers/date-time.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/public/empty-state/empty_label.svg
  web/public/empty-state/empty_members.svg
Labels: 🌐frontend, 🎨UI / UX, 🛠️refactor

#2552 fix: html sanitization function
  web/components/notifications/notification-card.tsx
  web/helpers/string.helper.ts
Labels: 🐛bug, 🌐frontend

#2555 revert: issues endpoint
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/view.py
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, revert

#2531 chore: add empty state for list and spreadsheet layouts
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/global-view.tsx
  web/components/issues/issue-layouts/empty-states/index.ts
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/empty-states/project-view.tsx
  web/components/issues/issue-layouts/empty-states/project.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/list/index.ts
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/store/archived-issues/issue.store.ts
  web/store/cycle/cycle_issue.store.ts
  web/store/cycle/cycle_issue_calendar_view.store.ts
  web/store/draft-issues/issue.store.ts
  web/store/issue/issue.store.ts
  web/store/module/module_issue.store.ts
  web/store/module/module_issue_calendar_view.store.ts
  web/store/project-view/project_view_issues.store.ts
Labels: 🌐frontend, 🧹chore

#2561 dev: implemented MobX in workspace settings and create workspace form
  web/components/integration/jira/import-users.tsx
  web/components/issues/index.ts
  web/components/issues/my-issues/index.ts
  web/components/issues/my-issues/my-issues-select-filters.tsx
  web/components/issues/my-issues/my-issues-view-options.tsx
  web/components/issues/my-issues/my-issues-view.tsx
  web/components/onboarding/workspace.tsx
  web/components/profile/index.ts
  web/components/profile/profile-issues-view-options.tsx
  web/components/workspace/confirm-workspace-member-remove.tsx
  web/components/workspace/create-workspace-form.tsx
  web/components/workspace/delete-workspace-modal.tsx
  web/components/workspace/index.ts
  web/components/workspace/send-workspace-invitation-modal.tsx
  web/components/workspace/settings/index.ts
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/settings/members-list.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/contexts/workspace-member.context.tsx
  web/hooks/my-issues/use-my-issues-filter.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/pages/create-workspace/index.tsx
  web/services/workspace.service.ts
  web/store/user.store.ts
  web/store/workspace/workspace.store.ts
  web/store/workspace/workspace_filters.store.ts
  web/types/users.d.ts
  web/types/workspace.d.ts
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2563 fix: global views filters, issue update function
  web/components/headers/global-issues.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/workspace/views/form.tsx
  web/store/global-view/global_view_issues.store.ts
Labels: 🐛bug, 🌐frontend, 🛠️refactor

#2564 fix: edit project button redirection
  web/components/project/card.tsx
  web/components/project/index.ts
  web/components/project/settings/delete-project-section.tsx
  web/components/project/settings/index.ts
  web/pages/404.tsx
Labels: 🐛bug, 🌐frontend

#2565 fix: custom theme form validations
  packages/ui/src/form-fields/input-color-picker.tsx
  web/components/core/theme/custom-theme-selector.tsx
Labels: 🐛bug, 🌐frontend, 🛠️refactor

#2566 style: list layout
  packages/ui/src/dropdowns/helper.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/profile/profile-issues-filter.tsx
Labels: 🌐frontend, 🎨UI / UX

#2569 chore: update members endpoint
  web/components/integration/github/single-user-select.tsx
  web/components/integration/jira/import-users.tsx
  web/components/issues/attachment/attachments.tsx
  web/components/issues/select/assignee.tsx
  web/components/issues/sidebar-select/assignee.tsx
  web/components/modules/select/lead.tsx
  web/components/modules/select/members.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar-select/select-members.tsx
  web/components/pages/pages-view.tsx
  web/components/project/member-select.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/ui/avatar.tsx
  web/components/views/select-filters.tsx
  web/components/web-view/select-assignee.tsx
  web/constants/fetch-keys.ts
  web/hooks/use-project-members.tsx
  web/hooks/use-workspace-members.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/workspace-invitations/index.tsx
  web/services/project/project.service.ts
  web/services/project/project_invitation.service.ts
  web/services/workspace.service.ts
  web/store/project/project.store.ts
  web/store/workspace/workspace.store.ts
  web/types/projects.d.ts
Labels: 🌐frontend, 🛠️refactor

#2554 style: spreadsheet columns
  web/components/command-palette/command-modal.tsx
  web/components/command-palette/issue/change-issue-assignee.tsx
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/inbox/main-content.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/issue-layouts/calendar/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/gantt/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/modal.tsx
  web/components/issues/peek-overview/issue-properties.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/issues/sidebar.tsx
  web/components/issues/sub-issues/properties.tsx
  web/components/issues/view-select/assignee.tsx
  web/components/issues/view-select/label.tsx
  web/components/modules/form.tsx
  web/components/modules/modal.tsx
  web/components/modules/sidebar.tsx
  web/components/project/label-select.tsx
  web/components/project/priority-select.tsx
  web/components/web-view/issue-properties-detail.tsx
  web/constants/issue.ts
  web/helpers/issue.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/m/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/store/issue/issue_draft.store.ts
  web/types/issues.d.ts
  web/types/modules.d.ts
  web/types/pages.d.ts
Labels: 🌐frontend, 🎨UI / UX

#2530 fix: Debounce title and Editor initialization
  packages/editor/core/src/ui/hooks/useEditor.tsx
  packages/editor/core/src/ui/hooks/useInitializedContent.tsx
  packages/editor/core/src/ui/hooks/useReadOnlyEditor.tsx
  packages/editor/core/src/ui/plugins/delete-image.tsx
  packages/editor/lite-text-editor/src/ui/extensions/custom-list-extension.tsx
  packages/editor/lite-text-editor/src/ui/extensions/enter-key-extension.tsx
  packages/editor/lite-text-editor/src/ui/extensions/index.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
Labels: 🌐web, ✍️editor

#2567 chore: remove unused files
  web/components/issues/issue-layouts/properties/dropdown-template.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/view-select/assignee.tsx
  web/components/issues/view-select/index.ts
  web/components/issues/view-select/label.tsx
  web/components/issues/view-select/priority.tsx
  web/components/labels/index.ts
  web/components/labels/label-select.tsx
  web/components/project/index.ts
  web/contexts/theme.context.tsx
  web/contexts/workspace.context.tsx
Labels: 🌐frontend, 🛠️refactor

#2553 chore: fix: changed assignees and labels list in pages and modules
  apiserver/plane/api/serializers/module.py
  apiserver/plane/api/serializers/page.py
  apiserver/plane/bgtasks/issue_activites_task.py
Labels: ⚙️backend, 🌟improvement

#2557 chore: user settings endpoint
  apiserver/plane/api/serializers/user.py
Labels: ⚙️backend, 🧹chore

#2576 fix: upgrading to turbo new version
  package.json
  yarn.lock
Labels: 📦dependencies, ⚙️config changes
