Repository makeplane/plane, pull requests merged in 2023-11, with the labels that each got.

#2575 refactor: project settings
  web/components/estimates/create-update-estimate-modal.tsx
  web/components/estimates/delete-estimate-modal.tsx
  web/components/estimates/estimate-list-item.tsx
  web/components/estimates/estimate-list.tsx
  web/components/estimates/index.ts
  web/components/issues/draft-issue-form.tsx
  web/components/issues/form.tsx
  web/components/labels/create-label-modal.tsx
  web/components/labels/create-update-label-inline.tsx
  web/components/labels/delete-label-modal.tsx
  web/components/labels/index.ts
  web/components/labels/labels-list-modal.tsx
  web/components/labels/project-setting-label-group.tsx
  web/components/labels/project-setting-label-list-item.tsx
  web/components/labels/project-setting-label-list.tsx
  web/components/project/confirm-project-member-remove.tsx
  web/components/project/form.tsx
  web/components/project/index.ts
  web/components/project/integration-card.tsx
  web/components/project/member-list-item.tsx
  web/components/project/member-list.tsx
  web/components/project/member-select.tsx
  web/components/project/project-settings-member-defaults.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/states/create-state-modal.tsx
  web/components/states/create-update-state-inline.tsx
  web/components/states/delete-state-modal.tsx
  web/components/states/index.ts
  web/components/states/project-setting-state-list-item.tsx
  web/components/states/project-setting-state-list.tsx
  web/components/states/state-select.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/store/project/index.ts
  web/store/project/project.store.ts
  web/store/project/project_estimates.store.ts
  web/store/project/project_label_store.ts
  web/store/project/project_state.store.ts
  web/store/root.ts
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#2574 style: issue peek overview ui improvement
  web/components/headers/project-issues.tsx
  web/components/issues/issue-layouts/index.ts
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/properties/date.tsx
  web/components/issues/issue-layouts/properties/estimates.tsx
  web/components/issues/issue-layouts/properties/index.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/activity/card.tsx
  web/components/issues/issue-peek-overview/activity/view.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/issue-peek-overview/reactions/preview.tsx
  web/components/issues/issue-peek-overview/reactions/selector.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/components/issues/sidebar-select/estimate.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/issues/sidebar.tsx
  web/components/issues/sub-issues/properties.tsx
  web/store/issue/issue_detail.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🧹chore, 🛠️refactor

#2560 chore: workspace members and project members endpoint
  apiserver/plane/api/urls/project.py
  apiserver/plane/api/urls/workspace.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/workspace.py
Labels: ⚙️backend, 🧹chore

#2570 chore: removed numbers from magic code
  apiserver/plane/api/views/authentication.py
Labels: ⚙️backend, 🧹chore

#2577 chore: importer permission
  apiserver/plane/api/views/importer.py
Labels: ⚙️backend, 🧹chore

#2582 chore: view creation and date filter fix
  apiserver/plane/utils/issue_filters.py
Labels: 🐛bug, ⚙️backend

#2584 style: new avatar and avatar group components
  packages/ui/package.json
  packages/ui/src/avatar/avatar-group.tsx
  packages/ui/src/avatar/avatar.tsx
  packages/ui/src/avatar/index.ts
  packages/ui/src/button/index.ts
  packages/ui/src/index.ts
  web/components/command-palette/issue/change-issue-assignee.tsx
  web/components/core/filters/filters-list.tsx
  web/components/core/filters/index.ts
  web/components/core/filters/workspace-filters-list.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/active-cycle-stats.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/cycles-view.tsx
  web/components/cycles/index.ts
  web/components/cycles/sidebar.tsx
  web/components/cycles/single-cycle-card.tsx
  web/components/cycles/single-cycle-list.tsx
  web/components/integration/github/single-user-select.tsx
  web/components/integration/jira/import-users.tsx
  web/components/issues/issue-layouts/filters/applied-filters/members.tsx
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/kanban/headers/assignee.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/headers/assignee.tsx
  web/components/issues/issue-layouts/list/headers/created-by.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/select/assignee.tsx
  web/components/issues/sidebar-select/assignee.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/select/lead.tsx
  web/components/modules/select/members.tsx
  web/components/modules/sidebar-select/select-lead.tsx
  web/components/modules/sidebar-select/select-members.tsx
  web/components/project/card.tsx
  web/components/project/member-select.tsx
  web/components/project/members-select.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/ui/avatar.tsx
  web/components/ui/index.ts
  web/components/views/index.ts
  web/components/views/select-filters.tsx
  web/components/workspace/member-select.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/constants/issue.ts
Labels: 🌐frontend, 🎨UI / UX

#2591 fix: build fixes
  web/components/core/filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
  web/components/views/select-filters.tsx
  web/components/web-view/add-comment.tsx
  web/components/web-view/comment-card.tsx
  web/components/web-view/issue-web-view-form.tsx
Labels: 🐛bug

#2589 fix: project wrapper
  web/components/auth-screens/project/join-project.tsx
  web/components/project/card.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/store/project/project.store.ts
  web/store/user.store.ts
Labels: 🐛bug, 🌐frontend

#2581 fix: bug fixes
  packages/ui/src/icons/cycle/circle-dot-full-icon.tsx
  web/components/common/empty-state.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/projects.tsx
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/modules/sidebar.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/join-project-modal.tsx
  web/components/workspace/member-select.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2587 [FED-594] fix: user change theme interface bug fixes
  web/components/command-palette/change-interface-theme.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2593 chore: added validation for archived issue
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: 🐛bug, ⚙️backend

#2592 chore: add issue option added in header group
  web/components/issues/issue-layouts/kanban/headers/assignee.tsx
  web/components/issues/issue-layouts/kanban/headers/created_by.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/kanban/headers/label.tsx
  web/components/issues/issue-layouts/kanban/headers/priority.tsx
  web/components/issues/issue-layouts/kanban/headers/project.tsx
  web/components/issues/issue-layouts/kanban/headers/state-group.tsx
  web/components/issues/issue-layouts/kanban/headers/state.tsx
  web/components/issues/issue-layouts/list/headers/assignee.tsx
  web/components/issues/issue-layouts/list/headers/created-by.tsx
  web/components/issues/issue-layouts/list/headers/empty-group.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/headers/label.tsx
  web/components/issues/issue-layouts/list/headers/priority.tsx
  web/components/issues/issue-layouts/list/headers/project.tsx
  web/components/issues/issue-layouts/list/headers/state-group.tsx
  web/components/issues/issue-layouts/list/headers/state.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2598 chore: unarchived issue and date format changes
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: 🐛bug, ⚙️backend

#2590 feat: search project & workspace members
  web/components/project/member-list.tsx
  web/components/workspace/settings/members-list.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
Labels: 🌐frontend, 🧹chore

#2588 chore: loading state for all layouts
  web/components/gantt-chart/chart/index.tsx
  web/components/headers/project-issues.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2583 chore: issue filters view more and less buttons
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/labels.tsx
  web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
  web/components/issues/issue-layouts/filters/header/filters/priority.tsx
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
  web/components/issues/issue-layouts/filters/header/filters/start-date.tsx
  web/components/issues/issue-layouts/filters/header/filters/state-group.tsx
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/components/issues/issue-layouts/filters/header/filters/target-date.tsx
Labels: 🌐frontend, 🌟improvement

#2602 enhancement: Added Module and Cycle Selection to Issue Creation Modal
  web/components/issues/form.tsx
  web/components/issues/modal.tsx
  web/components/issues/select/cycle.tsx
  web/components/issues/select/index.ts
  web/components/issues/select/module.tsx
Labels: 🌟enhancement, 🌐frontend

#2595 chore: fixes and improvement
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/modules-list.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/sidebar.tsx
  web/components/project/card.tsx
  web/constants/cycle.tsx
  web/constants/issue.ts
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore, 🛠️refactor

#2604 fix: Resolved Issue Property Dropdown Overflow in Issue Create Modal
  web/components/issues/select/cycle.tsx
  web/components/issues/select/date.tsx
  web/components/issues/select/label.tsx
  web/components/issues/select/module.tsx
Labels: 🌐frontend, 🎨UI / UX

#2599 fix: spreadsheet view properties fix
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/view-select/due-date.tsx
  web/components/issues/view-select/start-date.tsx
Labels: 🌐frontend, 🎨UI / UX

#2603 fix: peekoverview
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/gantt-chart/blocks/blocks-display.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/helpers/draggable.tsx
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/roots/module-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-root.tsx
  web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
  web/components/issues/issue-layouts/gantt/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/sub-issues/issue.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/store/issue/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2607 fix: bug fixes
  web/components/issues/confirm-issue-discard.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/modules/module-card-item.tsx
Labels: 🌐frontend

#2586 refactor: user profile store setup and bug fixes
  web/components/profile/navbar.tsx
  web/components/profile/profile-issues-filter.tsx
  web/layouts/profile-layout/layout.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
  web/store/profile-issues/issue_filters.store.ts
Labels: 🐛bug, 🌐frontend, 🛠️refactor

#2606 fix: exception error
  web/components/project/member-list.tsx
  web/store/project/project_label_store.ts
  web/store/project/project_state.store.ts
  web/store/user.store.ts
Labels: 🐛bug, 🌐frontend

#2601 style: lite text editor editor toolbar
  packages/editor/core/src/ui/components/editor-container.tsx
  packages/editor/core/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/menus/fixed-menu/index.tsx
  web/components/issues/issue-peek-overview/activity/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
Labels: 🌐frontend, 🎨UI / UX

#2605 chore: updated the contact email
  CODE_OF_CONDUCT.md
Labels: 📖docs

#2608 [FED-634] fix: select label dropdown fix for list view
  web/components/issues/issue-layouts/properties/labels.tsx
Labels: 🌐frontend

#2610 fix: calendar layout not being rendered
  web/store/issue/issue_filters.store.ts
Labels: 🐛bug, 🌐frontend

#2611 chore: removed unused hooks and components
  web/components/command-palette/change-interface-theme.tsx
  web/components/command-palette/issue/change-issue-assignee.tsx
  web/components/core/activity.tsx
  web/components/core/filters/filters-list.tsx
  web/components/core/filters/index.ts
  web/components/core/index.ts
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/core/sidebar/links-list.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/core/views/gantt-chart-view/inline-create-issue-form.tsx
  web/components/core/views/index.ts
  web/components/core/views/inline-issue-create-wrapper.tsx
  web/components/cycles/transfer-issues-modal.tsx
  web/components/inbox/actions-header.tsx
  web/components/inbox/main-content.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/issues/delete-draft-issue-modal.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/main-content.tsx
  web/components/issues/sidebar.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/modules/sidebar.tsx
  web/components/onboarding/invite-members.tsx
  web/components/profile/index.ts
  web/components/profile/profile-issues-view.tsx
  web/components/project/member-list-item.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/views/signin.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/contexts/project-member.context.tsx
  web/hooks/gantt-chart/issue-view.tsx
  web/hooks/my-issues/use-my-issues-filter.tsx
  web/hooks/my-issues/use-my-issues.tsx
  web/hooks/use-editor-suggestions.tsx
  web/hooks/use-issues-view.tsx
  web/hooks/use-profile-issues.tsx
  web/hooks/use-project-members.tsx
  web/hooks/use-workspace-members.tsx
  web/pages/create-workspace.tsx
  web/store/user.store.ts
  web/types/projects.d.ts
  web/types/workspace.d.ts
Labels: 🌐frontend, 🧹chore

#2612 [FED-636] fix: project view edit option
  web/components/views/view-list-item.tsx
Labels: 🌐frontend, 🧹chore

#2616 chore: Improved Handling of Empty Properties for Labels and Assignees
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/assignee.tsx
  web/components/issues/issue-layouts/kanban/headers/created_by.tsx
  web/components/issues/issue-layouts/kanban/properties.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/list/roots/project-root.tsx
  web/components/issues/issue-peek-overview/activity/card.tsx
Labels: 🌐frontend, 🧹chore

#2614 [FED-641 ] fix: module sidebar status select
  web/components/modules/sidebar.tsx
Labels: 🌐frontend, 🧹chore

#2617 chore: implemented MobX in the onboarding screens
  web/components/onboarding/user-details.tsx
  web/components/onboarding/workspace.tsx
  web/components/page-views/signin.tsx
  web/components/workspace/create-workspace-form.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/pages/onboarding/index.tsx
  web/store/user.store.ts
  web/store/workspace/workspace.store.ts
Labels: 🌐frontend, 🧹chore

#2609 chore: bug fixes
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/notification_task.py
Labels: 🐛bug, ⚙️backend

#2618 fix: active cycle fix
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/active-cycle-stats.tsx
Labels: 🐛bug, 🌐frontend

#2619 fix: user authentication on the index page
  web/components/page-views/signin.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/hooks/use-user-auth.tsx
Labels: 🐛bug, 🌐frontend

#2630 dev: migrations for 0.14
  apiserver/plane/db/migrations/0046_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0047_issue_mention_and_more.py
Labels: ⚙️backend, 🔄migrations

#2622 fix: slug field not working in the create workspace form
  web/components/workspace/create-workspace-form.tsx
  web/constants/workspace.ts
Labels: 🐛bug, 🌐frontend

#2629 fix: Project Rendering Error in Kanban Layout and Layout Rendering Fixes in Subscribed Profile Issues
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
Labels: 🐛bug, 🌐frontend

#2624 fix: resolve z-index and peek overview component bug
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/issue/spreadsheet-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#2625 chore: refactor and improve project member settings
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/project/member-list-item.tsx
Labels: 🌐frontend, 🎨UI / UX, 🛠️refactor

#2626 refactor: replace ui components with plane ui components
  packages/ui/src/breadcrumbs/index.ts
  packages/ui/src/dropdowns/index.ts
  packages/ui/src/form-fields/index.ts
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/state/index.ts
  packages/ui/src/progress/index.ts
  packages/ui/src/tooltip/index.ts
  web/components/cycles/cycles-view.tsx
  web/components/cycles/delete-modal.tsx
  web/components/estimates/estimate-select.tsx
  web/components/headers/project-views.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/labels/label-select.tsx
  web/components/labels/project-setting-label-group.tsx
  web/components/labels/project-setting-label-list-item.tsx
  web/components/project/members-select.tsx
  web/components/project/priority-select.tsx
  web/components/states/create-state-modal.tsx
  web/components/states/create-update-state-inline.tsx
  web/components/states/state-select.tsx
  web/components/ui/buttons/danger-button.tsx
  web/components/ui/buttons/index.ts
  web/components/ui/buttons/primary-button.tsx
  web/components/ui/buttons/secondary-button.tsx
  web/components/ui/buttons/type.d.ts
  web/components/ui/index.ts
  web/components/ui/multi-level-dropdown.tsx
  web/components/ui/product-updates-modal.tsx
  web/components/views/delete-view-modal.tsx
  web/components/views/form.tsx
  web/components/views/views-list.tsx
  web/components/views/workspace-dashboard.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
Labels: 🌐frontend, 🛠️refactor

#2627 chore: peek overview improvement and bug fixes
  packages/ui/src/icons/center-panel-icon.tsx
  packages/ui/src/icons/full-screen-panel-icon.tsx
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/side-panel-icon.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/components/issues/peek-overview/header.tsx
  web/components/issues/select/label.tsx
  web/components/issues/sidebar-select/cycle.tsx
  web/components/issues/sidebar-select/label.tsx
  web/components/issues/sidebar-select/module.tsx
  web/components/issues/sidebar-select/state.tsx
  web/components/issues/sidebar.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#2633 fix: string helper function
  web/components/analytics/custom-analytics/select-bar.tsx
  web/components/analytics/custom-analytics/select/x-axis.tsx
  web/helpers/string.helper.ts
Labels: 🐛bug, 🌐frontend

#2632 chore: peek overview authorization
  packages/editor/core/src/ui/menus/menu-items/index.tsx
  packages/editor/lite-text-editor/src/ui/menus/fixed-menu/index.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
  web/components/issues/issue-peek-overview/activity/view.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/components/project/join-project-modal.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/types/projects.d.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2640 chore: added missing columns to the spreadsheet layout
  web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/columns-list.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/index.ts
  web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-column.tsx
  web/constants/spreadsheet.ts
  web/types/view-props.d.ts
Labels: 🌐frontend, 🌟improvement

#2641 chore: updated all the layout selections
  web/components/headers/modules-list.tsx
  web/components/project/priority-select.tsx
  web/constants/cycle.tsx
  web/constants/module.ts
  web/constants/page.ts
  web/layouts/auth-layout/user-wrapper.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#2615 style: quick add issue UI improvements in all the layouts
  web/components/issues/issue-layouts/calendar/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/gantt/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/kanban/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/spreadsheet/inline-create-issue-form.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2636 style: custom analytics bar graph label overlapping
  web/components/analytics/custom-analytics/graph/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2639 fix: notification read and snooze bugs
  web/components/notifications/notification-card.tsx
  web/components/notifications/notification-header.tsx
  web/components/notifications/notification-popover.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/hooks/use-user-notifications.tsx
Labels: 🌐frontend, 🛠️refactor

#2637 fix: custom analytics graph display issue
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/utils/analytics_plot.py
Labels: 🐛bug, ⚙️backend

#2628 refactor: archive issue
  web/components/headers/project-archived-issues.tsx
  web/components/issues/delete-archived-issue-modal.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/index.ts
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/index.ts
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/index.ts
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/index.ts
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
  web/store/archived-issues/index.ts
  web/store/archived-issues/issue.store.ts
  web/store/archived-issues/issue_detail.store.ts
  web/store/archived-issues/issue_filters.store.ts
  web/store/root.ts
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#2643 chore : dropdown loading state added and project card avatar fix
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/project/card.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#2596 [feat]: Extended Tables Support
  packages/editor/core/package.json
  packages/editor/core/src/index.ts
  packages/editor/core/src/ui/components/editor-content.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/extensions/table/index.ts
  packages/editor/core/src/ui/extensions/table/table-cell.ts
  packages/editor/core/src/ui/extensions/table/table-cell/index.ts
  packages/editor/core/src/ui/extensions/table/table-cell/table-cell.ts
  packages/editor/core/src/ui/extensions/table/table-header.ts
  packages/editor/core/src/ui/extensions/table/table-header/index.ts
  packages/editor/core/src/ui/extensions/table/table-header/table-header.ts
  packages/editor/core/src/ui/extensions/table/table-row/index.ts
  packages/editor/core/src/ui/extensions/table/table-row/table-row.ts
  packages/editor/core/src/ui/extensions/table/table/icons.ts
  packages/editor/core/src/ui/extensions/table/table/index.ts
  packages/editor/core/src/ui/extensions/table/table/table-controls.ts
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
  packages/editor/core/src/ui/extensions/table/table/table.ts
  packages/editor/core/src/ui/extensions/table/table/utilities/create-cell.ts
  packages/editor/core/src/ui/extensions/table/table/utilities/create-table.ts
  packages/editor/core/src/ui/extensions/table/table/utilities/delete-table-when-all-cells-selected.ts
  packages/editor/core/src/ui/extensions/table/table/utilities/get-table-node-types.ts
  packages/editor/core/src/ui/extensions/table/table/utilities/is-cell-selection.ts
  packages/editor/core/src/ui/mentions/custom.tsx
  packages/editor/core/src/ui/menus/table-menu/index.tsx
  packages/editor/core/src/ui/read-only/extensions.tsx
  packages/editor/rich-text-editor/src/ui/extensions/slash-command.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/index.tsx
  space/pages/_app.tsx
  space/styles/table.css
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/pages/_app.tsx
  web/styles/table.css
  yarn.lock
Labels: ✍️editor

#2657 fix: product tour modal bugs
  web/components/onboarding/tour/root.tsx
  web/components/page-views/index.ts
  web/components/page-views/workspace-dashboard.tsx
  web/components/views/index.ts
  web/pages/[workspaceSlug]/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2658 refactor: removed unused packages
  web/components/dnd/StrictModeDroppable.tsx
  web/components/gantt-chart/cycle-sidebar.tsx
  web/components/gantt-chart/module-sidebar.tsx
  web/components/gantt-chart/sidebar.tsx
  web/components/pages/single-page-block.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/project/sidebar-list.tsx
  web/components/ui/icon-name-type.d.ts
  web/package.json
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#2660 chore: improved Drag and Drop Functionality, Gantt Hover in Issue Peek Overview
  web/components/issues/issue-peek-overview/root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/store/cycle/cycle_issue_kanban_view.store.ts
  web/store/issue/issue_kanban_view.store.ts
  web/store/module/module_issue_kanban_view.store.ts
Labels: 🌐frontend, 🧹chore

#2662 fix: notifications option in the sidebar menu not collapsing
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/notifications/notification-popover.tsx
  web/store/issue/issue_filters.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2665 fix: package version fixes and mentions build error fixes
  packages/editor/core/package.json
  packages/editor/lite-text-editor/package.json
  packages/editor/lite-text-editor/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/read-only/index.tsx
  packages/editor/lite-text-editor/src/ui/tooltip.tsx
  packages/editor/rich-text-editor/package.json
  packages/eslint-config-custom/package.json
  packages/tailwind-config-custom/package.json
  packages/ui/package.json
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/store/user.ts
  web/components/issues/comment/add-comment.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/description-form.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/form.tsx
  web/components/issues/issue-peek-overview/activity/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/pages/create-update-block-inline.tsx
  web/components/pages/single-page-block.tsx
  web/hooks/use-editor-suggestions.tsx
  web/package.json
  yarn.lock
Labels: 🐛bug, :card_file_box: packaging

#2664 fix: existing issues modal for cycle and module
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-peek-overview/properties.tsx
  web/components/issues/modal.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/store/cycle/cycle_issue.store.ts
  web/store/module/module_issue.store.ts
Labels: 🐛bug, 🌐frontend

#2671 style: updated layouts UI in the space app
  space/components/icons/index.ts
  space/components/icons/state-group/backlog-state-icon.tsx
  space/components/icons/state-group/cancelled-state-icon.tsx
  space/components/icons/state-group/completed-state-icon.tsx
  space/components/icons/state-group/index.ts
  space/components/icons/state-group/started-state-icon.tsx
  space/components/icons/state-group/state-group-icon.tsx
  space/components/icons/state-group/unstarted-state-icon.tsx
  space/components/icons/types.d.ts
  space/components/issues/board-views/block-state.tsx
  space/components/issues/board-views/kanban/block.tsx
  space/components/issues/board-views/kanban/header.tsx
  space/components/issues/board-views/list/block.tsx
  space/components/issues/board-views/list/header.tsx
  space/components/issues/board-views/list/index.tsx
  space/components/issues/peek-overview/comment/add-comment.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/state-group.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
  web/components/issues/issue-peek-overview/view.tsx
Labels: 🌐frontend, 🎨UI / UX

#2672 chore: update avatar group logic
  packages/ui/src/avatar/avatar-group.tsx
Labels: 🌐frontend, 🎨UI / UX

#2674 fix: bug fixes and ui improvement
  packages/ui/src/avatar/avatar-group.tsx
  space/styles/globals.css
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/issues/modal.tsx
  web/components/project/card.tsx
  web/components/project/create-project-modal.tsx
  web/styles/globals.css
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2669 style: update border across workspace and project settings.
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/estimates/estimate-list-item.tsx
  web/components/estimates/estimate-list.tsx
  web/components/exporter/guide.tsx
  web/components/integration/guide.tsx
  web/components/integration/single-integration-card.tsx
  web/components/labels/project-setting-label-group.tsx
  web/components/labels/project-setting-label-list-item.tsx
  web/components/labels/project-setting-label-list.tsx
  web/components/project/member-list.tsx
  web/components/project/project-settings-member-defaults.tsx
  web/components/project/settings/delete-project-section.tsx
  web/components/project/settings/features-list.tsx
  web/components/states/project-setting-state-list-item.tsx
  web/components/states/project-setting-state-list.tsx
  web/components/ui/integration-and-import-export-banner.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
  web/pages/[workspaceSlug]/me/profile/preferences.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
Labels: 🌐frontend, 🎨UI / UX

#2682 style: update project description as per design.
  web/components/project/card.tsx
Labels: 🌐frontend, 🎨UI / UX

#2684 fix: slack project integration
  apiserver/plane/api/views/integration/slack.py
Labels: 🐛bug, ⚙️backend, 🔗integrations

#2691 fix: cycle and module bug fixes and improvement
  space/constants/data.ts
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2678 fix: state group icon in the space app
  space/components/issues/filters-render/state/filter-state-block.tsx
  space/components/issues/navbar/issue-filter.tsx
  space/components/issues/peek-overview/issue-properties.tsx
  space/constants/data.ts
  space/types/issue.ts
Labels: 🌐frontend, 🎨UI / UX

#2692 chore: configuration variables
  apiserver/plane/api/views/config.py
Labels: ⚙️backend, 🧹chore, ⚙️config changes

#2697 style: update font weight in project general setting section.
  web/components/project/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#2573 dev: worker count
  apiserver/.env.example
  apiserver/bin/takeoff
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: ⚙️backend, 🐳docker, ⚙️.env changes

#2695 style: update user profile button alignment.
  packages/ui/src/avatar/avatar.tsx
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX

#2696 chore: issue draft delete
  apiserver/plane/api/views/issue.py
Labels: 🐛bug, ⚙️backend

#2706 fix: Error messages for creating or updating duplicate labels
  web/components/issues/sidebar-select/label.tsx
  web/components/labels/create-label-modal.tsx
  web/components/labels/create-update-label-inline.tsx
Labels: 🐛bug, 🌐frontend

#2708 style: spinner component improvement
  packages/ui/src/spinners/circular-spinner.tsx
Labels: 🌐frontend, 🎨UI / UX

#2689 fix: quick add not working for labels & assignee
  web/components/issues/issue-layouts/calendar/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/gantt/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/kanban/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/list/inline-create-issue-form.tsx
  web/components/issues/issue-layouts/spreadsheet/inline-create-issue-form.tsx
  web/constants/issue.ts
  web/helpers/issue.helper.ts
Labels: 🐛bug, 🌐frontend

#2688 refactor: replace keyboard events with command palette store
  web/components/command-palette/command-modal.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-list.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/projects.tsx
  web/components/integration/jira/give-details.tsx
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/global-view.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/empty-states/project-view.tsx
  web/components/issues/issue-layouts/empty-states/project.tsx
  web/components/modules/modules-list-view.tsx
  web/components/modules/sidebar.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/components/pages/pages-view.tsx
  web/components/project/card-list.tsx
  web/components/project/sidebar-list.tsx
  web/components/views/views-list.tsx
  web/components/workspace/help-section.tsx
  web/components/workspace/sidebar-quick-action.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/pages/[workspaceSlug]/analytics.tsx
Labels: 🌐frontend, 🛠️refactor

#2680 fix: project automation settings flickering
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/cycles/cycle-peek-overview.tsx
  web/components/modules/module-peek-overview.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
Labels: 🌐frontend, 🎨UI / UX, 🛠️refactor

#2681 chore: remove active ids from the MobX stores if not present in the route
  web/lib/mobx/store-init.tsx
  web/store/cycle/cycles.store.ts
  web/store/global-view/global_views.store.ts
  web/store/inbox/inbox.store.ts
  web/store/module/modules.store.ts
  web/store/project-view/project_views.store.ts
  web/store/project/project.store.ts
Labels: 🌐frontend, 🌟improvement

#2725 style: ui consistency and improvement
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/dropdowns/custom-select.tsx
  web/components/cycles/form.tsx
  web/components/issues/form.tsx
  web/components/issues/select/assignee.tsx
  web/components/issues/select/cycle.tsx
  web/components/issues/select/date.tsx
  web/components/issues/select/estimate.tsx
  web/components/issues/select/label.tsx
  web/components/issues/select/module.tsx
  web/components/issues/select/priority.tsx
  web/components/issues/select/project.tsx
  web/components/issues/select/state.tsx
  web/components/modules/select/lead.tsx
  web/components/modules/select/members.tsx
  web/components/project/create-project-modal.tsx
  web/components/ui/date.tsx
  web/components/ui/labels-list.tsx
  web/components/views/form.tsx
  web/components/workspace/member-select.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#2703 fix: bug fixes and ui improvements
  web/components/cycles/cycles-list-item.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/list/properties.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/components/project/card-list.tsx
  web/components/project/priority-select.tsx
  web/helpers/date-time.helper.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2727 fix: added empty project state when no project exists.
  web/components/issues/issue-layouts/empty-states/global-view.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
Labels: 🌐frontend, 🎨UI / UX

#2726 fix: issue property height and peek view date picker border radius
  web/components/issues/issue-layouts/properties/estimates.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
  web/components/issues/issue-peek-overview/properties.tsx
Labels: 🎨UI / UX

#2707 fix: all issues values not changeable and assignee image not rendering
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/issue-layouts/roots/global-view-layout-root.tsx
Labels: 🐛bug

#2710 [fix]: Error Handling for Images and Table Fix for Form Submissions in Editor
  packages/editor/core/src/ui/extensions/image/index.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
  packages/editor/core/src/ui/hooks/useEditor.tsx
  packages/editor/core/src/ui/menus/table-menu/InsertBottomTableIcon.tsx
  packages/editor/core/src/ui/menus/table-menu/InsertLeftTableIcon.tsx
  packages/editor/core/src/ui/menus/table-menu/InsertRightTableIcon.tsx
  packages/editor/core/src/ui/menus/table-menu/InsertTopTableIcon.tsx
  packages/editor/core/src/ui/menus/table-menu/tooltip.tsx
  packages/editor/core/src/ui/plugins/delete-image.tsx
  packages/editor/core/src/ui/plugins/upload-image.tsx
  packages/editor/lite-text-editor/package.json
  packages/editor/lite-text-editor/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/menus/fixed-menu/index.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  space/components/issues/peek-overview/comment/add-comment.tsx
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/services/file.service.ts
  space/styles/table.css
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/description-form.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/form.tsx
  web/components/issues/issue-peek-overview/activity/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/comment-editor.tsx
  web/components/issues/issue-peek-overview/issue-detail.tsx
  web/components/pages/create-update-block-inline.tsx
  web/components/pages/single-page-block.tsx
  web/services/file.service.ts
  web/styles/table.css
Labels: 🐛bug, ✍️editor

#2722 style: kanban card label overflow
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/properties/state.tsx
Labels: 🎨UI / UX

#2730 fix: toast alert inconsistency
  web/components/modules/delete-module-modal.tsx
  web/components/project/delete-project-modal.tsx
  web/components/views/modal.tsx
Labels: 🎨UI / UX

#2724 fix: Tooltip content on assignee hover in all layouts
  web/components/issues/issue-layouts/properties/assignee.tsx
Labels: 🌐frontend, 🎨UI / UX

#2717 feat: state list endpoint
  apiserver/plane/api/serializers/state.py
  apiserver/plane/api/urls/state.py
  apiserver/plane/api/views/state.py
Labels: ⚙️backend

#2737 fix: custom analytics bar graph index alignment
  web/components/analytics/custom-analytics/graph/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#2736 fix: Add horizontal scroll bar to views
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/styles/globals.css
Labels: 🐛bug, 🌐frontend

#2735 style: sidebar UI improvements
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-quick-action.tsx
Labels: 🌐frontend, 🎨UI / UX

#2734 fix: UI improvements.
  web/components/integration/single-integration-card.tsx
  web/components/labels/create-label-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2705 refactor: gantt sidebar
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/index.ts
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/cycle-sidebar.tsx
  web/components/gantt-chart/sidebar/index.ts
  web/components/gantt-chart/sidebar/module-sidebar.tsx
  web/components/gantt-chart/sidebar/project-view-sidebar.tsx
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/issues/issue-layouts/gantt/cycle-root.tsx
  web/components/issues/issue-layouts/gantt/module-root.tsx
  web/components/issues/issue-layouts/gantt/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/root.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
Labels: 🌐frontend, 🛠️refactor

#2709 chore: configuration add tracker variables
  apiserver/plane/api/views/config.py
Labels: ⚙️backend, ⚙️config changes

#2670 fix: mention notification
  apiserver/plane/bgtasks/notification_task.py
Labels: 🐛bug, ⚙️backend

#2719 chore: favourite cycle and module displayed at top
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
Labels: ⚙️backend, 🌟improvement

#2713 feat: issues v2 endpoint
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/urls/issue.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
Labels: ⚙️backend

#2741 fix: filter list overflow fix
  web/components/issues/issue-layouts/filters/applied-filters/date.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/label.tsx
  web/components/issues/issue-layouts/filters/applied-filters/members.tsx
  web/components/issues/issue-layouts/filters/applied-filters/priority.tsx
  web/components/issues/issue-layouts/filters/applied-filters/project.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/state-group.tsx
  web/components/issues/issue-layouts/filters/applied-filters/state.tsx
Labels: 🌐frontend, 🎨UI / UX

#2716 refactor: cycles store
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-gantt.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/cycles-view.tsx
  web/components/cycles/index.ts
  web/components/cycles/modal.tsx
  web/components/cycles/select.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/cycle-issues.tsx
  web/components/issues/select/cycle.tsx
  web/components/views/view-list-item.tsx
  web/components/workspace/views/view-list-item.tsx
  web/helpers/date-time.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/services/cycle.service.ts
  web/store/cycle/cycle_issue_filters.store.ts
  web/store/cycle/cycles.store.ts
  web/types/cycles.d.ts
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#2746 fix: workspace settings layout render in export
  web/pages/[workspaceSlug]/settings/exports.tsx
Labels: 🎨UI / UX

#2749 chore: unsplash response
  apiserver/plane/api/urls/__init__.py
  apiserver/plane/api/urls/external.py
  apiserver/plane/api/urls/gpt.py
  apiserver/plane/api/urls/release_note.py
  apiserver/plane/api/urls/unsplash.py
  apiserver/plane/api/views/external.py
Labels: ⚙️backend, 🌟improvement

#2750 fix: header consistency
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/profile-preferences.tsx
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issue-details.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/headers/user-profile.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/headers/workspace-dashboard.tsx
  web/components/headers/workspace-settings.tsx
Labels: 🌐frontend, 🎨UI / UX

#2751 fix: app sidebar dropdown
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🐛bug, 🌐frontend

#2752 fix: cycle card title responsiveness added
  web/components/cycles/cycles-board-card.tsx
Labels: 🌐frontend, 🎨UI / UX

#2753 chore: peek overview comment ordering and comment icon alignment fix
  web/components/issues/comment/comment-card.tsx
  web/components/issues/issue-peek-overview/activity/view.tsx
Labels: 🌐frontend, 🎨UI / UX

#2743 fix: workspace settings bugs
  web/components/core/activity.tsx
  web/components/integration/github/root.tsx
  web/components/integration/jira/give-details.tsx
  web/components/integration/jira/root.tsx
  web/components/project/delete-project-modal.tsx
  web/components/workspace/create-workspace-form.tsx
  web/components/workspace/delete-workspace-modal.tsx
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/settings/members-list.tsx
  web/layouts/settings-layout/workspace/sidebar.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/store/workspace/workspace-member.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2758 style: ui improvements and bug fixes
  web/components/project/integration-card.tsx
  web/components/project/leave-project-modal.tsx
  web/components/project/sidebar-list.tsx
  web/components/views/delete-view-modal.tsx
  web/components/views/view-list-item.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
Labels: 🌐frontend, 🎨UI / UX

#2720 dev: create bucket through application
  apiserver/bin/bucket_script.py
  apiserver/bin/takeoff
Labels: 🐳docker, devops

#2764 chore: breadcrumb project icon fix
  web/components/headers/project-issues.tsx
Labels: 🌐frontend, 🎨UI / UX

#2765 chore: create update issue modal improvement
  web/components/issues/form.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#2768 chore: spreadsheet layout column improvement
  web/components/issues/issue-layouts/spreadsheet/columns/issue/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
Labels: 🌐frontend, 🎨UI / UX

#2774 chore: lead select dropdown fix
  web/components/modules/select/lead.tsx
  web/components/workspace/member-select.tsx
Labels: 🌐frontend, 🎨UI / UX

#2775 chore: create update view modal improvement
  web/components/views/form.tsx
  web/components/workspace/views/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#2761 fix: bugs
  web/components/cycles/active-cycle-details.tsx
  web/components/issues/select/label.tsx
  web/components/issues/select/state.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/views/form.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
Labels: 🐛bug, 🌐frontend

#2769 style: text overflow fix and border color update
  web/components/core/activity.tsx
  web/components/issues/issue-layouts/properties/assignee.tsx
  web/components/issues/select/cycle.tsx
  web/components/issues/select/module.tsx
  web/components/modules/delete-module-modal.tsx
  web/components/project/join-project-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#2771 Fix: Custom menu item not automatically closing, affecting delete popup behavior.
  packages/ui/src/dropdowns/custom-menu.tsx
Labels: 🐛bug, 🌐frontend

#2763 enhancement: label sort order
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/migrations/0047_issuemention_label_sort_order_and_more.py
  apiserver/plane/db/models/issue.py
Labels: 🌟enhancement, ⚙️backend, 🔄migrations

#2594 dev: API settings
  apiserver/.env.example
  apiserver/plane/api/views/auth_extended.py
  apiserver/plane/api/views/authentication.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/workspace.py
  apiserver/plane/settings/common.py
  apiserver/plane/settings/local.py
  apiserver/plane/settings/production.py
  apiserver/plane/settings/selfhosted.py
  apiserver/plane/settings/staging.py
  apiserver/plane/settings/test.py
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: 🧹chore, ⚙️.env changes, ⚙️config changes

#2762 chore: user workflow
  apiserver/plane/api/permissions/__init__.py
  apiserver/plane/api/permissions/project.py
  apiserver/plane/api/permissions/workspace.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/urls/project.py
  apiserver/plane/api/urls/user.py
  apiserver/plane/api/urls/workspace.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/authentication.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/notification.py
  apiserver/plane/api/views/oauth.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/user.py
  apiserver/plane/api/views/workspace.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
  apiserver/plane/db/migrations/0047_issuemention_projectmember_is_deactivated_and_more.py
  apiserver/plane/db/migrations/0048_issuemention_remove_projectmember_is_deactivated_and_more.py
  apiserver/plane/db/migrations/0049_issuemention_remove_projectmember_is_deactivated_and_more.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/workspace.py
  apiserver/templates/emails/invitations/project_invitation.html
Labels: ⚙️backend, 🧹chore

#2767 dev: update bucket script to make the bucket public
  apiserver/bin/bucket_script.py
  deploy/selfhost/docker-compose.yml
  docker-compose-local.yml
  docker-compose.yml
Labels: 🐳docker, devops

#2779 dev: squashed migrations
  apiserver/plane/db/migrations/0046_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0046_label_sort_order_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0047_issuemention_label_sort_order_and_more.py
  apiserver/plane/db/migrations/0047_issuemention_projectmember_is_deactivated_and_more.py
  apiserver/plane/db/migrations/0047_webhook_apitoken_description_apitoken_expired_at_and_more.py
  apiserver/plane/db/migrations/0048_issuemention_remove_projectmember_is_deactivated_and_more.py
  apiserver/plane/db/migrations/0049_issuemention_remove_projectmember_is_deactivated_and_more.py
  apiserver/plane/settings/common.py
  apiserver/plane/settings/redis.py
  apiserver/requirements/base.txt
  apiserver/requirements/production.txt
Labels: ⚙️backend, 🔄migrations

#2783 fix: workspace setting dropdown improvement
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX

#2760 fix: pages revamping
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/page.py
  apiserver/plane/api/urls/page.py
  apiserver/plane/api/urls_deprecated.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/page.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/db/migrations/0048_auto_20231116_0713.py
  apiserver/plane/db/migrations/0049_auto_20231116_0713.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/page.py
Labels: ⚙️backend, 🌟improvement, 🔄migrations

#2788 dev: initialized cycle and module issue filters store
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/gantt/project-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/project-root.tsx
  web/services/issue/issue.service.ts
  web/store/cycle-issues/index.ts
  web/store/cycle-issues/issue_filters.store.ts
  web/store/module-issues/index.ts
  web/store/module-issues/issue_filters.store.ts
  web/store/project-issues/issue.store.ts
  web/store/project-issues/issue_filters.store.ts
  web/store/root.ts
Labels: 🌐frontend

#2792 feat: Instance Admin Panel: General Settings
  web/components/instance/general-form.tsx
  web/components/instance/index.ts
  web/components/instance/sidebar-dropdown.tsx
  web/components/instance/sidebar-menu.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/layouts/admin-layout/header.tsx
  web/layouts/admin-layout/sidebar.tsx
  web/layouts/auth-layout/user-wrapper.tsx
  web/pages/admin/index.tsx
  web/services/instance.service.ts
  web/services/user.service.ts
  web/store/instance/instance.store.ts
  web/store/user.store.ts
  web/types/users.d.ts
Labels: ✨feature

#2791 chore: user onboarding
  apiserver/plane/db/migrations/0050_user_use_case_alter_workspace_organization_size.py
  apiserver/plane/db/models/user.py
  apiserver/plane/db/models/workspace.py
Labels: ⚙️backend, 🧹chore

#2786 feat: v3 endpoint for module and cycle
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/urls/cycle.py
  apiserver/plane/api/urls/module.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
Labels: ✨feature, ⚙️backend

#2794 dev: environment settings
  apiserver/.env.example
  apiserver/bin/takeoff
  apiserver/plane/settings/common.py
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: 🐳docker, ⚙️config changes, devops

#2718 fix: delete issues in spreadsheet doesn't work
  web/components/issues/issue-layouts/spreadsheet/roots/project-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
Labels: 🐛bug, 🌐frontend

#2795 fix: self hosted instance
  apiserver/bin/takeoff
  apiserver/plane/license/api/views/instance.py
  apiserver/plane/license/management/commands/configure_instance.py
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: ⚙️backend, 🐳docker, 🧹chore

#2712 fix: archive issue bugs
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-peek-overview/view.tsx
  web/constants/issue.ts
  web/store/archived-issues/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🛠️refactor

#2673 fix: newly added cycle doesnt appear unlelss the page is manually reloaded
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🐛bug, 🌐frontend

#2804 fix: file asset delete
  apiserver/plane/app/views/asset.py
  apiserver/plane/bgtasks/file_asset_task.py
  apiserver/plane/celery.py
  apiserver/plane/db/migrations/0051_fileasset_is_deleted.py
  apiserver/plane/db/models/asset.py
  apiserver/plane/settings/common.py
Labels: ⚙️backend, 🌟improvement, 🔄migrations

#2805 chore: update exception detected screen action button
  web/pages/_error.tsx
Labels: 🌐frontend, 🧹chore

#2807 dev: openai configured
  apiserver/plane/app/views/config.py
Labels: ⚙️backend, ⚙️config changes

#2808 chore: aws bucket url name changed
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
  apiserver/plane/db/management/commands/create_bucket.py
  apiserver/plane/settings/common.py
Labels: 🐛bug, ⚙️backend

#2772 fix: bug fixes & ui improvements.
  web/components/core/activity.tsx
  web/components/project/create-project-modal.tsx
  web/components/workspace/member-select.tsx
  web/pages/[workspaceSlug]/me/profile/activity.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#2790 chore: onboarding
  apiserver/plane/app/serializers/user.py
  packages/tailwind-config-custom/tailwind.config.js
  web/components/account/delete-account-modal.tsx
  web/components/account/email-code-form.tsx
  web/components/account/github-login-button.tsx
  web/components/account/google-login.tsx
  web/components/account/sidebar.tsx
  web/components/account/step-indicator.tsx
  web/components/core/modals/image-upload-modal.tsx
  web/components/onboarding/invitations.tsx
  web/components/onboarding/invite-members.tsx
  web/components/onboarding/join-workspaces.tsx
  web/components/onboarding/user-details.tsx
  web/components/onboarding/workspace.tsx
  web/components/page-views/signin.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/pages/onboarding/index.tsx
  web/public/onboarding/onboarding-issues.svg
  web/public/onboarding/sign-in.svg
  web/public/users/user-1.png
  web/public/users/user-2.png
  web/services/user.service.ts
  web/services/workspace.service.ts
  web/styles/globals.css
  web/types/users.d.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2814 style: changing profile screen title
  web/components/profile/navbar.tsx
  web/pages/[workspaceSlug]/profile/[userId]/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#2813 chore: removed DOCKERIZED value and changed REDIS_SSL
  apiserver/.env.example
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
  apiserver/plane/settings/common.py
Labels: 🐛bug, ⚙️backend

#2810 dev: instance url
  apiserver/plane/license/management/commands/register_instance.py
Labels: ⚙️backend, 🧹chore

#2803 refactor: command k modal
  web/components/command-palette/actions/help-actions.tsx
  web/components/command-palette/actions/index.ts
  web/components/command-palette/actions/issue-actions/actions-list.tsx
  web/components/command-palette/actions/issue-actions/change-assignee.tsx
  web/components/command-palette/actions/issue-actions/change-priority.tsx
  web/components/command-palette/actions/issue-actions/change-state.tsx
  web/components/command-palette/actions/issue-actions/index.ts
  web/components/command-palette/actions/project-actions.tsx
  web/components/command-palette/actions/search-results.tsx
  web/components/command-palette/actions/theme-actions.tsx
  web/components/command-palette/actions/workspace-settings-actions.tsx
  web/components/command-palette/command-modal.tsx
  web/components/command-palette/command-pallette.tsx
  web/components/command-palette/helpers.tsx
  web/components/command-palette/index.ts
  web/components/command-palette/issue/change-issue-assignee.tsx
  web/components/command-palette/issue/change-issue-priority.tsx
  web/components/command-palette/issue/change-issue-state.tsx
  web/components/command-palette/issue/index.ts
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#2820 fix: complete pages editor not clickable, recent pages calculation logic
  packages/editor/document-editor/src/ui/components/page-renderer.tsx
  web/components/pages/create-update-page-modal.tsx
  web/components/pages/page-form.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/store/page.store.ts
  web/types/pages.d.ts
Labels: 🐛bug, 🌐frontend

#2821 chore: update join project endpoint
  web/components/project/join-project-modal.tsx
  web/services/project/project.service.ts
Labels: 🌐frontend, 🧹chore

#2818 fix: sidebar project section hover
  web/components/project/sidebar-list-item.tsx
Labels: 🐛bug, 🎨UI / UX

#2816 chore: file asset update
  apiserver/plane/app/views/asset.py
  apiserver/plane/app/views/project.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
  apiserver/plane/db/management/commands/create_bucket.py
  apiserver/plane/settings/common.py
Labels: ⚙️backend, 🌟improvement

#2823 style: revamped page details UI
  packages/editor/document-editor/src/ui/components/alert-label.tsx
  packages/editor/document-editor/src/ui/components/content-browser.tsx
  packages/editor/document-editor/src/ui/components/editor-header.tsx
  packages/editor/document-editor/src/ui/components/index.ts
  packages/editor/document-editor/src/ui/components/info-popover.tsx
  packages/editor/document-editor/src/ui/components/page-renderer.tsx
  packages/editor/document-editor/src/ui/components/popover.tsx
  packages/editor/document-editor/src/ui/components/summary-popover.tsx
  packages/editor/document-editor/src/ui/components/summary-side-bar.tsx
  packages/editor/document-editor/src/ui/components/vertical-dropdown-menu.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/document-editor/src/ui/menu/fixed-menu.tsx
  packages/editor/document-editor/src/ui/readonly/index.tsx
  packages/editor/document-editor/src/ui/utils/menu-options.ts
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#2824 Style: UI improvements
  web/components/issues/issue-peek-overview/view.tsx
  web/components/issues/sidebar.tsx
  web/components/notifications/notification-card.tsx
  web/components/project/member-list-item.tsx
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/settings/members-list.tsx
  web/constants/issue.ts
Labels: 🌐frontend, 🎨UI / UX
