Repository makeplane/plane, pull requests merged in 2023-08, with the labels that each got.

#1780 fix: custom theme persisting after signing out
  apps/app/components/command-palette/change-interface-theme.tsx
  apps/app/components/core/theme/custom-theme-selector.tsx
  apps/app/components/core/theme/theme-switch.tsx
  apps/app/components/workspace/sidebar-dropdown.tsx
  apps/app/constants/themes.ts
  apps/app/contexts/theme.context.tsx
  apps/app/helpers/theme.helper.ts
  apps/app/pages/[workspaceSlug]/me/profile/preferences.tsx
  apps/app/pages/_app.tsx
  apps/app/pages/colors.tsx
  apps/app/pages/index.tsx
  apps/app/pages/magic-sign-in.tsx
  apps/app/pages/onboarding.tsx
  apps/app/pages/reset-password.tsx
  apps/app/pages/sign-up.tsx
  apps/app/services/authentication.service.ts
  apps/app/types/users.d.ts
Labels: UI

#1781 feat: issue export csv
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/project_issue_export.py
  apiserver/templates/emails/exports/issues.html
Labels: Backend

#1179 feat: user display name
  apiserver/bin/user_script.py
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/people.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/serializers/user.py
  apiserver/plane/api/serializers/workspace.py
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/analytic.py
  apiserver/plane/api/views/auth_extended.py
  apiserver/plane/api/views/importer.py
  apiserver/plane/api/views/page.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/user.py
  apiserver/plane/api/views/workspace.py
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/db/migrations/0041_user_display_name_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/user.py
Labels: Backend

#1800 chore: subscribed by me tab on my issues page
  apps/app/components/issues/my-issues/my-issues-view.tsx
  apps/app/constants/fetch-keys.ts
  apps/app/contexts/issue-view.context.tsx
  apps/app/contexts/profile-issues-context.tsx
  apps/app/hooks/my-issues/use-my-issues-filter.tsx
  apps/app/hooks/my-issues/use-my-issues.tsx
  apps/app/hooks/use-profile-issues.tsx
  apps/app/pages/[workspaceSlug]/me/my-issues.tsx
  apps/app/types/issues.d.ts
Labels: Plane App

#1795 Fixed problem with empty label filter
  apps/app/components/ui/multi-level-dropdown.tsx
Labels: UI, Plane App

#1802 chore: empty state for multi-level dropdown
  apps/app/components/ui/multi-level-dropdown.tsx
Labels: UI

#1815 chore: profile and my issues page start date option
  apps/app/contexts/profile-issues-context.tsx
  apps/app/hooks/my-issues/use-my-issues-filter.tsx
Labels: bug, frontend

#1818 style: option to edit display name in profile page
  apps/app/pages/[workspaceSlug]/me/profile/index.tsx
Labels: bug, frontend

#1817 style: displaying email in members page depending on user role
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  apps/app/pages/[workspaceSlug]/settings/members.tsx
Labels: feature, frontend

#1819 fix: import user using endpoint with email
  apps/app/components/integration/jira/import-users.tsx
Labels: frontend

#1823 refactor: added validation for display_name
  apps/app/pages/[workspaceSlug]/me/profile/index.tsx
Labels: frontend

#1831 refactor: not making calls to member's endpoint to get membership status
  apps/app/components/project/single-project-card.tsx
  apps/app/types/projects.d.ts
Labels: frontend, UI

#1829 refactor: both delete or backspace can be used to open modal
  apps/app/components/command-palette/command-pallette.tsx
Labels: frontend

#1785 fix: issues n plus 1
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/view.py
Labels: Backend

#1799 remove: auto start date configuration
  apiserver/plane/db/models/issue.py
Labels: Backend

#1804 fix: project members endpoint email
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/project.py
Labels: Backend

#1808 fix: user id for default analytics
  apiserver/plane/api/views/analytic.py
Labels: Backend

#1820 chore: issue list date filters and properties
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/migrations/0043_auto_20230809_1645.py
  apiserver/plane/db/models/workspace.py
  apiserver/plane/utils/issue_filters.py
Labels: Backend

#1828 chore: project member role
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/views/project.py
Labels: Backend

#1830 fix: project states create
  apiserver/plane/api/views/project.py
Labels: Backend

#1835 chore: sort order for cycle and modules
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
Labels: Backend

#1834 fix: issue date filtering
  apiserver/plane/utils/issue_filters.py
Labels: Backend

#1805 chore: issue activity user redirection added
  apps/app/components/analytics/scope-and-demand/leaderboard.tsx
  apps/app/components/analytics/scope-and-demand/scope-and-demand.tsx
  apps/app/components/core/activity.tsx
  apps/app/types/analytics.d.ts
Labels: frontend

#1806 style: ui improvement
  apps/app/components/core/filters/issues-view-filter.tsx
  apps/app/components/core/views/board-view/board-header.tsx
  apps/app/components/core/views/board-view/single-issue.tsx
  apps/app/components/issues/label.tsx
  apps/app/components/issues/my-issues/my-issues-view-options.tsx
  apps/app/components/issues/view-select/assignee.tsx
  apps/app/components/issues/view-select/priority.tsx
  apps/app/components/issues/view-select/state.tsx
  apps/app/components/profile/profile-issues-view-options.tsx
  apps/app/components/ui/avatar.tsx
  apps/app/components/workspace/sidebar-dropdown.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
Labels: frontend, UI

#1816 style: sidebar ui improvement
  apps/app/components/notifications/notification-popover.tsx
  apps/app/components/project/sidebar-list.tsx
  apps/app/components/project/single-project-card.tsx
  apps/app/components/project/single-sidebar-project.tsx
  apps/app/components/workspace/index.ts
  apps/app/components/workspace/sidebar-menu.tsx
  apps/app/components/workspace/sidebar-quick-action.tsx
  apps/app/layouts/app-layout/app-sidebar.tsx
Labels: frontend, UI

#1836 chore: profile cover photo
  apps/app/components/core/image-picker-popover.tsx
  apps/app/pages/[workspaceSlug]/me/profile/index.tsx
  apps/app/types/users.d.ts
Labels: frontend

#1837 chore: project search added in project list page
  apps/app/pages/[workspaceSlug]/projects/index.tsx
Labels: frontend

#1810 chore: gantt chart resizable blocks, y-axis drag and drop
  apps/app/components/core/filters/issues-view-filter.tsx
  apps/app/components/cycles/cycles-list-gantt-chart.tsx
  apps/app/components/cycles/cycles-list/all-cycles-list.tsx
  apps/app/components/cycles/cycles-list/completed-cycles-list.tsx
  apps/app/components/cycles/cycles-list/draft-cycles-list.tsx
  apps/app/components/cycles/cycles-list/upcoming-cycles-list.tsx
  apps/app/components/cycles/cycles-view.tsx
  apps/app/components/cycles/gantt-chart.tsx
  apps/app/components/gantt-chart/blocks/block.tsx
  apps/app/components/gantt-chart/blocks/blocks-display.tsx
  apps/app/components/gantt-chart/blocks/index.ts
  apps/app/components/gantt-chart/blocks/index.tsx
  apps/app/components/gantt-chart/chart/bi-week.tsx
  apps/app/components/gantt-chart/chart/day.tsx
  apps/app/components/gantt-chart/chart/hours.tsx
  apps/app/components/gantt-chart/chart/index.tsx
  apps/app/components/gantt-chart/chart/month.tsx
  apps/app/components/gantt-chart/chart/quarter.tsx
  apps/app/components/gantt-chart/chart/week.tsx
  apps/app/components/gantt-chart/chart/year.tsx
  apps/app/components/gantt-chart/helpers/block-structure.tsx
  apps/app/components/gantt-chart/helpers/draggable.tsx
  apps/app/components/gantt-chart/helpers/index.ts
  apps/app/components/gantt-chart/hooks/block-update.tsx
  apps/app/components/gantt-chart/index.ts
  apps/app/components/gantt-chart/root.tsx
  apps/app/components/gantt-chart/types/index.ts
  apps/app/components/gantt-chart/views/month-view.ts
  apps/app/components/gantt-chart/views/year-view.ts
  apps/app/components/issues/gantt-chart.tsx
  apps/app/components/issues/modal.tsx
  apps/app/components/modules/gantt-chart.tsx
  apps/app/components/modules/modules-list-gantt-chart.tsx
  apps/app/components/project/sidebar-list.tsx
  apps/app/components/views/gantt-chart.tsx
  apps/app/constants/fetch-keys.ts
  apps/app/hooks/gantt-chart/cycle-issues-view.tsx
  apps/app/hooks/gantt-chart/issue-view.tsx
  apps/app/hooks/gantt-chart/module-issues-view.tsx
  apps/app/hooks/gantt-chart/view-issues-view.tsx
  apps/app/layouts/app-layout/app-sidebar.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  apps/app/services/modules.service.ts
  apps/app/types/cycles.d.ts
  apps/app/types/modules.d.ts
  yarn.lock
Labels: frontend, improvement

#1842 fix: cmdk not changing theme if active theme is custom-theme
  apps/app/components/command-palette/change-interface-theme.tsx
Labels: bug, frontend

#1833 fix: cmdk modal not closing when choosing an option
  apps/app/components/command-palette/command-k.tsx
Labels: frontend

#1839 feat: randomize color on label create
  apps/app/components/labels/create-label-modal.tsx
  apps/app/components/labels/create-update-label-inline.tsx
  apps/app/constants/label.ts
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
Labels: feature, frontend

#1807 chore: updated user permission for project and workspace settings
  apps/app/components/workspace/delete-workspace-modal.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  apps/app/pages/[workspaceSlug]/settings/index.tsx
Labels: frontend

#1847 fix: sub issue progress indicator fix
  apps/app/components/issues/sub-issues-list.tsx
Labels: frontend

#1824 chore: start date option added in spreadsheet view
  apps/app/components/core/views/spreadsheet-view/single-issue.tsx
  apps/app/components/issues/view-select/start-date.tsx
  apps/app/constants/spreadsheet.ts
Labels: frontend, UI

#1843 fix: empty groups not appearing on the my issues Kanban board
  apps/app/hooks/my-issues/use-my-issues.tsx
Labels: bug, frontend

#1772 feat: project public boards
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/project.py
  apiserver/plane/db/migrations/0041_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/project.py
Labels: Backend

#1794 fix: export issues in CSV, JSON and XLSX
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/exporter.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/exporter.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
  apiserver/plane/bgtasks/project_issue_export.py
  apiserver/plane/celery.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/exporter.py
  apiserver/plane/settings/common.py
  apiserver/requirements/base.txt
Labels: enhancement, Backend

#1840 feat: csv, json and, xlsx exporter
  apps/app/components/command-palette/command-k.tsx
  apps/app/components/exporter/export-modal.tsx
  apps/app/components/exporter/guide.tsx
  apps/app/components/exporter/index.tsx
  apps/app/components/exporter/single-export.tsx
  apps/app/components/integration/github/root.tsx
  apps/app/components/integration/guide.tsx
  apps/app/components/integration/jira/root.tsx
  apps/app/components/ui/integration-and-import-export-banner.tsx
  apps/app/constants/fetch-keys.ts
  apps/app/constants/workspace.ts
  apps/app/layouts/settings-navbar.tsx
  apps/app/pages/[workspaceSlug]/settings/exports.tsx
  apps/app/pages/[workspaceSlug]/settings/imports.tsx
  apps/app/public/services/csv.png
  apps/app/public/services/excel.png
  apps/app/public/services/json.png
  apps/app/services/integration/csv.services.ts
  apps/app/services/integration/index.ts
  apps/app/services/track-event.service.ts
  apps/app/types/importer/index.ts
  apps/app/types/index.d.ts
Labels: feature, frontend

#1854 fix: gantt chart block left drag flicker
  apps/app/components/cycles/cycles-list-gantt-chart.tsx
  apps/app/components/gantt-chart/helpers/draggable.tsx
  apps/app/components/gantt-chart/hooks/block-update.tsx
  apps/app/components/modules/modules-list-gantt-chart.tsx
Labels: frontend, UI

#1857 fix: route fix in imports and exports
  apps/app/components/exporter/guide.tsx
  apps/app/components/integration/guide.tsx
Labels: frontend

#1860 fix: slack queryset
  apiserver/plane/api/views/integration/slack.py
Labels: Backend

#1832 feat : Tiptap integration
  .gitignore
  apps/app/components/command-palette/change-interface-theme.tsx
  apps/app/components/command-palette/command-pallette.tsx
  apps/app/components/core/modals/gpt-assistant-modal.tsx
  apps/app/components/core/views/board-view/single-issue.tsx
  apps/app/components/core/views/list-view/single-issue.tsx
  apps/app/components/cycles/cycles-list-gantt-chart.tsx
  apps/app/components/estimates/single-estimate.tsx
  apps/app/components/gantt-chart/hooks/block-update.tsx
  apps/app/components/inbox/inbox-action-headers.tsx
  apps/app/components/issues/activity.tsx
  apps/app/components/issues/comment/add-comment.tsx
  apps/app/components/issues/comment/comment-card.tsx
  apps/app/components/issues/description-form.tsx
  apps/app/components/issues/form.tsx
  apps/app/components/issues/main-content.tsx
  apps/app/components/issues/sidebar-select/label.tsx
  apps/app/components/labels/labels-list-modal.tsx
  apps/app/components/modules/modules-list-gantt-chart.tsx
  apps/app/components/pages/create-update-block-inline.tsx
  apps/app/components/pages/page-form.tsx
  apps/app/components/pages/single-page-block.tsx
  apps/app/components/profile/profile-issues-view.tsx
  apps/app/components/rich-text-editor/index.tsx
  apps/app/components/rich-text-editor/mention-autocomplete.tsx
  apps/app/components/rich-text-editor/sample.tsx
  apps/app/components/rich-text-editor/toolbar/float-tool-tip.tsx
  apps/app/components/rich-text-editor/toolbar/heading-controls.tsx
  apps/app/components/rich-text-editor/toolbar/index.tsx
  apps/app/components/rich-text-editor/toolbar/link.tsx
  apps/app/components/rich-text-editor/toolbar/table-controls.tsx
  apps/app/components/tiptap/bubble-menu/index.tsx
  apps/app/components/tiptap/bubble-menu/link-selector.tsx
  apps/app/components/tiptap/bubble-menu/node-selector.tsx
  apps/app/components/tiptap/extensions/index.tsx
  apps/app/components/tiptap/index.tsx
  apps/app/components/tiptap/plugins/upload-image.tsx
  apps/app/components/tiptap/props.tsx
  apps/app/components/tiptap/slash-command/index.tsx
  apps/app/components/tiptap/utils.ts
  apps/app/components/workspace/help-section.tsx
  apps/app/contexts/inbox-view-context.tsx
  apps/app/contexts/issue-view.context.tsx
  apps/app/contexts/user-notification-context.tsx
  apps/app/hooks/use-comment-reaction.tsx
  apps/app/hooks/use-issue-properties.tsx
  apps/app/hooks/use-issue-reaction.tsx
  apps/app/hooks/use-user-notifications.tsx
  apps/app/package.json
  apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
  apps/app/pages/[workspaceSlug]/me/profile/index.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  apps/app/pages/[workspaceSlug]/settings/members.tsx
  apps/app/postcss.config.js
  apps/app/services/file.service.ts
  apps/app/styles/editor.css
  apps/app/tailwind.config.js
  yarn.lock
Labels: feature, frontend

#1862 fix: analytics export
  apiserver/plane/bgtasks/analytic_plot_export.py
Labels: Backend

#1865 chore: file name changed for exported issues
  apiserver/plane/bgtasks/export_task.py
Labels: Backend, improvement

#1866 chore: deploy board status for project
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/views/project.py
Labels: Backend

#1870 fix: added slug in filename for export issues
  apiserver/plane/api/views/exporter.py
  apiserver/plane/bgtasks/export_task.py
Labels: Backend

#1851 chore: updated migration files for 0.11
  apiserver/plane/db/migrations/0041_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py
  apiserver/plane/db/migrations/0041_user_display_name_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/migrations/0042_auto_20230809_1745.py
  apiserver/plane/db/migrations/0043_auto_20230809_1645.py
Labels: Backend, migrations

#1861 fix: notification card not redirecting to archive issue detail for archived issue
  apps/app/components/notifications/notification-card.tsx
Labels: bug, frontend

#1874 chore: new field in project lite serializer
  apiserver/plane/api/serializers/project.py
Labels: Backend

#1901 fix: completed cycle validation , style: assignee count alignment fix
  apps/app/components/cycles/single-cycle-card.tsx
  apps/app/components/cycles/single-cycle-list.tsx
  apps/app/components/ui/avatar.tsx
Labels: frontend

#1888 chore: start date property for custom analytics' x-axis and group
  apps/app/constants/analytics.ts
Labels: frontend, improvement

#1886 chore: set order by to manual on gantt chart
  apps/app/contexts/issue-view.context.tsx
Labels: bug, frontend, improvement

#1905 chore: module link model
  apiserver/plane/db/migrations/0041_cycle_sort_order_issuecomment_access_and_more.py
  apiserver/plane/db/models/module.py
Labels: Backend

#1904 fix: dashboard upcoming issues list
  apps/app/components/workspace/issues-list.tsx
  apps/app/types/issues.d.ts
Labels: bug, frontend

#1908 fix: priority ordering
  apiserver/plane/api/views/workspace.py
Labels: Backend

#1913 fix: context menu dynamic positioning, multiple context menus opening issue
  apps/app/components/core/views/board-view/single-issue.tsx
  apps/app/components/core/views/list-view/single-issue.tsx
  apps/app/components/ui/dropdowns/context-menu.tsx
  apps/app/hooks/use-outside-click-detector.tsx
Labels: bug, frontend

#1896 fix: Image resize, Link selector in Modals, Delete/ sync images and so much more
  apps/app/components/core/modals/gpt-assistant-modal.tsx
  apps/app/components/inbox/inbox-main-content.tsx
  apps/app/components/issues/activity.tsx
  apps/app/components/issues/comment/add-comment.tsx
  apps/app/components/issues/comment/comment-card.tsx
  apps/app/components/issues/description-form.tsx
  apps/app/components/issues/form.tsx
  apps/app/components/issues/main-content.tsx
  apps/app/components/pages/create-update-block-inline.tsx
  apps/app/components/pages/single-page-block.tsx
  apps/app/components/tiptap/bubble-menu/link-selector.tsx
  apps/app/components/tiptap/bubble-menu/utils/link-validator.tsx
  apps/app/components/tiptap/extensions/image-resize.tsx
  apps/app/components/tiptap/extensions/index.tsx
  apps/app/components/tiptap/extensions/updated-image.tsx
  apps/app/components/tiptap/index.tsx
  apps/app/components/tiptap/plugins/delete-image.tsx
  apps/app/components/tiptap/plugins/upload-image.tsx
  apps/app/components/tiptap/props.tsx
  apps/app/components/tiptap/slash-command/index.tsx
  apps/app/package.json
  apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
  apps/app/styles/editor.css
  yarn.lock
Labels: frontend, UI

#1915 refactor: project and workspace delete modals
  apps/app/components/project/delete-project-modal.tsx
  apps/app/components/ui/input/index.tsx
  apps/app/components/ui/input/types.d.ts
  apps/app/components/workspace/delete-workspace-modal.tsx
Labels: frontend, improvement

#1914 fix: create module form start and target date validations
  apps/app/components/issues/select/date.tsx
  apps/app/components/modules/form.tsx
Labels: bug, frontend

#1926 fix: create project button not appearing on the sidebar
  apps/app/components/project/sidebar-list.tsx
Labels: bug, frontend

#1945 fix: cycle and module date validation
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/serializers/module.py
Labels: Backend

#1946 chore: update export services icons
  apps/app/constants/workspace.ts
  apps/app/public/services/csv.png
  apps/app/public/services/csv.svg
  apps/app/public/services/excel.png
  apps/app/public/services/excel.svg
  apps/app/public/services/json.png
  apps/app/public/services/json.svg
Labels: frontend

#1948 Promot: Stage Release to Production
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/serializers/module.py
  apps/app/constants/workspace.ts
  apps/app/public/services/csv.png
  apps/app/public/services/csv.svg
  apps/app/public/services/excel.png
  apps/app/public/services/excel.svg
  apps/app/public/services/json.png
  apps/app/public/services/json.svg
Labels: Promot

#1949 fix: label color select popover overflow
  apps/app/components/issues/sidebar-select/label.tsx
  apps/app/components/issues/sidebar.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
Labels: bug, frontend

#1944 fix: mutate sidebar projects list after joining
  apps/app/components/project/join-project-modal.tsx
  apps/app/components/project/sidebar-list.tsx
  apps/app/pages/[workspaceSlug]/projects/index.tsx
Labels: bug, frontend

#1943 feat: project deploy boards list endpoint
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/project.py
Labels: Backend

#1955 feat: start date filter across the platform
  apps/app/components/core/filters/date-filter-modal.tsx
  apps/app/components/core/filters/date-filter-select.tsx
  apps/app/components/core/filters/filters-list.tsx
  apps/app/components/core/filters/index.ts
  apps/app/components/core/filters/issues-view-filter.tsx
  apps/app/components/core/views/issues-view.tsx
  apps/app/components/issues/my-issues/my-issues-select-filters.tsx
  apps/app/components/issues/my-issues/my-issues-view-options.tsx
  apps/app/components/issues/my-issues/my-issues-view.tsx
  apps/app/components/profile/profile-issues-view-options.tsx
  apps/app/components/profile/profile-issues-view.tsx
  apps/app/components/views/form.tsx
  apps/app/components/views/select-filters.tsx
  apps/app/constants/fetch-keys.ts
  apps/app/constants/filters.ts
  apps/app/contexts/issue-view.context.tsx
  apps/app/contexts/profile-issues-context.tsx
  apps/app/hooks/my-issues/use-my-issues-filter.tsx
  apps/app/hooks/my-issues/use-my-issues.tsx
  apps/app/hooks/use-issues-view.tsx
  apps/app/hooks/use-profile-issues.tsx
  apps/app/types/issues.d.ts
  apps/app/types/views.d.ts
Labels: feature, frontend

#1957 chore: group by assignees option for project issues
  apps/app/components/core/views/board-view/board-header.tsx
  apps/app/components/core/views/issues-view.tsx
  apps/app/components/core/views/list-view/single-list.tsx
  apps/app/components/issues/my-issues/my-issues-view-options.tsx
  apps/app/components/profile/profile-issues-view-options.tsx
  apps/app/constants/issue.ts
  apps/app/types/issues.d.ts
Labels: frontend, improvement

#1969 chore: custom CSS shadow variables added
  apps/app/styles/globals.css
  apps/app/tailwind.config.js
Labels: frontend

#1970 fix: redirection after deleting a project
  apps/app/components/project/delete-project-modal.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
Labels: bug, frontend

#1973 chore: issue activity redirection to cycle and module
  apps/app/components/core/activity.tsx
Labels: frontend, improvement

#1968 fix: tiptap editor max width
  apps/app/components/tiptap/index.tsx
Labels: bug, frontend

#1962 fix: add member role and member status in project create response
  apiserver/plane/api/views/project.py
Labels: Backend

#1981 dev: update python runtime
  apiserver/runtime.txt
Labels: Backend

#1979 feat: peek overview for spreadsheet issues
  apps/app/components/core/views/issues-view.tsx
  apps/app/components/core/views/spreadsheet-view/single-issue.tsx
  apps/app/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  apps/app/components/inbox/inbox-issue-activity.tsx
  apps/app/components/inbox/inbox-main-content.tsx
  apps/app/components/inbox/index.ts
  apps/app/components/issues/activity.tsx
  apps/app/components/issues/comment/add-comment.tsx
  apps/app/components/issues/description-form.tsx
  apps/app/components/issues/index.ts
  apps/app/components/issues/main-content.tsx
  apps/app/components/issues/peek-overview/full-screen-peek-view.tsx
  apps/app/components/issues/peek-overview/header.tsx
  apps/app/components/issues/peek-overview/index.ts
  apps/app/components/issues/peek-overview/issue-activity.tsx
  apps/app/components/issues/peek-overview/issue-details.tsx
  apps/app/components/issues/peek-overview/issue-properties.tsx
  apps/app/components/issues/peek-overview/layout.tsx
  apps/app/components/issues/peek-overview/side-peek-view.tsx
  apps/app/components/issues/sidebar-select/assignee.tsx
  apps/app/components/issues/sidebar-select/estimate.tsx
  apps/app/components/issues/sidebar-select/priority.tsx
  apps/app/components/issues/sidebar-select/state.tsx
  apps/app/components/issues/sidebar.tsx
Labels: feature, frontend

#1975 fix: project members n+1
  apiserver/plane/api/serializers/project.py
Labels: Backend

#1900 dev: gantt chart revamp
  apps/app/components/core/filters/issues-view-filter.tsx
  apps/app/components/core/views/all-views.tsx
  apps/app/components/cycles/gantt-chart/blocks.tsx
  apps/app/components/cycles/gantt-chart/cycle-issues-layout.tsx
  apps/app/components/cycles/gantt-chart/cycles-list-layout.tsx
  apps/app/components/cycles/gantt-chart/index.ts
  apps/app/components/cycles/index.ts
  apps/app/components/cycles/single-cycle-list.tsx
  apps/app/components/gantt-chart/blocks/block.tsx
  apps/app/components/gantt-chart/blocks/blocks-display.tsx
  apps/app/components/gantt-chart/blocks/index.ts
  apps/app/components/gantt-chart/chart/index.tsx
  apps/app/components/gantt-chart/chart/month.tsx
  apps/app/components/gantt-chart/contexts/index.tsx
  apps/app/components/gantt-chart/data/index.ts
  apps/app/components/gantt-chart/helpers/draggable.tsx
  apps/app/components/gantt-chart/hooks/index.tsx
  apps/app/components/gantt-chart/root.tsx
  apps/app/components/gantt-chart/sidebar.tsx
  apps/app/components/gantt-chart/types/index.ts
  apps/app/components/icons/state-group-icon.tsx
  apps/app/components/issues/gantt-chart/blocks.tsx
  apps/app/components/issues/gantt-chart/index.ts
  apps/app/components/issues/gantt-chart/layout.tsx
  apps/app/components/modules/gantt-chart/blocks.tsx
  apps/app/components/modules/gantt-chart/index.ts
  apps/app/components/modules/gantt-chart/module-issues-layout.tsx
  apps/app/components/modules/gantt-chart/modules-list-layout.tsx
  apps/app/components/modules/index.ts
  apps/app/components/views/gantt-chart.tsx
  apps/app/constants/issue.ts
  apps/app/helpers/date-time.helper.ts
  apps/app/hooks/gantt-chart/cycle-issues-view.tsx
  apps/app/hooks/gantt-chart/issue-view.tsx
  apps/app/hooks/gantt-chart/module-issues-view.tsx
  apps/app/hooks/gantt-chart/view-issues-view.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  apps/app/types/issues.d.ts
Labels: frontend, improvement

#1982 feat: mark all notifications as read
  apps/app/components/notifications/notification-header.tsx
  apps/app/components/notifications/notification-popover.tsx
  apps/app/hooks/use-user-notifications.tsx
  apps/app/services/notifications.service.ts
  apps/app/types/notifications.d.ts
Labels: frontend, improvement

#1984 chore: don't show completion percentage if user doesn't have any assigned issues
  apps/app/components/profile/sidebar.tsx
Labels: frontend, improvement

#1983 fix: my profile activity endpoint
  apps/app/pages/[workspaceSlug]/me/profile/activity.tsx
  apps/app/services/user.service.ts
Labels: bug, frontend

#1997 fix: Cycles and Modules Cards view responsiveness
  apps/app/components/cycles/cycles-view.tsx
  apps/app/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: UI, improvement

#1985 [chore] Update development workflows with every PR build and removed image update on every merge
  .github/workflows/Build_Test_Pull_Request.yml
  .github/workflows/Update_Docker_Images.yml
  .github/workflows/push-image-backend.yml
  .github/workflows/push-image-deploy.yml
  .github/workflows/push-image-frontend.yml
  .github/workflows/push-image-proxy.yml
Labels: CI/CD

#1956 chore: improve access field for comments for public boards
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/issue.py
Labels: Backend

#1980 chore: update user activity endpoint to return only workspace activities
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/user.py
Labels: Backend

#1994 fix: n+1 in issue history and issue automation tasks
  apiserver/plane/api/views/issue.py
  apiserver/plane/bgtasks/issue_automation_task.py
Labels: Backend, n+1

#1996 fix: issue exports in self hosted instances
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/exporter_expired_task.py
Labels: self-hosted, Backend

#1999 dev: remove gunicorn config
  apiserver/Procfile
Labels: Backend

#1963 feat: mark all read notifications
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/notification.py
Labels: feature, Backend

#2003 chore: project public board issue retrieve
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/urls.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/project.py
Labels: Backend

#2010 fix: external comments in deploy boards
  apiserver/plane/api/views/issue.py
Labels: Backend

#2006 fix: issue votes
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/migrations/0042_alter_issuevote_unique_together_alter_issuevote_vote_and_more.py
  apiserver/plane/db/models/issue.py
Labels: Backend, improvement

#2013 fix: access creation in comments
  apiserver/plane/api/serializers/issue.py
Labels: Backend

#2002 feat: user timezone select option in profile settings
  apps/app/constants/timezones.ts
  apps/app/pages/[workspaceSlug]/me/profile/index.tsx
  apps/app/types/users.d.ts
Labels: feature, frontend

#2012 feat: access selector for comment
  apps/app/components/issues/comment/add-comment.tsx
  apps/app/components/issues/main-content.tsx
  apps/app/services/issues.service.ts
  apps/app/types/issues.d.ts
  apps/app/types/projects.d.ts
Labels: feature, frontend

#2011 chore: update module status icons and colors
  apps/app/components/icons/index.ts
  apps/app/components/icons/module/backlog.tsx
  apps/app/components/icons/module/cancelled.tsx
  apps/app/components/icons/module/completed.tsx
  apps/app/components/icons/module/in-progress.tsx
  apps/app/components/icons/module/index.ts
  apps/app/components/icons/module/module-status-icon.tsx
  apps/app/components/icons/module/paused.tsx
  apps/app/components/icons/module/planned.tsx
  apps/app/components/modules/gantt-chart/blocks.tsx
  apps/app/components/modules/select/status.tsx
  apps/app/components/modules/sidebar.tsx
  apps/app/constants/module.ts
  apps/app/types/modules.d.ts
Labels: frontend, improvement

#1972 chore: track public board comments and reaction users for public deploy boards
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/project.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/project.py
Labels: Backend

#2009 feat: user timezones
  apiserver/plane/api/views/base.py
  apiserver/plane/db/migrations/0042_alter_analyticview_created_by_and_more.py
  apiserver/plane/db/models/user.py
  apiserver/plane/settings/common.py
Labels: feature, Backend

#2016 fix: user created by stats
  apiserver/plane/api/views/workspace.py
Labels: Backend

#1938 fix: asset key validation
  apiserver/plane/api/views/asset.py
Labels: Backend, improvement

#2021 dev: revamp peek overview
  apps/app/components/command-palette/command-k.tsx
  apps/app/components/core/views/spreadsheet-view/single-issue.tsx
  apps/app/components/core/views/spreadsheet-view/spreadsheet-view.tsx
  apps/app/components/issues/gantt-chart/blocks.tsx
  apps/app/components/issues/peek-overview/full-screen-peek-view.tsx
  apps/app/components/issues/peek-overview/header.tsx
  apps/app/components/issues/peek-overview/issue-properties.tsx
  apps/app/components/issues/peek-overview/layout.tsx
  apps/app/components/issues/peek-overview/side-peek-view.tsx
  apps/app/hooks/use-spreadsheet-issues-view.tsx
  apps/app/store/issues.ts
  apps/app/store/root.ts
Labels: frontend, improvement

#2022 dev: revamp publish project modal
  apps/app/components/project/publish-project/modal.tsx
  apps/app/components/project/publish-project/popover.tsx
  apps/app/components/project/single-sidebar-project.tsx
  apps/app/store/project-publish.tsx
Labels: frontend, improvement

#2018 fix: bugs on the user profile page
  apps/app/components/profile/sidebar.tsx
  apps/app/contexts/profile-issues-context.tsx
  apps/app/hooks/use-profile-issues.tsx
Labels: bug, frontend

#2026 chore: return issue votes in public issue list endpoint
  apiserver/plane/api/serializers/issue.py
Labels: Backend

#2008 [feat]: Tiptap table integration
  apps/app/components/tiptap/bubble-menu/index.tsx
  apps/app/components/tiptap/bubble-menu/link-selector.tsx
  apps/app/components/tiptap/extensions/index.tsx
  apps/app/components/tiptap/extensions/table/table-cell.ts
  apps/app/components/tiptap/extensions/table/table-header.ts
  apps/app/components/tiptap/extensions/table/table.ts
  apps/app/components/tiptap/index.tsx
  apps/app/components/tiptap/plugins/delete-image.tsx
  apps/app/components/tiptap/plugins/upload-image.tsx
  apps/app/components/tiptap/props.tsx
  apps/app/components/tiptap/slash-command/index.tsx
  apps/app/components/tiptap/table-menu/index.tsx
  apps/app/package.json
  apps/app/styles/editor.css
  yarn.lock
Labels: UI

#2033 style: tiptap table
  apps/app/components/tiptap/index.tsx
  apps/app/components/tiptap/table-menu/index.tsx
  apps/app/styles/editor.css
  apps/app/styles/globals.css
Labels: bug, frontend, UI

#2037 fix: subscribed issues are filtering
  apiserver/plane/api/views/issue.py
Labels: Backend

#2030 chore: public board endpoints
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/db/models/issue.py
Labels: Backend
