Repository makeplane/plane, pull requests merged in 2024-05, with the labels that each got.

#4320 [WEB-1096] fix: kanban collapsed vertical writing mode in firefox
  web/styles/globals.css
Labels: 🐛bug, 🌐frontend

#4323 [WEB-1132] fix: display datetime fields in user time zone format
  apiserver/plane/api/views/issue.py
  apiserver/plane/app/views/cycle/issue.py
  apiserver/plane/app/views/issue/archive.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/issue/sub_issue.py
  apiserver/plane/app/views/module/archive.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/module/issue.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/utils/user_timezone_converter.py
Labels: ⚙️backend, 🌟improvement

#4324 [WEB-1101] chore: workspace view quick action enhancement
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/workspace/views/default-view-quick-action.tsx
  web/components/workspace/views/header.tsx
  web/components/workspace/views/index.ts
  web/components/workspace/views/quick-action.tsx
Labels: 🌟enhancement, 🌐frontend

#4325 [WEB-1124] chore: default pages sorting order
  web/store/pages/project-page.store.ts
Labels: 🌐frontend, 🌟improvement

#4326 [WEB-1105] chore: show display name's first character in the avatar
  web/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx
Labels: 🐛bug, 🌐frontend

#4327 [WEB-1135] chore: store page full width information in local storage
  packages/types/src/pages.d.ts
  web/components/pages/editor/editor-body.tsx
  web/components/pages/editor/header/mobile-root.tsx
  web/components/pages/editor/header/options-dropdown.tsx
  web/components/pages/editor/header/root.tsx
  web/hooks/use-page-filters.ts
  web/store/pages/page.store.ts
Labels: 🌐frontend, 🌟improvement

#4328 [WEB-1145] chore: updated sub issue count in cycles, modules and project
  apiserver/plane/app/views/project/base.py
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-archives.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
Labels: 🌐frontend, ⚙️backend

#4329 [WEB-1146] fix: module sub-header empty state validation
  web/components/modules/modules-list-view.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: 🌐frontend, 🧹chore

#4337 [WEB-1101] fix: existing issue list modal loading flicker
  web/components/core/modals/existing-issues-list-modal.tsx
Labels: 🐛bug, 🌟enhancement, 🌐frontend

#4338 [WEB-1154] fix: delete attachment modal logic
  web/components/issues/attachment/attachment-detail.tsx
  web/components/issues/attachment/delete-attachment-modal.tsx
  web/components/issues/attachment/index.ts
  web/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend

#4335 [WEB-1143] fix: project context menu
  web/components/cycles/quick-actions.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/modules/quick-actions.tsx
  web/components/pages/dropdowns/quick-actions.tsx
  web/components/project/card.tsx
  web/components/views/quick-actions.tsx
  web/components/workspace/views/default-view-quick-action.tsx
  web/components/workspace/views/quick-action.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4333 [WEB -1149] dev: update dependencies
  apiserver/plane/api/views/issue.py
  apiserver/requirements/base.txt
  apiserver/requirements/local.txt
  apiserver/requirements/production.txt
  apiserver/requirements/test.txt
Labels: 📦dependencies

#4340 [WEB-1102 ] fix: inbox create issue comment fixed
  packages/editor/lite-text-editor/src/ui/index.tsx
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
  web/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🌐web, ✍️editor

#4341 [WEB-1126] fix: inbox issue attachment upload
  web/components/issues/attachment/attachment-upload.tsx
  web/components/issues/attachment/root.tsx
Labels: 🐛bug, 🌐frontend

#4343 [WEB-1158] chore: workspace module list endpoint
  apiserver/plane/app/views/workspace/cycle.py
  apiserver/plane/app/views/workspace/module.py
Labels: 🐛bug, ⚙️backend

#4346 [WEB-1109] chore: hide display properties in the calendar layout
  web/constants/issue.ts
Labels: 🌐frontend, 🌟improvement

#4344 [WEB-1150] fix: inbox issue header quick action validation
  web/components/inbox/content/inbox-issue-header.tsx
Labels: 🌐frontend, 🧹chore

#4348 chore: update the default name that is added to instance
  apiserver/plane/license/management/commands/register_instance.py
Labels: ⚙️backend, 🧹chore

#4350 [WEB-1136] chore: Kanban drag and drop improvements
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/kanban/utils.ts
  web/package.json
  web/styles/globals.css
  yarn.lock
Labels: 🌐frontend, 🌟improvement

#4354 [WEB-1171] fix: peek overview in Gantt chart full screen view
  web/components/gantt-chart/chart/root.tsx
  yarn.lock
Labels: 🐛bug, 🌐frontend

#4352 [WEB-1175] fix: modal context
  web/components/issues/issue-detail/parent-select.tsx
  web/components/issues/issue-detail/relation-select.tsx
  web/components/issues/peek-overview/header.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/root.tsx
  web/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4347 [WEB-1179] style: make editor height according to the content height
  web/components/editor/rich-text-editor/rich-text-editor.tsx
  web/components/editor/rich-text-editor/rich-text-read-only-editor.tsx
  web/components/inbox/content/issue-root.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/peek-overview/issue-detail.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4355 [WEB - 1180]dev: add start date and end date to projects
  apiserver/plane/db/migrations/0065_auto_20240415_0937.py
  apiserver/plane/db/models/project.py
Labels: ⚙️backend, 🔄migrations

#4357 [WEB-1183] fix: updated global issues filter while updating global view
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/workspace/views/modal.tsx
  web/store/global-view.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4358 [WEB-1181] chore: added a loader for page description
  web/components/pages/editor/editor-body.tsx
  web/components/pages/loaders/index.ts
  web/components/pages/loaders/page-content-loader.tsx
Labels: 🌐frontend, 🌟improvement

#4330 [WEB - 1122] fix: webhook for issues, issue comments, projects, cycles and modules.
  apiserver/plane/api/serializers/inbox.py
  apiserver/plane/api/views/base.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/project.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/base.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/cycle/issue.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/comment.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/module/issue.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/webhook_task.py
Labels: ⚙️backend, 📡api

#4374 [WEB-1206] chore: bulk delete api logs
  apiserver/plane/bgtasks/api_logs_task.py
  apiserver/plane/celery.py
  apiserver/plane/settings/common.py
Labels: 🌟enhancement, ⚙️backend

#4376 [WEB-1137] fix: Firefox distorted vertical text
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
Labels: 🐛bug, 🌐frontend

#4372 [WEB-1007] chore: invalid issue error empty state added
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4371 [WEB-1114] chore: recent activity message updated
  web/components/core/activity.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4370 [WEB-1157] chore: label select improvement
  web/components/issues/select/label.tsx
  web/components/ui/labels-list.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4360 [WEB-1151] fix: email notification for mentions
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/notification_task.py
Labels: 🐛bug, ⚙️backend

#4373 [WEB-1134] fix: module link create and delete mutation
  web/components/core/sidebar/links-list.tsx
  web/components/modules/sidebar.tsx
  web/store/module.store.ts
Labels: 🐛bug, 🌐frontend

#4345 [WEB-1127] style: create and delete modals' consistency
  web/components/api-token/delete-token-modal.tsx
  web/components/api-token/modal/create-token-modal.tsx
  web/components/api-token/modal/form.tsx
  web/components/api-token/modal/generated-token-details.tsx
  web/components/core/modals/alert-modal.tsx
  web/components/core/modals/index.ts
  web/components/core/modals/modal-core.tsx
  web/components/cycles/delete-modal.tsx
  web/components/cycles/form.tsx
  web/components/cycles/modal.tsx
  web/components/estimates/create-update-estimate-modal.tsx
  web/components/estimates/delete-estimate-modal.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/components/inbox/modals/create-edit-modal/issue-title.tsx
  web/components/inbox/modals/create-edit-modal/modal.tsx
  web/components/inbox/modals/decline-issue-modal.tsx
  web/components/inbox/modals/delete-issue-modal.tsx
  web/components/issues/attachment/delete-attachment-modal.tsx
  web/components/issues/confirm-issue-discard.tsx
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/labels/delete-label-modal.tsx
  web/components/modules/delete-module-modal.tsx
  web/components/modules/form.tsx
  web/components/modules/modal.tsx
  web/components/pages/modals/create-page-modal.tsx
  web/components/pages/modals/delete-page-modal.tsx
  web/components/pages/modals/page-form.tsx
  web/components/states/delete-state-modal.tsx
  web/components/views/delete-view-modal.tsx
  web/components/views/form.tsx
  web/components/views/modal.tsx
  web/components/web-hooks/create-webhook-modal.tsx
  web/components/web-hooks/delete-webhook-modal.tsx
  web/components/web-hooks/form/form.tsx
  web/components/web-hooks/generated-hook-details.tsx
  web/components/workspace/views/delete-view-modal.tsx
  web/components/workspace/views/form.tsx
  web/components/workspace/views/modal.tsx
  web/pages/[workspaceSlug]/settings/webhooks/[webhookId].tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4375 [WEB-1098] chore: dropdowns enhancement
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/dropdowns/custom-select.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4334 [WEB-1142] chore: optimistically add issue to cycle/modules
  web/components/issues/issue-detail/cycle-select.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/peek-overview/root.tsx
  web/hooks/use-issues-actions.tsx
  web/services/issue/issue.service.ts
  web/services/module.service.ts
  web/store/issue/cycle/issue.store.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/issue.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/root.store.ts
Labels: 🌐frontend, 🌟improvement

#4377 [WEB-1117] chore: add tool tip for Snooze under Notification Panel.
  web/components/notifications/notification-card.tsx
Labels: 🌐frontend, 🎨UI / UX

#4379 [WEB-1176] chore: filter dropdown indicator and code refactor
  web/components/cycles/archived-cycles/header.tsx
  web/components/cycles/cycle-mobile-header.tsx
  web/components/cycles/cycles-view-header.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/projects.tsx
  web/components/issues/archived-issues-header.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/archived-modules/header.tsx
  web/components/modules/module-mobile-header.tsx
  web/components/modules/module-view-header.tsx
  web/components/pages/header/root.tsx
  web/components/profile/profile-issues-filter.tsx
  web/components/profile/profile-issues-mobile-header.tsx
  web/components/project/projects-mobile-header.tsx
  web/components/views/view-list-item-action.tsx
  web/helpers/filter.helper.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4384 [WEB-1086] chore: update toast messages for consistency.
  web/components/api-token/delete-token-modal.tsx
  web/components/api-token/modal/create-token-modal.tsx
  web/components/cycles/transfer-issues-modal.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/instance/ai-form.tsx
  web/components/instance/email-form.tsx
  web/components/instance/general-form.tsx
  web/components/instance/github-config-form.tsx
  web/components/instance/google-config-form.tsx
  web/components/instance/image-config-form.tsx
  web/components/issues/issue-detail/issue-activity/root.tsx
  web/components/issues/issue-detail/label/create-label.tsx
  web/components/issues/issue-detail/label/root.tsx
  web/components/issues/issue-detail/parent-select.tsx
  web/components/issues/issue-detail/reactions/issue-comment.tsx
  web/components/issues/issue-detail/reactions/issue.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/modules/sidebar.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/components/pages/editor/header/options-dropdown.tsx
  web/components/profile/preferences/email-notification-form.tsx
  web/components/project/member-list-item.tsx
  web/components/project/project-settings-member-defaults.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/workspace/settings/invitations-list-item.tsx
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/pages/god-mode/authorization.tsx
Labels: 🌐frontend, 🎨UI / UX

#4387 [WEB-1113] fix: set focus on editor conditionally after image upload
  packages/editor/core/src/ui/plugins/upload-image.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#4385 [WEB - 1213] fix: module webhook
  apiserver/plane/app/views/module/base.py
  apiserver/plane/bgtasks/webhook_task.py
Labels: ⚙️backend, 🎣webhooks

#4389 [WEB-1237] fix: displaying issues when applied created by filter
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/utils/user_timezone_converter.py
Labels: 🐛bug, ⚙️backend

#4393 [WEB-1242] fix: draft archive issues listing
  apiserver/plane/app/views/issue/archive.py
  apiserver/plane/app/views/issue/draft.py
Labels: 🐛bug, ⚙️backend

#4390 [WEB-1140] chore: Gantt pragmatic dnd
  packages/types/src/module/module_filters.d.ts
  web/components/cycles/cycles-view.tsx
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/gantt-chart/sidebar/cycles/block.tsx
  web/components/gantt-chart/sidebar/cycles/sidebar.tsx
  web/components/gantt-chart/sidebar/gantt-dnd-HOC.tsx
  web/components/gantt-chart/sidebar/index.ts
  web/components/gantt-chart/sidebar/issues/block.tsx
  web/components/gantt-chart/sidebar/issues/sidebar.tsx
  web/components/gantt-chart/sidebar/modules/block.tsx
  web/components/gantt-chart/sidebar/modules/sidebar.tsx
  web/components/gantt-chart/sidebar/project-views.tsx
  web/components/gantt-chart/sidebar/root.tsx
  web/components/gantt-chart/sidebar/utils.ts
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/utils.ts
  web/components/issues/issue-layouts/utils.tsx
  web/components/modules/dropdowns/order-by.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/constants/module.ts
  web/helpers/cycle.helper.ts
  web/helpers/module.helper.ts
  web/package.json
  web/store/cycle.store.ts
  web/styles/globals.css
  yarn.lock
Labels: 🌐frontend

#4362 [WEB-] chore: trigger command k from input fields and editors
  web/components/command-palette/command-palette.tsx
Labels: 🌐frontend, 🌟improvement

#4402 [WEB-1215] chore: display `favorite module` filter in applied filter section.
  web/components/modules/applied-filters/root.tsx
  web/components/modules/archived-modules/root.tsx
  web/components/modules/module-view-header.tsx
  web/components/modules/modules-list-view.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/store/module_filter.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#4399 [WEB-1182] style: fix inbox state filter title.
  web/components/inbox/inbox-filter/applied-filters/state.tsx
Labels: 🌐frontend, 🎨UI / UX

#4400 [WEB-1217] style: fix inconsistency in height of project type and lead dropdown in create project modal.
  web/components/project/create-project-form.tsx
Labels: 🌐frontend, 🎨UI / UX

#4401 [WEB-1236] chore: add `Create page` button to public/ private page empty state.
  web/components/pages/pages-list-main-content.tsx
  web/constants/empty-state.ts
Labels: 🌐frontend, 🎨UI / UX

#4391 [WEB-1040] chore: spreadsheet indentation improvement
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4397 dev: upgrade `lucide-react` version to the latest one
  packages/editor/core/package.json
  packages/editor/document-editor/package.json
  packages/editor/extensions/package.json
  packages/editor/rich-text-editor/package.json
  space/package.json
  web/package.json
  yarn.lock
Labels: 🌐frontend

#4404 [WEB-1040] chore: list layout sub issue nesting implementation
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/index.ts
  web/components/issues/issue-layouts/properties/index.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4405 [WEB-1208] fix: todo list item word break
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/read-only/extensions.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#4388 [WEB-1211] fix: inbox issue description revalidate
  web/components/inbox/content/root.tsx
Labels: 🐛bug, 🌐frontend

#4383 feat: Self Host Data Backup
  .gitignore
  deploy/selfhost/README.md
  deploy/selfhost/install.sh
Labels: 🏠self-hosted

#4406 [WEB-1040] fix: list layout indentation fix
  web/components/issues/issue-layouts/list/block.tsx
Labels: 🐛bug, 🌐frontend

#4410 [WEB-1139] chore: Calendar pragmatic dnd
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-block-root.tsx
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/utils.ts
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/hooks/use-draggable-portal.ts
Labels: 🌐frontend

#4409 [WEB-1256] fix: accept image as a valid comment
  space/helpers/string.helper.ts
  web/helpers/string.helper.ts
Labels: 🐛bug, 🌐frontend, ✍️editor

#4407 [WEB-1248] chore: applied filters update view button alignment improvement
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4413 [WEB-1134] fix: module link mutation issue
  web/components/modules/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#4416 fix: spreadsheet layout sticky column
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🐛bug, 🌐frontend

#4427 [WEB-1251] chore: view list enhancement
  web/components/headers/project-views.tsx
  web/components/views/index.ts
  web/components/views/view-list-header.tsx
  web/components/views/view-list-item-action.tsx
  web/components/views/views-list.tsx
  web/store/project-view.store.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4426 [WEB-1273] chore: notification action item enhancement
  web/components/notifications/notification-card.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4425 [WEB-1250] chore: module list enhancement
  web/components/gantt-chart/chart/header.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/headers/modules-list.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item-action.tsx
  web/components/modules/module-list-item.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4424 [WEB-1252] chore: project card enhancement
  web/components/project/card.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4423 [WEB-1274] chore: issue spreadsheet enhancement
  web/components/dropdowns/module/index.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/cycle-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/module-column.tsx
  web/components/issues/issue-layouts/spreadsheet/index.ts
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4422 [WEB-1265] chore: project publish modal improvement
  web/components/project/publish-project/modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4431 fix: selfhosting fixes for custom branch and platform
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install.sh
  deploy/selfhost/variables.env
Labels: 🏠self-hosted

#4415 [WEB-1261] fix: list and spreadsheet sub issues mutation issue
  web/components/issues/issue-detail/parent-select.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🐛bug, 🌐frontend

#4430 [WEB-1131] fix: button click propagation stopped
  packages/editor/extensions/src/extensions/slash-commands.tsx
Labels: ✍️editor

#4429 [WEB-1118] fix: table selections using drag handle fixed
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/ui/extensions/table/table/table.ts
  packages/editor/core/src/ui/props.tsx
  packages/editor/extensions/src/extensions/drag-drop.tsx
Labels: ✍️editor

#4435 [WEB-1254] chore: list layout indentation enhancement and cycle list page ui improvement
  web/components/cycles/board/cycles-board-card.tsx
  web/components/cycles/list/cycle-list-item-action.tsx
  web/components/cycles/list/cycles-list-item.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/save-filter-view.tsx
  web/components/pages/list/block-item-action.tsx
Labels: 🌐frontend, 🧹chore

#4437 [WEB-1285] fix: issue layout application error
  web/components/issues/issue-layouts/list/block.tsx
Labels: 🐛bug, 🌐frontend

#4417 [WEB-1271] fix: show only joined projects in the filters list
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
Labels: 🐛bug, 🌐frontend

#4449 [WEB - 1302]dev: nginx headers and auth error codes.
  admin/helpers/authentication.helper.tsx
  nginx/nginx.conf.dev
  nginx/nginx.conf.template
  yarn.lock
Labels: 🔐authentication, devops

#4450 [WEB-1305] fix: issue link title updation
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/app/serializers/issue.py
Labels: 🐛bug, ⚙️backend

#4452 fix: auth fixes and improvement
  apiserver/plane/authentication/adapter/error.py
  apiserver/plane/authentication/views/common.py
  packages/constants/src/auth.ts
  space/components/accounts/auth-forms/unique-code.tsx
  space/helpers/authentication.helper.tsx
  web/components/account/auth-forms/auth-root.tsx
  web/helpers/authentication.helper.tsx
  web/pages/profile/change-password.tsx
  web/services/user.service.ts
Labels: 🐛bug, 🌟enhancement, 🌐frontend, ⚙️backend, 🧹chore

#4455 [WEB-1311] fix: Issue link copy shortcut macOS
  web/components/command-palette/command-palette.tsx
  web/components/command-palette/shortcuts-modal/commands-list.tsx
  web/hooks/use-platform-os.tsx
Labels: 🐛bug, 🌐frontend

#4459 [WEB-1319] fix: handled multiple children rendering in the space layout
  space/app/error.tsx
  space/app/layout.tsx
  space/app/not-found.tsx
  space/components/instance/instance-failure-view.tsx
  space/store/user.store.ts
Labels: 🌟enhancement, 🌐frontend

#4457 [WEB-1308] chore: project analytics ui improvement
  web/components/analytics/scope-and-demand/demand.tsx
  web/components/analytics/scope-and-demand/scope-and-demand.tsx
  web/components/analytics/scope-and-demand/scope.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4462 [WEB-1324] chore: change password page improvement
  admin/components/instance/setup-form.tsx
  space/components/accounts/auth-forms/password.tsx
  web/components/account/auth-forms/password.tsx
  web/pages/accounts/reset-password.tsx
  web/pages/accounts/set-password.tsx
  web/pages/profile/change-password.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4460 [WEB - 1315] fix: user sign up and sign in on a deactivated account
  apiserver/plane/app/views/user/base.py
  apiserver/plane/authentication/views/app/check.py
  apiserver/plane/authentication/views/app/email.py
  apiserver/plane/authentication/views/app/magic.py
  apiserver/plane/authentication/views/space/magic.py
  apiserver/plane/license/api/serializers/instance.py
  apiserver/plane/license/api/views/admin.py
  apiserver/plane/license/api/views/instance.py
Labels: ⚙️backend, 🔐authentication

#4470 [WEB-1328] chore: magic sign-in redirection
  apiserver/plane/authentication/provider/credentials/magic_code.py
  apiserver/plane/authentication/views/app/magic.py
Labels: 🐛bug, ⚙️backend

#4476 [WEB-1319] chore: sign out after deactivating account
  web/components/onboarding/switch-delete-account-modal.tsx
Labels: 🐛bug, 🌐frontend

#4466 [WEB-1238] chore: asset updated
  web/public/empty-state/search/issues-dark.webp
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4472 [WEB-1306] chore: custom theme input placeholder improvement
  web/components/core/theme/custom-theme-selector.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4469 [WEB-1260] fix: my activity user image overflow
  web/components/profile/overview/activity.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4468 [WEB-1327] chore: encode email before passing it as a query param
  packages/constants/src/auth.ts
  space/components/accounts/auth-forms/password.tsx
  space/helpers/authentication.helper.tsx
  web/components/account/auth-forms/password.tsx
  web/helpers/authentication.helper.tsx
Labels: 🐛bug, 🌐frontend

#4465 [WEB-1326] style: update space and admin app colors
  admin/app/globals.css
  space/app/layout.tsx
  space/components/instance/not-ready-view.tsx
  space/helpers/common.helper.ts
  space/styles/globals.css
  web/components/instance/not-ready-view.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/helpers/common.helper.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4473 [WEB-1319] fix: handled issue filters mutation and updated the useParams with useSearchParams
  space/app/[workspace_slug]/[project_id]/layout.tsx
  space/app/[workspace_slug]/[project_id]/page.tsx
  space/components/issues/board-views/block-priority.tsx
  space/components/issues/board-views/block-state.tsx
  space/components/issues/board-views/kanban/block.tsx
  space/components/issues/board-views/kanban/header.tsx
  space/components/issues/board-views/list/block.tsx
  space/components/issues/board-views/list/header.tsx
  space/components/issues/filters/applied-filters/filters-list.tsx
  space/components/issues/filters/applied-filters/label.tsx
  space/components/issues/filters/applied-filters/priority.tsx
  space/components/issues/filters/applied-filters/root.tsx
  space/components/issues/filters/applied-filters/state.tsx
  space/components/issues/filters/helpers/dropdown.tsx
  space/components/issues/filters/helpers/filter-header.tsx
  space/components/issues/filters/helpers/filter-option.tsx
  space/components/issues/filters/labels.tsx
  space/components/issues/filters/priority.tsx
  space/components/issues/filters/root.tsx
  space/components/issues/filters/selection.tsx
  space/components/issues/filters/state.tsx
  space/components/issues/navbar/controls.tsx
  space/components/issues/navbar/index.tsx
  space/components/issues/navbar/issue-board-view.tsx
  space/components/issues/peek-overview/issue-properties.tsx
  space/components/issues/peek-overview/layout.tsx
  space/components/views/project-details.tsx
  space/constants/data.ts
  space/constants/issue.ts
  space/lib/wrappers/auth-wrapper.tsx
  space/package.json
  space/services/api.service.ts
  space/store/issue-filters.store.ts
  space/store/issue.store.ts
  space/store/project.store.ts
  space/types/issue-filters.d.ts
  space/types/issue.d.ts
Labels: 🌟enhancement, 🌐frontend

#4475 [WEB-1319] fix: issue peek overview handled state and query parameters handlers
  space/components/issues/board-views/list/block.tsx
  space/components/issues/peek-overview/layout.tsx
  space/components/views/project-details.tsx
Labels: 🌟enhancement, 🌐frontend

#4474 [WEB-1329] fix: change password error messages, multiple requests
  web/pages/profile/change-password.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4477 [WEB - 1333]fix: session age for admin and user
  apiserver/plane/authentication/utils/login.py
  apiserver/plane/settings/common.py
  nginx/nginx.conf.dev
  nginx/nginx.conf.template
Labels: ⚙️backend, 🔐authentication

#4479 [WEB-1249] feat: Kanban multi dragndrop
  packages/tailwind-config-custom/tailwind.config.js
  packages/types/src/issues.d.ts
  web/components/core/render-if-visible-HOC.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/kanban/utils.ts
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/cycle-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/module-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/utils.tsx
  web/components/issues/issue-modal/modal.tsx
  web/store/issue/cycle/issue.store.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue_kanban_view.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/project-views/issue.store.ts
  web/store/issue/project/issue.store.ts
  web/styles/globals.css
Labels: 🌟enhancement, 🌐frontend

#4464 [WEB-1313] fix: email preferences form reset
  web/components/profile/preferences/email-notification-form.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4494 [WEB-1345] chore: auth and loader responsiveness
  web/components/common/logo-spinner.tsx
  web/pages/accounts/forgot-password.tsx
  web/pages/index.tsx
  web/pages/sign-in.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4492 [WEB-1319] chore: instance not ready pages improvement
  admin/public/instance/plane-instance-not-ready.webp
  apiserver/plane/authentication/views/app/magic.py
  space/components/instance/not-ready-view.tsx
  web/components/command-palette/actions/issue-actions/change-state.tsx
  web/components/instance/not-ready-view.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/public/instance/plane-instance-not-ready.webp
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4408 [WEB-1204] fix: Kanban and calendar drag and drop in mobile
  packages/ui/src/control-link/control-link.tsx
  packages/ui/src/dropdowns/context-menu/root.tsx
  packages/ui/src/hooks/use-platform-os.ts
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  yarn.lock
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4485 [WEB-1341] chore: unwanted loader
  web/components/page-views/workspace-dashboard.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4482 [WEB-1205] chore: hide bot accounts from the collabortors list
  web/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx
Labels: 🐛bug, 🌐frontend

#4484 [WEB-1210] chore: discard changes made after creating issue
  web/components/issues/issue-modal/modal.tsx
Labels: 🐛bug, 🌐frontend

#4493 [WEB-1258] chore: prevent route change on canceling confirm dialog
  web/hooks/use-reload-confirmation.tsx
Labels: 🐛bug, 🌐frontend

#4488 [WEB-1264] chore: nested issue highlighting improvement
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/store/issue/issue-details/root.store.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4480 [WEB-1336] fix: issue dates conflict in the calendar layout
  apiserver/plane/app/views/search.py
  packages/types/src/project/projects.d.ts
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
Labels: 🐛bug, 🌐frontend

#4486 [WEB-1310] chore: page title can be blank
  web/components/pages/editor/title.tsx
  web/components/pages/list/block.tsx
  web/helpers/page.helper.ts
  web/store/pages/project-page.store.ts
Labels: 🌐frontend, 🌟improvement

#4497 [WEB-1319] chore: handled redirection when user is not logged in
  apiserver/plane/authentication/provider/credentials/magic_code.py
  apiserver/plane/authentication/views/space/email.py
  apiserver/plane/authentication/views/space/github.py
  apiserver/plane/authentication/views/space/google.py
  apiserver/plane/authentication/views/space/magic.py
  apiserver/plane/authentication/views/space/password_management.py
  space/app/page.tsx
  space/components/account/auth-forms/auth-root.tsx
  space/components/account/auth-forms/password.tsx
  space/components/account/auth-forms/unique-code.tsx
  space/components/account/oauth/oauth-options.tsx
  space/components/issues/peek-overview/comment/comment-reactions.tsx
  space/components/issues/peek-overview/issue-emoji-reactions.tsx
  space/components/issues/peek-overview/issue-vote-reactions.tsx
Labels: 🌟enhancement, 🌐frontend, ⚙️backend

#4499 [WEB-1249] fix: New Minor UX changes to Kanban
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
Labels: 🌐frontend

#4500 fix: selfhost back to tar.gz
  deploy/selfhost/install.sh
Labels: 🏠self-hosted, devops

#4498 [WEB - 1351] chore: auth callback
  apiserver/plane/authentication/adapter/base.py
  apiserver/plane/authentication/adapter/credential.py
  apiserver/plane/authentication/adapter/oauth.py
  apiserver/plane/authentication/provider/credentials/email.py
  apiserver/plane/authentication/provider/credentials/magic_code.py
  apiserver/plane/authentication/provider/oauth/github.py
  apiserver/plane/authentication/provider/oauth/google.py
  apiserver/plane/authentication/utils/user_auth_workflow.py
  apiserver/plane/authentication/views/app/email.py
  apiserver/plane/authentication/views/app/github.py
  apiserver/plane/authentication/views/app/google.py
  apiserver/plane/authentication/views/app/magic.py
Labels: 🔐authentication

#4471 [WEB-1330] chore: show password toggle improvement
  admin/components/instance/setup-form.tsx
  web/components/onboarding/profile-setup.tsx
  web/pages/accounts/reset-password.tsx
  web/pages/accounts/set-password.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4489 dev: migrations
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/cycle.py
  apiserver/plane/app/serializers/module.py
  apiserver/plane/app/serializers/page.py
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/serializers/view.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/archive.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/authentication/views/common.py
  apiserver/plane/db/migrations/0065_auto_20240415_0937.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/estimate.py
  apiserver/plane/db/models/favorite.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/workspace.py
Labels: ⚙️backend, 🔄migrations

#4502 [WEB-1319] chore: resolved build errors on the comment reaction section and implemented sign out button
  space/components/account/user-logged-in.tsx
  space/components/issues/navbar/controls.tsx
  space/components/issues/navbar/user-avatar.tsx
  space/components/issues/peek-overview/comment/comment-reactions.tsx
  space/store/user.store.ts
Labels: 🌟enhancement, 🌐frontend

#4501 [WEB-1357] chore: user favorite sequence
  apiserver/plane/db/models/favorite.py
Labels: ⚙️backend, 🌟improvement

#4507 [WEB-1319] chore: after signout instead of redirecting to login page we are navigating to the same page where he logged out
  apiserver/plane/authentication/views/space/signout.py
  space/components/issues/navbar/user-avatar.tsx
Labels: 🌟enhancement, 🌐frontend, ⚙️backend

#4506 [WEB - 1370] dev: remove session save and add callback for providers
  apiserver/plane/authentication/adapter/credential.py
  apiserver/plane/authentication/adapter/oauth.py
  apiserver/plane/authentication/provider/credentials/email.py
  apiserver/plane/authentication/provider/credentials/magic_code.py
  apiserver/plane/settings/common.py
Labels: 🔐authentication

#4505 [WEB-1366] fix: show untitle for blank page titles
  web/store/pages/page.store.ts
Labels: 🐛bug, 🌐frontend

#4513 [WEB-1366] fix: page title not appearing on the list
  web/store/pages/page.store.ts
Labels: 🐛bug, 🌐frontend

#4515 [WEB-1361] fix: comments access specifier mutation issue.
  web/components/issues/issue-detail/issue-activity/comments/comment-block.tsx
  web/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
Labels: 🐛bug, 🌐frontend

#4509 [WEB-1249] chore: New Kanban column design changes
  packages/tailwind-config-custom/tailwind.config.js
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
Labels: 🌐frontend

#4519 [WEB-1319] chore: auth fixes and enhancement
  web/components/onboarding/invite-members.tsx
  web/pages/profile/change-password.tsx
Labels: 🌟enhancement, 🌐frontend, 🌟improvement, 🧹chore

#4520 [WEB-1319] chore: handled the auto reload issue in auth-wrapper and instance wrapper
  web/lib/wrappers/authentication-wrapper.tsx
  web/lib/wrappers/instance-wrapper.tsx
Labels: 🌟enhancement, 🌐frontend

#4518 [WEB-1319] fix: handled magic sign_in and sign_up error codes in authentication
  apiserver/plane/authentication/adapter/error.py
  apiserver/plane/authentication/provider/credentials/magic_code.py
  space/components/account/auth-forms/auth-root.tsx
  space/helpers/authentication.helper.tsx
  web/components/account/auth-forms/auth-root.tsx
  web/helpers/authentication.helper.tsx
Labels: 🌟enhancement, 🌐frontend, ⚙️backend

#4517 [WEB - 1378] dev: add pg port to configuration
  apiserver/.env.example
  apiserver/plane/settings/common.py
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: ⚙️backend, ⚙️config changes

#4514 [WEB - 1375] chore: delete workspace invitation on user deactivation
  apiserver/plane/app/views/user/base.py
Labels: ⚙️backend, 🔐authentication

#4521 [WEB - 1381] fix: magic code 500 error on wrong code or expired code
  apiserver/plane/authentication/provider/credentials/magic_code.py
Labels: 🐛bug, ⚙️backend

#4523 [WEB-1319] chore: reset password error handling
  web/helpers/authentication.helper.tsx
  web/pages/accounts/reset-password.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4524 [WEB-1261] Add back removed code changes to fix sub Issue mutation
  web/components/issues/issue-layouts/list/block.tsx
Labels: 🐛bug, 🌐frontend

#4527 [WEB-1319] fix: onboarded steps validation in web app
  web/lib/wrappers/authentication-wrapper.tsx
Labels: 🌟enhancement, 🌐frontend

#4529 [WEB-1385] chore: auth screen and space app improvement
  admin/components/instance/setup-form.tsx
  admin/components/login/sign-in-form.tsx
  space/components/account/auth-forms/password.tsx
  space/components/issues/peek-overview/side-peek-view.tsx
  web/components/account/auth-forms/password.tsx
  web/components/account/password-strength-meter.tsx
  web/pages/accounts/reset-password.tsx
  web/pages/accounts/set-password.tsx
  web/pages/profile/change-password.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4534 [WEB - 1388] dev: rate limiting for email check and other apis
  apiserver/plane/authentication/adapter/error.py
  apiserver/plane/authentication/adapter/exception.py
  apiserver/plane/authentication/rate_limit.py
  apiserver/plane/authentication/views/app/check.py
  apiserver/plane/authentication/views/app/password_management.py
  apiserver/plane/authentication/views/space/check.py
  apiserver/plane/authentication/views/space/password_management.py
Labels: ⚙️backend, 🔐authentication

#4531 [WEB - 1387]dev: custom csrf failure view
  apiserver/plane/authentication/views/common.py
  apiserver/plane/settings/common.py
  apiserver/templates/csrf_failure.html
Labels: ⚙️backend, 🔐authentication

#4536 [WEB-1138] feat: List lssue Layout Drag and Drop
  packages/ui/src/drag-handle.tsx
  packages/ui/src/index.ts
  web/components/issues/issue-layouts/group-drag-overlay.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/list-group.tsx
  web/components/issues/issue-layouts/utils.tsx
  web/components/labels/label-block/label-item-block.tsx
  web/constants/issue.ts
  web/hooks/use-group-dragndrop.ts
  web/store/issue/archived/issue.store.ts
  web/store/issue/issue_kanban_view.store.ts
Labels: 🌐frontend

#4539 [WEB-1385] style: oauth button enhancement
  space/components/issues/filters/applied-filters/filters-list.tsx
  space/components/issues/peek-overview/header.tsx
  space/components/issues/peek-overview/issue-reaction.tsx
  space/components/issues/peek-overview/issue-vote-reactions.tsx
  web/components/account/oauth/github-button.tsx
  web/components/account/oauth/google-button.tsx
  web/components/issues/title-input.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
  web/pages/create-workspace.tsx
  web/pages/invitations/index.tsx
Labels: 🌟enhancement, 🌐frontend, 🌟improvement, 🧹chore

#4540 [WEB-1063] style: fix activity/ comment overflow issue.
  web/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
  web/components/issues/issue-detail/issue-activity/comments/comment-block.tsx
Labels: 🌐frontend, 🎨UI / UX

#4516 [WEB-1177] fix: sub-issues count mutation.
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/store/issue/issue-details/sub_issues.store.ts
Labels: 🐛bug, 🌐frontend

#4543 [WEB-1138] chore: fix list view visual alignments
  packages/ui/src/drag-handle.tsx
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/quick-add-issue-form.tsx
Labels: 🌐frontend

#4542 [WEB-1394] fix: unassigned issues count in analytics page
  web/components/analytics/scope-and-demand/scope-and-demand.tsx
  web/components/analytics/scope-and-demand/scope.tsx
Labels: 🌐frontend

#4545 [WEB-1400] fix: enable toast in admin app.
  admin/app/layout.tsx
Labels: 🐛bug

#4544 [WEB-1396] chore: remove/ disable all actionable items from deploy url in case url is embedded using Iframe.
  space/components/issues/navbar/controls.tsx
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/components/issues/peek-overview/comment/comment-reactions.tsx
  space/components/issues/peek-overview/header.tsx
  space/components/issues/peek-overview/issue-activity.tsx
  space/components/issues/peek-overview/issue-reaction.tsx
  space/components/issues/peek-overview/issue-vote-reactions.tsx
  space/hooks/use-clipboard-write-permission.tsx
  space/hooks/use-is-in-iframe.tsx
Labels: 🐛bug, 🚀space

#4420 [WEB-1262] refactor: custom hook for common dropdown logic
  web/components/dropdowns/cycle/index.tsx
  web/components/dropdowns/date-range.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/index.tsx
  web/components/dropdowns/module/index.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/select/label.tsx
  web/hooks/use-dropdown.ts
Labels: 🌐frontend, 🌟improvement

#4550 [WEB-1382] fix: infinite loop for sub issues
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/root.tsx
Labels: 🐛bug, 🌐frontend

#4548 [WEB-1386] chore: fix `update view` button to right even if no filters are applied.
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
Labels: 🌐frontend, 🎨UI / UX

#4546 [WEB-1401] chore: toast refactor in space app.
  space/app/layout.tsx
  space/components/issues/peek-overview/comment/add-comment.tsx
  space/components/issues/peek-overview/header.tsx
  space/components/issues/peek-overview/issue-properties.tsx
  space/components/ui/toast-alert.tsx
  space/contexts/toast.context.tsx
  space/helpers/common.helper.ts
  space/hooks/use-toast.tsx
  space/lib/toast-provider.tsx
  space/store/issue-detail.store.ts
  space/types/issue.d.ts
Labels: 🌐frontend, 🛠️refactor

#4541 [WEB-1393] chore: change color of quick add button
  packages/tailwind-config-custom/tailwind.config.js
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/list/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/spreadsheet/quick-add-issue-form.tsx
  web/styles/globals.css
Labels: 🌐frontend

#4490 WEB-1344 chore: Add storybook
  .eslintrc-staged.js
  .gitignore
  .husky/pre-commit
  packages/tailwind-config-custom/tailwind.config.js
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/package.json
  packages/ui/src/avatar/avatar.stories.tsx
  packages/ui/styles/globals.css
  packages/ui/tailwind.config.js
  yarn.lock
Labels: 🌐frontend, 🧹chore

#4552 [WEB-1404] chore: auth ui / ux fixes
  turbo.json
  web/components/account/auth-forms/auth-header.tsx
  web/components/account/auth-forms/auth-root.tsx
  web/helpers/authentication.helper.tsx
  web/helpers/common.helper.ts
  web/lib/wrappers/authentication-wrapper.tsx
  web/next.config.js
  web/pages/accounts/forgot-password.tsx
  web/pages/index.tsx
  web/pages/sign-up.tsx
Labels: 🌐frontend, 🎨UI / UX

#4554 [WEB-1406] fix: upgrade cmdk version to 1.0 to fix a critical issue
  web/package.json
  yarn.lock
Labels: 🐛bug, 🌐frontend

#4556 [WEB-1404] chore: space app logo redirection updated
  space/components/instance/not-ready-view.tsx
  space/components/views/auth.tsx
  space/lib/instance-provider.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4557 [WEB-1380] chore: fix sidebar expanding issue on sign out.
  apiserver/plane/authentication/views/app/signout.py
  docker-compose-local.yml
  web/store/root.store.ts
Labels: 🌐frontend, 🎨UI / UX

#4561 [WEB-1240] chore: toast messages updates
  web/components/issues/delete-issue-modal.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/sub-issues/root.tsx
Labels: 🌐frontend, 🎨UI / UX
