Repository makeplane/plane, pull requests merged in 2024-03, with the labels that each got.

#3854 [WEB-615] fix: multiple issue comment
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3853 [WEB-619] fix: workspace all issue quick action
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/helper.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3851 [WEB-616] fix: inbox issue navigation issue title and description event propagation
  web/components/inbox/inbox-issue-actions.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3871 fix: crash while updating link text on the last node
  packages/editor/document-editor/src/ui/components/links/link-edit-view.tsx
Labels: ✍️editor

#3847 [CHANG-6] Added Workflow for comparing version between Master & Head before Release
  .github/workflows/check-version.yml
Labels: 🚀CI/CD, 🔄workflows, devops, github_actions

#3835 [WEB-579] style: scrollbar implementation
  web/components/analytics/custom-analytics/main-content.tsx
  web/components/analytics/custom-analytics/sidebar/projects-list.tsx
  web/components/analytics/custom-analytics/sidebar/sidebar.tsx
  web/components/core/image-picker-popover.tsx
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/emoji-icon-picker/index.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/parent-issues-list-modal.tsx
  web/components/profile/sidebar.tsx
  web/layouts/settings-layout/profile/layout.tsx
  web/layouts/settings-layout/profile/preferences/layout.tsx
  web/layouts/settings-layout/profile/sidebar.tsx
  web/layouts/settings-layout/project/layout.tsx
  web/layouts/settings-layout/workspace/layout.tsx
  web/pages/[workspaceSlug]/profile/[userId]/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/settings/api-tokens.tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
  web/pages/profile/activity.tsx
  web/pages/profile/index.tsx
  web/pages/profile/preferences/email.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#3852 [WEB-510] fix: changed model field for issue links
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/db/migrations/0061_alter_issuelink_url.py
  apiserver/plane/db/models/issue.py
Labels: ⚙️backend, 🌟improvement, 🔄migrations

#3855 [WEB-617] fix: link behaviour fixed on formatting
  packages/editor/core/src/ui/extensions/custom-link/helpers/clickHandler.ts
  packages/editor/core/src/ui/extensions/custom-link/helpers/pasteHandler.ts
  packages/editor/core/src/ui/extensions/custom-link/index.ts
Labels: 🐛bug, ✍️editor

#3859 [WEB-621] chore: 404 page not found
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/error_404.py
  apiserver/plane/urls.py
Labels: 🌟enhancement, ⚙️backend

#3860 [WEB-662] chore: posthog debugging based on env variable
  turbo.json
  web/lib/posthog-provider.tsx
Labels: 🌐frontend, 🌟improvement

#3864 [WEB-581] chore: project states setting page improvement
  web/pages/[workspaceSlug]/projects/[projectId]/settings/states.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3862 [WEB-618] fix: remove member button alignment in the workspace invite modal
  web/components/workspace/send-workspace-invitation-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#3865 [WEB-623] fix: module quick action dropdown overflow fix
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3866 [WEB-627] fix: kanban card state name overflow
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3867 [WEB-566] feat: Added text to empty color picker boxes and other fixes
  packages/editor/core/src/styles/table.css
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
Labels: ✍️editor

#3887 [WEB-654] fix: enums export in the types package
  packages/types/src/dashboard.ts
  packages/types/src/dashboard/enums.ts
  packages/types/src/dashboard/index.ts
  packages/types/src/index.d.ts
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/dropdowns/duration-filter.tsx
  web/components/dashboard/widgets/issue-panels/tabs-list.tsx
  web/components/dashboard/widgets/issues-by-priority.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/constants/dashboard.ts
  web/helpers/dashboard.helper.ts
Labels: 🐛bug, 🌐frontend

#3868 [WEB-393] feat: new emoji picker using `emoji-picker-react`
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/views/workspace.py
  apiserver/plane/db/migrations/0061_alter_issuelink_url.py
  apiserver/plane/db/migrations/0061_project_logo_props.py
  apiserver/plane/db/models/project.py
  packages/types/src/projects.d.ts
  packages/types/src/users.d.ts
  packages/ui/package.json
  packages/ui/src/emoji/emoji-icon-picker.tsx
  packages/ui/src/emoji/icons-list.tsx
  packages/ui/src/emoji/icons.ts
  packages/ui/src/emoji/index.ts
  packages/ui/src/form-fields/input.tsx
  packages/ui/src/index.ts
  space/components/common/index.ts
  space/components/common/project-logo.tsx
  space/components/issues/navbar/index.tsx
  space/types/project.ts
  web/components/analytics/custom-analytics/sidebar/projects-list.tsx
  web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
  web/components/dashboard/widgets/recent-projects.tsx
  web/components/dropdowns/project.tsx
  web/components/emoji-icon-picker/emojis.json
  web/components/emoji-icon-picker/helpers.ts
  web/components/emoji-icon-picker/icons.json
  web/components/emoji-icon-picker/index.tsx
  web/components/emoji-icon-picker/types.d.ts
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issue-details.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/issues/issue-layouts/filters/applied-filters/project.tsx
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
  web/components/issues/issue-layouts/utils.tsx
  web/components/profile/sidebar.tsx
  web/components/project/card.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/form.tsx
  web/components/project/index.ts
  web/components/project/project-logo.tsx
  web/components/project/sidebar-list-item.tsx
  web/helpers/emoji.helper.tsx
  web/helpers/project.helper.ts
  web/layouts/settings-layout/project/sidebar.tsx
  web/pages/_app.tsx
  web/styles/emoji.css
  yarn.lock
Labels: ✨feature, 🌐frontend, ⚙️backend, 🔄migrations

#3888 [WEB-655] chore: peek overview dropdowns keyboard navigation improvement
  web/components/issues/peek-overview/view.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3885 [WED-635] chore: enable module and cycle display properties in module and cycle issues
  web/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🌐frontend, 🧹chore

#3858 [WEB-630] refactor: empty state
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-list.tsx
  web/components/empty-state/empty-state.tsx
  web/components/estimates/estimates-list.tsx
  web/components/exporter/guide.tsx
  web/components/integration/guide.tsx
  web/components/issues/issue-layouts/empty-states/archived-issues.tsx
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/draft-issues.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/empty-states/project-issues.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/labels/project-setting-label-list.tsx
  web/components/modules/modules-list-view.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/list-view.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/components/profile/profile-issues.tsx
  web/components/project/card-list.tsx
  web/components/views/views-list.tsx
  web/constants/empty-state.ts
  web/pages/[workspaceSlug]/analytics.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/api-tokens.tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
  web/public/empty-state/module-issues/gantt_chart-dark-resp.webp
  web/public/empty-state/module-issues/gantt_chart-dark.webp
  web/public/empty-state/module-issues/gantt_chart-light-resp.webp
  web/public/empty-state/module-issues/gantt_chart-light.webp
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#3892 [WEB-660] fix: issue details page breadcrumb loading state
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-issue-details.tsx
  web/components/project/integration-card.tsx
Labels: 🌐frontend, 🌟improvement

#3872 [WEB-438] fix: ai insertion behaviour
  packages/editor/core/package.json
  packages/editor/core/src/helpers/insert-content-at-cursor-position.ts
  packages/editor/core/src/hooks/use-editor.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/issues/issue-modal/form.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/store/page.store.ts
  yarn.lock
Labels: ✍️editor

#3707 [WEB - 471] dev: caching users and workspace apis
  apiserver/plane/app/views/config.py
  apiserver/plane/app/views/estimate.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/app/views/project.py
  apiserver/plane/app/views/state.py
  apiserver/plane/app/views/user.py
  apiserver/plane/app/views/workspace.py
  apiserver/plane/license/api/views/instance.py
  apiserver/plane/settings/local.py
  apiserver/plane/utils/cache.py
Labels: ⚙️backend, ⚡performance

#3630 chore: integrations and importers
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/integration/__init__.py
  apiserver/plane/app/serializers/integration/base.py
  apiserver/plane/app/serializers/integration/github.py
  apiserver/plane/app/serializers/integration/slack.py
  apiserver/plane/app/urls/__init__.py
  apiserver/plane/app/urls/external.py
  apiserver/plane/app/urls/importer.py
  apiserver/plane/app/urls/integration.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/urls/module.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/external.py
  apiserver/plane/app/views/importer.py
  apiserver/plane/app/views/integration/__init__.py
  apiserver/plane/app/views/integration/base.py
  apiserver/plane/app/views/integration/github.py
  apiserver/plane/app/views/integration/slack.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/db/models/social_connection.py
  apiserver/plane/utils/importers/__init__.py
  apiserver/plane/utils/importers/jira.py
  apiserver/plane/utils/integrations/__init__.py
  apiserver/plane/utils/integrations/github.py
  apiserver/plane/utils/integrations/slack.py
Labels: ⚙️backend

#3894 [WEB-663] fix: project members settings flickering
  web/components/project/member-select.tsx
  web/components/project/project-settings-member-defaults.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3899 [WEB-612] fix: rendering Issue in kanban swimlanes view for unassigned cycle or Modules
  web/store/issue/helpers/issue-helper.store.ts
Labels: 🐛bug, 🌐frontend

#3898 [WEB-667] fix: unable to deselect project lead in create project modal
  web/components/project/create-project-modal.tsx
Labels: 🐛bug, 🌐frontend

#3869 [WEB-469] chore: selected filter sorting added in filter dropdown
  web/components/issues/issue-layouts/empty-states/archived-issues.tsx
  web/components/issues/issue-layouts/empty-states/draft-issues.tsx
  web/components/issues/issue-layouts/empty-states/project-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/cycle.tsx
  web/components/issues/issue-layouts/filters/header/filters/labels.tsx
  web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
  web/components/issues/issue-layouts/filters/header/filters/module.tsx
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
  web/components/issues/issue-layouts/filters/header/filters/state-group.tsx
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
Labels: 🌟enhancement, 🌐frontend, 🌟improvement, 🧹chore

#3901 [WEB-671] chore: remove unused images in the app
  web/public/empty-state/Project_full_screen.svg
  web/public/empty-state/analytics.svg
  web/public/empty-state/dashboard.svg
  web/public/empty-state/estimate.svg
  web/public/empty-state/integration.svg
  web/public/empty-state/issue-archive.svg
  web/public/empty-state/my-issues.svg
  web/public/empty-state/page.svg
  web/public/onboarding/sign-in.webp
  web/public/theme-mode/custom-mode.svg
  web/public/theme-mode/custom-theme-banner.svg
  web/public/theme-mode/dark-high-contrast.svg
  web/public/theme-mode/dark-mode.svg
  web/public/theme-mode/light-high-contrast.svg
  web/public/theme-mode/light-mode.svg
  web/public/web-view-spinner.png
Labels: 🧹chore

#3905 [WEB-665] fix Padding in the project dropdown.
  web/components/project/sidebar-list.tsx
Labels: 🌐frontend, 🎨UI / UX

#3906 [WEB-666] chore: rename `View profile` to `My activity`.
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX

#3909 [WEB-440] feat: create project feature selection modal.
  web/components/project/create-project-form.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/index.ts
  web/components/project/project-feature-update.tsx
  web/components/project/settings/features-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
Labels: ✨feature

#3915 [WEB-687] fix: project page empty state and empty state error handling
  web/components/empty-state/empty-state.tsx
  web/constants/empty-state.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#3913 [WEB-670] fix: date filter modal selection
  web/components/core/filters/date-filter-modal.tsx
Labels: 🐛bug, 🌐frontend

#3912 [WEB-686] chore: app sidebar label update
  web/components/workspace/sidebar-menu.tsx
  web/constants/dashboard.ts
Labels: 🌐frontend, 🧹chore

#3910 [WEB-682] feat: cycles list filtering and searching
  packages/types/src/cycle/cycle.d.ts
  packages/types/src/cycle/cycle_filters.d.ts
  packages/types/src/cycle/index.ts
  packages/types/src/index.d.ts
  packages/ui/src/icons/cycle/circle-dot-full-icon.tsx
  web/components/cycles/active-cycle/index.ts
  web/components/cycles/active-cycle/root.tsx
  web/components/cycles/active-cycle/stats.tsx
  web/components/cycles/active-cycle/upcoming-cycles-list-item.tsx
  web/components/cycles/active-cycle/upcoming-cycles-list.tsx
  web/components/cycles/applied-filters/date.tsx
  web/components/cycles/applied-filters/index.ts
  web/components/cycles/applied-filters/root.tsx
  web/components/cycles/applied-filters/status.tsx
  web/components/cycles/board/cycles-board-card.tsx
  web/components/cycles/board/cycles-board-map.tsx
  web/components/cycles/board/index.ts
  web/components/cycles/board/root.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-list.tsx
  web/components/cycles/cycles-view-header.tsx
  web/components/cycles/cycles-view.tsx
  web/components/cycles/delete-modal.tsx
  web/components/cycles/dropdowns/filters/end-date.tsx
  web/components/cycles/dropdowns/filters/index.ts
  web/components/cycles/dropdowns/filters/root.tsx
  web/components/cycles/dropdowns/filters/start-date.tsx
  web/components/cycles/dropdowns/filters/status.tsx
  web/components/cycles/dropdowns/index.ts
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/cycles/index.ts
  web/components/cycles/list/cycles-list-item.tsx
  web/components/cycles/list/cycles-list-map.tsx
  web/components/cycles/list/index.ts
  web/components/cycles/list/root.tsx
  web/components/cycles/modal.tsx
  web/components/cycles/quick-actions.tsx
  web/components/gantt-chart/chart/header.tsx
  web/components/headers/cycles.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/constants/cycle.ts
  web/constants/empty-state.ts
  web/helpers/cycle.helper.ts
  web/helpers/filter.helper.ts
  web/hooks/store/index.ts
  web/hooks/store/use-cycle-filter.ts
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/public/empty-state/cycle/all-filters.svg
  web/public/empty-state/cycle/name-filter.svg
  web/store/cycle.store.ts
  web/store/cycle_filter.store.ts
  web/store/root.store.ts
Labels: ✨feature, 🌐frontend

#3914 [WEB-683] fix: update issue modal parent select
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#3916 [WEB-685] fix: module empty state issue creation
  web/components/issues/issue-layouts/empty-states/module.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3918 [WEB-688] chore: applied filters improvement
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3919 [WEB-689] chore: issue quick action dropdown improvement
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3932 [WEB-697] fix: cycle & module sidebar progress-stats scroll
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
Labels: 🐛bug, 🌐frontend

#3923 [WEB - 691]: Remove caching on DEBUG and server restart
  apiserver/bin/takeoff
  apiserver/bin/takeoff.local
  apiserver/plane/db/management/commands/clear_cache.py
  apiserver/plane/utils/cache.py
Labels: 🐛bug, ⚙️backend

#3911 [WEB-402] chore: project issues count
  apiserver/plane/app/serializers/module.py
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/project/base.py
  packages/types/src/cycle/cycle.d.ts
  packages/types/src/modules.d.ts
  packages/types/src/projects.d.ts
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#3925 [WEB-641] fix: update extensions in read only instance of the editor
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/read-only/extensions.tsx
  packages/editor/document-editor/src/ui/readonly/index.tsx
Labels: regression

#3927 chore: remove deprecated envs
  apiserver/.env.example
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: 🧹chore

#3928 [WEB-673] chore: added view less button to the collaborators widget
  web/components/dashboard/widgets/recent-collaborators/default-list.tsx
  web/components/dashboard/widgets/recent-collaborators/root.tsx
  web/components/dashboard/widgets/recent-collaborators/search-list.tsx
  web/components/project/send-project-invitation-modal.tsx
Labels: 🌐frontend, 🌟improvement

#3934 [WEB-690] chore: error state for the issues widgets
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/error-states/index.ts
  web/components/dashboard/widgets/error-states/issues.tsx
  web/components/dashboard/widgets/index.ts
  web/store/dashboard.store.ts
Labels: 🌐frontend, 🌟improvement

#3933 [WEB-585] chore: list layout scrollbar improvement
  web/components/issues/issue-layouts/list/default.tsx
  web/styles/globals.css
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#3936 [WEB-719] chore: active issue total count
  apiserver/plane/app/views/cycle/base.py
Labels: 🐛bug, ⚙️backend

#3939 [WEB-725] fix: page empty state
  web/components/pages/pages-list/list-view.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3940 [WEB-723] fix: gantt sidebar blocks cursor
  web/components/cycles/gantt-chart/blocks.tsx
  web/components/gantt-chart/chart/views/month.tsx
  web/components/modules/gantt-chart/blocks.tsx
Labels: 🌐frontend, 🌟improvement

#3941 [WEB-724] fix: emoji picker unnecessary scroll
  packages/ui/src/emoji/emoji-icon-picker.tsx
Labels: 🐛bug, 🌐frontend

#3942 [WEB-722] fix: label mutation in peek-overview & issue detail
  web/components/issues/issue-detail/label/label-list.tsx
Labels: 🐛bug, 🌐frontend

#3944 [WEB-717] fix: delete issue modal UI fixes.
  web/components/issues/issue-detail/root.tsx
  web/components/issues/peek-overview/view.tsx
Labels: 🌐frontend, 🎨UI / UX

#3945 [WEB-720] chore: reaction tooltip added
  web/components/issues/issue-detail/reactions/issue-comment.tsx
  web/components/issues/issue-detail/reactions/issue.tsx
  web/helpers/issue.helper.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3946 [WEB-721] chore: removed module tooltip from peek-overview & issue detail
  web/components/dropdowns/module/index.tsx
  web/components/issues/issue-detail/module-select.tsx
Labels: 🌟improvement, 🧹chore

#3970 [WEB-752] chore: ai modal disclaimer added
  web/components/core/modals/gpt-assistant-popover.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3971 [WEB-753] chore: project active filter
  apiserver/plane/app/views/project.py
Labels: 🐛bug, ⚙️backend

#3957 [WEB-741] chore: swapped dates and status properties in the cycle list item
  web/components/cycles/list/cycles-list-item.tsx
Labels: 🌐frontend, 🌟improvement

#3972 [WEB-754] fix: cycle date check endpoint
  web/components/cycles/modal.tsx
Labels: 🐛bug, 🌐frontend

#3950 [WEB-715] chore: closing custom dropdown on button click
  packages/ui/src/dropdowns/custom-menu.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3951 [WEB-747] chore: issue reaction response
  packages/types/src/issues/issue_reaction.d.ts
  web/components/issues/issue-detail/reactions/issue.tsx
  web/store/issue/issue-details/reaction.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#3955 [WEB-504] chore: command k and issue relation modal empty state
  web/components/command-palette/command-modal.tsx
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/core/modals/index.ts
  web/components/core/modals/issue-search-modal-empty-state.tsx
  web/components/empty-state/empty-state.tsx
  web/components/inbox/modals/select-duplicate.tsx
  web/components/issues/parent-issues-list-modal.tsx
  web/components/notifications/notification-popover.tsx
  web/constants/empty-state.ts
  web/public/empty-state/search/archive-dark.webp
  web/public/empty-state/search/archive-light.webp
  web/public/empty-state/search/comments-dark.webp
  web/public/empty-state/search/comments-light.webp
  web/public/empty-state/search/issue-dark.webp
  web/public/empty-state/search/issues-light.webp
  web/public/empty-state/search/notification-dark.webp
  web/public/empty-state/search/notification-light.webp
  web/public/empty-state/search/search-dark.webp
  web/public/empty-state/search/search-light.webp
  web/public/empty-state/search/snooze-dark.webp
  web/public/empty-state/search/snooze-light.webp
Labels: 🌟enhancement, 🌐frontend, 🌟improvement, 🧹chore

#3958 [WEB-698] chore: profile activity page scrollbar added
  web/pages/[workspaceSlug]/profile/[userId]/activity.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3959 [WEB-545] chore: completed cycle empty state validation
  web/components/issues/issue-layouts/empty-states/cycle.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3961 [WEB-748] fix: cycle layout not getting initialized
  web/components/cycles/board/root.tsx
  web/components/cycles/cycles-view-header.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🐛bug, 🌐frontend

#3976 [WEB-757] chore: app sidebar improvement
  web/components/workspace/sidebar-menu.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3966 [WEB-746] chore: draft issue modal improvement
  web/components/issues/issue-modal/draft-issue-layout.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3952 [WEB-738] chore: conditionally render projects in the dropdown
  web/components/command-palette/command-palette.tsx
  web/components/cycles/form.tsx
  web/components/dropdowns/project.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/modules/form.tsx
  web/components/project/create-project-modal.tsx
  web/helpers/project.helper.ts
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#3960 [WEB-700] chore: sidebar hamburger refactor
  web/components/cycles/cycle-mobile-header.tsx
  web/components/cycles/cycles-list-mobile-header.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issue-details.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/headers/user-profile.tsx
  web/components/headers/workspace-active-cycles.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/headers/workspace-dashboard.tsx
  web/components/headers/workspace-settings.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/moduels-list-mobile-header.tsx
  web/components/modules/module-mobile-header.tsx
  web/layouts/app-layout/layout.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#3969 [WEB-759] style: added calendar layout responsiveness
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
  web/components/issues/issue-layouts/calendar/header.tsx
  web/components/issues/issue-layouts/calendar/index.ts
  web/components/issues/issue-layouts/calendar/issue-block-root.tsx
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3974 [WEB-755] fix: Clearing nodes to default node i.e. paragraph before converting it to other type
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/extensions/src/extensions/slash-commands.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/index.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/link-selector.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/node-selector.tsx
Labels: ✍️editor

#2538 dev: enable api logging
  .gitignore
  apiserver/.env.example
  apiserver/Dockerfile.api
  apiserver/plane/api/views/base.py
  apiserver/plane/app/views/base.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/dashboard/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/event_tracking_task.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/bgtasks/magic_link_code_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/webhook_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
  apiserver/plane/db/models/user.py
  apiserver/plane/settings/common.py
  apiserver/plane/settings/local.py
  apiserver/plane/settings/production.py
  apiserver/plane/settings/test.py
  apiserver/plane/space/views/base.py
  apiserver/plane/utils/exception_logger.py
  apiserver/plane/utils/logging.py
  apiserver/requirements/base.txt
  deploy/selfhost/docker-compose.yml
Labels: ⚙️backend, 🐳docker

#3983 [WEB-766] fix: Project issues mobile header visibility
  web/components/issues/issues-mobile-header.tsx
Labels: 🐛bug, 🌐frontend

#3986 [WEB-761] fix: Time zone date misalignment
  packages/editor/document-editor/src/ui/components/editor-header.tsx
  packages/editor/document-editor/src/ui/components/info-popover.tsx
  web/components/core/filters/date-filter-modal.tsx
  web/components/core/sidebar/progress-chart.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/form.tsx
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/cycles/sidebar.tsx
  web/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/components/dropdowns/date.tsx
  web/components/exporter/single-export.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/gantt-chart/types/index.ts
  web/components/gantt-chart/views/month-view.ts
  web/components/inbox/inbox-issue-actions.tsx
  web/components/inbox/inbox-issue-status.tsx
  web/components/issues/issue-detail/inbox/sidebar.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/months-dropdown.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/modules/form.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/sidebar.tsx
  web/components/notifications/notification-card.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/constants/inbox.tsx
  web/contexts/user-notification-context.tsx
  web/helpers/date-time.helper.ts
  web/helpers/filter.helper.ts
  web/helpers/issue.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/store/cycle.store.ts
  web/store/project-page.store.ts
Labels: 🐛bug, 🌐frontend

#3989 [WEB - 779] fix: user caching when the user leaves/deletes the workspace
  apiserver/plane/app/views/workspace/base.py
  apiserver/plane/app/views/workspace/member.py
Labels: ⚙️backend

#3987 [WEB-675] fix: analytics dialog close on outside click
  web/components/analytics/project-modal/modal.tsx
Labels: 🌐frontend, 🌟improvement

#3988 fix: test email command to use new SSL settings
  apiserver/plane/db/management/commands/test_email.py
Labels: 🌟improvement, ⚙️config changes

#3992 [WEB-782] fix: Date timezone changes error
  packages/editor/document-editor/src/ui/components/editor-header.tsx
  packages/editor/document-editor/src/ui/components/info-popover.tsx
  packages/editor/document-editor/src/utils/date-utils.ts
  packages/types/src/pages.d.ts
  web/components/api-token/modal/form.tsx
  web/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/components/gantt-chart/blocks/block.tsx
  web/components/notifications/notification-card.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/components/pages/pages-list/list-item.tsx
  web/helpers/cycle.helper.ts
  web/helpers/date-time.helper.ts
  web/helpers/module.helper.ts
  web/helpers/project.helper.ts
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/store/page.store.ts
  web/store/project-page.store.ts
Labels: 🌐frontend, 📡api

#3990 [WEB-780]feat: project cycle module archive
  apiserver/plane/api/urls/cycle.py
  apiserver/plane/api/urls/module.py
  apiserver/plane/api/urls/project.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/project.py
  apiserver/plane/api/views/state.py
  apiserver/plane/app/serializers/cycle.py
  apiserver/plane/app/serializers/module.py
  apiserver/plane/app/urls/cycle.py
  apiserver/plane/app/urls/module.py
  apiserver/plane/app/urls/project.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/cycle/issue.py
  apiserver/plane/app/views/dashboard/base.py
  apiserver/plane/app/views/exporter/base.py
  apiserver/plane/app/views/issue/activity.py
  apiserver/plane/app/views/issue/comment.py
  apiserver/plane/app/views/issue/link.py
  apiserver/plane/app/views/issue/reaction.py
  apiserver/plane/app/views/issue/relation.py
  apiserver/plane/app/views/issue/subscriber.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/search.py
  apiserver/plane/app/views/state/base.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/app/views/workspace/label.py
  apiserver/plane/app/views/workspace/state.py
  apiserver/plane/app/views/workspace/user.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/db/migrations/0062_cycle_archived_at_module_archived_at_and_more.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/project.py
Labels: ✨feature, ⚙️backend

#3994 [WEB-768] fix: project, module, cycle filter store infinite loop.
  web/store/cycle_filter.store.ts
  web/store/module_filter.store.ts
  web/store/project/project_filter.store.ts
Labels: 🐛bug, 🌐frontend

#3995 [WEB-767] fix: Labels overflow in peek, detail view
  web/components/issues/issue-detail/label/create-label.tsx
  web/components/issues/issue-detail/label/select/label-select.tsx
Labels: 🐛bug, 🌐frontend

#3997 [WEB-413] chore: project active cycle UI revamp
  web/components/core/sidebar/progress-chart.tsx
  web/components/cycles/active-cycle/cycle-stats.tsx
  web/components/cycles/active-cycle/header.tsx
  web/components/cycles/active-cycle/index.ts
  web/components/cycles/active-cycle/productivity.tsx
  web/components/cycles/active-cycle/progress.tsx
  web/components/cycles/active-cycle/root.tsx
  web/components/cycles/active-cycle/upcoming-cycles-list.tsx
Labels: 🌟enhancement

#4003 [WEB-784] chore: create workspace fields as required indication
  web/components/workspace/create-workspace-form.tsx
Labels: 🌐frontend, 🌟improvement

#4006 [WEB-786] fix: create label inline overflow
  web/components/labels/project-setting-label-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
Labels: 🐛bug, 🌐frontend

#4008 [WEB-792] dev: removed double issue count
  apiserver/plane/api/views/module.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/workspace/module.py
Labels: 🐛bug, ⚙️backend

#4002 [WEB-781] fix: peek overview sub issue edit
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/root.tsx
Labels: 🐛bug, 🌐frontend

#4000 [WEB-762] chore: cycle, module modal improvement and cycle, module
  web/components/cycles/form.tsx
  web/components/cycles/sidebar.tsx
  web/components/modules/form.tsx
  web/components/modules/sidebar.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4009 [WEB-774] fix: issue assignee display persistence for departed users
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/cycle/issue.py
  apiserver/plane/app/views/dashboard/base.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/app/views/issue/archive.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/issue/sub_issue.py
  apiserver/plane/app/views/module/issue.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/app/views/workspace/user.py
Labels: 🐛bug, ⚙️backend

#4010 [WEB-787] fix: profile cover upload
  web/components/core/image-picker-popover.tsx
  web/pages/profile/index.tsx
Labels: 🐛bug, 🌐frontend

#4018 [WEB-692] fix: project modal cover image popover z-index fix
  web/components/core/image-picker-popover.tsx
Labels: 🌐frontend, 🌟improvement

#4024 [WEB-750] fix: default state rendering fix in issue create/update modal project switching
  web/components/dropdowns/state.tsx
  web/store/state.store.ts
Labels: 🐛bug

#4025 [WEB-795] fix: prevent custom menu button from opening cycle/ module details page when closed.
  packages/ui/src/dropdowns/custom-menu.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#4026 [WEB-797] fix: project list dropdown placement
  web/components/dropdowns/module/index.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#4029 [WEB-794] fix: issue card assignee empty state tooltip
  web/components/dropdowns/member/index.tsx
  web/components/dropdowns/member/types.d.ts
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🐛bug, 🌐frontend

#4030 [WEB-802] fix: handling empty issue properties, enabling creation in edit modal, and draft management enhancement
  web/components/issues/issue-modal/draft-issue-layout.tsx
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug

#4031 [WEB-804] fix: module and cycle list page quick action
  web/components/cycles/list/cycles-list-item.tsx
  web/components/modules/module-list-item.tsx
Labels: 🌐frontend, 🌟improvement

#4037 [WEB-815] fix: project order by dropdown
  web/components/project/dropdowns/order-by.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4033 [WEB-806] fix: initial empty state closure in issue Create/Edit modal
  web/components/issues/issue-modal/draft-issue-layout.tsx
Labels: 🐛bug

#4032 [WEB-800] fix: issue peekview, and detail page create label colour selector autoplacement
  web/components/issues/issue-detail/label/create-label.tsx
Labels: 🌐frontend, 🌟improvement

#4034 [WEB-805] fix: quick actions handling for project draft issues
  web/components/issues/issue-layouts/kanban/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/index.ts
Labels: 🐛bug

#4039 [WED-731] fix: resetting changes made on "create more" toggle activation in issue create-edit modal
  web/components/issues/issue-modal/modal.tsx
Labels: 🐛bug, 🌐frontend

#4040 [WEB-814] fix: module list filter and order by
  web/components/modules/modules-list-view.tsx
  web/helpers/module.helper.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4041 [WEB-813] chore: cycle list page alignment
  web/components/cycles/list/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4042 [WEB-818] fix: sub-issue and attachment delete not working in the peek overview
  web/components/issues/attachment/attachment-detail.tsx
  web/components/issues/peek-overview/header.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/root.tsx
  web/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend

#4043 [WEB-811] chore: filter dropdown custom date select improvement
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/issue-layouts/filters/header/filters/start-date.tsx
  web/components/issues/issue-layouts/filters/header/filters/target-date.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/module-mobile-header.tsx
  web/components/profile/profile-issues-filter.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4044 [WEB-793] style: hide cycle and module dropdown placeholder from list and kanban view.
  web/components/dropdowns/cycle/index.tsx
  web/components/dropdowns/module/index.tsx
  web/components/issues/issue-modal/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#4045 [WEB-816] fix: project total issue count mutation.
  web/store/issue/project/issue.store.ts
Labels: 🐛bug, 🌐frontend

#4038 [WEB-789] fix: disabling issue property validation in issue edit modal
  web/components/issues/issue-modal/draft-issue-layout.tsx
Labels: 🐛bug

#4048 [WEB-802] fix: handling undefined condition for issue title while saving the issue as draft
  web/components/issues/issue-modal/draft-issue-layout.tsx
Labels: 🐛bug, 🌐frontend

#4049 [WEB-821] fix: profile activity load more button visibility
  web/pages/profile/activity.tsx
Labels: 🐛bug, 🌐frontend

#4052 [WEB-820] fix: state count in cycle and module
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
Labels: 🐛bug, ⚙️backend

#4053 [WEB-812] chore: project active cycle stats empty state
  web/components/cycles/active-cycle/cycle-stats.tsx
  web/components/cycles/active-cycle/productivity.tsx
  web/components/cycles/active-cycle/progress.tsx
  web/components/cycles/active-cycle/upcoming-cycles-list.tsx
  web/components/empty-state/empty-state.tsx
  web/constants/empty-state.ts
  web/public/empty-state/active-cycle/assignee-dark.webp
  web/public/empty-state/active-cycle/assignee-light.webp
  web/public/empty-state/active-cycle/chart-dark.webp
  web/public/empty-state/active-cycle/chart-light.webp
  web/public/empty-state/active-cycle/cycle-dark.webp
  web/public/empty-state/active-cycle/cycle-light.webp
  web/public/empty-state/active-cycle/label-dark.webp
  web/public/empty-state/active-cycle/label-light.webp
  web/public/empty-state/active-cycle/priority-dark.webp
  web/public/empty-state/active-cycle/priority-light.webp
  web/public/empty-state/active-cycle/progress-dark.webp
  web/public/empty-state/active-cycle/progress-light.webp
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4054 [WEB-823] fix: quick add flicker and dropdown placement in calendar layout
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-block-root.tsx
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/list/list-view-types.d.ts
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX, 🌟improvement

#4058 [WEB-827] fix: kanban layout quick add
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4061 [WEB-828] fix: issue reaction
  apiserver/plane/app/serializers/issue.py
Labels: 🐛bug, ⚙️backend, 🧹chore

#4062 [WEB-828] fix: peek overview delete modal
  web/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4064 [WEB-832] chore: removed project from workspace estimate
  apiserver/plane/app/views/workspace/estimate.py
Labels: 🐛bug, ⚙️backend

#4065 fix: optimise cycles endpoint for sql
  apiserver/plane/app/views/cycle/base.py
Labels: ⚙️backend, ⚡performance

#4063 [WEB-831] fix: sentry issue and code refactor
  web/components/command-palette/command-palette.tsx
  web/components/cycles/modal.tsx
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/modules/modal.tsx
  web/components/project/create-project-form.tsx
  web/components/project/form.tsx
  web/components/project/project-logo.tsx
  web/components/views/modal.tsx
Labels: 🌐frontend, 🧹chore

#4066 fix: cycle issue subquery filter when adding multiple assignees
  apiserver/plane/app/views/cycle/base.py
Labels: 🐛bug, ⚙️backend

#4067 fix: active cycle stats empty state
  web/components/cycles/active-cycle/cycle-stats.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4068 [WEB-831] chore: image picker popover improvement
  web/components/core/image-picker-popover.tsx
Labels: 🌐frontend, 🧹chore

#4070 chore: workspace estimate project filter
  apiserver/plane/app/views/workspace/estimate.py
Labels: 🐛bug, ⚙️backend

#4071 fix: module endpoint validations
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/workspace/estimate.py
Labels: 🐛bug, ⚙️backend

#4072 dev: fix api security error
  apiserver/plane/api/serializers/issue.py
Labels: ⚙️backend, 🛡️security

#4073 [WEB-849] fix: issue detail identifier and workspace settings
  web/components/issues/issue-update-status.tsx
  web/layouts/settings-layout/workspace/sidebar.tsx
Labels: 🌐frontend, 🧹chore

#4085 [WEB-851] chore: update all instances of `Dashboard` with `Home`.
  web/components/headers/workspace-dashboard.tsx
  web/components/onboarding/onboarding-sidebar.tsx
  web/pages/[workspaceSlug]/index.tsx
  web/pages/invitations/index.tsx
  web/pages/workspace-invitations/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#4084 [WEB-852] chore: remove `Estimate Demand` data from the anaylytics.
  web/components/analytics/scope-and-demand/demand.tsx
Labels: 🌐frontend, 🎨UI / UX

#4083 [WEB-833] chore: remove `create a new issue` option from command k modal if no projects are there.
  web/components/command-palette/command-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#4082 [WEB-839] chore: limit project identifier to 5 letters in project settings page.
  web/components/project/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#4081 [WEB-840] chore: remove `make a copy` option from draft issue quick action menu.
  web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
Labels: 🌐frontend, 🎨UI / UX

#4080 [WEB-843] fix: `chat with us` option not working in command k modal.
  web/components/command-palette/actions/help-actions.tsx
Labels: 🌐frontend, 🎨UI / UX

#4079 [WEB-836] fix: color picker overlapping with themes dropdown issue.
  packages/ui/src/dropdowns/custom-select.tsx
Labels: 🌐frontend, 🎨UI / UX

#4078 [WEB-834] fix: close shortcut modal on outside click.
  web/components/command-palette/shortcuts-modal/modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#4076 [WEB-838] fix: cycle dropdown fetch
  web/components/issues/issue-modal/form.tsx
  web/hooks/use-project-issue-properties.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore
