Repository makeplane/plane, pull requests merged in 2024-06, with the labels that each got.

#4681 fix: instance register script
  apiserver/plane/license/management/commands/register_instance.py
  packages/types/src/instance/base.d.ts
Labels: 🌐frontend, ⚙️backend

#4682 [WEB-1492] fix: resolved issue creation error in layouts while group_by and sub_group_by filters applied in quick add
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/project-views/issue.store.ts
  web/store/issue/project/issue.store.ts
Labels: 🐛bug, 🌐frontend

#4683 [WEB-1325] fix: inbox issue store update logic.
  web/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌐frontend

#4674 [WEB-1184] feat: issue bulk operations
  admin/components/admin-sidebar/help-section.tsx
  web/components/gantt-chart/blocks/block.tsx
  web/components/gantt-chart/blocks/blocks-list.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/gantt-chart/constants.ts
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/cycles/block.tsx
  web/components/gantt-chart/sidebar/issues/block.tsx
  web/components/gantt-chart/sidebar/issues/sidebar.tsx
  web/components/gantt-chart/sidebar/modules/block.tsx
  web/components/gantt-chart/sidebar/root.tsx
  web/components/issues/bulk-operations/index.ts
  web/components/issues/bulk-operations/root.tsx
  web/components/issues/bulk-operations/upgrade-banner.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/list-group.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/attachment-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/created-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/cycle-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/link-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/module-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/updated-on-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/workspace/help-section.tsx
  web/constants/common.ts
  web/constants/spreadsheet.ts
Labels: ✨feature, 🌐frontend

#4684 [WEB-1511] style: fix overlapping of response container in AI popover.
  web/components/core/modals/gpt-assistant-popover.tsx
Labels: 🌐frontend, 🎨UI / UX

#4686 [WEB-1498] style: fix comments reaction alignment.
  web/components/issues/issue-detail/reactions/reaction-selector.tsx
Labels: 🎨UI / UX

#4685 [WEB-1503] chore: add `autofocus` to name field in inline create/ update state component.
  web/components/states/create-update-state-inline.tsx
Labels: 🌟improvement

#4661 [WEB-1312] fix: trim file name before uploading
  apiserver/plane/db/models/asset.py
  packages/editor/core/src/ui/plugins/image/image-upload-handler.ts
Labels: 🌐frontend, ✍️editor

#4691 [WEB-1481] fix: multiple API calls in inbox issues on closed issues tab.
  web/components/inbox/root.tsx
  web/components/inbox/sidebar/root.tsx
  web/hooks/use-intersection-observer.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
  web/store/inbox/project-inbox.store.ts
Labels: 🌟improvement

#4697 [WEB-1521] chore: add configuration to enable/disable sign-ups.
  admin/app/authentication/page.tsx
  admin/components/admin-sidebar/help-section.tsx
Labels: 🌟improvement

#4700 [WEB-1523] regression: focus changing issue with the peek overview editor
  packages/editor/core/src/hooks/use-editor.tsx
Labels: ✍️editor

#4701 [WEB-1459] chore: save users all / favorite project list collapse state into local storage.
  web/components/project/sidebar-list.tsx
Labels: 🌟improvement

#4702 [WEB-1501] chore: update selected entity details on entities list change
  web/components/gantt-chart/chart/main-content.tsx
  web/components/issues/bulk-operations/root.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/hooks/use-multiple-select.ts
  web/store/multiple_select.store.ts
Labels: 🐛bug, 🌐frontend

#4707 fix: email validation
  apiserver/plane/authentication/adapter/base.py
  apiserver/plane/authentication/adapter/error.py
  apiserver/plane/authentication/adapter/oauth.py
Labels: ⚙️backend, 🔐authentication

#4699 [WEB - 1518] fix: cache invalidation on new members invite
  apiserver/plane/authentication/utils/workspace_project_join.py
  apiserver/plane/utils/cache.py
Labels: 🐛bug, ⚙️backend

#4713 [WEB - 1532] fix: instance models max length
  apiserver/plane/license/migrations/0003_alter_changelog_title_alter_changelog_version_and_more.py
  apiserver/plane/license/models/instance.py
Labels: ⚙️backend

#4714 [WEB-1533] chore: fix alignment issues in List and Spreadsheet view
  web/components/issues/issue-layouts/list/block-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
Labels: 🌐frontend

#4717 chore: deploy board fields changes
  apiserver/plane/space/views/issue.py
Labels: ⚙️backend, 🌟improvement

#4719 [WEB-1540] chore: handle undefined identifier error
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/store/project/project.store.ts
  yarn.lock
Labels: 🐛bug, 🌐frontend

#4716 [WEB-1516] refactor: publish project modal and types
  apiserver/plane/app/serializers/project.py
  apiserver/plane/app/views/project/base.py
  packages/types/src/index.d.ts
  packages/types/src/project/projects.d.ts
  packages/types/src/publish.d.ts
  space/app/[workspaceSlug]/[projectId]/page.ts
  space/services/publish.service.ts
  space/store/publish/publish.store.ts
  space/store/publish/publish_list.store.ts
  space/types/project.d.ts
  web/components/headers/project-issues.tsx
  web/components/issues/issue-detail/issue-activity/root.tsx
  web/components/project/publish-project/index.ts
  web/components/project/publish-project/index.tsx
  web/components/project/publish-project/modal.tsx
  web/components/project/publish-project/popover.tsx
  web/components/project/sidebar-list-item.tsx
  web/services/project/project-publish.service.ts
  web/store/project/project-publish.store.ts
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#4710 [WEB-1529] chore: workspace sidebar updates.
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🎨UI / UX

#4725 fix: temporary fix exiting lines with slashes
  packages/editor/extensions/src/extensions/slash-commands.tsx
Labels: ✍️editor

#4709 [WEB-1537] fix: inline code block size fixed for headers, etc
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/ui/extensions/code-inline/index.tsx
  packages/editor/core/src/ui/extensions/code/utils/replace-code-block-with-text.ts
  packages/editor/core/src/ui/extensions/custom-list-keymap/list-keymap.ts
Labels: ✍️editor

#4703 [WEB-1526] feat: add auto merge behaviour to task lists and fix infinite backspace case
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/ui/extensions/custom-list-keymap/list-helpers.ts
  packages/editor/core/src/ui/extensions/keymap.tsx
Labels: ✍️editor

#4721 [WEB-1201] dev: dropdowns
  packages/ui/src/dropdown/Readme.md
  packages/ui/src/dropdown/common/button.tsx
  packages/ui/src/dropdown/common/index.ts
  packages/ui/src/dropdown/common/input-search.tsx
  packages/ui/src/dropdown/common/loader.tsx
  packages/ui/src/dropdown/common/options.tsx
  packages/ui/src/dropdown/dropdown.d.ts
  packages/ui/src/dropdown/index.ts
  packages/ui/src/dropdown/multi-select.tsx
  packages/ui/src/dropdown/single-select.tsx
  packages/ui/src/hooks/use-dropdown-key-pressed.ts
  packages/ui/src/index.ts
Labels: 🌐frontend, 🧹chore

#4724 chore: added disabled prop to multiple select components
  web/components/core/multiple-select/entity-select-action.tsx
  web/components/core/multiple-select/group-select-action.tsx
  web/components/core/multiple-select/select-group.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/issues/bulk-operations/root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/hooks/use-multiple-select.ts
Labels: 🌐frontend, 🌟improvement

#4731 [WEB-1544] fix: don't add issue as a sub-issue if parent has been removed
  web/components/issues/sub-issues/root.tsx
Labels: 🐛bug, 🌐frontend

#4729 [WEB-1507] fix: member list item custom menu placement
  web/components/workspace/settings/members-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4718 [WEB-1535] chore: project logo picker improvement
  web/components/project/form.tsx
Labels: 🌐frontend, 🧹chore

#4727 [WEB-1409] fix: border flicker on issue title
  web/components/issues/title-input.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#4732 [WEB-1379] chore: profile activity empty state
  packages/types/src/users.d.ts
  web/components/profile/activity/profile-activity-list.tsx
  web/constants/empty-state.ts
  web/pages/profile/activity.tsx
  web/public/empty-state/profile/activity-dark.webp
  web/public/empty-state/profile/activity-light.webp
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4715 [WEB-1481] fix: inbox issue list update after changing issue status.
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/sidebar/root.tsx
  web/store/inbox/project-inbox.store.ts
Labels: 🐛bug

#4730 [WEB-412] chore: estimates analytics
  apiserver/plane/api/views/cycle.py
  apiserver/plane/app/serializers/module.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/archive.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/utils/analytics_plot.py
  packages/types/src/module/modules.d.ts
  web/components/analytics/custom-analytics/select/y-axis.tsx
  web/components/estimates/points/create.tsx
  web/components/estimates/points/update.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
Labels: 🌐frontend, ⚙️backend

#4733 [WEB-1538] chore: issue and properties filter dropdown improvement
  web/components/cycles/cycle-mobile-header.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/archived-issues-header.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/module-mobile-header.tsx
  web/components/profile/profile-issues-filter.tsx
  web/components/profile/profile-issues-mobile-header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4728 [WEB-1442] feat: Save all filters and properties for views
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/archived-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/draft-issue.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/save-filter-view.tsx
  web/components/issues/issue-layouts/utils.tsx
  web/components/views/form.tsx
Labels: 🌐frontend

#4762 [WEB-1561] chore: project publish url
  web/core/components/project/publish-project/modal.tsx
Labels: 🌐frontend, 🧹chore

#4764 [WEB-1559] dev: create separate folder for page service
  web/core/hooks/use-page-description.ts
  web/core/services/page/index.ts
  web/core/services/page/project-page.service.ts
  web/core/store/pages/page.store.ts
  web/core/store/pages/project-page.store.ts
Labels: 🌐frontend, 🛠️refactor

#4765 [WEB-1572] fix: inbox issues
  apiserver/plane/utils/paginator.py
Labels: 🐛bug, ⚙️backend

#4758 [WEB-1508] chore: module and cycle peek view improvement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/[moduleId]/page.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#4757 [WEB-1504] chore: profile picture modal improvement and mutation fix
  web/app/profile/page.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🧹chore

#4755 [WEB-1549] fix: dashboard empty state flicker
  web/core/components/page-views/workspace-dashboard.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4756 [WEB-1509] chore: spreadsheet layout assignee column improvement
  web/core/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#4753 [WEB-1554] chore: page loader improvement
  web/core/components/pages/loaders/page-content-loader.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4768 [WEB-1574] dev: page head hook
  web/core/hooks/use-page-title.tsx
Labels: 🌐frontend, 🧹chore

#4769 [WEB-1548] chore: Remove Drag Handles
  web/core/components/cycles/gantt-chart/blocks.tsx
  web/core/components/gantt-chart/sidebar/cycles/block.tsx
  web/core/components/gantt-chart/sidebar/cycles/sidebar.tsx
  web/core/components/gantt-chart/sidebar/gantt-dnd-HOC.tsx
  web/core/components/gantt-chart/sidebar/issues/block.tsx
  web/core/components/gantt-chart/sidebar/issues/sidebar.tsx
  web/core/components/gantt-chart/sidebar/modules/block.tsx
  web/core/components/gantt-chart/sidebar/modules/sidebar.tsx
  web/core/components/labels/label-block/label-item-block.tsx
  web/core/components/labels/label-block/label-name.tsx
  web/core/components/labels/project-setting-label-group.tsx
  web/core/components/labels/project-setting-label-item.tsx
  web/core/components/modules/gantt-chart/blocks.tsx
  web/core/components/project/sidebar-list-item.tsx
  web/core/components/project/sidebar-list.tsx
Labels: 🌐frontend

#4774 [WEB-1564] chore: handled next_path redirections in auth-wrapper and the form request pages
  web/core/components/account/auth-forms/auth-root.tsx
  web/core/components/account/auth-forms/password.tsx
  web/core/components/account/auth-forms/unique-code.tsx
  web/core/lib/wrappers/authentication-wrapper.tsx
Labels: 🌐frontend, 🌟improvement

#4773 [WEB-1574] chore: page head
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/use-page-title.tsx
  packages/ui/src/index.ts
  web/core/components/core/page-title.tsx
  web/core/hooks/use-page-title.tsx
Labels: 🌐frontend, 🧹chore

#4770 [WEB-1559] chore: make AI assistant endpoint workspace level
  apiserver/plane/app/urls/external.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/external/base.py
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/core/components/core/modals/gpt-assistant-popover.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/services/ai.service.ts
Labels: 🌐frontend, 🌟improvement

#4775 [WEB-1409] fix: issue title input flicker
  web/core/components/issues/title-input.tsx
Labels: 🌐frontend, 🧹chore

#4779 [WEB-1565] fix: total onboarding steps logic.
  web/app/onboarding/page.tsx
Labels: 🐛bug, 🌐frontend

#4778 [WEB-1578] chore: add max length validation for workspace slug in create workspace form.
  web/core/components/onboarding/create-workspace.tsx
  web/core/components/workspace/create-workspace-form.tsx
Labels: 🌐frontend, 🌟improvement

#4780 [WEB-1580] chore: drag handler and sidebar improvement
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
  web/app/profile/sidebar.tsx
  web/core/components/labels/label-block/label-item-block.tsx
  web/core/components/labels/label-block/label-name.tsx
  web/core/components/labels/project-setting-label-group.tsx
  web/core/components/labels/project-setting-label-item.tsx
  web/core/components/project/sidebar-list-item.tsx
  web/core/components/project/sidebar-list.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4767 [WEB - 1581] fix: magic code when smtp is not configured
  apiserver/plane/authentication/provider/credentials/magic_code.py
Labels: 🐛bug, ⚙️backend

#4784 [WEB-1562] chore: duplicated project collaborators
  apiserver/plane/app/views/dashboard/base.py
Labels: 🐛bug, ⚙️backend

#4786 [WEB-1598] style: spreadsheet layout loader
  web/core/components/ui/loader/layouts/spreadsheet-layout-loader.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#4781 [WEB-1597] fix: toast themes.
  web/app/provider.tsx
Labels: 🐛bug, 🌐frontend

#4783 [WEB - 1593] fix: pagination grouping when grouping by created_by
  apiserver/plane/utils/grouper.py
  apiserver/plane/utils/paginator.py
Labels: 🐛bug, ⚙️backend

#4741 [WEB - 1552]chore: attach pages to multiple projects
  apiserver/plane/app/serializers/page.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/search.py
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/bgtasks/page_transaction_task.py
  apiserver/plane/db/migrations/0068_remove_pagelabel_project_remove_pagelog_project_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/page.py
  apiserver/plane/utils/exception_logger.py
Labels: ⚙️backend, 🔄migrations

#4787 [WEB-1598] style: list layout load more
  web/core/components/issues/issue-layouts/list/list-group.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#4788 [WEB-1564] chore: add interceptor to handle 401 errors and redirect users to login page.
  web/core/services/api.service.ts
  web/core/services/user.service.ts
Labels: 🐛bug, 🌐frontend

#4789 [WEB-1571] [WEB-1566] fix: headless ui version
  packages/ui/package.json
  yarn.lock
Labels: 🌐frontend, 🧹chore

#4782 [WEB-1559] chore: add page prop to the quick actions dropdown
  web/core/components/pages/dropdowns/quick-actions.tsx
  web/core/components/pages/list/block-item-action.tsx
Labels: 🌐frontend, 🌟improvement

#4796 chore: create extended root store
  web/ce/store/root.store.ts
  web/core/lib/store-context.tsx
  web/core/store/cycle.store.ts
  web/core/store/cycle_filter.store.ts
  web/core/store/dashboard.store.ts
  web/core/store/estimates/estimate-point.ts
  web/core/store/estimates/estimate.ts
  web/core/store/estimates/project-estimate.store.ts
  web/core/store/event-tracker.store.ts
  web/core/store/global-view.store.ts
  web/core/store/inbox/inbox-issue.store.ts
  web/core/store/inbox/project-inbox.store.ts
  web/core/store/issue/issue_kanban_view.store.ts
  web/core/store/issue/root.store.ts
  web/core/store/label.store.ts
  web/core/store/member/index.ts
  web/core/store/member/project-member.store.ts
  web/core/store/member/workspace-member.store.ts
  web/core/store/module.store.ts
  web/core/store/module_filter.store.ts
  web/core/store/pages/page.store.ts
  web/core/store/pages/project-page.store.ts
  web/core/store/project-view.store.ts
  web/core/store/project/index.ts
  web/core/store/project/project.store.ts
  web/core/store/project/project_filter.store.ts
  web/core/store/root.store.ts
  web/core/store/state.store.ts
  web/core/store/theme.store.ts
  web/core/store/user/account.store.ts
  web/core/store/user/index.ts
  web/core/store/user/profile.store.ts
  web/core/store/user/user-membership.store.ts
  web/core/store/workspace/api-token.store.ts
  web/core/store/workspace/index.ts
  web/core/store/workspace/webhook.store.ts
Labels: 🌐frontend

#4799 chore: rename page store
  web/core/components/pages/dropdowns/quick-actions.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/info-popover.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/hooks/store/pages/use-page.ts
  web/core/hooks/use-page-description.ts
  web/core/store/pages/page.ts
  web/core/store/pages/project-page.store.ts
Labels: 🌐frontend, 🛠️refactor

#4791 [WEB-1599] chore: auth email input one password extenction improvement
  space/components/account/auth-forms/email.tsx
  space/components/account/auth-forms/password.tsx
  space/components/account/auth-forms/unique-code.tsx
  web/core/components/account/auth-forms/email.tsx
  web/core/components/account/auth-forms/password.tsx
  web/core/components/account/auth-forms/unique-code.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4802 [WEB-1580] chore: admin sidebar improvement
  admin/components/admin-sidebar/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4804 [WEB-1584] fix: issue mutation inconsistencies with pagination
  web/core/store/issue/helpers/base-issues-utils.ts
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🌐frontend

#4805 [WEB-1559] chore: update page search input props
  web/core/components/pages/header/root.tsx
  web/core/components/pages/list/search-input.tsx
Labels: 🌐frontend, 🌟improvement

#4692 feat: add GitLab OAuth client
  admin/app/authentication/components/gitlab-config.tsx
  admin/app/authentication/components/index.ts
  admin/app/authentication/gitlab/form.tsx
  admin/app/authentication/gitlab/page.tsx
  admin/app/authentication/page.tsx
  admin/components/auth-header.tsx
  admin/public/logos/gitlab-logo.svg
  apiserver/bin/docker-entrypoint-beat.sh
  apiserver/bin/docker-entrypoint-migrator.sh
  apiserver/plane/authentication/adapter/error.py
  apiserver/plane/authentication/adapter/oauth.py
  apiserver/plane/authentication/provider/oauth/gitlab.py
  apiserver/plane/authentication/urls.py
  apiserver/plane/authentication/views/__init__.py
  apiserver/plane/authentication/views/app/gitlab.py
  apiserver/plane/authentication/views/space/gitlab.py
  apiserver/plane/db/migrations/0067_alter_account_provider_and_more.py
  apiserver/plane/db/models/social_connection.py
  apiserver/plane/db/models/user.py
  apiserver/plane/license/api/views/instance.py
  apiserver/plane/license/management/commands/configure_instance.py
  packages/constants/src/auth.ts
  packages/types/src/current-user/accounts.d.ts
  packages/types/src/instance/auth.d.ts
  packages/types/src/instance/base.d.ts
  packages/types/src/users.d.ts
  packages/ui/src/icons/gitlab-icon.tsx
  packages/ui/src/icons/index.ts
  space/components/account/auth-forms/auth-root.tsx
  space/components/account/oauth/gitlab-button.tsx
  space/components/account/oauth/index.ts
  space/components/account/oauth/oauth-options.tsx
  space/helpers/authentication.helper.tsx
  space/public/logos/gitlab-logo.svg
  space/types/app.d.ts
  web/components/account/oauth/gitlab-button.tsx
  web/components/account/oauth/index.ts
  web/components/account/oauth/oauth-options.tsx
  web/helpers/authentication.helper.tsx
  web/public/logos/gitlab-logo.svg
Labels: ✨feature, 🔐oauth

#4822 [WEB-522] chore: ui fix and validation on estimate on active cycles estimate in project cycles
  web/core/components/cycles/active-cycle/productivity.tsx
Labels: 🌐frontend, 🌟improvement

#4819 [WEB-522] chore: handled numeric validation on estimate point update in categories
  web/core/components/estimates/points/create.tsx
  web/core/components/estimates/points/update.tsx
Labels: 🐛bug, 🌐frontend

#4815 [WEB-1601] fix: archive issues mutation.
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🌐frontend, 🧪api tests

#4794 chore: move modal core components to the UI package
  packages/ui/src/index.ts
  packages/ui/src/modals/alert-modal.tsx
  packages/ui/src/modals/constants.ts
  packages/ui/src/modals/index.ts
  packages/ui/src/modals/modal-core.tsx
  web/core/components/api-token/delete-token-modal.tsx
  web/core/components/api-token/modal/create-token-modal.tsx
  web/core/components/core/modals/index.ts
  web/core/components/cycles/delete-modal.tsx
  web/core/components/cycles/modal.tsx
  web/core/components/estimates/create/modal.tsx
  web/core/components/estimates/delete/modal.tsx
  web/core/components/inbox/modals/create-edit-modal/modal.tsx
  web/core/components/inbox/modals/decline-issue-modal.tsx
  web/core/components/inbox/modals/delete-issue-modal.tsx
  web/core/components/issues/attachment/delete-attachment-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-modal/modal.tsx
  web/core/components/labels/delete-label-modal.tsx
  web/core/components/modules/delete-module-modal.tsx
  web/core/components/modules/modal.tsx
  web/core/components/pages/modals/create-page-modal.tsx
  web/core/components/pages/modals/delete-page-modal.tsx
  web/core/components/project/publish-project/modal.tsx
  web/core/components/states/delete-state-modal.tsx
  web/core/components/views/delete-view-modal.tsx
  web/core/components/views/modal.tsx
  web/core/components/web-hooks/create-webhook-modal.tsx
  web/core/components/web-hooks/delete-webhook-modal.tsx
  web/core/components/workspace/views/delete-view-modal.tsx
  web/core/components/workspace/views/modal.tsx
Labels: 🌐frontend, 🛠️refactor

#4823 [WEB-1613] chore: material logo loader
  packages/ui/package.json
  packages/ui/src/emoji/icons-list.tsx
  web/core/components/common/logo.tsx
  web/package.json
  yarn.lock
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4818 [WEB - 1604]fix: pagination on many to many fields when grouping and sub grouping
  apiserver/plane/utils/paginator.py
Labels: 🐛bug, ⚙️backend

#4826 [WEB - 1629] fix: backend crash on app startup
  apiserver/plane/authentication/provider/oauth/gitlab.py
Labels: ⚙️backend

#4829 [WEB-1596] fix: empty groups for issue list and kanban
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
Labels: 🌐frontend

#4830 [WEB-1603] fix: load more issues when issues are deleted
  web/core/components/inbox/sidebar/root.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/core/store/issue/archived/issue.store.ts
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/draft/issue.store.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/module/issue.store.ts
  web/core/store/issue/profile/issue.store.ts
  web/core/store/issue/project-views/issue.store.ts
  web/core/store/issue/project/issue.store.ts
  web/core/store/issue/workspace/issue.store.ts
Labels: 🌐frontend

#4832 [WEB-1600] chore: issue detail ui enhancement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/[archivedIssueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/core/components/issues/issue-detail/index.ts
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4831 [WEB-1617] chore: created by implementation
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/peek-overview/properties.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4821 [WEB-1559] chore: updated pages response
  apiserver/plane/app/serializers/page.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/search/base.py
  apiserver/plane/app/views/search/issue.py
  packages/types/src/pages.d.ts
  packages/types/src/workspace.d.ts
  web/core/components/command-palette/helpers.tsx
  web/core/store/pages/page.ts
  web/core/store/pages/project-page.store.ts
Labels: 🌐frontend, 🌟improvement

#4843 [WEB-1592] fix: exception while switching groups in list view
  web/core/hooks/use-multiple-select.ts
Labels: 🐛bug, 🌐frontend

#4840 [WEB-1622] chore: profile setting layout improvement
  web/app/profile/activity/page.tsx
  web/app/profile/appearance/page.tsx
  web/app/profile/notifications/page.tsx
  web/app/profile/page.tsx
  web/app/profile/security/page.tsx
  web/core/components/profile/index.ts
  web/core/components/profile/notification/email-notification-form.tsx
  web/core/components/profile/profile-setting-content-header.tsx
  web/core/components/profile/profile-setting-content-wrapper.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4838 [WEB-1551] fix: theme mutation when custom theme is applied.
  web/core/lib/wrappers/store-wrapper.tsx
Labels: 🐛bug, 🌐frontend

#4835 [WEB-1630] chore: fix project doesn't exist empty state fluctuation on refresh.
  web/core/layouts/auth-layout/project-wrapper.tsx
Labels: 🌐frontend, 🌟improvement

#4841 [WEB-1397] chore: update project publish types
  packages/types/src/publish.d.ts
  space/app/[workspaceSlug]/[projectId]/page.ts
  space/services/publish.service.ts
  space/store/publish/publish.store.ts
  space/store/publish/publish_list.store.ts
  space/types/publish.d.ts
  web/core/components/project/publish-project/modal.tsx
  web/core/services/project/project-publish.service.ts
  web/core/store/project/project-publish.store.ts
Labels: 🌐frontend, 🌟improvement

#4842 [WEB-1594] fix: bulk issues selection checkbox
  web/core/components/core/multiple-select/entity-select-action.tsx
  web/core/components/issues/issue-layouts/list/default.tsx
  web/core/components/issues/issue-layouts/utils.tsx
Labels: 🐛bug

#4844 [WEB-1397] chore: add anchor key to page type
  packages/types/src/pages.d.ts
  web/core/store/pages/page.ts
Labels: 🌐frontend

#4849 [WEB-1646] fix: bug that incorrectly updates issue store for array properties during bulk ops
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🐛bug, 🌐frontend

#4850 [WEB-1632] fix: validating and showing proper alert estimate point has to be taken greater than 0 in create and update
  web/core/components/estimates/points/create.tsx
  web/core/components/estimates/points/update.tsx
Labels: 🌟improvement

#4576 [WEB - 1418] chore: events for auth & onboarding
  web/core/components/account/auth-forms/auth-root.tsx
  web/core/components/account/auth-forms/password.tsx
  web/core/components/account/auth-forms/unique-code.tsx
  web/core/components/onboarding/create-workspace.tsx
  web/core/components/onboarding/profile-setup.tsx
  web/core/constants/event-tracker.ts
Labels: 🌐frontend, 🧹chore

#4851 [WEB-1397] dev: create a global component for emoji/icon logo
  packages/ui/src/emoji/helpers.ts
  packages/ui/src/emoji/index.ts
  packages/ui/src/emoji/logo.tsx
Labels: 🌐frontend, 🌟improvement

#4853 [WEB-1640] fix: validating the error in estimate delete
  web/ce/components/estimates/index.ts
  web/ce/components/estimates/points/delete.tsx
  web/ce/components/estimates/points/index.ts
  web/core/components/estimates/points/delete.tsx
  web/core/components/estimates/points/index.ts
  web/core/components/estimates/points/preview.tsx
  web/ee/components/estimates/index.ts
  web/ee/components/estimates/points/delete.tsx
  web/ee/components/estimates/points/index.ts
Labels: 🌟improvement

#4858 [WEB-1397] fix: UI package logo component
  packages/ui/src/emoji/logo.tsx
  space/core/store/root.store.ts
  web/core/store/pages/page.ts
Labels: 🐛bug, 🌐frontend

#4859 [WEB-1611] style: fixed state column width for consistency.
  web/core/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
Labels: 🌐frontend, 🎨UI / UX

#4855 [WEB-1635] style: fix vertical section tabs highlights.
  web/core/components/archives/archive-tabs-list.tsx
  web/core/constants/dashboard.ts
  web/core/constants/profile.ts
  web/core/constants/project.ts
  web/core/constants/workspace.ts
Labels: 🌐frontend, 🎨UI / UX

#4857 [WEB-1648] fix: issue pagination logic for Gantt and Spreadsheet
  web/core/components/gantt-chart/sidebar/issues/sidebar.tsx
  web/core/components/inbox/sidebar/root.tsx
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🐛bug, 🌐frontend

#4861 [WEB-1397] chore: update space app types
  space/core/types/issue.d.ts
  space/core/types/project.d.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/ce/components/pages/extra-actions.tsx
  web/ce/components/pages/index.ts
  web/ee/components/pages/extra-actions.tsx
  web/ee/components/pages/index.ts
Labels: 🌐frontend, 🛠️refactor

#4854 [WEB-1624] chore: add un-snooze option and minor fixes in inbox issue
  packages/types/src/inbox.d.ts
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/inbox-issue-mobile-header.tsx
  web/core/store/inbox/inbox-issue.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4862 [WEB-1642] chore: mutating issue estimation_point when we delete the estimate point from the project
  web/core/store/estimates/estimate.ts
Labels: 🌟improvement

#4870 [WEB-1397] chore: updated error state, sign in page and 404 page content
  space/app/error.tsx
  space/app/not-found.tsx
  space/core/components/account/auth-forms/auth-header.tsx
  space/core/components/account/user-logged-in.tsx
  web/app/error.tsx
Labels: 🌐frontend, 🌟improvement

#4873 [WEB-1663] chore: improve create new label UI.
  web/core/components/issues/issue-detail/label/create-label.tsx
Labels: 🌟improvement

#4871 [WEB-1652] fix: add optional chaining to fix app crash if router params are not available.
  web/core/components/cycles/gantt-chart/blocks.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block.tsx
  web/core/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/core/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/issue-modal/modal.tsx
  web/core/components/modules/module-list-item.tsx
Labels: 🐛bug

#4876 [WEB-1615] chore: sign up password strength improvement
  web/core/components/account/auth-forms/password.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4878 [WEB-1654] fix: issue creation logic for modules and cycles
  web/core/components/issues/issue-modal/modal.tsx
  web/core/store/issue/module/issue.store.ts
Labels: 🐛bug, 🌐frontend

#4880 [WEB-1610] chore: re-implement reload confirmation hook.
  packages/editor/core/src/ui/mentions/mention-node-view.tsx
  web/core/hooks/use-reload-confirmation.tsx
Labels: 🛠️refactor

#4869 [WEB-1665] chore: advance views migration
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/view.py
  apiserver/plane/app/urls/views.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/db/migrations/0069_alter_account_provider_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/view.py
Labels: ⚙️backend, 🔄migrations

#4883 fix: update root store import in space app.
  space/core/store/instance.store.ts
  space/core/store/issue-detail.store.ts
  space/core/store/issue-filters.store.ts
  space/core/store/issue.store.ts
  space/core/store/mentions.store.ts
  space/core/store/profile.store.ts
  space/core/store/publish/publish.store.ts
  space/core/store/publish/publish_list.store.ts
  space/core/store/user.store.ts
Labels: 🐛bug

#4582 [WEB-1420] chore: considering telemetry settings while capturing events
  web/core/lib/posthog-provider.tsx
Labels: 🌐frontend, 🧹chore, event tracking

#4885 [WEB-1674] chore: views access control
  apiserver/plane/app/serializers/view.py
  apiserver/plane/app/views/view/base.py
Labels: ⚙️backend, 🌟improvement

#4886 [WEB-1676] chore: workspace cycles list endpoint
  apiserver/plane/app/views/workspace/cycle.py
Labels: ⚙️backend, 🌟improvement

#4887 [WEB-1647] chore: breadcrumb items loader
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/inbox/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/settings/header.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4834 chore: move `FavoriteStar` component to ui package
  packages/ui/src/favorite-star.tsx
  packages/ui/src/index.ts
  web/core/components/core/index.ts
  web/core/components/cycles/active-cycle/upcoming-cycles-list-item.tsx
  web/core/components/cycles/board/cycles-board-card.tsx
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/modules/module-card-item.tsx
  web/core/components/modules/module-list-item-action.tsx
  web/core/components/pages/list/block-item-action.tsx
  web/core/components/project/card.tsx
  web/core/components/views/view-list-item-action.tsx
Labels: 🌐frontend, 🛠️refactor

#4891 [WEB-1681] chore: handled password strength validation and improved the acceptable char
  web/app/accounts/reset-password/page.tsx
  web/app/accounts/set-password/page.tsx
  web/app/profile/security/page.tsx
  web/core/components/account/auth-forms/password.tsx
  web/core/components/account/password-strength-meter.tsx
  web/core/components/onboarding/profile-setup.tsx
  web/helpers/password.helper.ts
Labels: 🌐frontend, 🌟improvement

#4892 [WEB-1675] fix: issue peek view label with longer title
  web/core/components/issues/peek-overview/properties.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4890 [WEB-1667] chore: icon list improvement
  packages/ui/src/emoji/emoji-icon-picker-new.tsx
  packages/ui/src/emoji/emoji-icon-picker.tsx
  packages/ui/src/emoji/icons-list.tsx
  packages/ui/src/emoji/lucide-icons-list.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4895 [WEB-1673] fix: project label error message and improvement
  web/core/components/labels/create-update-label-inline.tsx
  web/core/components/labels/label-block/label-item-block.tsx
  web/core/components/labels/label-block/label-name.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4896 [WEB-522] chore: Move the estimates store and service out of core
  web/ce/services/index.ts
  web/ce/services/project/estimate.service.ts
  web/ce/services/project/index.ts
  web/ce/store/estimates/estimate.ts
  web/core/components/dropdowns/estimate.tsx
  web/core/hooks/store/estimates/use-estimate.ts
  web/core/services/project/index.ts
  web/core/store/estimates/estimate-point.ts
  web/core/store/estimates/project-estimate.store.ts
  web/ee/services/index.ts
  web/ee/services/project/estimate.service.ts
  web/ee/services/project/index.ts
  web/ee/store/estimates/estimate.ts
Labels: 🌟improvement, 🧹chore

#4882 chore: external api cycle snapshot
  apiserver/plane/api/views/cycle.py
Labels: ⚙️backend, 🌟improvement

#4899 [WEB-1681] fix: onboarding password validation on weak password
  web/core/components/onboarding/profile-setup.tsx
  yarn.lock
Labels: 🐛bug, 🌐frontend

#4900 [WEB-1672] chore: updated input validation on create and update estimate point form and truncated in issues
  web/core/components/estimates/points/create.tsx
  web/core/components/estimates/points/update.tsx
Labels: 🌐frontend, 🌟improvement

#4904 [WEB-1686] fix: issues incorrect filters while switching between, projects, modules etc
  web/core/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
  web/core/components/issues/issue-layouts/list/roots/project-view-root.tsx
  web/core/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/roots/project-view-root.tsx
  web/core/hooks/use-issues-actions.tsx
  web/core/store/issue/archived/filter.store.ts
  web/core/store/issue/archived/issue.store.ts
  web/core/store/issue/cycle/filter.store.ts
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/draft/filter.store.ts
  web/core/store/issue/draft/issue.store.ts
  web/core/store/issue/helpers/issue-filter-helper.store.ts
  web/core/store/issue/module/filter.store.ts
  web/core/store/issue/module/issue.store.ts
  web/core/store/issue/profile/filter.store.ts
  web/core/store/issue/profile/issue.store.ts
  web/core/store/issue/project-views/filter.store.ts
  web/core/store/issue/project-views/issue.store.ts
  web/core/store/issue/project/filter.store.ts
  web/core/store/issue/project/issue.store.ts
  web/core/store/issue/workspace/filter.store.ts
  web/core/store/issue/workspace/issue.store.ts
Labels: 🐛bug, 🌐frontend

#4905 [WEB-1682] chore: additional document editor extensions
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/ce/extensions/index.ts
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/ee/extensions/index.ts
Labels: 🌐frontend, 🌟improvement

#4906 [WEB-1685] chore: page and view list page improvement
  admin/core/components/admin-sidebar/root.tsx
  web/core/components/pages/list/block.tsx
  web/core/components/views/view-list-item.tsx
  web/core/components/workspace/help-section.tsx
Labels: 🌐frontend, 🧹chore

#4910 [WEB - 1703] fix: pagination when group is not present in result
  apiserver/plane/utils/grouper.py
Labels: 🐛bug, ⚙️backend

#4915 [WEB-1682] fix: mentions not working in any editor
  packages/editor/src/core/extensions/mentions/extension.tsx
  web/core/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#4918 [WEB-1695] chore: draft issue quick action menu validation
  web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4914 [WEB-1008] chore: issue toast alert improvement
  packages/ui/src/toast/index.tsx
  web/core/components/issues/create-issue-toast-action-items.tsx
  web/core/components/issues/index.ts
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/list/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/spreadsheet/quick-add-issue-form.tsx
  web/core/components/issues/issue-modal/modal.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4923 [WEB-1717] fix: order by on issues not updating for custom global views
  web/core/store/issue/workspace/filter.store.ts
Labels: 🐛bug, 🌐frontend

#4922 [WEB-1714] fix: module and cycle sidebar issue progress
  web/core/components/cycles/analytics-sidebar/issue-progress.tsx
  web/core/components/modules/analytics-sidebar/issue-progress.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4927 [WEB-1691] fix: update `ControlLink` default target to `_blank` to avoid unwanted N-progress trigger.
  packages/ui/src/control-link/control-link.tsx
  web/core/components/core/list/list-item.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/issue-properties.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block.tsx
  web/core/components/issues/issue-layouts/gantt/blocks.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
Labels: 🐛bug, 🌐frontend

#4933 [WEB-1716] fix: sidebar UI inconsistencies
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/user-menu.tsx
  web/core/components/workspace/sidebar/workspace-menu.tsx
  web/core/constants/dashboard.ts
Labels: 🌐frontend, 🎨UI / UX

#4932 [WEB-1255] chore: public and unlocked views
  packages/types/src/views.d.ts
  packages/types/src/workspace-views.d.ts
  packages/ui/src/dropdown/common/button.tsx
  packages/ui/src/dropdown/common/options.tsx
  packages/ui/src/dropdown/dropdown.d.ts
  packages/ui/src/dropdown/multi-select.tsx
  packages/ui/src/dropdown/single-select.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/page.tsx
  web/app/[workspaceSlug]/(projects)/workspace-views/header.tsx
  web/core/components/core/list/list-item.tsx
  web/core/components/dropdowns/layout.tsx
  web/core/components/dropdowns/member/avatar.tsx
  web/core/components/icons/locked-component.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/views/form.tsx
  web/core/components/views/update-view-component.tsx
  web/core/components/views/view-list-item-action.tsx
  web/core/components/workspace/views/quick-action.tsx
  web/core/constants/issue.ts
  web/core/constants/views.ts
  web/core/store/issue/project-views/filter.store.ts
  web/core/store/issue/workspace/filter.store.ts
Labels: 🌐frontend

#4926 [WEB-1727] refactor: pages editor sync logic solidified
  apiserver/plane/app/views/page/base.py
  packages/editor/src/ce/providers/collaboration-provider.ts
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/editor.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/hooks/use-auto-save.tsx
  web/core/hooks/use-page-description.ts
  web/core/services/page/project-page.service.ts
Labels: ✍️editor

#4935 [WEB-1726] fix: password strength banner validation
  web/core/components/account/auth-forms/password.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4939 [WEB-1724] fix: initial pages list loading.
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/core/components/inbox/root.tsx
  web/core/components/inbox/sidebar/root.tsx
  web/core/components/pages/pages-list-view.tsx
  web/core/hooks/use-auto-save.tsx
  web/core/store/inbox/project-inbox.store.ts
  web/core/store/pages/project-page.store.ts
Labels: 🐛bug

#4943 [WEB-1718] style: fix spreadsheet column width when other properties are hidden.
  web/core/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx
Labels: 🌐frontend, 🎨UI / UX

#4946 fix: added import order rules to the editor package
  packages/editor/.eslintrc.js
  packages/editor/src/core/components/editors/editor-content.tsx
  packages/editor/src/core/components/menus/block-menu.tsx
  packages/editor/src/core/extensions/code/code-block-node-view.tsx
  packages/editor/src/core/extensions/code/index.tsx
  packages/editor/src/core/extensions/core-without-props.tsx
  packages/editor/src/core/extensions/custom-list-keymap/list-helpers.ts
  packages/editor/src/core/extensions/custom-list-keymap/list-keymap.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/image/extension.tsx
  packages/editor/src/core/extensions/image/image-extension-without-props.tsx
  packages/editor/src/core/extensions/image/image-resize.tsx
  packages/editor/src/core/extensions/image/utilities/insert-line-above-image.ts
  packages/editor/src/core/extensions/image/utilities/insert-line-below-image.ts
  packages/editor/src/core/extensions/keymap.tsx
  packages/editor/src/core/extensions/mentions/extension.tsx
  packages/editor/src/core/extensions/mentions/mention-node-view.tsx
  packages/editor/src/core/extensions/mentions/mentions-without-props.tsx
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/slash-commands.tsx
  packages/editor/src/core/extensions/table/table/table-controls.ts
  packages/editor/src/core/extensions/table/table/table.ts
  packages/editor/src/core/extensions/table/table/utilities/create-table.ts
  packages/editor/src/core/extensions/table/table/utilities/delete-table-when-all-cells-selected.ts
  packages/editor/src/core/extensions/typography/index.ts
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/helpers/insert-content-at-cursor-position.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/plugins/image/utils/placeholder.ts
  packages/editor/src/core/types/editor.ts
Labels: 🌐frontend, 🌟improvement, ✍️editor

#4945 chore: add extra check to fetch pages list and page details
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/core/components/pages/pages-list-view.tsx
Labels: 🌐frontend

#4941 [WEB-1716] chore: sidebar improvements for guests/viewers
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
  web/core/components/workspace/sidebar/workspace-menu.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4951 [WEB-1746] fix: remove password validation for sign-in.
  web/core/components/account/auth-forms/password.tsx
Labels: 🐛bug, 🌐frontend

#4940 [WEB-1668] fix: drag drop issues with h4, h5, h6, images and nodes inside tables
  packages/editor/src/core/extensions/drag-drop.tsx
  packages/editor/src/styles/table.css
Labels: ✍️editor

#4938 [WEB-1682] fix: removed issue embed option from the slash commands
  packages/editor/src/ce/extensions/document-extensions.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#4955 [WEB-1255] chore: necessary changes for advanced views
  packages/types/src/views.d.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/core/components/views/applied-filters/access.tsx
  web/core/components/views/applied-filters/index.tsx
  web/core/components/views/applied-filters/root.tsx
  web/core/store/global-view.store.ts
  web/core/store/project-view.store.ts
  web/helpers/project-views.helpers.ts
Labels: 🌐frontend

#4950 [WEB-1691] chore: refactor finish onboarding logic to avoid multiple redirections.
  web/app/onboarding/page.tsx
  web/core/components/onboarding/invitations.tsx
  web/core/lib/wrappers/authentication-wrapper.tsx
  web/core/services/api.service.ts
  web/core/store/user/profile.store.ts
  web/core/store/workspace/index.ts
Labels: 🐛bug, 🌟improvement

#4953 [WEB - 1750] fix: dummy data script to create Pages without project
  apiserver/plane/bgtasks/dummy_data_task.py
Labels: 🐛bug, ⚙️backend

#4944 [WEB - 1742] chore: user activation and deactivation workflow
  apiserver/plane/app/views/user/base.py
  apiserver/plane/authentication/adapter/base.py
  apiserver/plane/authentication/views/app/check.py
  apiserver/plane/authentication/views/app/email.py
  apiserver/plane/authentication/views/app/magic.py
  apiserver/plane/authentication/views/space/check.py
  apiserver/plane/authentication/views/space/email.py
  apiserver/plane/authentication/views/space/magic.py
  apiserver/plane/bgtasks/user_activation_email_task.py
  apiserver/plane/bgtasks/user_deactivation_email_task.py
  apiserver/plane/utils/host.py
  apiserver/templates/emails/user/user_activation.html
  apiserver/templates/emails/user/user_deactivation.html
Labels: ⚙️backend, 🧹chore

#4957 [WEB-1757] chore: rename deploy to publish
  space/app/issues/[anchor]/layout.tsx
  space/app/layout.tsx
  space/core/constants/seo.ts
Labels: 🌐frontend, 🌟improvement

#4961 [WEB-1748] fix: onboarding infinite loading issue.
  web/app/onboarding/page.tsx
Labels: 🐛bug

#4962 [WEB-1255] chore: make core changes for Advanced views
  web/ce/components/views/access-controller.tsx
  web/ce/components/views/filters/access-filter.tsx
  web/core/components/common/access-field.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/core/components/pages/modals/page-form.tsx
  web/core/components/views/filters/filter-selection.tsx
  web/core/components/views/form.tsx
  web/core/components/workspace/views/form.tsx
  web/ee/components/views/access-controller.tsx
  web/ee/components/views/filters/access-filter.tsx
Labels: 🌐frontend
