Repository makeplane/plane, pull requests merged in 2024-07, with the labels that each got.

#4977 Fix: image insertion in node boundaries and missing extensions
  packages/editor/src/core/components/editors/document/helpers.ts
  packages/editor/src/core/components/editors/document/index.ts
  packages/editor/src/core/extensions/core-without-props.tsx
  packages/editor/src/core/extensions/document-without-props.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/image/extension.tsx
  packages/editor/src/core/extensions/image/image-extension-without-props.tsx
  packages/editor/src/core/extensions/image/utilities/insert-line-above-image.ts
  packages/editor/src/core/extensions/image/utilities/insert-line-below-image.ts
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/issue-embed/index.ts
  packages/editor/src/core/extensions/issue-embed/issue-embed-without-props.ts
  packages/editor/src/core/helpers/common.ts
  packages/editor/src/core/helpers/insert-empty-paragraph-at-node-boundary.ts
  packages/editor/src/index.ts
  web/core/hooks/use-page-description.ts
Labels: ✍️editor

#4978 fix: multiline copy paste
  packages/editor/src/core/extensions/extensions.tsx
Labels: ✍️editor

#4980 [WEB-1791] fix: issue delete redirection
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
Labels: 🐛bug, 🌐frontend

#4984 [WEB-1255] chore: modify default filter options for views
  web/core/store/project-view.store.ts
Labels: 🌐frontend

#4983 [WEB-1753] fix: padding inside the blockquotes inside list items
  packages/editor/src/styles/editor.css
Labels: ✍️editor

#4981 [WEB-1790] chore: delete view permission change
  apiserver/plane/app/views/view/base.py
Labels: ⚙️backend, 🌟improvement

#4986 [WEB-1689] fix: command enter submits the form
  packages/editor/src/core/extensions/enter-key-extension.tsx
  packages/editor/src/core/types/editor.ts
  space/core/components/editor/lite-text-editor.tsx
  space/core/components/editor/toolbar.tsx
  space/core/components/issues/peek-overview/comment/add-comment.tsx
  space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/workspace-menu.tsx
Labels: 🌐frontend, 🌟improvement

#4992 [WEB-1802] chore: remove redirection logic from security settings page if the user password is not setup.
  web/app/profile/security/page.tsx
Labels: 🌐frontend, 🌟improvement

#4999 [WEB-1814] chore: admin app UI & UX improvements.
  admin/app/authentication/github/form.tsx
  admin/app/authentication/github/page.tsx
  admin/app/authentication/gitlab/form.tsx
  admin/app/authentication/gitlab/page.tsx
  admin/app/authentication/google/form.tsx
  admin/app/authentication/google/page.tsx
  admin/ce/components/authentication/authentication-modes.tsx
  admin/core/components/admin-sidebar/root.tsx
  admin/core/components/authentication/authentication-method-card.tsx
  admin/core/components/common/code-block.tsx
  admin/core/components/common/controller-input.tsx
  admin/core/components/common/index.ts
  admin/core/components/common/upgrade-button.tsx
  admin/helpers/authentication.helper.tsx
  admin/public/logos/oidc-logo.png
  admin/public/logos/saml-logo.svg
  packages/types/src/instance/auth.d.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#5006 [WEB-1822] fix: issue link count mutation
  web/core/store/issue/issue-details/link.store.ts
Labels: 🐛bug, 🌐frontend

#5003 [WEB-1821] dev: open dropdown on hover
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/helper.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5008 [WEB-1792] chore: integrated inbox issue in notification peek view and handled increment/decrement of unread notifications
  apiserver/plane/app/serializers/notification.py
  apiserver/plane/app/views/notification/base.py
  packages/types/src/workspace-notifications.d.ts
  web/app/[workspaceSlug]/(projects)/notifications/page.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/root.tsx
  web/core/components/issues/peek-overview/loader.tsx
  web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
  web/core/components/workspace-notifications/sidebar/header/root.tsx
  web/core/components/workspace-notifications/sidebar/loader.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/options/archive.tsx
  web/core/components/workspace-notifications/sidebar/root.tsx
  web/core/store/notifications/notification.ts
  web/core/store/notifications/workspace-notifications.store.ts
  web/core/store/user/user-membership.store.ts
Labels: 🌐frontend, ⚙️backend

#5000 [WEB-1801] improvement: open shortcut guide using `shift+/` key combination.
  web/core/components/command-palette/command-palette.tsx
  web/core/components/command-palette/shortcuts-modal/commands-list.tsx
Labels: 🌐frontend, 🌟improvement

#5005 [WEB-1679] chore: relation and attachment icons
  packages/ui/src/icons/dropdown-icon.tsx
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/relations-icon.tsx
  web/core/components/icons/attachment/attachment-icon.tsx
  web/core/components/issues/attachment/attachment-detail.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5002 [WEB-1798] fix : Add empty state when view is not available
  web/app/[workspaceSlug]/(projects)/workspace-views/[globalViewId]/page.tsx
  web/core/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
Labels: 🌐frontend

#5001 [WEB-1819] dev: collapsible component
  packages/ui/src/collapsible/collapsible.tsx
  packages/ui/src/collapsible/index.ts
  packages/ui/src/index.ts
Labels: 🌐frontend

#4989 [WEB-1823] fix: update link view now updates the link
  packages/editor/src/core/components/links/link-edit-view.tsx
Labels: ✍️editor

#4991 [WEB-1798] chore: tweak pagination and virtualization thresholds to have a smoother scroll
  web/core/components/gantt-chart/sidebar/issues/sidebar.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block-root.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
Labels: 🌐frontend

#4993 [WEB-1800] fix: peek overview layout dropdown icons in the space app
  space/core/components/issues/peek-overview/header.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#4995 [WEB-1808] style: fix `settings` highlight on app sidebar.
  web/core/constants/dashboard.ts
Labels: 🌐frontend, 🎨UI / UX

#5004 [WEB-1265] fix: project publish redirection
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
  web/core/components/project/publish-project/modal.tsx
Labels: 🐛bug, 🌐frontend

#5018 [WEB-1836] fix: modal core onClose functionality
  packages/ui/src/modals/modal-core.tsx
Labels: 🐛bug, 🌐frontend

#5023 [WEB - 1838]fix: workspace slug validation
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/views/workspace/base.py
  apiserver/plane/db/models/workspace.py
Labels: 🐛bug

#4976 fix:feature preview
  .github/workflows/build-aio-base.yml
  .github/workflows/build-aio-branch.yml
  .github/workflows/feature-deployment.yml
Labels: 🚀CI/CD, 🐳docker, devops

#5020 [WEB-1807] fix: sidebar quick action overlapping
  web/core/components/workspace/sidebar/quick-actions.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5027 [WEB-1715] chore: issue filters indicator enhancement
  web/app/[workspaceSlug]/(projects)/profile/[userId]/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/workspace-views/header.tsx
  web/core/components/issues/archived-issues-header.tsx
  web/core/components/profile/profile-issues-filter.tsx
  web/helpers/filter.helper.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5029 [WEB - 1841] fix: issue pagination listing
  apiserver/plane/db/models/issue.py
Labels: 🐛bug, ⚙️backend

#5015 [WEB-1829] fix: stop issues query before fetching the view filters
  web/core/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/core/store/project-view.store.ts
  web/helpers/project-views.helpers.ts
Labels: 🐛bug, 🌐frontend

#5031 [WEB-1843] chore: active cycles file restructuring.
  web/app/[workspaceSlug]/(projects)/active-cycles/page.tsx
  web/ce/components/active-cycles/index.ts
  web/ce/components/active-cycles/root.tsx
  web/ce/components/active-cycles/workspace-active-cycles-upgrade.tsx
  web/core/components/workspace/index.ts
  web/ee/components/active-cycles/index.ts
  web/ee/components/active-cycles/root.tsx
  web/ee/components/active-cycles/workspace-active-cycles-upgrade.tsx
Labels: 🧹chore

#5039 [WEB-1853] fix: Module Issue Quick add
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/module/issue.store.ts
Labels: 🐛bug, 🌐frontend

#5010 [WEB-1818] fix: issue changes done in Peek overview to reflect in the issue list boards
  web/core/components/issues/issue-detail/module-select.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/peek-overview/root.tsx
  web/core/store/issue/archived/issue.store.ts
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/draft/issue.store.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/issue-details/root.store.ts
  web/core/store/issue/module/issue.store.ts
  web/core/store/issue/profile/issue.store.ts
  web/core/store/issue/project-views/issue.store.ts
  web/core/store/issue/project/issue.store.ts
  web/core/store/issue/workspace/issue.store.ts
Labels: 🐛bug, 🌐frontend

#5042 [WEB-1857] chore: update comment box placeholder
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
Labels: 🌐frontend, 🌟improvement

#5045 [WEB-1858] fix: issue peek view link list ui
  web/core/components/issues/issue-detail/links/links.tsx
Labels: 🐛bug, 🌐frontend

#5030 [WEB-1840] chore: corrected the sub issue ordering
  apiserver/plane/api/views/inbox.py
  apiserver/plane/app/views/issue/sub_issue.py
Labels: ⚙️backend, 🌟improvement

#5053 chore: update assignes for github issue template workflow
  .github/ISSUE_TEMPLATE/--bug-report.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: 🚀CI/CD

#5052 [WEB-1868] chore: custom analytics chart
  apiserver/plane/utils/analytics_plot.py
Labels: 🐛bug, ⚙️backend

#4942 [WEB - 1740] chore: add issue id in pages detail endpoint
  apiserver/plane/app/views/page/base.py
  apiserver/plane/db/models/page.py
Labels: ⚙️backend, 🧹chore

#5043 [WEB-1519] chore: update component structure in project state settings and implement DND
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/states/page.tsx
  web/core/components/project-states/create-update/create.tsx
  web/core/components/project-states/create-update/form.tsx
  web/core/components/project-states/create-update/index.ts
  web/core/components/project-states/create-update/update.tsx
  web/core/components/project-states/group-item.tsx
  web/core/components/project-states/group-list.tsx
  web/core/components/project-states/index.ts
  web/core/components/project-states/loader.tsx
  web/core/components/project-states/options/delete.tsx
  web/core/components/project-states/options/index.ts
  web/core/components/project-states/options/mark-as-default.tsx
  web/core/components/project-states/root.tsx
  web/core/components/project-states/state-delete-modal.tsx
  web/core/components/project-states/state-item.tsx
  web/core/components/project-states/state-list.tsx
  web/core/components/states/create-state-modal.tsx
  web/core/components/states/create-update-state-inline.tsx
  web/core/components/states/index.ts
  web/core/components/states/project-setting-state-list-item.tsx
  web/core/components/states/project-setting-state-list.tsx
  web/core/constants/state.ts
  web/core/store/state.store.ts
  web/helpers/state.helper.ts
Labels: 🌐frontend, 🧹chore

#5055 [WEB-1683] fix: kanban subgroup quick add validation
  web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
Labels: 🐛bug, 🌐frontend

#5040 [WEB-1437] feat: notifications mention filter
  apiserver/plane/app/views/notification/base.py
  packages/types/src/workspace-notifications.d.ts
  web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
  web/core/components/workspace-notifications/sidebar/empty-state.tsx
  web/core/components/workspace-notifications/sidebar/header/root.tsx
  web/core/components/workspace-notifications/sidebar/index.ts
  web/core/components/workspace-notifications/sidebar/root.tsx
  web/core/constants/notification.ts
  web/core/store/notifications/workspace-notifications.store.ts
Labels: 🌐frontend, ⚙️backend

#5034 [WEB-1679] feat: issue detail widgets
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/issue/relation.py
  packages/ui/src/collapsible/collapsible-button.tsx
  packages/ui/src/collapsible/index.ts
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/relations-icon.tsx
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/core/components/issues/index.ts
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail-widgets/attachments/content.tsx
  web/core/components/issues/issue-detail-widgets/attachments/helper.tsx
  web/core/components/issues/issue-detail-widgets/attachments/index.ts
  web/core/components/issues/issue-detail-widgets/attachments/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/attachments/root.tsx
  web/core/components/issues/issue-detail-widgets/attachments/title.tsx
  web/core/components/issues/issue-detail-widgets/index.ts
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-collapsibles.tsx
  web/core/components/issues/issue-detail-widgets/links/content.tsx
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
  web/core/components/issues/issue-detail-widgets/links/index.ts
  web/core/components/issues/issue-detail-widgets/links/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/links/root.tsx
  web/core/components/issues/issue-detail-widgets/links/title.tsx
  web/core/components/issues/issue-detail-widgets/relations/content.tsx
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail-widgets/relations/index.ts
  web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/relations/root.tsx
  web/core/components/issues/issue-detail-widgets/relations/title.tsx
  web/core/components/issues/issue-detail-widgets/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/index.ts
  web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/issue-detail-widgets/widget-button.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/relations/index.ts
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/relations/issue-list.tsx
  web/core/components/issues/relations/properties.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX, 🧹chore

#5062 [WEB-1722] fix: dashboard collaborators endpoint
  apiserver/plane/app/views/dashboard/base.py
Labels: 🐛bug, ⚙️backend, 🧹chore

#5064 [WEB-1875] fix: module sidebar scroll
  web/core/components/modules/analytics-sidebar/root.tsx
Labels: 🐛bug, 🌐frontend

#5065 [WEB - 1879] fix: remove user workspace cache on account deactivation
  apiserver/plane/app/views/user/base.py
Labels: 🐛bug, ⚙️backend

#5068 [WEB-1874] fix: issue link error toast alert
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
  web/core/components/issues/issue-detail/links/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5069 [WEB-1679] dev: issue details widgets added to issue peek overview
  web/core/components/issues/peek-overview/properties.tsx
  web/core/components/issues/peek-overview/view.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5066 [WEB-1872] fix: completed cycle gantt layout quick add issue validation
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/roots/cycle-layout-root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5076 [WEB-1720] fix: created by tooltip removed
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/peek-overview/properties.tsx
Labels: 🌐frontend, 🧹chore

#5072 [WEB-1890] fix: issue creation by using appropriate stores
  web/core/components/command-palette/command-palette.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/core/components/issues/issue-modal/modal.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
  web/core/hooks/use-issue-layout-store.ts
Labels: 🐛bug, 🌐frontend

#5077 [WEB-1510] chore: project active cycle progress state group color updated
  web/core/constants/cycle.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5075 [WEB-1680] dev: issue detail activity revamp and issue detail page improvement
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/core/components/issues/issue-detail-widgets/relations/content.tsx
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail/issue-activity/activity-comment-root.tsx
  web/core/components/issues/issue-detail/issue-activity/activity-filter.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/link.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
  web/core/components/issues/issue-detail/issue-activity/index.ts
  web/core/components/issues/issue-detail/issue-activity/root.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/peek-overview/view.tsx
  web/core/constants/issue.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5080 [WEB-1899] fix: attachment delete modal
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5073 [WEB - 1888] dev: log issue activity when transferring issues from one cycle to another
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/app/views/cycle/base.py
Labels: ⚙️backend

#5083 [WEB-1900] chore: mentions mutation, ui fix on app sidebar notification badge, and back button inbox issue notification embed
  apiserver/plane/app/serializers/notification.py
  apiserver/plane/app/views/notification/base.py
  packages/types/src/workspace-notifications.d.ts
  web/app/[workspaceSlug]/(projects)/notifications/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
  web/core/components/common/count-chip.tsx
  web/core/components/common/index.ts
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/inbox-issue-mobile-header.tsx
  web/core/components/workspace-notifications/notification-app-sidebar-option.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
  web/core/components/workspace-notifications/sidebar/root.tsx
  web/core/store/notifications/notification.ts
  web/core/store/notifications/workspace-notifications.store.ts
Labels: 🌐frontend, ⚙️backend, 🧹chore

#5082 [WEB-1904] chore: updated setup env
  ENV_SETUP.md
Labels: 🌟improvement

#5085 [WEB-1899] fix: issue attachment delete modal and code refactor
  web/core/components/issues/attachment/attachment-detail.tsx
  web/core/components/issues/attachment/attachment-item-list.tsx
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/core/components/issues/attachment/delete-attachment-modal.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5092 dev: remove page version back migrations
  apiserver/plane/db/migrations/0070_issuetype_issue_type.py
Labels: ⚙️backend, 🔄migrations

#5100 fix: data migrations for page versioning
  apiserver/plane/db/backfills/__init__.py
  apiserver/plane/db/backfills/backfill_0070_page_versions.py
  apiserver/plane/db/migrations/0070_page_versions.py
  apiserver/plane/db/models/page.py
  apiserver/plane/settings/common.py
Labels: 🔄migrations

#5103 chore: page version migrations
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/project.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/db/backfills/__init__.py
  apiserver/plane/db/backfills/backfill_0070_page_versions.py
  apiserver/plane/db/migrations/0070_apitoken_is_service_exporterhistory_filters_and_more.py
  apiserver/plane/db/migrations/0070_page_versions.py
  apiserver/plane/db/models/exporter.py
  apiserver/plane/db/models/issue_type.py
Labels: ⚙️backend

#5087 [WEB-1513] chore: auth screen layout padding
  space/core/components/views/auth.tsx
  web/app/accounts/forgot-password/page.tsx
  web/app/accounts/reset-password/page.tsx
  web/app/accounts/set-password/page.tsx
  web/app/page.tsx
  web/app/sign-up/page.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5104 [WEB-1935] dev: fix page versioning task
  apiserver/plane/bgtasks/page_version_task.py
Labels: 🐛bug, ⚙️backend

#5101 [WEB-1925] dev: issue detail widget enhancement
  packages/types/src/issues/issue.d.ts
  packages/ui/src/collapsible/collapsible-button.tsx
  web/core/components/issues/issue-detail-widgets/attachments/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/attachments/root.tsx
  web/core/components/issues/issue-detail-widgets/links/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/links/root.tsx
  web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/relations/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/links/link-detail.tsx
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/components/issues/issue-detail/links/root.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5095 [WEB-1909] chore: removed duplication of assignee and label activity
  apiserver/plane/app/views/issue/base.py
Labels: ⚙️backend, 🌟improvement

#5106 [WEB-1921] fix: issue widgets modal and code refactor
  apiserver/plane/settings/common.py
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail-widgets/attachments/root.tsx
  web/core/components/issues/issue-detail-widgets/index.ts
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-detail-widgets/links/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/links/root.tsx
  web/core/components/issues/issue-detail-widgets/links/title.tsx
  web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/relations/root.tsx
  web/core/components/issues/issue-detail-widgets/relations/title.tsx
  web/core/components/issues/issue-detail-widgets/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore, 🛠️refactor

#5105 [WEB-1929] chore: improve finishOnboarding logic to handle case where user profile setup is done and user already has a workspace.
  web/app/onboarding/page.tsx
  web/core/lib/wrappers/authentication-wrapper.tsx
Labels: 🎨UI / UX, 🌟improvement

#5110 [WEB-1902] fix: last draft issue properties
  web/core/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5112 [WEB-1905] fix: sort order for workspace views
  web/core/store/issue/workspace/filter.store.ts
Labels: 🐛bug, 🌐frontend

#5120 [WEB-1697] fix: issue label activity truncate fix and chip component added
  web/core/components/issues/issue-detail/issue-activity/activity/actions/index.ts
  web/core/components/issues/issue-detail/issue-activity/activity/actions/label-activity-chip.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/label.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#5113 [WEB-1875] fix: module and cycle sidebar scroll
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/[moduleId]/page.tsx
  web/core/components/cycles/analytics-sidebar/root.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5118 [WEB-1834] fix: export issues validation
  web/core/components/exporter/guide.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5121 [WEB-1869] chore: space app issue comment placeholder updated
  space/core/components/issues/peek-overview/comment/add-comment.tsx
Labels: 🌐frontend, 🧹chore

#5109 [WEB-1945] fix: added atomic transactions for sequence id in issue
  apiserver/plane/db/models/issue.py
Labels: ⚙️backend, 🌟improvement

#5102 [WEB-1557] fix: create issue disabled for guests
  web/core/components/command-palette/command-modal.tsx
  web/core/components/command-palette/command-palette.tsx
  web/core/store/user/index.ts
  yarn.lock
Labels: 🐛bug, 🌐frontend

#5125 [WEB-1954] chore: implemented table component in ui library
  packages/ui/src/index.ts
  packages/ui/src/tables/index.ts
  packages/ui/src/tables/table.stories.tsx
  packages/ui/src/tables/table.tsx
  packages/ui/src/tables/types.ts
Labels: 🎨UI / UX, 🧹chore

#5126 [WEB-1921] fix: isssue widgets collapsible ui
  web/core/components/issues/issue-detail-widgets/attachments/root.tsx
  web/core/components/issues/issue-detail-widgets/links/root.tsx
  web/core/components/issues/issue-detail-widgets/relations/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5119 dev: rename user display configuration model
  apiserver/plane/api/views/project.py
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/project/invite.py
  apiserver/plane/app/views/project/member.py
  apiserver/plane/db/migrations/0071_rename_issueproperty_issueuserproperty_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/issue_type.py
  apiserver/plane/db/models/project.py
Labels: ⚙️backend, 🔄migrations

#5139 [WEB-1958] fix: handled the auto form submit for all authenticators
  space/core/components/account/auth-forms/password.tsx
  web/core/components/account/auth-forms/password.tsx
Labels: 🌐frontend

#5140 [WEB-1730] chore: project intake
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/intake.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/inbox/header.tsx
  web/ce/constants/project/settings/features.tsx
  web/core/components/core/activity.tsx
  web/core/components/inbox/root.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/inbox.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/constants/empty-state.ts
  web/public/empty-state/disabled-feature/inbox-dark.webp
  web/public/empty-state/disabled-feature/inbox-light.webp
  web/public/empty-state/disabled-feature/intake-dark.webp
  web/public/empty-state/disabled-feature/intake-light.webp
  web/public/empty-state/inbox/filter-issue-dark.webp
  web/public/empty-state/inbox/filter-issue-light.webp
  web/public/empty-state/inbox/inbox-dark-resp.webp
  web/public/empty-state/inbox/inbox-dark.webp
  web/public/empty-state/inbox/inbox-issue-dark.webp
  web/public/empty-state/inbox/inbox-issue-light.webp
  web/public/empty-state/inbox/inbox-light-resp.webp
  web/public/empty-state/inbox/inbox-light.webp
  web/public/empty-state/intake/filter-issue-dark.webp
  web/public/empty-state/intake/filter-issue-light.webp
  web/public/empty-state/intake/intake-dark-resp.webp
  web/public/empty-state/intake/intake-dark.webp
  web/public/empty-state/intake/intake-issue-dark.webp
  web/public/empty-state/intake/intake-issue-light.webp
  web/public/empty-state/intake/intake-light-resp.webp
  web/public/empty-state/intake/intake-light.webp
  web/public/empty-state/intake/issue-detail-dark.webp
  web/public/empty-state/intake/issue-detail-light.webp
Labels: 🌐frontend, 🧹chore

#5130 [WEB-1962] fix: disabled custom menu
  packages/ui/src/dropdowns/custom-menu.tsx
  web/package.json
Labels: 🐛bug, 🌐frontend

#5131 [WEB-1937] fix: issue detail widgets permission validation
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail-widgets/attachments/title.tsx
  web/core/components/issues/issue-detail-widgets/links/title.tsx
  web/core/components/issues/issue-detail-widgets/relations/title.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/issue-detail-widgets/widget-button.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5138 [WEB-1952] fix: issues export project select dropdown
  web/core/components/exporter/export-modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5141 [WEB-1951] fix: spreadsheet layout issue quick action event propagation
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5143 [WEB-1730] chore: project intake toast and activity message
  web/core/components/core/activity.tsx
  web/core/components/inbox/modals/create-edit-modal/create-root.tsx
  web/core/components/inbox/modals/delete-issue-modal.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/inbox.tsx
  web/core/store/inbox/project-inbox.store.ts
Labels: 🌐frontend, 🧹chore

#5152 [WEB-1984] fix: code block padding and margin in pages.
  packages/editor/src/core/extensions/code-inline/index.tsx
  packages/editor/src/core/extensions/code/code-block-node-view.tsx
  web/ee/components/issues/activity/root.tsx
  web/ee/components/issues/activity/worklog-create-button.tsx
  web/ee/components/issues/index.ts
  web/ee/components/issues/properties/root.tsx
  web/ee/components/issues/worklog/activity/index.ts
  web/ee/components/issues/worklog/activity/root.tsx
  web/ee/components/issues/worklog/activity/worklog-create-button.tsx
  web/ee/components/issues/worklog/index.ts
  web/ee/components/issues/worklog/property/index.ts
  web/ee/components/issues/worklog/property/root.tsx
  web/ee/issues/index.ts
  web/ee/issues/worklog/activity/index.ts
  web/ee/issues/worklog/property/index.ts
Labels: 🌐frontend, 🎨UI / UX

#5149 [WEB-1960]: chore: upgrade to plane paid plans modal.
  packages/ui/src/modals/constants.ts
  packages/ui/src/modals/modal-core.tsx
  turbo.json
  web/ce/components/workspace/edition-badge.tsx
  web/ce/components/workspace/upgrade/index.tsx
  web/ce/components/workspace/upgrade/one-plan-upgrade.tsx
  web/ce/components/workspace/upgrade/paid-plans-upgrade-modal.tsx
  web/ce/components/workspace/upgrade/pro-plan-upgrade.tsx
  web/core/hooks/use-app-router.tsx
Labels: 🌐frontend, 🌟improvement

#5153 [WEB-1981] chore: project view icon and empty state
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/ce/constants/project/settings/features.tsx
  web/core/components/command-palette/actions/project-actions.tsx
  web/core/components/command-palette/helpers.tsx
  web/core/components/onboarding/tour/sidebar.tsx
  web/core/components/views/form.tsx
  web/core/components/views/view-list-item.tsx
  web/core/components/views/views-list.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/constants/empty-state.ts
  web/public/empty-state/disabled-feature/views-dark.webp
  web/public/empty-state/disabled-feature/views-light.webp
  web/public/empty-state/onboarding/views-dark.webp
  web/public/empty-state/onboarding/views-light.webp
  web/public/empty-state/search/views-dark.webp
  web/public/empty-state/search/views-light.webp
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5137 [WEB-1799] fix: page breadcrumb tooltip persistence
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
Labels: 🐛bug, 🌐frontend

#5158 [WEB-1910] fix: disable selection if no issues are present
  web/core/components/issues/issue-layouts/list/headers/group-by-card.tsx
Labels: 🐛bug, 🌐frontend

#5160 [WEB-1918]: Fix/sidebar button issue
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#5161 [WEB-1920] fix: project intake disabled validation
  web/core/components/workspace/sidebar/projects-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5170 [WEB-1995] fix: searched page redirection from command palette.
  web/core/components/command-palette/actions/search-results.tsx
  web/core/components/command-palette/helpers.tsx
Labels: 🐛bug, 🌐frontend

#5172 [WEB-2000] fix: issue link edit modal and mutation fix
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/links/link-detail.tsx
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement

#5173 [WEB-2004] fix: empty issue title indicator
  web/core/components/issues/title-input.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5133 [WEB-1877] fix: editor history(undo/redo) not working for issue descriptions and comments
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
Labels: 🐛bug, 🌐frontend, ✍️editor

#5168 [WEB - 1998] fix: profile creation on user signup
  apiserver/plane/authentication/utils/redirection_path.py
  apiserver/plane/authentication/views/app/magic.py
Labels: 🐛bug, ⚙️backend

#5171 [WEB-1997] chore: changed the table name of workspace user property model
  apiserver/plane/db/migrations/0052_auto_20231220_1141.py
Labels: ⚙️backend, 🌟improvement

#5154 [WEB-1985] chore: page access control
  apiserver/plane/app/urls/page.py
  apiserver/plane/app/views/page/base.py
  web/core/services/page/project-page.service.ts
  web/core/store/pages/page.ts
Labels: 🌐frontend, ⚙️backend, 🌟improvement, 🧹chore

#5132 [WEB-1693] chore: added details in cycle detail endpoint
  apiserver/plane/app/views/cycle/base.py
Labels: ⚙️backend, 🌟improvement

#5175 [WEB-1968] fix: leave project mutation
  web/core/store/user/user-membership.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5184 [WEB-1982] chore: sidebar navigation item refactor
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/sidebar.tsx
  web/app/[workspaceSlug]/(projects)/settings/sidebar.tsx
  web/app/profile/sidebar.tsx
  web/core/components/cycles/analytics-sidebar/root.tsx
  web/core/components/cycles/cycle-peek-overview.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
  web/core/components/modules/module-peek-overview.tsx
Labels: 🌐frontend, 🧹chore

#5174 [WEB-1967] chore: issue load more button improvement
  web/core/components/issues/issue-layouts/list/list-group.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#5135 [WEB-1797] chore: add missing headings to the rich text editor
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/slash-commands.tsx
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/slash-commands-suggestion.ts
  space/core/components/editor/toolbar.tsx
  space/core/constants/editor.ts
  web/core/components/editor/lite-text-editor/toolbar.tsx
  web/core/components/pages/editor/header/toolbar.tsx
  web/core/constants/editor.ts
Labels: 🌐frontend, 🌟improvement, ✍️editor

#5187 [WEB-1550] fix: editor focus after mentioning a user
  packages/editor/src/core/extensions/mentions/mentions-list.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5182 [WEB-1255] chore: advance views queryset change
  apiserver/plane/space/urls/inbox.py
  apiserver/plane/space/urls/issue.py
  apiserver/plane/space/views/issue.py
Labels: ⚙️backend

#5186 [WEB-2020] chore: display cross project issue relations
  apiserver/plane/app/views/issue/relation.py
Labels: ⚙️backend, 🌟improvement

#5179 [WEB-2011] chore: export history filters
  apiserver/plane/app/views/exporter/base.py
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend

#5189 [WEB-1992] fix: calendar layout issue mutation and code refactor
  web/core/components/issues/issue-layouts/calendar/calendar.tsx
  web/core/components/issues/issue-layouts/calendar/day-tile.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block-root.tsx
  web/core/components/issues/issue-layouts/calendar/issue-blocks.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5195 [WEB-2023] chore: sidebar content update
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/constants/dashboard.ts
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#5205 [WEB-1988] fix: archived issue detail widget validation
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5204 [WEB-2012] fix: add project button alignment
  web/core/components/workspace/sidebar/projects-list.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5197 [WEB-1833] fix: editor bold text color
  packages/tailwind-config-custom/tailwind.config.js
Labels: 🐛bug, 🌐frontend, ✍️editor

#5193 feat: added external api endpoints for creating users and adding attachments to issues
  apiserver/plane/api/urls/__init__.py
  apiserver/plane/api/urls/issue.py
  apiserver/plane/api/urls/member.py
  apiserver/plane/api/views/__init__.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/member.py
  apiserver/plane/db/migrations/0072_issueattachment_external_id_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/recent_visit.py
Labels: ⚙️backend

#5209 [WEB-2025] chore: profile page enhancements
  packages/types/src/issues/issue.d.ts
  web/app/[workspaceSlug]/(projects)/profile/[userId]/header.tsx
  web/app/[workspaceSlug]/(projects)/profile/[userId]/layout.tsx
  web/app/[workspaceSlug]/(projects)/profile/[userId]/navbar.tsx
  web/core/components/profile/sidebar.tsx
  web/core/components/workspace/sidebar/user-menu.tsx
  web/core/constants/dashboard.ts
  web/core/constants/profile.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5219 [WEB-2039] chore: issue parent type
  packages/types/src/issues/issue.d.ts
  web/core/hooks/use-group-dragndrop.ts
  web/helpers/issue.helper.ts
Labels: 🐛bug, 🌐frontend

#5220 [WEB-2031] fix: display update view button even when any filters are not applied for views
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
Labels: 🐛bug, 🌐frontend

#5218 [WEB-1973] fix: Gantt layout in project views
  web/core/components/issues/issue-layouts/roots/project-view-layout-root.tsx
Labels: 🐛bug, 🌐frontend

#5222 [WEB-2008] fix: issue reactions in space app
  space/core/store/issue-detail.store.ts
Labels: 🐛bug, 🌐frontend

#5224 [WEB-2053] fix: my work page scroll
  web/app/[workspaceSlug]/(projects)/profile/[userId]/layout.tsx
  web/core/components/profile/sidebar.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5223 [WEB-2042] fix: project publish issue loader and error handling
  space/app/issues/[anchor]/layout.tsx
  space/core/components/issues/issue-layouts/error.tsx
  space/core/components/issues/issue-layouts/root.tsx
Labels: 🐛bug, 🌐frontend

#5227 [WEB-2059] chore: Add live button on views
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/helpers/project-views.helpers.ts
Labels: 🌐frontend

#5225 [WEB-2041] fix: view layout in space app
  space/app/views/[anchor]/layout.tsx
Labels: 🐛bug, 🌐frontend

#5231 [WEB-2043] chore: updated permissions for delete operation
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/inbox.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/view/base.py
Labels: ⚙️backend

#5230 [WEB-1762] fix: incorrectly placed image resize outline
  packages/editor/src/core/extensions/image/image-resize.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5236 [WEB-2055] fix: enable admins to change role of other admins and add missing observers
  web/core/components/project/settings/member-columns.tsx
  web/core/components/workspace/settings/member-columns.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5242 [WEB-1756] fix: unable to create new todo-list item in the lite-text editor
  packages/editor/src/core/extensions/enter-key-extension.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5240 [WEB-2013] fix: issue link modal preloading previous data
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5239 [WEB-2035] fix: checkbox color on inbox page filters
  web/core/components/workspace-notifications/sidebar/filters/menu/menu-option-item.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5237 [WEB-2038] fix: error message for display name in profile settings
  web/app/profile/page.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5232 [WEB-2054] fix: kanban layout loader enhancements and issue count alignment
  web/core/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/core/components/ui/loader/layouts/kanban-layout-loader.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5246 [WEB-1971] fix: remove issue from cycle while changing cycle
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🐛bug, 🌐frontend

#5244 [WEB-2092] chore: soft delete operation
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/bgtasks/deletion_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/celery.py
  apiserver/plane/db/migrations/0073_analyticview_deleted_at_apiactivitylog_deleted_at_and_more.py
  apiserver/plane/db/mixins.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/view.py
  apiserver/plane/license/migrations/0004_changelog_deleted_at_instance_deleted_at_and_more.py
Labels: ⚙️backend, 🔄migrations

#5241 [WEB-2026] fix: avatar visibility on project list after user leaves project
  web/core/store/user/user-membership.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5253 [WEB-2090] chore: load more button
  web/core/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5254 [WEB-2043] fix: delete action validation and toast alert
  web/core/components/command-palette/command-palette.tsx
  web/core/components/cycles/delete-modal.tsx
  web/core/components/inbox/modals/delete-issue-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/modules/delete-module-modal.tsx
  web/core/constants/project.ts
  web/core/store/inbox/project-inbox.store.ts
  web/core/store/user/index.ts
Labels: 🌐frontend, 🧹chore

#5256 [WEB-2091] fix: profile issue layout
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/profile-issues-root.tsx
  web/core/components/profile/profile-issues.tsx
Labels: 🌐frontend, 🧹chore

#5261 [WEB-2099] fix: modules and cycle peek views toggle
  web/core/components/cycles/board/cycles-board-card.tsx
  web/core/components/cycles/list/cycles-list-item.tsx
  web/core/components/modules/module-card-item.tsx
  web/core/components/modules/module-list-item.tsx
Labels: 🐛bug, 🌐frontend

#5263 [WEB-2110] fix: broken link while trying to copy page link
  web/core/components/pages/editor/header/options-dropdown.tsx
Labels: 🐛bug, 🌐frontend

#5265 [WEB-2066] fix: completed cycle date picker validation
  web/core/components/cycles/analytics-sidebar/root.tsx
Labels: 🐛bug, 🌐frontend

#5233 [WEB-1974] fix: images getting replaced on resize
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/document/read-only-editor.tsx
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/components/editors/editor-content.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/read-only-editor-wrapper.tsx
  packages/editor/src/core/extensions/image/image-resize.tsx
  packages/editor/src/core/extensions/mentions/extension.tsx
  packages/editor/src/core/extensions/slash-commands.tsx
  packages/editor/src/core/types/editor.ts
  space/core/components/issues/peek-overview/comment/add-comment.tsx
  space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/core/components/issues/peek-overview/issue-details.tsx
  web/core/components/core/modals/gpt-assistant-popover.tsx
  web/core/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/core/components/issues/description-input.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/profile/activity/activity-list.tsx
  web/core/components/profile/activity/profile-activity-list.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5264 chore: deploy board publish validation
  apiserver/plane/space/views/project.py
Labels: ⚙️backend

#5258 chore: only admin can perform bulk delete operation
  apiserver/plane/app/views/issue/base.py
Labels: ⚙️backend

#5272 [WEB-2102] feat: Block level reactions for Kanban layout in Space App
  space/core/components/issues/issue-layouts/kanban/block-reactions.tsx
  space/core/components/issues/issue-layouts/kanban/block.tsx
  space/core/components/issues/peek-overview/index.ts
  space/core/components/issues/peek-overview/issue-reaction.tsx
  space/core/components/issues/reactions/index.ts
  space/core/components/issues/reactions/issue-emoji-reactions.tsx
  space/core/components/issues/reactions/issue-vote-reactions.tsx
Labels: 🌟enhancement, 🌐frontend

#5267 [WEB-2087] fix: pages full width toggle seems laggy
  web/core/components/pages/editor/editor-body.tsx
Labels: 🌐frontend, 🎨UI / UX

#5269 [WEB-2101] fix: Visibility of empty Grouping in Kanban for Space views
  space/core/components/issues/issue-layouts/kanban/default.tsx
Labels: 🐛bug, 🌐frontend

#5268 [WEB-2066] fix: workspace export settings mutation
  web/core/components/exporter/guide.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5255 [WEB-2092] chore: changed the hard delete days
  apiserver/.env.example
  apiserver/plane/app/views/issue/archive.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/bgtasks/deletion_task.py
  apiserver/plane/settings/common.py
Labels: ⚙️backend

#5270 [WEB-1671] fix: expired snooze issues fixed
  web/core/components/inbox/inbox-issue-status.tsx
  web/core/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌐frontend

#5276 [WEB-2130] chore: list layout responsiveness improvement
  web/core/components/core/list/list-item.tsx
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/list/cycles-list-item.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/modules/module-list-item-action.tsx
  web/core/components/modules/module-list-item.tsx
  web/core/components/views/view-list-item-action.tsx
  web/core/components/views/view-list-item.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#5278 [WEB-2140] fix: member setting role edit validation
  web/core/components/project/settings/member-columns.tsx
  web/core/components/workspace/settings/member-columns.tsx
Labels: 🐛bug, 🌐frontend
