Repository makeplane/plane, pull requests merged in 2024-12, with the labels that each got.

#6131 [WEB-2799] chore: global component and code refactor
  packages/helpers/hooks/index.ts
  packages/helpers/hooks/use-local-storage.tsx
  packages/ui/src/collapsible/collapsible-button.tsx
  packages/ui/src/icons/comment-fill-icon.tsx
  packages/ui/src/icons/epic-icon.tsx
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/info-fill-icon.tsx
  packages/ui/src/index.ts
  packages/ui/src/progress/linear-progress-indicator.tsx
  packages/ui/src/tabs/index.ts
  packages/ui/src/tabs/tabs.tsx
Labels: 🌐frontend, 🧹chore

#5992 [WEB-2762] chore: loader code refactor
  packages/ui/src/dropdown/common/loader.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/sidebar.tsx
  web/core/components/dashboard/widgets/loaders/issues-by-state-group.tsx
  web/core/components/dashboard/widgets/loaders/overview-stats.tsx
  web/core/components/dashboard/widgets/loaders/recent-activity.tsx
  web/core/components/dashboard/widgets/loaders/recent-collaborators.tsx
  web/core/components/dashboard/widgets/loaders/recent-projects.tsx
  web/core/components/issues/workspace-draft/loader.tsx
  web/core/components/pages/loaders/page-loader.tsx
  web/core/components/ui/loader/cycle-module-board-loader.tsx
  web/core/components/ui/loader/cycle-module-list-loader.tsx
  web/core/components/ui/loader/layouts/calendar-layout-loader.tsx
  web/core/components/ui/loader/layouts/gantt-layout-loader.tsx
  web/core/components/ui/loader/layouts/kanban-layout-loader.tsx
  web/core/components/ui/loader/layouts/list-layout-loader.tsx
  web/core/components/ui/loader/layouts/members-layout-loader.tsx
  web/core/components/ui/loader/layouts/project-inbox/inbox-sidebar-loader.tsx
  web/core/components/ui/loader/layouts/spreadsheet-layout-loader.tsx
  web/core/components/ui/loader/notification-loader.tsx
  web/core/components/ui/loader/pages-loader.tsx
  web/core/components/ui/loader/projects-loader.tsx
  web/core/components/ui/loader/settings/activity.tsx
  web/core/components/ui/loader/settings/api-token.tsx
  web/core/components/ui/loader/settings/email.tsx
  web/core/components/ui/loader/settings/import-and-export.tsx
  web/core/components/ui/loader/settings/integration.tsx
  web/core/components/ui/loader/settings/members.tsx
  web/core/components/ui/loader/view-list-loader.tsx
  web/core/components/web-hooks/form/secret-key.tsx
  web/core/components/workspace-notifications/sidebar/loader.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#6119 [WEB-2774]fix:reordering favorites and favorite folders
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/favorites/favorites.helpers.ts
  web/core/store/favorite.store.ts
Labels: 🐛bug, 🌐frontend

#6110 [WEB-2382]chore:notifications file rearranging
  web/app/[workspaceSlug]/(projects)/notifications/layout.tsx
  web/ce/components/workspace-notifications/index.ts
  web/ce/components/workspace-notifications/root.tsx
  web/core/components/workspace-notifications/sidebar/index.ts
  web/ee/components/workspace-notifications/root.tsx
Labels: 🌟enhancement, 🌐frontend

#6096 [PE-80] fix: escape markdown content for images
  packages/editor/src/core/extensions/custom-image/custom-image.ts
  packages/editor/src/core/extensions/custom-image/read-only-custom-image.ts
Labels: 🐛bug, 🌐frontend, pages

#6113 fix: todo list item color when item is checked and custom color is applied
  packages/editor/src/styles/editor.css
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, ✍️editor

#6102 refactor: editor code splitting
  packages/editor/src/ce/extensions/core/extensions.ts
  packages/editor/src/ce/extensions/core/index.ts
  packages/editor/src/ce/extensions/core/read-only-extensions.ts
  packages/editor/src/ce/extensions/core/without-props.ts
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/ce/extensions/index.ts
  packages/editor/src/ce/extensions/slash-commands.tsx
  packages/editor/src/core/components/editors/document/collaborative-read-only-editor.tsx
  packages/editor/src/core/components/editors/document/read-only-editor.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/read-only-editor-wrapper.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/slash-commands/command-items-list.tsx
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/collaboration.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/extensions.ts
  packages/editor/src/core/types/slash-commands-suggestion.ts
  space/core/components/editor/lite-text-editor.tsx
  space/core/components/editor/lite-text-read-only-editor.tsx
  space/core/components/editor/rich-text-editor.tsx
  space/core/components/editor/rich-text-read-only-editor.tsx
  web/ce/hooks/use-editor-flagging.ts
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/editor/lite-text-editor/lite-text-read-only-editor.tsx
  web/core/components/editor/rich-text-editor/rich-text-editor.tsx
  web/core/components/editor/rich-text-editor/rich-text-read-only-editor.tsx
  web/core/components/global/product-updates/modal.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/version/editor.tsx
Labels: 🌐frontend, 🛠️refactor, ✍️editor

#6094 dev: revamp pages authorization
  apiserver/plane/app/views/page/base.py
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/core/store/pages/page.ts
  web/core/store/pages/project-page.store.ts
Labels: 🌐frontend, ⚙️backend, pages

#5629 [PE-31] feat: Add lock unlock archive restore realtime sync
  live/src/core/hocuspocus-server.ts
  packages/editor/src/core/constants/document-collaborative-events.ts
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/image-node.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu.tsx
  packages/editor/src/core/helpers/get-document-server-event.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/document-collaborative-events.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/index.ts
  packages/editor/src/lib.ts
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/type.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/hooks/use-collaborative-page-actions.tsx
  web/core/store/pages/page.ts
Labels: ✍️editor

#6135 [WEB-2803] fix: Timeline chart half block dragging
  web/ce/store/timeline/base-timeline.store.ts
  web/core/components/gantt-chart/helpers/blockResizables/use-gantt-resizable.ts
  web/core/components/gantt-chart/views/helpers.ts
Labels: 🐛bug, 🌐frontend

#6136 [WEB-2759] fix: intake issue permission
  web/core/components/inbox/content/root.tsx
Labels: 🌐frontend, 🧹chore

#6133 [WEB-2802]fix:filters drop down fix safari
  web/core/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
Labels: 🐛bug, 🌐frontend

#6141 fix: pages empty state authorization
  web/core/constants/empty-state.ts
Labels: 🐛bug, 🌐frontend

#6143 style: add custom class to editor paragraph and heading blocks
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/styles/editor.css
Labels: 🌐frontend, 🎨UI / UX, ✍️editor

#6147 [WEB-2807] fix: Root issue store to have updated url params at all times
  web/core/store/issue/root.store.ts
Labels: 🐛bug, 🌐frontend

#6151 [WEB-2802]fix: dorpdown visibility issue in safari
  packages/ui/src/dropdowns/custom-menu.tsx
Labels: 🐛bug, 🌐frontend

#6156 chore: refactor project states to make way for new features
  packages/ui/src/tooltip/tooltip.tsx
  web/ce/components/workflow/add-state-transition.tsx
  web/ce/components/workflow/index.tsx
  web/ce/components/workflow/state-item-child.tsx
  web/ce/components/workflow/state-option.tsx
  web/ce/components/workflow/state-transition-count.tsx
  web/ce/components/workflow/use-workflow-drag-n-drop.ts
  web/ce/components/workflow/workflow-disabled-message.tsx
  web/ce/components/workflow/workflow-group-tree.tsx
  web/ce/services/index.ts
  web/ce/services/project/project-state.service.ts
  web/ce/store/state.store.ts
  web/ce/types/index.ts
  web/ce/types/state.d.ts
  web/core/components/dropdowns/state.tsx
  web/core/components/issues/issue-layouts/group-drag-overlay.tsx
  web/core/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/core/components/issues/issue-layouts/kanban/headers/sub-group-by-card.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/core/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/project-states/index.ts
  web/core/components/project-states/root.tsx
  web/core/components/project-states/state-item-title.tsx
  web/core/components/project-states/state-item.tsx
  web/core/hooks/store/use-project-state.ts
  web/core/layouts/auth-layout/project-wrapper.tsx
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/issue-details/sub_issues.store.ts
  web/core/store/issue/root.store.ts
  web/core/store/root.store.ts
  web/core/store/state.store.ts
  web/ee/components/workflow/index.ts
  web/ee/services/project/project-state.service.ts
  web/ee/store/state.store.ts
  web/ee/types/index.ts
  web/helpers/array.helper.ts
Labels: 🌐frontend, 🧹chore

#6161 chore: Remove Unnecessary CTA
  web/ce/components/workflow/state-item-child.tsx
  web/core/constants/state.ts
Labels: 🧹chore

#6164 [WEB-2382]chore:notification snooze modal
  web/app/[workspaceSlug]/(projects)/notifications/layout.tsx
  web/ce/components/workspace-notifications/root.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/options/snooze/modal.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/options/snooze/root.tsx
  web/core/store/notifications/workspace-notifications.store.ts
  web/ee/components/workspace-notifications/index.ts
  web/ee/components/workspace-notifications/root.tsx
Labels: 🌟enhancement, 🌐frontend

#6168 fix: email check validation to handle case in-sensitive email
  apiserver/plane/authentication/views/app/check.py
  apiserver/plane/authentication/views/space/check.py
Labels: 🐛bug

#6169 [WEB-2817] fix: creating a new sub-issue from workspace level
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
Labels: 🐛bug, 🌐frontend

#6170 [WEB-2818] chore: project navigation items code refactor
  web/ce/components/sidebar/index.ts
  web/ce/components/sidebar/project-navigation-root.tsx
  web/core/components/workspace/sidebar/index.ts
  web/core/components/workspace/sidebar/project-navigation.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/local-db/utils/load-workspace.ts
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#6171 [WEB-2809] chore: changed the soft deletion logic
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/bgtasks/deletion_task.py
  apiserver/plane/db/models/__init__.py
Labels: ⚙️backend

#6180 [WEB-2836] chore: workspace draft and project issue local db mutation
  web/core/store/inbox/inbox-issue.store.ts
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🌐frontend, 🧹chore

#6181 [WEB-2382]chore:notification files restructuring
  packages/types/src/workspace-notifications.d.ts
  web/app/[workspaceSlug]/(projects)/notifications/layout.tsx
  web/ce/components/workspace-notifications/index.ts
  web/ce/components/workspace-notifications/notification-card/root.tsx
  web/core/components/workspace-notifications/index.ts
  web/core/components/workspace-notifications/root.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/index.ts
  web/core/store/notifications/notification.ts
Labels: 🌐frontend, 🧹chore

#6179 [WEB-2774] fix:favorites reorder
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/root.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/store/favorite.store.ts
Labels: 🐛bug, 🌐frontend

#6185 [WEB-2753]fix: intake issue activity
  web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
Labels: 🐛bug, 🌐frontend

#6193 fix: GitHub casing across the platform
  admin/app/authentication/github/page.tsx
  admin/core/components/auth-header.tsx
  app.json
  web/core/components/integration/github/root.tsx
  web/core/constants/event-tracker.ts
Labels: 🌐frontend, 🌟improvement

#6205 feat: add language support
  apiserver/plane/db/migrations/0087_remove_issueversion_description_and_more.py
  apiserver/plane/db/models/user.py
Labels: ⚙️backend, 🔄migrations

#6162 chore: Check github releases for upgrades
  deploy/selfhost/README.md
  deploy/selfhost/install.sh
Labels: 🏠self-hosted

#5575 fix: separated docker compose environment variables
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: 🏠self-hosted

#6200 [WEB-2769]fix: transfer cycles mutation issue
  web/core/store/issue/cycle/issue.store.ts
Labels: 🐛bug, 🌐frontend

#6211 [WEB-2678]feat: added functionality to add labels directly from dropdown
  web/core/components/issues/issue-detail/label/root.tsx
  web/core/components/issues/issue-detail/label/select/label-select.tsx
  web/core/components/issues/issue-detail/label/select/root.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#6216 [WEB-2678]fix: create labels empty state
  web/core/components/issues/issue-detail/label/select/label-select.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
Labels: 🐛bug, 🌐frontend

#6217 [PE-94] refactor: remove `cn` helper function from the editor package
  packages/editor/package.json
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/components/menus/ai-menu.tsx
  packages/editor/src/core/components/menus/bubble-menu/alignment-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/link-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/node-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
  packages/editor/src/core/extensions/callout/color-selector.tsx
  packages/editor/src/core/extensions/callout/logo-selector.tsx
  packages/editor/src/core/extensions/code/code-block-node-view.tsx
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/root.tsx
  packages/editor/src/core/extensions/mentions/mention-node-view.tsx
  packages/editor/src/core/extensions/mentions/mentions-list.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu-item.tsx
  packages/editor/src/core/helpers/common.ts
  packages/editor/src/core/props/props.tsx
  packages/editor/src/core/props/read-only.tsx
  packages/utils/package.json
  packages/utils/src/common.ts
  packages/utils/src/index.ts
  space/core/components/issues/issue-layouts/kanban/block-reactions.tsx
  space/core/components/issues/issue-layouts/kanban/block.tsx
  space/core/components/issues/issue-layouts/list/block.tsx
  space/core/components/issues/issue-layouts/list/list-group.tsx
  space/core/components/issues/issue-layouts/properties/all-properties.tsx
  space/core/components/issues/issue-layouts/properties/cycle.tsx
  space/core/components/issues/issue-layouts/properties/member.tsx
  space/core/components/issues/issue-layouts/properties/modules.tsx
  space/core/components/issues/issue-layouts/properties/state.tsx
  web/ce/components/workflow/add-state-transition.tsx
  web/core/components/common/access-field.tsx
  web/core/components/dropdowns/layout.tsx
  web/core/components/dropdowns/member/avatar.tsx
  web/core/components/gantt-chart/chart/views/quarter.tsx
  web/core/components/gantt-chart/chart/views/week.tsx
  web/core/components/gantt-chart/helpers/blockResizables/left-resizable.tsx
  web/core/components/gantt-chart/helpers/blockResizables/right-resizable.tsx
  web/core/components/inbox/inbox-filter/root.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/modules/module-view-header.tsx
  web/core/components/project/create/common-attributes.tsx
  web/core/components/project/filters.tsx
  web/core/components/ui/loader/layouts/kanban-layout-loader.tsx
  web/core/components/ui/loader/layouts/list-layout-loader.tsx
  web/core/components/workspace/logo.tsx
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#6209 [PE-92] fix: removing readonly collaborative document editor
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/collaborative-read-only-editor.tsx
  packages/editor/src/core/components/editors/document/index.ts
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/extensions/drop.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-file-upload.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
  packages/editor/src/core/types/collaboration.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/index.ts
  packages/editor/src/styles/editor.css
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/info-popover.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/editor/summary/content-browser.tsx
  web/core/components/pages/editor/summary/popover.tsx
  web/core/components/pages/modals/export-page-modal.tsx
  web/core/hooks/use-collaborative-page-actions.tsx
Labels: pages

#6219 chore: gif image support for all editors
  apiserver/plane/app/views/asset/v2.py
  apiserver/plane/space/views/asset.py
  packages/editor/src/core/constants/config.ts
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/plugins/image/utils/validate-file.ts
Labels: 🌐frontend, ✍️editor

#6227 [WEB-2808] chore: remove workspace-level toggle from parent select modal
  web/core/components/issues/parent-issues-list-modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6230 [WEB-2878]fix: draft creation
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/modules/module-view-header.tsx
Labels: 🐛bug, 🌐frontend

#6232 [WEB-2859]chore: sub issue list optimization
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
Labels: 🌟enhancement, 🌐frontend

#6242 [PE-98] fix: page title fixed height
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/title.tsx
Labels: 🐛bug, 🌐frontend, pages

#6241 fix: issue serializer to remove deleted labels and assignees
  apiserver/plane/api/serializers/issue.py
Labels: 🐛bug, ⚙️backend

#6249 [PE-93] refactor: accept generic function to search mentions
  web/core/components/editor/rich-text-editor/rich-text-editor.tsx
  web/core/components/inbox/modals/create-modal/issue-description.tsx
  web/core/components/issues/description-input.tsx
  web/core/components/issues/issue-modal/components/description-editor.tsx
Labels: 🌐frontend

#6255 chore: common services package
  packages/constants/src/ai.ts
  packages/constants/src/endpoints.ts
  packages/constants/src/index.ts
  packages/eslint-config/library.js
  packages/services/.eslintignore
  packages/services/.eslintrc.js
  packages/services/.prettierrc
  packages/services/package.json
  packages/services/src/ai/ai.service.ts
  packages/services/src/ai/index.ts
  packages/services/src/analytics/analytics.service.ts
  packages/services/src/analytics/index.ts
  packages/services/src/api.service.ts
  packages/services/src/auth/auth.service.ts
  packages/services/src/auth/index.ts
  packages/services/src/cycle/cycle-analytics.service.ts
  packages/services/src/cycle/cycle-archive.service.ts
  packages/services/src/cycle/cycle-operations.service.ts
  packages/services/src/cycle/cycle.service.ts
  packages/services/src/cycle/index.ts
  packages/services/src/dashboard/dashboard.service.ts
  packages/services/src/dashboard/index.ts
  packages/services/src/developer/api-token.service.ts
  packages/services/src/developer/index.ts
  packages/services/src/developer/webhook.service.ts
  packages/services/src/index.ts
  packages/services/src/instance/index.ts
  packages/services/src/instance/instance.service.ts
  packages/services/src/intake/index.ts
  packages/services/src/intake/intake.service.ts
  packages/services/src/intake/issue.service.ts
  packages/services/src/live.service.ts
  packages/services/src/module/index.ts
  packages/services/src/module/link.service.ts
  packages/services/src/module/module.service.ts
  packages/services/src/module/operations.service.ts
  packages/services/src/project/index.ts
  packages/services/src/project/view.service.ts
  packages/services/src/user/favorite.service.ts
  packages/services/src/user/index.ts
  packages/services/src/workspace/index.ts
  packages/services/src/workspace/invitation.service.ts
  packages/services/src/workspace/member.service.ts
  packages/services/src/workspace/notification.service.ts
  packages/services/src/workspace/view.service.ts
  packages/services/src/workspace/workspace.service.ts
  packages/services/tsconfig.json
Labels: 🛠️refactor

#6258 [PE-93] regression: mention users highlight color, reomve bot users from search list
  apiserver/plane/app/views/search/base.py
  space/core/components/editor/embeds/mentions/user.tsx
  web/core/components/editor/embeds/mentions/user.tsx
Labels: 🐛bug, 🌐frontend, ⚙️backend

#6259 [WEB-2859] fix: sub-issue collapsible visibility
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
Labels: 🐛bug, 🌐frontend

#6265 [PE-93] regression: issue mentions and subscribers logic
  apiserver/plane/bgtasks/notification_task.py
Labels: 🐛bug, ⚙️backend

#6267 [WEB-2830]fix: create view modal - layout drop down close
  packages/ui/src/dropdown/single-select.tsx
Labels: 🐛bug, 🌐frontend

#6253 [WEB-1412]fix: split labels in kanban board
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/properties/index.ts
  web/core/components/issues/issue-layouts/properties/label-dropdown.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/core/components/issues/workspace-draft/draft-issue-properties.tsx
Labels: 🐛bug, 🌟enhancement

#6270 [WEB-2903] fix: active cycle update payload
  web/core/components/cycles/modal.tsx
Labels: 🐛bug, 🌐frontend

#6274 chore: quick link migration
  apiserver/plane/db/migrations/0088_sticky_sort_order_workspaceuserlink.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/sticky.py
  apiserver/plane/db/models/workspace.py
Labels: ⚙️backend, 🔄migrations

#6271 [WEB-2879]fix: label creation
  web/core/components/issues/issue-detail/label/select/label-select.tsx
Labels: 🐛bug, 🌐frontend

#6273 [WEB-2699]chore: added issue count for upcoming cycles
  web/core/components/cycles/list/cycle-list-item-action.tsx
Labels: 🌟enhancement, 🌐frontend

#6257 chore: create unique constraints for webhook
  apiserver/plane/app/serializers/webhook.py
  apiserver/plane/db/migrations/0088_sticky_sort_order_workspaceuserlink.py
  apiserver/plane/db/models/webhook.py
Labels: ⚙️backend, 🔄migrations

#6278 [WEB-2857]fix: updating user role in profile
  web/app/profile/page.tsx
Labels: 🐛bug, 🌐frontend

#6279 [WEB-2907] chore: issue store updated and code refactor
  web/ce/components/issues/quick-add/root.tsx
  web/ce/store/issue/issue-details/activity.store.ts
  web/core/components/issues/create-issue-toast-action-items.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-actions.tsx
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/list/default.tsx
  web/core/components/issues/issue-layouts/quick-add/form/calendar.tsx
  web/core/components/issues/issue-layouts/quick-add/form/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/form/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/form/list.tsx
  web/core/components/issues/issue-layouts/quick-add/form/spreadsheet.tsx
  web/core/components/issues/issue-layouts/quick-add/root.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/hooks/store/use-issue-detail.ts
  web/core/store/issue/issue.store.ts
  web/core/store/issue/root.store.ts
  web/core/store/root.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#6281 [WEB-2880] chore: project detail response updated
  packages/types/src/project/projects.d.ts
  web/core/components/dropdowns/project.tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#6284 [WEB-2912]chore: modified link behaviour to improve accessibility
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/components/modules/links/list-item.tsx
Labels: 🌟enhancement, 🌐frontend

#6285 chore: code refactor and build fix
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/filters.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/issue-detail/issue-activity/sort-root.tsx
  web/core/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/core/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/issue-grouping.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/group-drag-overlay.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/quick-add/button/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/button/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/button/list.tsx
  web/core/components/issues/issue-layouts/quick-add/button/spreadsheet.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/core/components/issues/parent-issues-list-modal.tsx
  web/core/components/issues/sub-issues/issues-list.tsx
  web/core/constants/empty-state.ts
  web/core/constants/issue.ts
  web/core/services/issue/issue.service.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/issue-details/sub_issues.store.ts
Labels: 🌐frontend, 🛠️refactor

#6283 [PE-182] refactor: pages' components and store for scalability
  packages/editor/src/core/types/editor.ts
  packages/types/src/pages.d.ts
  packages/types/src/search.d.ts
  packages/utils/src/editor.ts
  packages/utils/src/index.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/page.tsx
  web/ce/components/pages/editor/ai/ask-pi-menu.tsx
  web/ce/components/pages/editor/ai/menu.tsx
  web/ce/components/pages/extra-actions.tsx
  web/ce/hooks/use-issue-embed.tsx
  web/core/components/pages/dropdowns/edit-information-popover.tsx
  web/core/components/pages/dropdowns/quick-actions.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/editor/title.tsx
  web/core/components/pages/list/block-item-action.tsx
  web/core/components/pages/list/block.tsx
  web/core/components/pages/list/root.tsx
  web/core/components/pages/modals/delete-page-modal.tsx
  web/core/components/pages/version/editor.tsx
  web/core/hooks/store/pages/use-page.ts
  web/core/hooks/use-collaborative-page-actions.tsx
  web/core/hooks/use-favorite-item-details.tsx
  web/core/services/page/project-page.service.ts
  web/core/store/pages/base-page.ts
  web/core/store/pages/project-page.store.ts
  web/core/store/pages/project-page.ts
  web/core/store/root.store.ts
Labels: 🌐frontend, 🛠️refactor, pages

#6234 [PE-97] refactor: pages actions
  apiserver/plane/app/serializers/page.py
  apiserver/plane/app/urls/page.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/page/base.py
  packages/editor/src/core/constants/document-collaborative-events.ts
  packages/ui/src/dropdowns/context-menu/item.tsx
  packages/ui/src/dropdowns/context-menu/root.tsx
  packages/ui/src/dropdowns/custom-menu.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/ce/components/pages/index.ts
  web/ce/components/pages/modals/index.ts
  web/ce/components/pages/modals/move-page-modal.tsx
  web/core/components/pages/dropdowns/actions.tsx
  web/core/components/pages/dropdowns/index.ts
  web/core/components/pages/dropdowns/quick-actions.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/list/block-item-action.tsx
  web/core/hooks/use-collaborative-page-actions.tsx
  web/core/hooks/use-page-filters.ts
  web/core/hooks/use-page-operations.ts
  web/core/services/page/project-page.service.ts
  web/core/store/pages/base-page.ts
  web/core/store/pages/project-page.store.ts
  web/core/store/pages/project-page.ts
Labels: 🌐frontend, ⚙️backend, 🛠️refactor, pages

#6289 [PE-147] chore: merge two separate page info popovers into one
  web/core/components/pages/dropdowns/edit-information-popover.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/info-popover.tsx
Labels: 🌐frontend, 🌟improvement, pages

#6291 [WEB-2935] fix: search issues endpoint
  apiserver/plane/app/views/issue/relation.py
  apiserver/plane/app/views/search/issue.py
Labels: 🐛bug
