Repository makeplane/plane, pull requests merged in 2024-09, with the labels that each got.

#5478 [WEB-2363] fix: Error while updating issue in cycles
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/module/issue.store.ts
  web/helpers/distribution-update.helper.ts
Labels: 🐛bug, 🌐frontend

#5472 [WEB-2360] fix: highlight current user on read only lite text editor
  web/core/components/editor/lite-text-editor/lite-text-read-only-editor.tsx
Labels: 🐛bug, 🌐frontend

#5471 [WEB-2348] fix: allow updating comments with just mentions in them
  space/core/components/editor/lite-text-editor.tsx
  space/helpers/string.helper.ts
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/helpers/string.helper.ts
Labels: 🐛bug, 🌐frontend

#5486 [WEB-2365] fix: Misaligned tooltips in few components
  packages/ui/src/tooltip/tooltip.tsx
  web/core/components/dropdowns/buttons.tsx
  web/core/components/dropdowns/module/index.tsx
  web/core/components/dropdowns/priority.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
Labels: 🐛bug, 🌐frontend

#5494 [WEB-2367] fix: completed cycle issue transfer
  web/core/components/cycles/transfer-issues.tsx
  web/core/components/issues/issue-layouts/roots/cycle-layout-root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5495 [ENG-37] chore: sidebar help section revamp.
  web/app/[workspaceSlug]/(projects)/header.tsx
  web/ce/components/global/index.ts
  web/ce/components/global/product-updates-modal.tsx
  web/ce/components/global/product-updates.tsx
  web/ce/components/workspace/edition-badge.tsx
  web/core/components/workspace/sidebar/help-section.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#5503 [WEB-1116] refactor: page helpers for document transformation
  live/package.json
  live/src/core/helpers/page.ts
  live/src/core/lib/authentication.ts
  live/src/core/lib/page.ts
  live/src/core/services/user.service.ts
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/types/extensions.ts
  web/ce/hooks/use-editor-flagging.ts
Labels: 🌐frontend, 🛠️refactor

#5506 fix: Development build for plane ui
  packages/ui/package.json
Labels: 🌐frontend

#5492 [WEB-2254] fix: change message for issue via link empty state
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
Labels: 🐛bug, 🌐frontend

#5508 [WEB-1116] chore: live server code splitting
  live/.babelrc
  live/package.json
  live/src/ce/lib/authentication.ts
  live/src/ce/lib/fetch-document.ts
  live/src/ce/lib/update-document.ts
  live/src/core/lib/authentication.ts
  live/src/core/lib/page.ts
  live/src/core/services/page.service.ts
  live/src/core/services/user.service.ts
  live/src/core/types/common.d.ts
  live/src/ee/lib/authentication.ts
  live/src/ee/lib/fetch-document.ts
  live/src/ee/lib/update-document.ts
  live/src/server.ts
  live/tsconfig.json
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#5502 fix: parse redis url to get hostname and port
  live/.env.example
  live/src/core/config/redis-config.ts
  live/src/server.ts
Labels: pages

#5509 [WEB-2364] fix: Issue filters persisting in user properties
  web/core/store/issue/helpers/issue-filter-helper.store.ts
Labels: 🐛bug, 🌐frontend

#5474 [WEB-2362] fix: replace svg files with newly provided webp files on the /onboarding route
  space/public/onboarding/profile-setup.svg
  web/core/components/onboarding/invite-members.tsx
  web/core/components/onboarding/profile-setup.tsx
  web/public/onboarding/invite-members-dark.svg
  web/public/onboarding/invite-members-dark.webp
  web/public/onboarding/invite-members-light.svg
  web/public/onboarding/invite-members-light.webp
  web/public/onboarding/user-personalization-dark.svg
  web/public/onboarding/user-personalization-dark.webp
  web/public/onboarding/user-personalization-light.svg
  web/public/onboarding/user-personalization-light.webp
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#5510 [WEB-1116] refactor: utility handlers
  live/src/ce/lib/authentication.ts
  live/src/ce/lib/update-document.ts
  live/src/core/lib/authentication.ts
  live/src/server.ts
Labels: 🌐frontend, 🛠️refactor

#5517 [WEB-2379] fix: remove ESM build for the ui package
  packages/ui/package.json
Labels: 🐛bug, 🌐frontend

#5522 [PWA-27] fix: pwa intake issue comment section z-index
  web/core/components/issues/issue-detail/issue-activity/comments/comment-block.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5515 [WEB-2374] fix: untitle page title in favorites list
  web/core/hooks/use-favorite-item-details.tsx
Labels: 🐛bug, 🌐frontend

#5521 [WEB-2049] chore: add extra check to the version editor
  web/core/components/pages/version/editor.tsx
Labels: 🌐frontend, 🌟improvement

#5512 [WEB-2373] chore: add favorites option inside a page
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/list/block-item-action.tsx
  web/core/store/pages/page.ts
Labels: 🌐frontend, 🌟improvement

#5513 [WEB-2375] chore: added identifiers in the notification
  apiserver/plane/bgtasks/issue_activities_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/settings/common.py
Labels: ⚙️backend

#5511 [WEB-2372] fix: parent key added for expansion in external api
  apiserver/plane/api/serializers/__init__.py
  apiserver/plane/api/serializers/base.py
  apiserver/plane/api/serializers/issue.py
Labels: ⚙️backend

#5530 chore: Add missing Mobx observers to components
  web/core/components/issues/filters.tsx
  web/core/components/project/filters.tsx
Labels: 🌐frontend

#5470 [WEB-2358] chore: optimised the recent collaborators endpoint
  apiserver/plane/app/views/dashboard/base.py
  packages/types/src/dashboard.d.ts
  web/core/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx
  web/core/components/dashboard/widgets/recent-collaborators/default-list.tsx
  web/core/components/dashboard/widgets/recent-collaborators/root.tsx
  web/core/components/dashboard/widgets/recent-collaborators/search-list.tsx
Labels: 🌐frontend, ⚙️backend, 🌟improvement

#5531 [WEB-2394] chore: workspace page favourite filter
  apiserver/plane/app/views/workspace/favorite.py
Labels: ⚙️backend, 🌟improvement

#5532 [WEB-2358] fix: recent collaborators
  web/core/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5524 fix: add the redis extension conditionally
  live/.env.example
  live/Dockerfile.live
  live/package.json
  live/src/core/config/sentry-config.ts
  live/src/core/extensions/index.ts
  live/src/core/helpers/error-handler.ts
  live/src/core/helpers/logger.ts
  live/src/core/hocuspocus-server.ts
  live/src/core/lib/utils/redis-url.ts
  live/src/server.ts
  live/tsconfig.json
  yarn.lock
Labels: 🐛bug

#5540 [PWA-28] chore: pwa issue detail improvement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/core/components/issues/issue-detail/main-content.tsx
Labels: 🌐frontend, 🧹chore

#5544 [PWA-22] chore: pwa issue redirection
  web/core/components/dashboard/widgets/issue-panels/issues-list.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block.tsx
  web/core/components/issues/issue-layouts/gantt/blocks.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
  web/core/hooks/use-issue-peek-overview-redirection.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5507 [PWA-26] chore: pwa input focus improvement
  packages/ui/src/dropdown/common/input-search.tsx
  packages/ui/src/dropdown/common/options.tsx
  packages/ui/src/dropdown/dropdown.d.ts
  web/ce/components/projects/create/attributes.tsx
  web/ce/components/projects/create/root.tsx
  web/core/components/command-palette/command-modal.tsx
  web/core/components/core/modals/existing-issues-list-modal.tsx
  web/core/components/cycles/dropdowns/filters/root.tsx
  web/core/components/cycles/form.tsx
  web/core/components/cycles/modal.tsx
  web/core/components/dropdowns/cycle/cycle-options.tsx
  web/core/components/dropdowns/member/member-options.tsx
  web/core/components/dropdowns/module/index.tsx
  web/core/components/dropdowns/module/module-options.tsx
  web/core/components/inbox/inbox-filter/filters/filter-selection.tsx
  web/core/components/inbox/modals/create-edit-modal/create-root.tsx
  web/core/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/core/components/inbox/modals/create-edit-modal/issue-properties.tsx
  web/core/components/inbox/modals/create-edit-modal/issue-title.tsx
  web/core/components/issues/issue-detail/label/select/label-select.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
  web/core/components/issues/issue-modal/components/default-properties.tsx
  web/core/components/issues/issue-modal/components/description-editor.tsx
  web/core/components/issues/issue-modal/components/parent-tag.tsx
  web/core/components/issues/issue-modal/components/project-select.tsx
  web/core/components/issues/issue-modal/components/title-input.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/parent-issues-list-modal.tsx
  web/core/components/issues/select/label.tsx
  web/core/components/labels/create-label-modal.tsx
  web/core/components/modules/dropdowns/filters/root.tsx
  web/core/components/modules/form.tsx
  web/core/components/modules/modal.tsx
  web/core/components/pages/list/filters/root.tsx
  web/core/components/pages/modals/page-form.tsx
  web/core/components/project/create/common-attributes.tsx
  web/core/components/project/create/header.tsx
  web/core/components/project/create/project-create-buttons.tsx
  web/core/components/project/dropdowns/filters/root.tsx
  web/core/components/views/filters/filter-selection.tsx
  web/core/components/views/form.tsx
  web/core/constants/issue-modal.ts
  web/core/constants/tab-indices.ts
  web/core/hooks/use-dropdown.ts
  web/helpers/issue-modal.helper.ts
  web/helpers/tab-indices.helper.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5542 [WEB-2208] fix: space error message alignment
  space/core/components/issues/issue-layouts/error.tsx
Labels: 🐛bug, 🌐frontend

#5538 [WEB-2332] chore: layout structure improvement.
  web/app/layout.tsx
Labels: 🌟improvement

#5545 [WEB-2365] fix: Minor UI in-consistencies cause by tooltip changes
  web/core/components/dropdowns/buttons.tsx
  web/core/components/dropdowns/priority.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/parent-issues-list-modal.tsx
  web/core/components/views/filters/filter-selection.tsx
Labels: 🐛bug, 🌐frontend

#5550 [WEB-2129] fix: module creation and updation toast error
  apiserver/plane/api/serializers/module.py
  apiserver/plane/app/serializers/module.py
  web/core/components/modules/modal.tsx
Labels: 🐛bug, 🌐frontend, ⚙️backend

#5548 [WEB-1116] fix: editor info badges occupying multiple lines
  live/src/server.ts
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  web/core/components/icons/locked-component.tsx
  web/core/components/pages/editor/header/extra-options.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#5549 [WEB-2361] fix: Sidebar loosing its collapse context of on refresh and on changing the size of the window
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#5546 [WEB-2201] fix: clear email button on login screen
  space/core/components/account/auth-forms/email.tsx
  web/core/components/account/auth-forms/email.tsx
Labels: 🐛bug, 🌐frontend

#5557 [WEB-2413] chore: admin application restructuring.
  admin/ce/components/authentication/authentication-modes.tsx
  admin/ce/components/common/index.ts
  admin/ce/components/common/upgrade-button.tsx
  admin/ce/store/root.store.ts
  admin/core/components/common/index.ts
  admin/core/layouts/admin-layout.tsx
  admin/core/lib/store-provider.tsx
  admin/core/store/instance.store.ts
  admin/core/store/root.store.ts
  admin/core/store/theme.store.ts
  admin/core/store/user.store.ts
  admin/ee/components/common/index.ts
  admin/ee/store/root.store.ts
Labels: 🌟improvement

#5554 fix: character count to work properly on editor rerenders and read only mode
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  web/core/components/pages/editor/header/info-popover.tsx
Labels: ✍️editor, pages

#5563 [WEB-2415] fix:remove input type to fix image upload
  web/core/components/core/image-picker-popover.tsx
  web/core/components/core/modals/user-image-upload-modal.tsx
  web/core/components/core/modals/workspace-image-upload-modal.tsx
Labels: 🐛bug, 🌐frontend

#5560 [WEB-2228] fix: dashboard peek overview issue stats #5442
  packages/types/src/dashboard.d.ts
  web/core/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/core/components/issues/peek-overview/root.tsx
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/issue.store.ts
Labels: 🌐frontend, 🧹chore

#5566 [WEB-1116] fix: task list not getting synced in realtime collaboration
  packages/editor/src/styles/editor.css
Labels: 🐛bug, 🌐frontend, ✍️editor

#5571 [WEB-2424] fix: add optional chaining for parent node
  packages/editor/src/core/extensions/custom-link/helpers/clickHandler.ts
  packages/editor/src/core/extensions/slash-commands.tsx
  yarn.lock
Labels: 🌐frontend, 🛠️refactor, ✍️editor

#5564 [WEB-2417] fix: header theme
  web/core/components/core/app-header.tsx
Labels: 🐛bug, 🌐frontend

#5573 [WEB-1116] fix: current version not displaying the latest content
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/version/editor.tsx
  web/core/components/pages/version/main-content.tsx
  web/core/components/pages/version/root.tsx
Labels: 🐛bug, 🌐frontend

#5577 [WEB-2421] chore: issue display properties and issue identifier improvements.
  packages/types/src/view-props.d.ts
  web/ce/components/issues/issue-details/issue-identifier.tsx
  web/ce/helpers/issue-filter.helper.ts
  web/core/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/gantt/blocks.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/constants/issue.ts
  web/ee/helpers/issue-filter.helper.ts
  web/helpers/issue.helper.ts
Labels: 🌐frontend, 🌟improvement

#5580 [WEB-2391] fix: join project permission mutation
  web/core/store/user/user-membership.store.ts
Labels: 🐛bug, 🌐frontend

#5579 [WEB-2430] fix: issue exports for project
  apiserver/plane/bgtasks/export_task.py
Labels: ⚙️backend

#5587 [WEB-2443] fix: project favorite permission validation
  web/core/components/project/card.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5582 [WEB-2393] chore: removal of .svg from supported image formats
  web/core/components/core/image-picker-popover.tsx
  web/core/components/core/modals/user-image-upload-modal.tsx
  web/core/components/core/modals/workspace-image-upload-modal.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5574 [WEB-2313] chore: Custom Theming needed as an option in Search
  web/core/components/command-palette/actions/theme-actions.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5569 [WEB-2419] chore: add toast alerts post access change of a page
  web/core/components/pages/dropdowns/quick-actions.tsx
Labels: 🌐frontend, 🌟improvement

#5559 [WEB-2310] fix: Issue count alignment when states are collapsed in kanban layout
  web/core/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
Labels: 🐛bug, 🌐frontend, 🌐web

#5555 [WEB-2282] fix: date picker and member picker dropdown z-index for list, kanban and spreadsheet views
  web/core/components/dropdowns/date.tsx
  web/core/components/dropdowns/member/index.tsx
  web/core/components/dropdowns/member/member-options.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
Labels: 🐛bug, 🌐frontend

#5589 [WEB-2443] fix: page permission validation
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5588 [WEB-2443] fix: project intake edit permission
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/app/views/project/invite.py
  web/core/components/inbox/content/root.tsx
  web/core/components/project/send-project-invitation-modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5592 [WEB-2443] fix: issue properties dropdown
  web/core/components/dropdowns/cycle/index.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/dropdowns/estimate.tsx
  web/core/components/dropdowns/member/index.tsx
  web/core/components/dropdowns/module/index.tsx
  web/core/components/dropdowns/priority.tsx
  web/core/components/dropdowns/project.tsx
  web/core/components/dropdowns/state.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5593 [WEB-2443] fix: not authorized flicker
  web/core/layouts/auth-layout/workspace-wrapper.tsx
  web/core/store/user/permissions.store.ts
Labels: 🐛bug, 🌐frontend

#5596 [WEB-2443] fix: role validation and code refactor
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/page.tsx
  web/core/components/automation/auto-archive-automation.tsx
  web/core/components/inbox/content/root.tsx
  web/core/components/inbox/modals/create-edit-modal/issue-properties.tsx
  web/core/components/issues/issue-modal/components/default-properties.tsx
  web/core/components/issues/select/label.tsx
  web/core/components/labels/label-block/label-item-block.tsx
  web/core/components/labels/project-setting-label-item.tsx
  web/core/components/labels/project-setting-label-list.tsx
  web/core/components/project-states/group-item.tsx
  web/core/components/project-states/state-item.tsx
  web/core/components/project-states/state-list.tsx
  web/core/constants/project.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5597 [WEB-2445] fix: date picker and member picker dropdown z-index for list, kanban and spreadsheet views
  web/core/components/dropdowns/date.tsx
  web/core/components/dropdowns/member/index.tsx
  web/core/components/dropdowns/member/member-options.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
Labels: 🐛bug, 🌐frontend

#5601 [WEB-2443] fix: project member validation
  web/core/components/project/settings/member-columns.tsx
Labels: 🐛bug, 🌐frontend

#5606 [WEB-2443] fix: workspace settings access validation updated
  web/app/[workspaceSlug]/(projects)/settings/layout.tsx
  web/ce/constants/workspace.ts
  web/core/components/workspace/sidebar/dropdown.tsx
Labels: 🌐frontend, 🧹chore

#5602 [WEB-2443] fix: join project flicker
  web/core/layouts/auth-layout/project-wrapper.tsx
  web/core/store/user/permissions.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5612 [WEB-1506] chore: workspace role demotion
  apiserver/plane/app/views/project/invite.py
  apiserver/plane/app/views/workspace/member.py
Labels: ⚙️backend

#5603 [WEB-1116] chore: remove yjs packages from the editor
  packages/editor/package.json
  packages/editor/src/core/helpers/yjs.ts
  packages/editor/src/index.ts
  yarn.lock
Labels: 🌐frontend, ✍️editor

#5615 [WEB-2460] fix: role permission validation
  apiserver/plane/app/views/issue/comment.py
  apiserver/plane/app/views/issue/reaction.py
  web/core/components/command-palette/command-modal.tsx
  web/core/components/issues/issue-detail/label/root.tsx
  web/core/components/issues/issue-detail/subscription.tsx
  web/core/components/project/settings/member-columns.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
  web/core/components/workspace/sidebar/workspace-menu.tsx
  web/core/layouts/auth-layout/project-wrapper.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5617 [WEB-2460] fix: build error
  web/core/components/command-palette/command-modal.tsx
Labels: 🐛bug, 🌐frontend

#5621 [WEB-2467] fix: platform bug
  apiserver/plane/app/views/issue/reaction.py
  web/core/components/cycles/delete-modal.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/issues/issue-layouts/list/roots/project-root.tsx
  web/core/components/labels/project-setting-label-group.tsx
  web/core/components/labels/project-setting-label-list.tsx
  web/core/components/modules/delete-module-modal.tsx
  web/core/components/project/leave-project-modal.tsx
  web/core/components/project/member-list-item.tsx
  web/core/components/project/settings/member-columns.tsx
  web/core/components/workspace/settings/member-columns.tsx
Labels: 🐛bug, 🌐frontend, ⚙️backend, 🧹chore

#5628 [WEB-2476] fix: removed creation of multiple intakes
  apiserver/plane/api/views/project.py
  apiserver/plane/app/views/project/base.py
Labels: ⚙️backend

#5625 [WEB-2308] fix: description editor loader on issue modal when editing sub issue from another project.
  web/core/components/issues/issue-modal/base.tsx
Labels: 🐛bug, 🌐frontend

#5640 [WEB-2460] chore: restrict member to see private projects
  apiserver/plane/app/views/project/base.py
Labels: ⚙️backend

#5638 [WEB-2480] fix: project settings layout
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/layout.tsx
Labels: 🌐frontend, 🧹chore

#5639 [WEB-2482] fix: list layout quick action styling
  web/core/components/issues/issue-layouts/list/list-group.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5565 [WEB-2316] chore: Kanban group virtualization
  web/core/components/core/render-if-visible-HOC.tsx
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/components/ui/loader/layouts/kanban-layout-loader.tsx
Labels: 🌐frontend, ⚡performance

#5645 [WEB-2462] [WEB-2461] fix: project intake filters
  web/core/components/inbox/inbox-filter/root.tsx
  web/core/components/inbox/inbox-filter/sorting/order-by.tsx
  web/core/constants/inbox.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5636 [WEB-1804] fix: issue description content being overwritten on each swr call
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/[archivedIssueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
  web/core/components/issues/description-input.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/peek-overview/issue-detail.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5635 [WEB-2474] chore: update page lock authorization
  web/core/store/pages/page.ts
Labels: 🌐frontend, 🌟improvement

#5650 chore: render the first intake from the list
  apiserver/plane/app/views/inbox/base.py
Labels: ⚙️backend

#5647 [WEB-2316] fix: Style Calculation performance issue in virtualization
  web/core/components/core/render-if-visible-HOC.tsx
  web/core/components/issues/issue-layouts/list/block-root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/ui/loader/layouts/list-layout-loader.tsx
  web/core/store/issue/issue.store.ts
Labels: 🌐frontend, ⚡performance

#5632 [WEB-2475] fix: applied filters header z-index and transparency
  packages/ui/src/header/helper.tsx
  web/core/components/workspace/views/header.tsx
Labels: 🐛bug, 🌐frontend

#5637 [WEB-2478] style: remove side menu position transition
  packages/editor/src/styles/drag-drop.css
Labels: 🌐frontend, 🎨UI / UX, ✍️editor

#5599 [WEB-2330] fix: you don't have permission toast on on bulk delete
  web/core/components/command-palette/command-palette.tsx
Labels: 🐛bug, 🌐frontend

#5627 [WEB-1970] fix: onboarding invitation page fluctuation on refresh.
  web/app/onboarding/page.tsx
  web/core/components/onboarding/create-or-join-workspaces.tsx
  web/core/components/onboarding/invitations.tsx
Labels: 🐛bug, 🌐frontend

#5616 [WEB-2425] fix:changes for web-2425
  web/ce/components/issues/worklog/activity/filter-root.tsx
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🐛bug, 🌐frontend

#5561 [WEB-2414] chore: remove modal for creating a page
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/core/components/pages/editor/title.tsx
Labels: 🌐frontend, 🌟improvement

#5664 [WEB-2316] chore: Change kanban group virtualization logic
  web/core/components/core/render-if-visible-HOC.tsx
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/list/block-root.tsx
  web/core/components/issues/issue-layouts/list/blocks-list.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
Labels: 🌐frontend, 🧹chore

#5672 [WEB-2512] fix: Large dropdown properties truncation
  web/core/components/dropdowns/buttons.tsx
Labels: 🐛bug, 🌐frontend

#5666 [WEB-2316] chore: fix animation performance on kanban group virtualization
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/ui/loader/layouts/kanban-layout-loader.tsx
Labels: 🌐frontend, ⚡performance

#5567 [WEB-1116] fix: page outline not reflecting changes in realtime
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/drop.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/headers.ts
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/table/table/utilities/create-cell.ts
  packages/editor/src/core/extensions/table/table/utilities/get-table-node-types.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/editor/summary/content-browser.tsx
  web/core/components/pages/editor/summary/popover.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5591 [WEB-2518] chore: Reverse order by of priority keys
  apiserver/plane/utils/order_queryset.py
  web/core/constants/issue.ts
  web/core/constants/spreadsheet.ts
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🌐frontend, 🧹chore

#5622 [WEB-1116] chore: add fallback for the live server
  live/src/core/hocuspocus-server.ts
  packages/editor/src/core/helpers/yjs.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/index.ts
  packages/types/src/pages.d.ts
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/hooks/use-auto-save.tsx
  web/core/hooks/use-page-fallback.ts
  web/core/services/page/project-page.service.ts
  web/core/store/pages/page.ts
Labels: 🌐frontend

#5652 [WEB-2497] chore: update pages' offline badge tooltip content
  web/core/components/pages/editor/header/extra-options.tsx
  yarn.lock
Labels: 🌐frontend, 🌟improvement

#5654 [WEB-2498] fix: workspace archives and setting validation
  web/core/components/workspace/sidebar/workspace-menu.tsx
Labels: 🌐frontend, 🧹chore

#5665 [WEB-2509] feat: fullscreen option for editor images
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/index.ts
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/index.ts
  packages/editor/src/core/extensions/custom-image/components/toolbar/root.tsx
Labels: ✨feature, 🌐frontend, ✍️editor

#5667 [WEB-2511] fix: fix overlapping issues for headers globally
  packages/ui/src/header/helper.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/page.tsx
  web/core/components/core/app-header.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/inbox-issue-mobile-header.tsx
  web/core/components/inbox/content/root.tsx
Labels: 🌐frontend

#5624 [WEB-2427] fix: white background behind emoji
  web/core/components/project/card.tsx
  web/core/components/project/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#5670 [WEB-2466] fix-Date Sorting Dropdown Not Mutating Between Ascending and Descending
  web/core/components/modules/dropdowns/order-by.tsx
  web/core/components/pages/list/order-by.tsx
  web/core/components/views/filters/order-by.tsx
Labels: 🐛bug, 🌐frontend, 🌐web

#5671 [WEB-2504] chore: issue relation hard delete
  apiserver/plane/api/views/project.py
  apiserver/plane/app/views/issue/relation.py
  apiserver/plane/app/views/project/base.py
Labels: ⚙️backend

#5674 [WEB-2515] style: updated create workspace option text color
  web/core/components/workspace/sidebar/dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX

#5675 [WEB-2516] fix: casing across all settings pages
  web/ce/components/projects/settings/useProjectColumns.tsx
  web/ce/components/workspace/billing/root.tsx
  web/ce/components/workspace/delete-workspace-section.tsx
  web/core/components/automation/auto-close-automation.tsx
  web/core/components/estimates/create/modal.tsx
  web/core/components/exporter/guide.tsx
  web/core/components/onboarding/tour/root.tsx
  web/core/components/profile/notification/email-notification-form.tsx
  web/core/components/project-states/create-update/form.tsx
  web/core/components/project/delete-project-modal.tsx
  web/core/components/project/form-loader.tsx
  web/core/components/project/form.tsx
  web/core/components/project/project-settings-member-defaults.tsx
  web/core/components/project/send-project-invitation-modal.tsx
  web/core/components/project/settings/delete-project-section.tsx
  web/core/components/workspace/delete-workspace-modal.tsx
  web/core/components/workspace/settings/workspace-details.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
  web/core/constants/themes.ts
Labels: 🌐frontend, 🌟improvement

#5656 [WEB-2501] chore: add server name to the HocusPocus server while initialization
  live/package.json
  live/src/core/hocuspocus-server.ts
Labels: 🌐frontend

#5669 [WEB-2513] fix: page container height
  web/core/components/pages/editor/editor-body.tsx
Labels: 🌐frontend, 🌟improvement, pages

#5659 [WEB-2503] chore: remove line-through decoration from checked todo list items
  packages/editor/src/styles/editor.css
Labels: 🌐frontend, 🎨UI / UX, ✍️editor

#5683 [WEB-2001] chore: Code refactor for noload changes.
  packages/constants/issue.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/[archivedIssueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
  web/core/components/common/logo.tsx
  web/core/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/peek-overview/root.tsx
  web/core/hooks/use-local-storage.tsx
  web/core/store/issue/cycle/filter.store.ts
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/module/filter.store.ts
  web/core/store/issue/module/issue.store.ts
Labels: 🌐frontend, 🧹chore

#5682 [WEB-2525] fix: activity filters
  web/ce/components/issues/worklog/activity/filter-root.tsx
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🌐frontend, 🧹chore

#5686 [WEB-2509] fix: image fullscreen size
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#5689 [WEB-2534] fix: Add requestIdleCallback polyfill to fix crash in Safari browser
  web/app/provider.tsx
  web/core/lib/polyfills/index.ts
  web/core/lib/polyfills/requestIdleCallback.ts
Labels: 🐛bug, 🌐frontend

#5692 [WEB-2537 ] fix: issue quick action
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
Labels: 🐛bug, 🌐frontend

#5694 [WEB-2539] fix: update version history overlay z-index
  web/core/components/pages/version/root.tsx
Labels: 🐛bug, 🌐frontend

#5695 [WEB-2543] chore: workspace inbox guest permission
  apiserver/plane/app/views/notification/base.py
  web/core/components/issues/peek-overview/view.tsx
  web/core/constants/dashboard.ts
  web/next.config.js
Labels: 🌐frontend, 🧹chore

#5704 [WEB-2551] fix: list layout item
  web/core/components/issues/issue-layouts/list/block.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5711 [WEB-2562] chore: moved headings list extension to the collaborative editor hook
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
Labels: 🐛bug, 🌐frontend, ✍️editor

#5607 [WEB-2455] fix: Quick action menu is overflowing for created link notification under inbox
  web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
Labels: 🐛bug, 🌐frontend, 🌐web

#5618 [WEB-2266] chore-No favorites should be aligned like the rest of the things
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
Labels: 🌐frontend, 🌐web, 🧹chore

#5657 [WEB-2502] chore: add a loader to the collaborative editor until it has synced with the live server
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/collaborative-read-only-editor.tsx
  packages/editor/src/core/components/editors/document/index.ts
  packages/editor/src/core/components/editors/document/loader.tsx
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
Labels: 🌐frontend, 🌟improvement

#5699 [WEB-2550] fix: spacing by removing the right border
  space/core/components/editor/toolbar.tsx
  web/core/components/editor/lite-text-editor/toolbar.tsx
Labels: 🐛bug, 🌐frontend

#5724 [WEB-2579] fix: frequent loader on issue detail / archived issue detail page.
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/[archivedIssueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
Labels: 🐛bug, 🌐frontend

#5693 [PE-46] fix: added aspect ratio to resizing
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/image-node.tsx
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/root.tsx
  packages/editor/src/core/extensions/custom-image/custom-image.ts
  packages/editor/src/core/extensions/custom-image/read-only-custom-image.ts
  packages/editor/src/core/extensions/drop.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/image/image-component-without-props.tsx
  packages/editor/src/core/extensions/image/image-extension-without-props.tsx
  packages/editor/src/core/extensions/slash-commands.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-file-upload.ts
  packages/editor/src/core/plugins/image/image-upload-handler.ts
  packages/editor/src/core/plugins/image/index.ts
  packages/editor/src/core/plugins/image/upload-image.ts
  packages/editor/src/core/plugins/image/utils/index.ts
  packages/editor/src/core/plugins/image/utils/placeholder.ts
  packages/editor/src/styles/editor.css
  web/core/components/editor/rich-text-editor/rich-text-editor.tsx
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/peek-overview/issue-detail.tsx
Labels: ✍️editor
