Repository makeplane/plane, pull requests merged in 2024-02, with the labels that each got.

#3530 fix: update cycle error
  apiserver/plane/app/serializers/cycle.py
  packages/types/src/cycles.d.ts
  web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/sidebar.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3537 chore: breadcrumb component improvement
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  web/components/common/breadcrumb-link.tsx
  web/components/common/index.ts
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/profile-preferences.tsx
  web/components/headers/profile-settings.tsx
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issue-details.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/headers/user-profile.tsx
  web/components/headers/workspace-active-cycles.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/headers/workspace-dashboard.tsx
  web/components/headers/workspace-settings.tsx
  web/layouts/admin-layout/header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3549 fix: create issue modal project select
  web/components/issues/issue-modal/modal.tsx
Labels: 🐛bug, 🌐frontend

#3541 chore: responsive and styling fixes
  packages/ui/src/icons/priority-icon.tsx
  web/components/account/deactivate-account-modal.tsx
  web/components/dashboard/widgets/dropdowns/duration-filter.tsx
  web/components/dashboard/widgets/issue-panels/issues-list.tsx
  web/components/dashboard/widgets/overview-stats.tsx
  web/components/headers/workspace-dashboard.tsx
  web/layouts/app-layout/sidebar.tsx
Labels: 🎨UI / UX

#3550 fix: all issues spreadsheet sorting and kanban dnd for long lists
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
Labels: 🐛bug, 🌐frontend

#3552 dev: validation for external id and external source
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/state.py
Labels: ⚙️backend

#3559 chore: cycle and module sidebar analytics improvement
  apiserver/plane/app/views/cycle.py
  apiserver/plane/app/views/module.py
  packages/ui/src/icons/priority-icon.tsx
  web/components/core/sidebar/progress-chart.tsx
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
  web/layouts/app-layout/sidebar.tsx
  web/store/cycle.store.ts
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
  web/store/module.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#3560 chore: active cycle issue transfer validation
  web/components/dropdowns/date.tsx
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/roots/cycle-root.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/list-view-types.d.ts
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/cycle-root.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3556 chore: added `None` filter option to the dashboard widgets
  apiserver/plane/app/views/dashboard.py
  packages/types/src/dashboard.d.ts
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/issue-panels/issues-list.tsx
  web/components/dashboard/widgets/issue-panels/tabs-list.tsx
  web/components/dashboard/widgets/issues-by-priority.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/constants/dashboard.ts
  web/helpers/dashboard.helper.ts
Labels: 🌐frontend, 🌟improvement

#3561 chore: email notification turned off for new users
  apiserver/plane/db/models/user.py
Labels: ⚙️backend, 🧹chore

#3562 chore: cycle and module sidebar improvement
  web/components/core/sidebar/sidebar-progress-stats.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3565 chore: module date validation
  web/components/modules/form.tsx
  web/components/modules/sidebar.tsx
Labels: 🐛bug, 🧹chore

#3571 fix: APP_RELEASE default value handled
  deploy/selfhost/install.sh
Labels: ⚙️config changes

#3580 style: responsive breadcrumbs and headers for dashboard, projects, pr…
  web/components/analytics/project-modal/modal.tsx
  web/components/cycles/cycle-mobile-header.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/projects.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/headers/workspace-dashboard.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/module-mobile-header.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
Labels: 🎨UI / UX

#3581 fix: dashboard header z index and workspace active cycles fix
  web/components/headers/workspace-dashboard.tsx
  web/components/workspace/workspace-active-cycles-upgrade.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3582 fix: draft issue peek overview
  web/components/command-palette/shortcuts-modal/modal.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/project/create-project-modal.tsx
  web/components/views/modal.tsx
  web/store/issue/draft/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3566 chore: module issue count
  apiserver/plane/app/views/module.py
Labels: 🐛bug, ⚙️backend

#3573 chore: mention notification and webhook faliure
  apiserver/plane/api/views/base.py
  apiserver/plane/app/views/base.py
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/bgtasks/webhook_task.py
  apiserver/plane/settings/common.py
  apiserver/templates/emails/notifications/issue-updates.html
  apiserver/templates/emails/notifications/webhook-deactivate.html
Labels: 🐛bug, ⚙️backend

#3584 chore: workspace dashboard refactor
  web/components/headers/workspace-dashboard.tsx
Labels: 🌐frontend, 🧹chore

#3577 fix: show window closing alert only when page is not saved
  web/hooks/use-reload-confirmation.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🐛bug, ✍️editor, pages

#3586 chore: posthog code refactor
  web/pages/_document.tsx
Labels: 🌐frontend, 🧹chore

#3575 chore: email template logo changed
  apiserver/templates/emails/notifications/issue-updates.html
Labels: 🌟improvement

#3588 fix: handled the draft issue from issue create modal and optimised the draft issue store
  apiserver/plane/app/views/issue.py
  web/components/command-palette/command-palette.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-modal/draft-issue-layout.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/store/issue/draft/issue.store.ts
Labels: 🌐frontend, ⚙️backend, 🌟improvement, 🧹chore

#3590 fix: module header hide on bigger screens
  web/components/headers/project-issues.tsx
  web/components/modules/module-mobile-header.tsx
Labels: 🎨UI / UX

#3569 feat: muti-arch build
  .github/workflows/build-branch.yml
  deploy/1-click/install.sh
  deploy/1-click/plane-app
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install.sh
  deploy/selfhost/variables.env
Labels: 🏠self-hosted, 🐳docker, devops

#3564 feat: Keyboard navigation spreadsheet layout for issues
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/helper.tsx
  packages/ui/src/hooks/use-dropdown-key-down.tsx
  web/components/common/breadcrumb-link.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/types.d.ts
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/label-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/priority-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/state-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/constants/spreadsheet.ts
  web/hooks/use-dropdown-key-down.tsx
  web/hooks/use-table-keyboard-navigation.tsx
Labels: 🌟enhancement, 🌐frontend

#3593 fix: handled issue create modal submission on clicking enter key
  web/components/issues/issue-modal/form.tsx
Labels: 🌐frontend, 🧹chore

#3570 fix: cycle and module reordering in the gantt chart
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/cycles/sidebar.tsx
  web/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/components/gantt-chart/helpers/block-structure.tsx
  web/components/gantt-chart/sidebar/cycle-sidebar.tsx
  web/components/gantt-chart/sidebar/module-sidebar.tsx
  web/components/gantt-chart/sidebar/project-view-sidebar.tsx
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/issues/index.ts
  web/components/issues/view-select/due-date.tsx
  web/components/issues/view-select/estimate.tsx
  web/components/issues/view-select/index.ts
  web/components/issues/view-select/start-date.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
  web/helpers/date-time.helper.ts
  web/store/cycle.store.ts
  web/store/module.store.ts
Labels: 🐛bug, 🌐frontend

#3596 style: responsive profile
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/components/headers/user-profile.tsx
  web/components/profile/navbar.tsx
  web/components/profile/sidebar.tsx
  web/layouts/settings-layout/profile/preferences/layout.tsx
  web/layouts/settings-layout/profile/preferences/sidebar.tsx
  web/layouts/settings-layout/profile/sidebar.tsx
  web/layouts/user-profile-layout/layout.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/index.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
  web/pages/profile/activity.tsx
  web/pages/profile/change-password.tsx
  web/pages/profile/index.tsx
  web/pages/profile/preferences/theme.tsx
  web/store/application/theme.store.ts
Labels: 🎨UI / UX

#3599 chore: custom menu dropdown improvement
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  packages/ui/src/dropdowns/custom-menu.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3598 fix: notification card snooze
  packages/ui/src/dropdowns/custom-menu.tsx
  web/components/notifications/notification-card.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3597 fix: incorrect dashboard tab
  apiserver/plane/db/migrations/0059_auto_20240208_0957.py
  packages/types/src/dashboard.d.ts
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/issue-panels/tabs-list.tsx
  web/components/dashboard/widgets/issues-by-priority.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/helpers/dashboard.helper.ts
Labels: 🐛bug, 🌐frontend, 🔄migrations

#3604 style: responsive analytics
  web/components/analytics/custom-analytics/custom-analytics.tsx
  web/components/analytics/custom-analytics/select-bar.tsx
  web/components/analytics/custom-analytics/sidebar/projects-list.tsx
  web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
  web/components/analytics/custom-analytics/sidebar/sidebar.tsx
  web/components/analytics/project-modal/main-content.tsx
  web/components/headers/user-profile.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/profile/sidebar.tsx
  web/pages/[workspaceSlug]/analytics.tsx
  web/store/application/theme.store.ts
Labels: 🎨UI / UX

#3538 chore: virtualization ish behaviour for issue layouts
  packages/types/src/issues.d.ts
  web/components/core/render-if-visible-HOC.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/issue-layouts/utils.tsx
  web/constants/issue.ts
Labels: 🌐frontend

#3600 feat: completed cycle snapshot
  apiserver/plane/app/views/cycle.py
  apiserver/plane/db/migrations/0060_cycle_progress_snapshot.py
  apiserver/plane/db/models/cycle.py
  packages/types/src/cycles.d.ts
  packages/ui/src/dropdowns/custom-menu.tsx
  web/components/cycles/sidebar.tsx
Labels: ✨feature, 🌐frontend, ⚙️backend, 🌟improvement, 🔄migrations

#3607 fix: spreadsheet date validation and sorting
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/store/issue/helpers/issue-helper.store.ts
  web/store/issue/root.store.ts
  web/store/member/workspace-member.store.ts
Labels: 🐛bug, 🌐frontend

#3602 fix: notification popover responsiveness
  web/components/notifications/notification-card.tsx
  web/components/notifications/notification-header.tsx
  web/components/notifications/notification-popover.tsx
  web/components/notifications/select-snooze-till-modal.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3620 fix: breadcrumbs responsiveness fix, modules list mobile responsive l…
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  web/components/cycles/cycle-peek-overview.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/sidebar.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/projects.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/module-peek-overview.tsx
  web/components/modules/sidebar.tsx
Labels: 🎨UI / UX

#3611 chore: show project tour modal before project creation
  web/components/page-views/workspace-dashboard.tsx
Labels: 🐛bug, 🌐frontend

#3585 refactor: Gantt chart layout
  web/components/cycles/gantt-chart/blocks.tsx
  web/components/cycles/gantt-chart/cycles-list-layout.tsx
  web/components/gantt-chart/blocks/blocks-list.tsx
  web/components/gantt-chart/blocks/index.ts
  web/components/gantt-chart/chart/header.tsx
  web/components/gantt-chart/chart/index.ts
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/gantt-chart/chart/month.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/gantt-chart/chart/views/bi-week.tsx
  web/components/gantt-chart/chart/views/day.tsx
  web/components/gantt-chart/chart/views/hours.tsx
  web/components/gantt-chart/chart/views/index.ts
  web/components/gantt-chart/chart/views/month.tsx
  web/components/gantt-chart/chart/views/quarter.tsx
  web/components/gantt-chart/chart/views/week.tsx
  web/components/gantt-chart/chart/views/year.tsx
  web/components/gantt-chart/constants.ts
  web/components/gantt-chart/contexts/index.tsx
  web/components/gantt-chart/helpers/block-structure.ts
  web/components/gantt-chart/helpers/draggable.tsx
  web/components/gantt-chart/index.ts
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/cycle-sidebar.tsx
  web/components/gantt-chart/sidebar/cycles.tsx
  web/components/gantt-chart/sidebar/index.ts
  web/components/gantt-chart/sidebar/issues.tsx
  web/components/gantt-chart/sidebar/modules.tsx
  web/components/gantt-chart/sidebar/project-views.tsx
  web/components/gantt-chart/sidebar/root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/components/modules/gantt-chart/blocks.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🛠️refactor

#3623 chore: Removing 'description_html' from Issue List
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/issue.py
  web/components/issues/description-form.tsx
  web/components/issues/peek-overview/issue-detail.tsx
  web/services/issue/issue_draft.service.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue.store.ts
Labels: 🌐frontend, ⚙️backend, 🌟improvement

#3622 fix: inbox icon
  web/components/headers/project-issues.tsx
Labels: 🎨UI / UX

#3625 style: issue detail responsiveness
  web/components/headers/project-issue-details.tsx
  web/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/store/application/theme.store.ts
Labels: 🎨UI / UX

#3624 fix: project-pages responsiveness
  packages/editor/document-editor/src/ui/components/editor-header.tsx
  packages/editor/document-editor/src/ui/components/page-renderer.tsx
  packages/editor/document-editor/src/ui/components/summary-popover.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/document-editor/src/ui/menu/fixed-menu.tsx
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/components/empty-state/empty-state.tsx
  web/components/headers/page-details.tsx
  web/components/pages/create-update-page-modal.tsx
  web/components/pages/page-form.tsx
  web/components/pages/pages-list/list-item.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#3626 fix: sidebar height, authorization
  web/components/gantt-chart/blocks/blocks-list.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/gantt-chart/chart/views/month.tsx
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/modules/gantt-chart/modules-list-layout.tsx
Labels: 🐛bug, 🌐frontend

#3629 fix: pages table of content drop down close on click and app sidebar …
  packages/editor/document-editor/src/ui/components/content-browser.tsx
  packages/editor/document-editor/src/ui/components/summary-popover.tsx
  web/layouts/app-layout/sidebar.tsx
Labels: 🎨UI / UX

#3631 chore: change border of placeholder for spreadsheet
  web/components/core/render-if-visible-HOC.tsx
  web/components/cycles/sidebar.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🌐frontend

#3642 fix local development setup issue makeplane/plane#3641
  docker-compose-local.yml
Labels: 🐳docker, ⚙️config changes

#3645 fix: scroll sync for the sidebar and blocks
  web/components/gantt-chart/blocks/blocks-list.tsx
Labels: 🐛bug, 🌐frontend

#3644 chore: app sidebar state
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/layouts/app-layout/sidebar.tsx
  web/store/application/theme.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3646 fix: Kanban DND within the array
  web/components/issues/issue-layouts/kanban/utils.ts
Labels: 🐛bug, 🌐frontend

#3649 fix: add existing issue modal
  packages/types/src/projects.d.ts
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3651 fix: sort order in the same list for Kanban
  web/components/issues/issue-layouts/kanban/utils.ts
Labels: 🐛bug, 🌐frontend

#3639 feat: loading states update
  web/components/cycles/cycles-view.tsx
  web/components/exporter/guide.tsx
  web/components/integration/guide.tsx
  web/components/integration/single-integration-card.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/components/modules/modules-list-view.tsx
  web/components/notifications/notification-popover.tsx
  web/components/profile/profile-issues.tsx
  web/components/project/card-list.tsx
  web/components/project/member-list.tsx
  web/components/ui/index.ts
  web/components/ui/loader/cycle-module-board-loader.tsx
  web/components/ui/loader/cycle-module-list-loader.tsx
  web/components/ui/loader/index.ts
  web/components/ui/loader/layouts/calendar-layout-loader.tsx
  web/components/ui/loader/layouts/gantt-layout-loader.tsx
  web/components/ui/loader/layouts/index.ts
  web/components/ui/loader/layouts/kanban-layout-loader.tsx
  web/components/ui/loader/layouts/list-layout-loader.tsx
  web/components/ui/loader/layouts/spreadsheet-layout-loader.tsx
  web/components/ui/loader/notification-loader.tsx
  web/components/ui/loader/pages-loader.tsx
  web/components/ui/loader/projects-loader.tsx
  web/components/ui/loader/settings/activity.tsx
  web/components/ui/loader/settings/api-token.tsx
  web/components/ui/loader/settings/email.tsx
  web/components/ui/loader/settings/import-and-export.tsx
  web/components/ui/loader/settings/index.ts
  web/components/ui/loader/settings/integration.tsx
  web/components/ui/loader/settings/members.tsx
  web/components/ui/loader/settings/web-hook.tsx
  web/components/ui/loader/utils.tsx
  web/components/ui/loader/view-list-loader.tsx
  web/components/views/views-list.tsx
  web/components/workspace/settings/members-list.tsx
  web/components/workspace/views/views-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/api-tokens.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
  web/pages/profile/activity.tsx
  web/pages/profile/preferences/email.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3652 fix: issue spillover on switching workspace
  web/components/profile/profile-issues.tsx
  web/store/issue/profile/issue.store.ts
  web/store/issue/workspace/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3653 fix: empty state loaders and filter cancel state updates for modules and cycles
  web/components/issues/issue-layouts/filters/applied-filters/roots/cycle-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/module-root.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/store/issue/archived/issue.store.ts
  web/store/issue/draft/issue.store.ts
  yarn.lock
Labels: 🐛bug, 🌐frontend

#3657 chore: loading state improvement
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
Labels: 🌐frontend, 🌟improvement

#3656 fix: infinity loader in the issue description in the issue peek overview and issue detail page
  web/components/issues/description-form.tsx
Labels: 🐛bug, 🌐frontend

#3647 fix: kanban-layout responsiveness
  web/components/issues/issue-layouts/kanban/default.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3658 chore: module & cycle empty state improvement
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
Labels: 🌐frontend, 🌟improvement

#3659 fix: cycle favorite mutation
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/issues/issue-detail/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#3661 fix: mobile responsive sidebar close on item tap
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/help-section.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-menu.tsx
  web/layouts/settings-layout/profile/preferences/layout.tsx
  web/layouts/settings-layout/profile/sidebar.tsx
  web/pages/profile/activity.tsx
  web/pages/profile/change-password.tsx
  web/pages/profile/index.tsx
Labels: 🐛bug, 🎨UI / UX

#3662 fix: issue details page parent issue redirection
  web/components/issues/issue-detail/parent/root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3664 fix: horizontal scroll in gantt chart while dragging
  web/components/gantt-chart/chart/main-content.tsx
  web/components/gantt-chart/chart/root.tsx
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/issues.tsx
  web/components/gantt-chart/sidebar/root.tsx
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
Labels: 🐛bug, 🌐frontend

#3665 chore: parent can be added to issue
  apiserver/plane/app/views/search.py
Labels: ⚙️backend, 🌟improvement

#3670 fix: peek overview issue description initial load bug
  web/components/issues/description-form.tsx
Labels: 🐛bug, 🌐frontend

#3677 fix: inbox description and mutation
  apiserver/plane/app/views/inbox.py
  web/components/inbox/inbox-issue-status.tsx
  web/components/issues/description-form.tsx
Labels: 🌐frontend, ⚙️backend

#3682 chore: dropdown and peek overview improvement
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/select/label.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3690 fix: improved issue description editor focus and state management
  web/components/issues/description-input.tsx
  web/components/issues/issue-detail/inbox/main-content.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/peek-overview/header.tsx
  web/components/issues/peek-overview/index.ts
  web/components/issues/peek-overview/issue-detail.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/title-input.tsx
Labels: 🐛bug, 🌐frontend

#3695 chore : project inbox improvement
  web/components/headers/project-issues.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/ui/loader/layouts/index.ts
  web/components/ui/loader/layouts/project-inbox/inbox-layout-loader.tsx
  web/components/ui/loader/layouts/project-inbox/inbox-sidebar-loader.tsx
  web/components/ui/loader/layouts/project-inbox/index.ts
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3678 fix: project description
  web/components/project/form.tsx
  web/layouts/settings-layout/project/layout.tsx
  web/layouts/settings-layout/project/sidebar.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3692 chore: adding page titles using project title.
  web/components/core/index.ts
  web/components/core/page-title.tsx
  web/components/page-views/signin.tsx
  web/pages/404.tsx
  web/pages/[workspaceSlug]/active-cycles.tsx
  web/pages/[workspaceSlug]/analytics.tsx
  web/pages/[workspaceSlug]/index.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/index.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/automations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/estimates.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/features.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/integrations.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/labels.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/settings/members.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/[viewId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
  web/pages/[workspaceSlug]/projects/index.tsx
  web/pages/[workspaceSlug]/settings/api-tokens.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/imports.tsx
  web/pages/[workspaceSlug]/settings/index.tsx
  web/pages/[workspaceSlug]/settings/integrations.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/pages/[workspaceSlug]/settings/webhooks/[webhookId].tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
  web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
  web/pages/[workspaceSlug]/workspace-views/index.tsx
  web/pages/accounts/forgot-password.tsx
  web/pages/accounts/reset-password.tsx
  web/pages/accounts/sign-up.tsx
  web/pages/create-workspace.tsx
  web/pages/god-mode/ai.tsx
  web/pages/god-mode/authorization.tsx
  web/pages/god-mode/email.tsx
  web/pages/god-mode/image.tsx
  web/pages/god-mode/index.tsx
  web/pages/invitations/index.tsx
  web/pages/onboarding/index.tsx
  web/pages/profile/activity.tsx
  web/pages/profile/change-password.tsx
  web/pages/profile/index.tsx
  web/pages/profile/preferences/email.tsx
  web/pages/profile/preferences/theme.tsx
Labels: 🌟enhancement, 🌐frontend

#3706 chore: sidebar new issue button validation added
  web/components/workspace/sidebar-quick-action.tsx
Labels: 🌐frontend, 🌟improvement

#3708 fix: kanban layout empty group toggle
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
Labels: 🐛bug, 🌐frontend

#3709 chore: dashboard widget heading updated
  web/components/dashboard/widgets/recent-projects.tsx
Labels: 🌐frontend, 🧹chore

#3705 chore : calendar layout improvement
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#3720 [WEB-462] fix: inbox mutation
  web/components/project/sidebar-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3723 [WEB-472] fix: Page title for global view
  web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
Labels: 🌐frontend, 🌟improvement

#3729 [WEB-474]: Layout change not working in cycles and modules
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
  web/store/issue/issue_calendar_view.store.ts
Labels: 🐛bug, 🌐frontend

#3725 [WEB-464] improvement: remove `add sub-issues` button from the bottom if sub-issues are available.
  web/components/issues/sub-issues/root.tsx
Labels: 🌐frontend, 🌟improvement

#3712 [WEB-456] chore: display sub issues option added in global view issues
  web/constants/issue.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#3703 [WEB-327] chore: scrollbar implementation
  web/components/analytics/scope-and-demand/scope-and-demand.tsx
  web/components/command-palette/command-modal.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/cycles/active-cycle-stats.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-list.tsx
  web/components/gantt-chart/chart/main-content.tsx
  web/components/inbox/sidebar/inbox-list.tsx
  web/components/issues/issue-detail/inbox/root.tsx
  web/components/issues/issue-detail/label/select/label-select.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/modules/modules-list-view.tsx
  web/components/notifications/notification-popover.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/list-view.tsx
  web/components/project/card-list.tsx
  web/components/project/sidebar-list.tsx
  web/components/ui/loader/layouts/calendar-layout-loader.tsx
  web/components/views/views-list.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/views/header.tsx
  web/components/workspace/workspace-active-cycles-upgrade.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/[cycleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/[moduleId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/workspace-views/index.tsx
  web/styles/globals.css
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX

#3715 [WEB-461] chore: issue transfer validation added for completed cycle
  web/components/cycles/transfer-issues.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#3719 [WEB-457] fix: email notification duplicates
  apiserver/plane/bgtasks/email_notification_task.py
Labels: 🐛bug, ⚙️backend

#3724 [WEB-463] improvement: open sub-issues accordion by default in issue details page.
  web/components/issues/sub-issues/root.tsx
Labels: 🌐frontend, 🌟improvement

#3730 [WEB-483] chore: issue embed suggestion dropdown improvement
  packages/editor/document-editor/src/ui/extensions/widgets/issue-embed-suggestion-list/issue-suggestion-renderer.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3731 [WEB-465] improvement: redirect to issue detail on click on the sub-issue count property.
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
  web/components/issues/sub-issues/root.tsx
Labels: 🌐frontend, 🌟improvement

#3733 [WEB-482] chore: issue sidebar improvement
  web/components/dropdowns/module.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/peek-overview/properties.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#3717 [WEB-394]: Added a description to project network options
  packages/ui/src/dropdowns/custom-select.tsx
  web/components/core/filters/date-filter-select.tsx
  web/components/modules/sidebar-select/select-status.tsx
  web/components/project/create-project-modal.tsx
  web/components/project/form.tsx
  web/constants/project.ts
Labels: 🌐frontend, 🌟improvement

#3710 [WEB - 467] perf: issues listing endpoints
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/cycle.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/app/views/module.py
  apiserver/plane/app/views/view.py
  apiserver/plane/app/views/workspace.py
  web/components/issues/issue-detail/subscription.tsx
Labels: ⚡performance

#3738 [WEB-486] fix: In archived issues, `Ctrl + click` is redirecting to `/issues/[issue-id]` route instead of `/archived-issues/[issue-id]` resulting in infinite loading.
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/block.tsx
Labels: 🐛bug, 🌐frontend

#3736 [WEB-327] chore: scrollbar improvement
  web/styles/globals.css
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3737 [WEB - 485] chore: external apis validation
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/state.py
Labels: ⚙️backend, 🧹chore

#3679 [WEB-371]: Implemented `react-day-picker` for date selections
  web/components/api-token/modal/form.tsx
  web/components/core/filters/date-filter-modal.tsx
  web/components/cycles/form.tsx
  web/components/cycles/sidebar.tsx
  web/components/dropdowns/date-range.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/index.ts
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/workspace-member.tsx
  web/components/inbox/inbox-issue-actions.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/properties/with-display-properties-HOC.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/modules/form.tsx
  web/components/modules/sidebar.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/components/ui/datepicker.tsx
  web/components/ui/index.ts
  web/components/ui/range-datepicker.tsx
  web/constants/issue.ts
  web/constants/spreadsheet.ts
  web/helpers/date-time.helper.ts
  web/package.json
  web/pages/_app.tsx
  web/styles/react-datepicker.css
  web/styles/react-day-picker.css
  yarn.lock
Labels: 🌐frontend, 🌟improvement

#3741 [WEB - 490] chore: issue serializer changes
  apiserver/plane/app/views/dashboard.py
  web/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🐛bug, ⚙️backend

#3745 [WEB-491] chore: project filter updated
  apiserver/plane/app/views/workspace.py
Labels: 🐛bug, ⚙️backend

#3740 [WEB - 489] dev: update python runtime version
  apiserver/runtime.txt
Labels: 📦dependencies

#3746 [WEB - 492] fix: transfer cycle issues
  apiserver/plane/app/views/cycle.py
Labels: 🐛bug, ⚙️backend

#3739 [WEB-487] chore: inbox loader improvement
  web/components/ui/loader/layouts/project-inbox/inbox-layout-loader.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3754 [WEB-496] improvement: disable submit button when there is no text in comment box.
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🌐frontend, 🌟improvement

#3752 [WEB-494] fix: selected label indicator are not showing up on the issue create modal.
  web/components/issues/select/label.tsx
Labels: 🌐frontend, 🎨UI / UX

#3755 [WEB-521] fix: kanban column collapse toggle not working
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
Labels: 🐛bug, 🌐frontend

#3758 [WEB-515] fix: spreadsheet layout overflow
  web/components/headers/cycle-issues.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3751 [WEB - 508] chore: bot filter
  apiserver/plane/app/views/workspace.py
  web/store/member/workspace-member.store.ts
Labels: 🧹chore

#3749 [WEB-501] fix: disable peek overview for temporary issues until it is confirmed
  packages/ui/src/control-link/control-link.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🐛bug, 🌐frontend

#3722 [WEB-468] fix: issue detail endpoints
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/base.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/issue.py
  packages/types/src/issues/issue.d.ts
  packages/types/src/issues/issue_attachment.d.ts
  packages/types/src/issues/issue_link.d.ts
  packages/types/src/issues/issue_reaction.d.ts
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-detail/links/link-detail.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/peek-overview/root.tsx
  web/services/issue/issue.service.ts
  web/services/issue/issue_archive.service.ts
  web/store/issue/archived/issue.store.ts
  web/store/issue/cycle/issue.store.ts
  web/store/issue/draft/issue.store.ts
  web/store/issue/issue-details/attachment.store.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/link.store.ts
  web/store/issue/issue-details/reaction.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/issue-details/subscription.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/profile/issue.store.ts
  web/store/issue/project-views/issue.store.ts
  web/store/issue/project/issue.store.ts
  web/store/issue/workspace/issue.store.ts
Labels: ⚡performance

#3779 [WEB-547] fix: Re enable sub issues toggle in spreadsheet layout
  web/constants/issue.ts
  web/store/issue/archived/filter.store.ts
  web/store/issue/cycle/filter.store.ts
  web/store/issue/draft/filter.store.ts
  web/store/issue/module/filter.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project/filter.store.ts
Labels: 🌐frontend

#3777 [WEB-543] chore: project and workspace views list improvement
  web/components/views/view-list-item.tsx
  web/components/workspace/views/default-view-list-item.tsx
  web/components/workspace/views/view-list-item.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3748 [WEB-459] fix: tables row color retention, images in tables and css fixes
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/styles/table.css
  packages/editor/core/src/ui/extensions/table/table-cell/table-cell.ts
  packages/editor/core/src/ui/extensions/table/table-header/table-header.ts
  packages/editor/core/src/ui/extensions/table/table-row/table-row.ts
  packages/editor/core/src/ui/extensions/table/table/icons.ts
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
  packages/editor/core/src/ui/extensions/table/table/table.ts
  packages/editor/core/src/ui/props.tsx
  packages/editor/document-editor/src/ui/menu/fixed-menu.tsx
  packages/editor/extensions/src/extensions/drag-drop.tsx
  packages/editor/lite-text-editor/src/ui/menus/fixed-menu/index.tsx
Labels: 🐛bug, 🌟enhancement, 🌐frontend, ✍️editor

#3767 [WEB-536] fix: analytics highlight while switching between `scope_and_demand` and `custom` tab.
  web/constants/dashboard.ts
Labels: 🌐frontend, 🎨UI / UX

#3750 [WEB-507] fix: cycle lead details not visible
  packages/types/src/cycles.d.ts
  web/components/analytics/custom-analytics/sidebar/sidebar-header.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/sidebar.tsx
Labels: 🐛bug, 🌐frontend

#3753 [WEB-512] fix: date inputs keyboard navigation
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#3762 [WEB-532] fix: email notification assignees
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/bgtasks/email_notification_task.py
Labels: 🐛bug, ⚙️backend

#3768 [WEB-540] fix: hide `sub_issue`, `link`, `attachment` property from list/ kanban view if their count is 0.
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/sub-issue-column.tsx
Labels: 🌐frontend, 🎨UI / UX

#3774 [WEB-476] chore: max length validation added in user name inputs
  web/components/onboarding/user-details.tsx
  web/pages/profile/index.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3769 [WEB-539] style: add background to user email in dashboard dropdown for better UX on workspace list scroll.
  web/components/workspace/sidebar-dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX

#3770 [WEB-541] fix: calendar misalignment because of scrollbar
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/week-header.tsx
Labels: 🐛bug, 🌐frontend

#3764 [WEB-506] style: add right padding to sidebar projects list
  web/components/project/sidebar-list.tsx
Labels: 🌐frontend, 🎨UI / UX

#3771 [WEB-517] bug: workspace view navbar scroll to view improvement
  web/components/workspace/views/header.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3773 [WEB-542] fix: project draft issue button
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/draft-issues/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3763 [WEB-513] chore: issue due date highlight logic
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/peek-overview/properties.tsx
  web/helpers/issue.helper.ts
Labels: 🌐frontend, 🌟improvement

#3785 chore: fix sentry profiling rate
  apiserver/plane/settings/common.py
Labels: 🧹chore

#3783 [WEB-552] fix: Gantt chart scroll container height
  web/components/gantt-chart/chart/main-content.tsx
Labels: 🌐frontend, 🎨UI / UX

#3789 [WEB-553] fix: cycle select dropdown issue layout overflow
  web/components/dropdowns/cycle.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3788 [WEB-509] fix: issue sidebar label overflow
  web/components/issues/issue-detail/label/label-list-item.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3780 [WEB-495] chore: issue title improvement
  web/components/issues/title-input.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3792 [WEB-555] fix: profile sidebar layout
  web/layouts/user-profile-layout/layout.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3793 [WEB-556] fix: cycle store get completed cycle function updated
  web/store/cycle.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3795 [WEB-544] fix: dashboard issues widget tab rendering bug
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/issue-panels/issues-list.tsx
Labels: 🐛bug, 🌐frontend

#3796 [WEB-496] fix: issue comment
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
  web/helpers/string.helper.ts
  web/package.json
  yarn.lock
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3804 [WEB-552] fix: Gantt chart unnecessary overflow
  web/components/gantt-chart/chart/views/month.tsx
  yarn.lock
Labels: 🐛bug, 🌐frontend

#3803 [WEB-565] chore: inbox layout loader and peek overview subscription improvement
  web/components/issues/issue-detail/subscription.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3787 [WEB-493] chore: custom search select input key down improvement
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/state.tsx
  web/components/issues/issue-detail/label/select/label-select.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3806 [INFRA-7] feat: selective build
  .github/workflows/build-branch.yml
Labels: devops

#3766 [WEB-533] chore: posthog key validation
  apiserver/plane/app/views/config.py
Labels: ⚙️backend, 🌟improvement

#3807 [WEB-572] chore: sequence id search in the issue search
  apiserver/plane/utils/issue_search.py
Labels: ⚙️backend, 🌟improvement

#3808 [WEB-560] chore: onboarding improvement
  web/components/onboarding/user-details.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#3809 [WEB-581] fix: issue editing functionality enhancement in Create/Edit modal
  apiserver/plane/app/views/issue.py
  web/components/inbox/inbox-issue-actions.tsx
  web/components/issues/issue-detail/inbox/root.tsx
  web/components/issues/issue-detail/inbox/sidebar.tsx
  web/components/issues/issue-detail/label/root.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/peek-overview/root.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archived-issues/[archivedIssueId].tsx
  web/services/issue/issue_draft.service.ts
  web/store/inbox/inbox_issue.store.ts
  web/store/issue/draft/issue.store.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/root.store.ts
Labels: 🐛bug, 🌐frontend, ⚙️backend

#3820 [WEB-590] chore: project member active
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/issue.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/state.py
  apiserver/plane/app/views/cycle.py
  apiserver/plane/app/views/integration/slack.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/app/views/module.py
  apiserver/plane/app/views/page.py
  apiserver/plane/app/views/search.py
  apiserver/plane/app/views/state.py
  apiserver/plane/app/views/view.py
  apiserver/plane/app/views/workspace.py
  apiserver/plane/bgtasks/export_task.py
Labels: 🐛bug, ⚙️backend

#3805 [WEB-575] chore: safely re-enable SWR
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/cycle/cycle-options.tsx
  web/components/dropdowns/cycle/index.tsx
  web/components/dropdowns/member/index.ts
  web/components/dropdowns/member/index.tsx
  web/components/dropdowns/member/member-options.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module/index.tsx
  web/components/dropdowns/module/module-options.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/issue-detail/inbox/sidebar.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/draft-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/assignee-column.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/cycle-root.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/sub-issues/properties.tsx
  web/components/labels/index.ts
  web/components/labels/labels-list-modal.tsx
  web/components/modules/form.tsx
  web/components/modules/sidebar.tsx
  web/components/profile/profile-issues.tsx
  web/components/project/create-project-modal.tsx
  web/constants/swr-config.ts
  web/hooks/use-workspace-issue-properties.ts
  web/layouts/app-layout/layout.tsx
  web/layouts/auth-layout/project-wrapper.tsx
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/store/cycle.store.ts
  web/store/module.store.ts
  web/store/project/project.store.ts
Labels: 🌐frontend, 🛠️refactor

#3812 [WEB-127] fix: issue with command palette outside click detection.
  web/components/command-palette/command-modal.tsx
Labels: 🌐frontend, 🎨UI / UX

#3817 [WEB-582] chore: issue comment edit validation
  web/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3821 [WEB-580] chore: issue peek overview improvement
  web/components/issues/peek-overview/view.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3819 [WEB-587] chore: inbox issue detail activity and comment initial load improvement
  web/components/issues/issue-detail/inbox/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#2125 Add support for Claude-2, Cohere Llama2, CodeLlama, Azure OpenAI, Replicate LLMs (100+LLMs)
  apiserver/plane/app/views/external.py
  apiserver/requirements/base.txt
Labels: ⚙️backend, 🔗integrations, ⚙️config changes

#3826 [WEB-592] chore: update issue start and due date icons across the platform
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/due-date-column.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/start-date-column.tsx
  web/components/issues/peek-overview/properties.tsx
  web/constants/spreadsheet.ts
Labels: 🌐frontend, 🌟improvement

#3827 [WEB-591] fix: navigating to a page through Cmd K throws error
  web/hooks/store/use-page.ts
Labels: 🐛bug, 🌐frontend

#3825 [WEB-562] chore: spreadsheet layout dropdown z index improvement
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3829 [WEB-594] fix: app sidebar toggle
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/help-section.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-menu.tsx
  web/layouts/app-layout/sidebar.tsx
  web/layouts/settings-layout/profile/sidebar.tsx
  web/store/application/theme.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#3833 [WEB-586] chore: spreadsheet layout dropdowns focus on toggle functionality added
  web/components/dropdowns/cycle/index.tsx
  web/components/dropdowns/member/index.tsx
Labels: 🌟enhancement, 🌐frontend, 🌟improvement, 🧹chore
