Repository makeplane/plane, pull requests merged in 2024-10, with the labels that each got.

#5743 [WEB-2593] fix: Duplicate Issue layout change update calls
  web/core/components/issues/issue-layouts/filters/header/layout-selection.tsx
Labels: 🐛bug, 🌐frontend

#5590 [WEB-2213] fix: group by persistence for list view
  web/core/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/core/components/issues/issue-layouts/kanban/headers/sub-group-by-card.tsx
  web/core/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/core/components/issues/issue-layouts/list/base-list-root.tsx
  web/core/components/issues/issue-layouts/list/default.tsx
  web/core/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/store/issue/archived/filter.store.ts
  web/core/store/issue/cycle/filter.store.ts
  web/core/store/issue/draft/filter.store.ts
  web/core/store/issue/helpers/issue-filter-helper.store.ts
  web/core/store/issue/module/filter.store.ts
  web/core/store/issue/profile/filter.store.ts
  web/core/store/issue/project-views/filter.store.ts
  web/core/store/issue/workspace/filter.store.ts
Labels: 🐛bug, ✨feature, 🌐frontend

#5688 [WEB-2520] fix-Sorted Icon Not Updating Dynamically in Spreadsheet View
  web/core/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
Labels: 🐛bug, 🌐frontend, 🌐web

#5766 [WEB-2604] chore: only admin can changed the project settings
  apiserver/plane/app/views/project/base.py
Labels: 🐛bug, ⚙️backend

#5619 fix: drag handle scrolling fixed
  packages/editor/src/core/extensions/side-menu.tsx
  packages/editor/src/core/plugins/drag-handle.ts
Labels: ✍️editor

#5661 [WEB-2433] chore-Update name of the Layout
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/mobile-header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/mobile-header.tsx
  web/core/constants/cycle.ts
  web/core/constants/issue.ts
  web/core/constants/module.ts
Labels: 🌟enhancement, 🌐frontend, 🌐web, 🧹chore

#5685 [WEB-2532] fix: custom theme mutation logic
  web/app/profile/appearance/page.tsx
  web/core/lib/wrappers/store-wrapper.tsx
  web/helpers/theme.helper.ts
Labels: 🌐frontend, 🌟improvement

#5749 [WEB-2388] fix: workspace draft issues migration
  apiserver/plane/api/views/cycle.py
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/draft.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/urls/workspace.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/cycle/issue.py
  apiserver/plane/app/views/dashboard/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/workspace/draft.py
  apiserver/plane/app/views/workspace/user.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/db/migrations/0077_draftissue_cycle_user_timezone_project_user_timezone_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/draft.py
  apiserver/plane/db/models/project.py
  apiserver/plane/utils/analytics_plot.py
Labels: ⚙️backend, 🔄migrations

#5751 [WEB-2306] chore: IssueParentDetail added to issue peekoverview
  web/core/components/issues/peek-overview/issue-detail.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5705 [PE-45] feat: page export as PDF & Markdown
  packages/editor/src/styles/editor.css
  packages/ui/src/modals/constants.ts
  web/core/components/editor/index.ts
  web/core/components/editor/pdf/document.tsx
  web/core/components/editor/pdf/index.ts
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/title.tsx
  web/core/components/pages/modals/export-page-modal.tsx
  web/core/components/pages/modals/index.ts
  web/core/constants/editor.ts
  web/helpers/common.helper.ts
  web/helpers/editor.helper.ts
  web/helpers/file.helper.ts
  web/package.json
  web/public/fonts/inter/bold-italic.ttf
  web/public/fonts/inter/bold.ttf
  web/public/fonts/inter/heavy-italic.ttf
  web/public/fonts/inter/heavy.ttf
  web/public/fonts/inter/light-italic.ttf
  web/public/fonts/inter/light.ttf
  web/public/fonts/inter/medium-italic.ttf
  web/public/fonts/inter/medium.ttf
  web/public/fonts/inter/regular-italic.ttf
  web/public/fonts/inter/regular.ttf
  web/public/fonts/inter/semibold-italic.ttf
  web/public/fonts/inter/semibold.ttf
  web/public/fonts/inter/thin-italic.ttf
  web/public/fonts/inter/thin.ttf
  web/public/fonts/inter/ultrabold-italic.ttf
  web/public/fonts/inter/ultrabold.ttf
  web/public/fonts/inter/ultralight-italic.ttf
  web/public/fonts/inter/ultralight.ttf
  yarn.lock
Labels: ✨feature, 🌐frontend, pages

#5759 [WEB-2380] chore: cycle sidebar refactor
  web/ce/components/cycles/analytics-sidebar/base.tsx
  web/ce/components/cycles/analytics-sidebar/index.ts
  web/ce/components/cycles/analytics-sidebar/root.tsx
  web/ce/components/cycles/analytics-sidebar/sidebar-chart.tsx
  web/core/components/cycles/analytics-sidebar/issue-progress.tsx
  web/core/components/cycles/analytics-sidebar/sidebar-details.tsx
Labels: 🌐frontend, 🧹chore

#5761 [WEB-2603] fix: remove validation of roles from the live server
  live/src/ce/lib/authentication.ts
  live/src/core/hocuspocus-server.ts
  live/src/core/lib/authentication.ts
  live/src/core/services/user.service.ts
Labels: pages

#5770 [WEB-2555] fix: add "mark all as read" in the notifications header
  web/core/components/workspace-notifications/sidebar/header/options/menu-option/root.tsx
  web/core/components/workspace-notifications/sidebar/header/options/root.tsx
Labels: ✨feature, 🌐frontend

#5773 [PE-45] refactor: page export components
  web/core/components/pages/modals/export-page-modal.tsx
  web/core/constants/editor.ts
  web/helpers/editor.helper.ts
  web/helpers/file.helper.ts
Labels: 🌐frontend, pages

#5653 [WEB-2494] feat: text color and highlight options for all editors
  packages/editor/package.json
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/index.ts
  packages/editor/src/core/components/menus/bubble-menu/link-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/node-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/constants/common.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/slash-commands.tsx
  packages/editor/src/core/extensions/slash-commands/command-items-list.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu-item.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu.tsx
  packages/editor/src/core/extensions/slash-commands/index.ts
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/slash-commands-suggestion.ts
  packages/editor/src/index.ts
  space/core/components/editor/lite-text-editor.tsx
  space/core/components/editor/toolbar.tsx
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/editor/lite-text-editor/toolbar.tsx
  web/core/components/pages/editor/header/color-dropdown.tsx
  web/core/components/pages/editor/header/index.ts
  web/core/components/pages/editor/header/toolbar.tsx
  yarn.lock
Labels: ✨feature, 🌐frontend, ✍️editor

#5760 [WEB-2601] improvement: add click to copy issue identifier on peek-overview and issue detail page.
  web/ce/components/issues/issue-details/issue-identifier.tsx
  web/ce/components/issues/issue-details/issue-type-switcher.tsx
Labels: 🌐frontend, 🌟improvement

#5790 fix: only admins can delete a project
  apiserver/plane/app/views/project/base.py
Labels: 🐛bug, ⚙️backend

#5795 fix: workspace draft build
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/workspace-draft-root.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/pages/editor/header/color-dropdown.tsx
  web/core/hooks/use-group-dragndrop.ts
  web/core/hooks/use-issues-actions.tsx
  web/core/services/issue/workspace_draft.service.ts
  web/core/store/issue/root.store.ts
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🌐frontend

#5798 fix: workspace drafts build
  web/core/components/issues/workspace-draft/draft-issue-block.tsx
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🌐frontend

#5800 [WEB-2388] fix: workspace draft issues
  apiserver/plane/app/serializers/draft.py
  web/app/[workspaceSlug]/(projects)/drafts/header.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/workspace-draft/root.tsx
  web/core/store/issue/root.store.ts
  web/core/store/issue/workspace-draft/issue.store.ts
  web/public/empty-state/workspace-draft/issue-dark.webp
  web/public/empty-state/workspace-draft/issue-light.webp
Labels: 🌐frontend, 🧹chore

#5786 [WEB-2494] dev: custom text color and background color extensions
  packages/editor/package.json
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/constants/common.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/custom-background-color.ts
  packages/editor/src/core/extensions/custom-text-color.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/slash-commands/command-items-list.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu.tsx
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/index.ts
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/variables.css
  web/core/components/pages/editor/header/color-dropdown.tsx
  yarn.lock
Labels: ✨feature, 🌐frontend, ✍️editor

#5808 [WEB-2388] chore: workspace draft issue improvements
  apiserver/plane/app/views/workspace/draft.py
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/issue-modal/modal.tsx
  web/core/components/issues/workspace-draft/quick-action.tsx
Labels: 🌐frontend, ⚙️backend, 🌟improvement, 🧹chore

#5809 [WEB-2388] fix: workspace draft issues count
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🌐frontend

#5810 [WEB-2622] fix: intake exception error
  web/core/components/inbox/content/root.tsx
Labels: 🐛bug, 🌐frontend

#5820 [WEB-2616] fix: issue widget attachment
  web/core/components/issues/issue-detail-widgets/attachments/quick-action-button.tsx
Labels: 🐛bug, 🌐frontend

#5822 [WEB-2629] fix: workspace draft delete and move mutation
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/workspace-draft-root.tsx
  web/core/components/issues/workspace-draft/root.tsx
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5825 [WEB-2629] chore: workspace draft issue ux copy updated
  web/app/[workspaceSlug]/(projects)/drafts/header.tsx
  web/core/components/issues/confirm-issue-discard.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/workspace-draft/delete-modal.tsx
  web/core/components/issues/workspace-draft/draft-issue-block.tsx
  web/core/constants/empty-state.ts
Labels: 🌐frontend, 🧹chore

#5829 [WEB-2631] chore: changed the cascading logic for soft delete
  apiserver/plane/app/views/workspace/draft.py
  apiserver/plane/bgtasks/deletion_task.py
  apiserver/plane/db/models/project.py
Labels: 🐛bug, ⚙️backend

#5834 [WEB-2676 ] fix: workspace draft move to project
  web/core/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#5836 [WEB-2677] chore: draft issue issue type
  web/ce/components/issues/issue-modal/additional-properties.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/context/issue-modal.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/issue-modal/form.tsx
Labels: 🌐frontend, 🧹chore

#5837 [WEB-2626] chore: removed the deleted issue's count
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/workspace/cycle.py
  apiserver/plane/utils/analytics_plot.py
Labels: ⚙️backend

#5833 chore: delete deprecated tables
  apiserver/plane/db/migrations/0081_remove_globalview_created_by_and_more.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/issue_type.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/view.py
  apiserver/plane/utils/paginator.py
Labels: ⚙️backend

#5818 dev: move storage metadata collection to background job
  apiserver/plane/app/views/asset/v2.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/issue/attachment.py
  apiserver/plane/bgtasks/storage_metadata_task.py
  apiserver/plane/settings/storage.py
  apiserver/plane/space/views/asset.py
  deploy/selfhost/docker-compose.yml
  nginx/nginx.conf.dev
  nginx/nginx.conf.template
Labels: 🐛bug, ⚙️backend

#5843 [WEB-2682] fix: delete project mutation and workspace draft header validation
  web/app/[workspaceSlug]/(projects)/drafts/header.tsx
  web/core/store/project/project.store.ts
Labels: 🌐frontend, 🧹chore

#5849 fix: draft issue asset conversion to issue
  apiserver/plane/app/views/workspace/draft.py
Labels: ⚙️backend

#5848 [WEB-2679] fix: draft issue empty state flicker
  web/core/components/issues/workspace-draft/root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5852 fix: color extension not working on issue description and published page
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/custom-background-color.ts
  packages/editor/src/core/extensions/custom-color.ts
  packages/editor/src/core/extensions/custom-text-color.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.tsx
Labels: 🐛bug, 🌐frontend

#5854 [WEB-2686] chore: added draft cycle and module in draft issue
  apiserver/plane/app/views/workspace/draft.py
Labels: ⚙️backend

#5844 [WEB-2680] chore: updated queryset for soft delete
  apiserver/plane/api/serializers/issue.py
  apiserver/plane/app/serializers/draft.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/db/mixins.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/space/serializer/issue.py
Labels: ⚙️backend, 🌟improvement

#5855 [WEB-2625] chore: workspace favorite and draft improvement
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/views/workspace/member.py
  packages/types/src/workspace.d.ts
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
  web/core/components/workspace/sidebar/user-menu.tsx
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🌐frontend, 🧹chore

#5846 [WEB-2448] chore: workspace collaborators improvements
  web/core/components/dashboard/widgets/recent-collaborators/collaborators-list.tsx
Labels: 🌐frontend, 🧹chore

#5857 fix: improvements for project types.
  web/core/components/dropdowns/project.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/services/project/project.service.ts
  web/core/store/project/project.store.ts
  web/helpers/project.helper.ts
Labels: 🌟improvement

#5875 [WEB-2696] fix: unable to view intake issue
  apiserver/plane/app/views/inbox/base.py
Labels: ⚙️backend

#5842 [WEB-2681] fix: module progress indicator
  web/core/components/modules/module-card-item.tsx
  web/core/components/modules/module-list-item.tsx
Labels: 🌐frontend, 🧹chore

#5879 [WEB-2695] chore: urgent priority icon improvement
  packages/ui/src/icons/priority-icon.tsx
  web/core/components/dropdowns/priority.tsx
Labels: 🌐frontend, 🧹chore

#5887 fix: bucket policy script to handle error conditions
  apiserver/plane/db/management/commands/update_bucket.py
Labels: ⚙️backend, devops

#5864 [PE-68] fix: markdown transformation of mention and custom image components
  packages/editor/src/core/extensions/custom-image/custom-image.ts
  packages/editor/src/core/extensions/custom-image/read-only-custom-image.ts
  packages/editor/src/core/extensions/mentions/extension.tsx
  web/ce/components/pages/editor/embed/issue-embed-upgrade-card.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, ✍️editor

#5889 [WEB-2707] fix: draft issue module update and code refactor
  web/core/components/issues/workspace-draft/draft-issue-block.tsx
  web/core/components/issues/workspace-draft/draft-issue-properties.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5891 [WEB-2709] chore: intake issue navigation improvement
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/description-input.tsx
  web/core/store/inbox/inbox-issue.store.ts
Labels: 🌐frontend, 🧹chore

#5900 [WEB-2709] fix: intake issue description and navigation
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/description-input.tsx
  web/core/store/inbox/inbox-issue.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5902 [WEB-2715] fix: draft issue type update outside click
  web/core/components/issues/issue-modal/base.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5888 [WEB-2333] chore: intake issue back date snooze disabled
  web/core/components/inbox/modals/snooze-issue-modal.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5881 [WEB-2499] fix: project state setting dnd
  web/core/components/project-states/state-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5802 [WEB-2606] fix: project members shouldn't be able to change others roles
  web/core/components/project/settings/member-columns.tsx
Labels: 🐛bug, 🌐frontend

#5789 [WEB-2609] fix: inconsistent background colour of hamburger menu in inbox
  web/core/components/workspace-notifications/sidebar/header/options/menu-option/root.tsx
Labels: 🐛bug, 🌐frontend

#5787 [WEB-2587] fix: hide log work button for guest user
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🐛bug, 🌐frontend

#5920 [WEB-2723] fix: callout content not being saved in description html
  packages/editor/src/core/extensions/callout/extension-config.ts
Labels: 🐛bug, 🌐frontend, ✍️editor

#5922 [WEB-2442] fix: Timeline Improvements and bug fixes
  web/ce/store/timeline/base-timeline.store.ts
  web/core/components/gantt-chart/blocks/block-row.tsx
  web/core/components/gantt-chart/chart/main-content.tsx
  web/core/components/gantt-chart/chart/root.tsx
  web/core/components/gantt-chart/data/index.ts
  web/core/components/gantt-chart/helpers/blockResizables/left-resizable.tsx
  web/core/components/gantt-chart/helpers/blockResizables/right-resizable.tsx
  web/core/components/gantt-chart/helpers/blockResizables/use-gantt-resizable.ts
  web/core/components/gantt-chart/views/helpers.ts
  web/core/components/gantt-chart/views/month-view.ts
  web/core/components/gantt-chart/views/quarter-view.ts
  web/core/components/gantt-chart/views/week-view.ts
  web/core/hooks/use-auto-scroller.tsx
  web/core/store/timeline/issues-timeline.store.ts
  web/core/store/timeline/modules-timeline.store.ts
Labels: 🌐frontend, 🌟improvement

#5921 [WEB-2725] chore: app sidebar add issue button improvement
  web/core/components/workspace/sidebar/quick-actions.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5924 [WEB-2723] fix: change html tag name for editor callout component
  packages/editor/src/core/extensions/callout/extension-config.ts
  packages/editor/src/core/extensions/callout/types.ts
  packages/editor/src/core/extensions/callout/utils.ts
  yarn.lock
Labels: 🐛bug, 🌐frontend, ✍️editor

#5926 [WEB-2442] chore: Refactor timeline store
  web/ce/store/issue/issue-details/activity.store.ts
  web/ce/store/root.store.ts
  web/ce/store/timeline/base-timeline.store.ts
  web/ce/store/timeline/index.ts
  web/core/components/gantt-chart/contexts/index.tsx
  web/core/components/gantt-chart/sidebar/utils.ts
  web/core/components/gantt-chart/types/index.ts
  web/core/hooks/use-timeline-chart.ts
  web/core/store/issue/root.store.ts
  web/core/store/root.store.ts
  web/core/store/timeline/index.ts
  web/core/store/timeline/issues-timeline.store.ts
  web/core/store/timeline/modules-timeline.store.ts
Labels: 🌐frontend, 🧹chore

#5928 chore: code refactoring
  packages/types/src/de-dupe.d.ts
  packages/types/src/index.d.ts
  web/ce/components/de-dupe/duplicate-modal/index.ts
  web/ce/components/de-dupe/duplicate-modal/root.tsx
  web/ce/components/de-dupe/duplicate-popover/index.ts
  web/ce/components/de-dupe/duplicate-popover/root.tsx
  web/ce/components/de-dupe/index.ts
  web/ce/components/de-dupe/issue-block/button-label.tsx
  web/ce/components/de-dupe/issue-block/index.ts
  web/ce/hooks/use-debounced-duplicate-issues.tsx
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/inbox/modals/create-modal/create-root.tsx
  web/core/components/inbox/modals/create-modal/modal.tsx
  web/core/components/issues/archive-issue-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/peek-overview/issue-detail.tsx
  web/helpers/editor.helper.ts
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#5877 [WEB-2449] fix: admin is not able to edit issues in notifications peek overview
  web/core/components/inbox/content/root.tsx
Labels: 🐛bug, 🌐frontend

#5929 [WEB-2442] chore: minor build fix
  web/core/store/issue/issue-details/root.store.ts
Labels: 🌐frontend, 🧹chore

#5876 fix: integrity error on account creation
  apiserver/plane/authentication/adapter/oauth.py
Labels: ⚙️backend, 🔐authentication

#5913 [WEB-2729] chore: updated live server auth cookies handling
  live/src/core/extensions/index.ts
  live/src/core/hocuspocus-server.ts
  live/src/core/lib/authentication.ts
  live/src/core/types/common.d.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/types/editor.ts
Labels: 🧹chore
