Repository makeplane/plane, pull requests merged in 2024-11, with the labels that each got.

#5945 [WEB-2732] fix: global css conflicts
  packages/editor/src/styles/editor.css
Labels: 🐛bug

#5946 [WEB-2442] fix : Timeline layout bugs
  apiserver/plane/app/views/issue/relation.py
  web/ce/components/relations/activity.ts
  web/ce/components/relations/index.tsx
  web/core/components/gantt-chart/blocks/block-row-list.tsx
  web/core/components/gantt-chart/blocks/block-row.tsx
  web/core/components/gantt-chart/chart/main-content.tsx
  web/core/components/gantt-chart/chart/root.tsx
  web/core/components/gantt-chart/chart/views/month.tsx
  web/core/components/gantt-chart/chart/views/quarter.tsx
  web/core/components/gantt-chart/chart/views/week.tsx
  web/core/components/gantt-chart/views/month-view.ts
  web/core/components/gantt-chart/views/quarter-view.ts
  web/core/components/gantt-chart/views/week-view.ts
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-collapsibles.tsx
  web/core/components/issues/issue-detail-widgets/relations/content.tsx
  web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/relations/title.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/relation.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
  web/core/components/issues/issue-detail/relation-select.tsx
  web/core/store/issue/issue-details/relation.store.ts
  web/helpers/array.helper.ts
Labels: 🐛bug, 🌐frontend, ⚙️backend

#5948 [WEB-2734] fix: Issues fetching with change in filters
  web/core/local-db/storage.sqlite.ts
Labels: 🐛bug, 🌐frontend

#5949 [PE-73] fix: floating toolbar max width
  packages/editor/src/styles/editor.css
Labels: 🐛bug, 🌐frontend, ✍️editor

#5954 fix: wrong token being passed in the read-only editor
  packages/editor/src/core/hooks/use-read-only-collaborative-editor.ts
Labels: 🐛bug, 🌐frontend, ✍️editor

#5847 [PULSE-42] feat: text alignment for all editors
  packages/editor/package.json
  packages/editor/src/core/components/menus/bubble-menu/alignment-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/node-selector.tsx
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu.tsx
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/extensions/text-align.ts
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/slash-commands-suggestion.ts
  space/core/components/editor/lite-text-editor.tsx
  space/core/components/editor/toolbar.tsx
  space/core/components/issues/peek-overview/comment/add-comment.tsx
  space/core/constants/editor.ts
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/editor/lite-text-editor/toolbar.tsx
  web/core/components/pages/editor/header/color-dropdown.tsx
  web/core/components/pages/editor/header/toolbar.tsx
  web/core/constants/editor.ts
  yarn.lock
Labels: ✨feature, 🌐frontend, ✍️editor

#5955 [WEB-2734] fix: Add missing config to get issues api call
  web/core/local-db/storage.sqlite.ts
Labels: 🌐frontend

#5950 chore: intake migration
  apiserver/plane/db/migrations/0084_remove_label_label_unique_name_project_when_deleted_at_null_and_more.py
  apiserver/plane/db/models/deploy_board.py
  apiserver/plane/db/models/inbox.py
  apiserver/plane/db/models/label.py
  apiserver/plane/db/models/user.py
Labels: ⚙️backend, 🔄migrations

#5964 [WEB-2738] chore: app sidebar behaviour
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/root.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
Labels: 🌐frontend, 🧹chore

#5971 [WEB-2742] chore: issue link ui revamp
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/components/issues/issue-detail/links/link-list.tsx
Labels: 🌐frontend, 🧹chore

#5974 fix: memoize user config before passing it to the editor
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  web/core/components/pages/editor/editor-body.tsx
Labels: 🐛bug, 🌐frontend, pages

#5972 [WEB-2442] fix: Issue detail activity for related to relation
  web/ce/components/relations/activity.ts
Labels: 🐛bug, 🌐frontend

#5981 [WEB-2743] chore: restrict sub-issue to have different project id than parent
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/issue-modal/modal.tsx
Labels: 🌐frontend, 🌟improvement

#5976 style: remove unnecessary bottom padding from the rich text editor
  web/core/components/editor/rich-text-editor/rich-text-editor.tsx
Labels: 🌐frontend, 🎨UI / UX, ✍️editor

#5984 chore: filter the deleted assignee from the issue
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend

#5982 [WEB-2401] chore: worklog enhancements
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🌟enhancement, 🌐frontend

#5988 [WEB-2628] fix: Sorting by estimates
  packages/types/src/view-props.d.ts
  web/core/constants/spreadsheet.ts
  web/core/local-db/storage.sqlite.ts
  web/core/local-db/utils/load-workspace.ts
  web/core/local-db/utils/query-constructor.ts
  web/core/local-db/utils/query.utils.ts
  web/core/store/issue/helpers/base-issues.store.ts
Labels: 🐛bug, 🌐frontend

#5987 [WEB-2442] feat: Minor Timeline view Enhancements
  web/ce/store/timeline/base-timeline.store.ts
  web/core/components/gantt-chart/blocks/block-row.tsx
  web/core/components/gantt-chart/blocks/block.tsx
  web/core/components/gantt-chart/chart/main-content.tsx
  web/core/components/gantt-chart/chart/views/month.tsx
  web/core/components/gantt-chart/chart/views/quarter.tsx
  web/core/components/gantt-chart/chart/views/week.tsx
  web/core/components/gantt-chart/constants.ts
  web/core/components/gantt-chart/helpers/blockResizables/use-gantt-resizable.ts
  web/core/components/gantt-chart/sidebar/gantt-dnd-HOC.tsx
  web/core/components/gantt-chart/sidebar/issues/block.tsx
  web/core/components/gantt-chart/sidebar/modules/block.tsx
  web/core/components/gantt-chart/views/helpers.ts
  web/core/components/issues/issue-layouts/gantt/blocks.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/components/modules/gantt-chart/blocks.tsx
Labels: 🐛bug, 🌟enhancement, 🌐frontend

#5994 fix: issue and module link validation
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/links/root.tsx
  web/core/components/modules/links/create-update-modal.tsx
Labels: 🐛bug, 🌐frontend

#6068 [WEB-2765] fix: issue detail page unnecessary scroll
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/layout.tsx
  web/core/components/core/content-wrapper.tsx
  web/core/components/issues/issue-detail/root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6082 [WEB-2778] chore: private project join restriction
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/project/invite.py
  web/core/layouts/auth-layout/project-wrapper.tsx
Labels: ⚙️backend

#6081 [WEB-2776] fix: restrict notifications
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/utils/issue_filters.py
Labels: ⚙️backend

#6084 chore: management command to add user to a project
  apiserver/plane/db/management/commands/create_project_member.py
Labels: ⚙️backend

#6086 chore: remove check for already existing project member
  apiserver/plane/db/management/commands/create_project_member.py
Labels: ⚙️backend

#6091 [WEB-2781] fix: project view application error
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/page.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6087 [WEB - 2779] feat: Added sort order for issue activity
  web/ce/components/issues/worklog/activity/sort-root.tsx
  web/ce/store/issue/issue-details/activity.store.ts
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🌟enhancement, 🌐frontend

#6095 [WEB-2432]fix: project not found state and error page alignment
  web/app/error.tsx
  web/core/constants/empty-state.ts
  web/core/layouts/auth-layout/project-wrapper.tsx
Labels: 🐛bug, 🌐frontend

#6078 [WEB-2774] Chore: re-ordering functionality for entities in favorites.
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/root.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/favorites/favorites.helpers.ts
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/store/favorite.store.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#6116 [WEB-2795]chore:removed header links for project bread crumb inside project detail and list
  packages/types/src/issues/issue.d.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/ce/components/projects/settings/intake/header.tsx
  web/core/local-db/storage.sqlite.ts
Labels: 🌟enhancement, 🌐frontend
