Repository makeplane/plane, pull requests merged in 2024-08, with the labels that each got.

#5280 [WEB-1999] dev: interactive active cycle stats
  web/core/components/core/list/list-item.tsx
  web/core/components/cycles/active-cycle/cycle-stats.tsx
  web/core/components/cycles/active-cycle/progress.tsx
  web/core/components/cycles/active-cycle/root.tsx
  web/core/components/cycles/list/cycle-list-item-action.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#5282 [WEB-2123] chore: hard delete favorites
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/view/base.py
Labels: ⚙️backend

#5283 [WEB-2144] fix: project intake store
  web/core/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5286 [WEB-2092] chore: soft delete migration
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/search/issue.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/db/migrations/0073_alter_commentreaction_unique_together_and_more.py
  apiserver/plane/db/migrations/0073_analyticview_deleted_at_apiactivitylog_deleted_at_and_more.py
  apiserver/plane/db/migrations/0074_alter_label_unique_together_and_more.py
  apiserver/plane/db/models/cycle.py
  apiserver/plane/db/models/dashboard.py
  apiserver/plane/db/models/deploy_board.py
  apiserver/plane/db/models/estimate.py
  apiserver/plane/db/models/favorite.py
  apiserver/plane/db/models/inbox.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/issue_type.py
  apiserver/plane/db/models/module.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/project.py
  apiserver/plane/db/models/state.py
  apiserver/plane/db/models/workspace.py
  web/public/sw.js.map
Labels: ⚙️backend, 🔄migrations

#5289 [WEB-2146] fix: fetch issue activity on peek issue update
  web/core/components/issues/peek-overview/root.tsx
Labels: 🐛bug, 🌐frontend

#5293 [WEB-2165] fix: casing throughout the platform
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/inbox/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/workspace-views/header.tsx
  web/core/components/core/modals/link-modal.tsx
  web/core/components/cycles/delete-modal.tsx
  web/core/components/cycles/form.tsx
  web/core/components/dropdowns/member/index.tsx
  web/core/components/estimates/empty-screen.tsx
  web/core/components/inbox/modals/accept-issue-modal.tsx
  web/core/components/inbox/modals/create-edit-modal/create-root.tsx
  web/core/components/inbox/modals/decline-issue-modal.tsx
  web/core/components/inbox/modals/delete-issue-modal.tsx
  web/core/components/inbox/modals/index.ts
  web/core/components/integration/delete-import-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail/cycle-select.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/module-select.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/peek-overview/properties.tsx
  web/core/components/modules/delete-module-modal.tsx
  web/core/components/modules/form.tsx
  web/core/components/pages/modals/delete-page-modal.tsx
  web/core/components/pages/modals/page-form.tsx
  web/core/components/project/create-project-form.tsx
  web/core/components/project/send-project-invitation-modal.tsx
  web/core/components/views/delete-view-modal.tsx
  web/core/components/views/form.tsx
  web/core/components/workspace/views/delete-view-modal.tsx
  web/public/sw.js.map
Labels: 🌐frontend, 🌟improvement

#5290 [WEB-1887] chore: Optimistically update cycle and module distributions
  web/core/components/core/sidebar/progress-chart.tsx
  web/core/constants/state.ts
  web/core/store/cycle.store.ts
  web/core/store/estimates/project-estimate.store.ts
  web/core/store/issue/archived/issue.store.ts
  web/core/store/issue/cycle/issue.store.ts
  web/core/store/issue/draft/issue.store.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/module/issue.store.ts
  web/core/store/issue/profile/issue.store.ts
  web/core/store/issue/project-views/issue.store.ts
  web/core/store/issue/project/issue.store.ts
  web/core/store/issue/workspace/issue.store.ts
  web/core/store/module.store.ts
  web/helpers/distribution-update.helper.ts
Labels: 🌐frontend

#5297 [WEB-2168] fix: yjs duplicate import error
  web/next.config.js
Labels: 🌐frontend, 🌟improvement

#5296 [WEB-2166] chore: smoother drag experience in the document editor
  packages/editor/src/core/extensions/drag-drop.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/styles/drag-drop.css
  web/next.config.js
  web/public/sw.js.map
Labels: 🌐frontend, 🌟improvement, ✍️editor

#5300 [WEB-2173] fix: app sidebar spacing and build error
  admin/app/general/form.tsx
  admin/app/general/intercom.tsx
  web/app/[workspaceSlug]/(projects)/sidebar.tsx
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5299 [WEB-2134] chore: modify cycle options
  web/core/components/dropdowns/cycle/cycle-options.tsx
  web/core/components/dropdowns/cycle/index.tsx
Labels: 🌐frontend

#5304 [WEB-1907] fix: fav feature review changes
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-item.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/store/cycle.store.ts
  web/core/store/favorite.store.ts
  web/core/store/module.store.ts
  web/core/store/project-view.store.ts
  web/core/store/project/project.store.ts
Labels: 🐛bug, 🌐frontend

#5302 [WEB-2092] chore: favorite delete changes
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/project.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/view/base.py
Labels: ⚙️backend, 🌟improvement

#5315 [WEB-2183] fix: delete action mutation
  web/core/store/cycle.store.ts
  web/core/store/module.store.ts
  web/core/store/pages/project-page.store.ts
  web/core/store/project-view.store.ts
  web/core/store/project/project.store.ts
Labels: 🐛bug, 🌐frontend

#5312 feat: added endpoint for creating service tokens
  apiserver/plane/app/urls/api.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/api.py
Labels: ⚙️backend

#5306 feat: added `deleted_at` as read-only property for the label serializer
  apiserver/plane/api/serializers/issue.py
Labels: ⚙️backend

#5316 [WEB-2182] fix: favorite item alignment and redirection
  web/core/components/workspace/sidebar/favorites/favorite-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5317 [WEB-2192] fix: order of state groups in space app
  apiserver/plane/space/views/state.py
  space/core/components/issues/issue-layouts/utils.tsx
  space/core/store/state.store.ts
  space/helpers/state.helper.ts
Labels: 🐛bug, 🌐frontend

#5318 [WEB-2182] chore: user favorites improvement
  packages/types/src/favorite/favorite.d.ts
  web/core/components/project/create-project-form.tsx
  web/core/components/project/form.tsx
  web/core/components/workspace/sidebar/favorites/favorite-item.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5321 [WEB-2182] chore: user favorites item enhancements
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-item.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#5322 chore: add rate limiting in magic generate endpoint
  apiserver/plane/authentication/views/app/magic.py
Labels: ⚙️backend, 🔐authentication

#5279 [WEB-2127] dev: editor extensions configuration
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/core/types/extensions.ts
  packages/editor/src/core/types/index.ts
  packages/editor/src/core/types/slash-commands-suggestion.ts
  web/ce/hooks/use-editor-flagging.ts
  web/ce/hooks/use-issue-embed.tsx
  web/core/components/pages/editor/editor-body.tsx
Labels: 🌐frontend, 🌟improvement, ✍️editor

#5323 improvement: merge quick add logic for all layouts.
  web/ce/components/issues/index.ts
  web/ce/components/issues/quick-add/index.ts
  web/ce/components/issues/quick-add/root.tsx
  web/core/components/issues/issue-layouts/calendar/index.ts
  web/core/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-actions.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/gantt/index.ts
  web/core/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/index.ts
  web/core/components/issues/issue-layouts/kanban/index.ts
  web/core/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/core/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/list/index.ts
  web/core/components/issues/issue-layouts/list/list-group.tsx
  web/core/components/issues/issue-layouts/list/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/quick-add/button/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/button/index.ts
  web/core/components/issues/issue-layouts/quick-add/button/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/button/list.tsx
  web/core/components/issues/issue-layouts/quick-add/button/spreadsheet.tsx
  web/core/components/issues/issue-layouts/quick-add/form/calendar.tsx
  web/core/components/issues/issue-layouts/quick-add/form/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/form/index.ts
  web/core/components/issues/issue-layouts/quick-add/form/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/form/list.tsx
  web/core/components/issues/issue-layouts/quick-add/form/spreadsheet.tsx
  web/core/components/issues/issue-layouts/quick-add/index.ts
  web/core/components/issues/issue-layouts/quick-add/root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/index.ts
  web/core/components/issues/issue-layouts/spreadsheet/quick-add-issue-form.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/core/components/issues/title-input.tsx
  web/ee/components/issues/index.ts
  web/ee/components/issues/quick-add/index.ts
  web/ee/components/issues/quick-add/root.tsx
Labels: 🌟improvement

#5329 [WEB-2047] refactor: editor side menu
  packages/editor/src/ce/extensions/ai-features/handle.ts
  packages/editor/src/ce/extensions/ai-features/index.ts
  packages/editor/src/ce/extensions/index.ts
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/lite-text/editor.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/side-menu.tsx
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/core/types/extensions.ts
  packages/editor/src/ee/extensions/ai-features/index.ts
  packages/editor/src/styles/drag-drop.css
Labels: 🌐frontend, 🛠️refactor, ✍️editor

#5334 [WEB-2047] chore: add missing exports
  packages/editor/src/ee/extensions/ai-features/index.ts
  web/ee/hooks/use-editor-flagging.ts
Labels: 🌐frontend

#5332 [WEB-2186] fix: work log activity validation
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5328 [WEB-2207] fix: Issue description in space app's peek overview
  space/core/components/issues/peek-overview/layout.tsx
Labels: 🐛bug, 🌐frontend

#5330 [WEB-2202] chore: user favorites mutation and code refactor
  packages/types/src/favorite/favorite.d.ts
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-item.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-drag-handle.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-quick-action.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-wrapper.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/helper.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/index.ts
  web/core/components/workspace/sidebar/favorites/favorite-items/index.ts
  web/core/components/workspace/sidebar/favorites/favorite-items/root.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/favorites/index.ts
  web/core/components/workspace/sidebar/index.ts
  web/core/hooks/use-favorite-item-details.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore, 🛠️refactor

#5333 [WEB-2211] fix: input autoComplete
  admin/app/general/form.tsx
  admin/core/components/instance/setup-form.tsx
  admin/core/components/login/sign-in-form.tsx
  packages/ui/src/form-fields/input.tsx
  space/core/components/account/auth-forms/email.tsx
  space/core/components/account/auth-forms/password.tsx
  web/app/accounts/forgot-password/page.tsx
  web/app/accounts/reset-password/page.tsx
  web/app/accounts/set-password/page.tsx
  web/app/profile/page.tsx
  web/core/components/account/auth-forms/email.tsx
  web/core/components/account/auth-forms/password.tsx
  web/core/components/account/auth-forms/unique-code.tsx
  web/core/components/onboarding/profile-setup.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5344 [WEB-2178] fix: empty folder title
  packages/ui/src/collapsible/collapsible.tsx
  web/core/components/workspace/sidebar/favorites/new-fav-folder.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5341 [WEB-2189] fix: issue peek overview and issue detail unauthorised delete action
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
  web/core/components/issues/peek-overview/root.tsx
  web/core/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5342 [WEB-2190] fix: unauthorised delete and redirections
  web/core/components/cycles/delete-modal.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#5340 [WEB-2045] dev: editor variable font sizes and styles support
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/document/read-only-editor.tsx
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/read-only-editor-wrapper.tsx
  packages/editor/src/core/constants/config.ts
  packages/editor/src/core/extensions/code/code-block-node-view.tsx
  packages/editor/src/core/hooks/use-document-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/props/props.tsx
  packages/editor/src/core/props/read-only.tsx
  packages/editor/src/core/types/config.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/index.ts
  packages/editor/src/index.ts
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/table.css
  packages/ui/src/icons/index.ts
  packages/ui/src/icons/monospace-icon.tsx
  packages/ui/src/icons/sans-serif-icon.tsx
  packages/ui/src/icons/serif-icon.tsx
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/title.tsx
  web/core/constants/editor.ts
  web/core/hooks/use-page-filters.ts
Labels: 🌐frontend, 🌟improvement, ✍️editor

#5346 [WEB-2204] chore: asset optimization
  space/public/onboarding/onboarding-pages.svg
  space/public/onboarding/profile-setup-dark.svg
  space/public/onboarding/profile-setup-light.svg
  web/core/components/common/latest-feature-block.tsx
  web/core/components/dashboard/project-empty-state.tsx
  web/core/components/onboarding/create-or-join-workspaces.tsx
  web/core/components/onboarding/profile-setup.tsx
  web/core/layouts/auth-layout/project-wrapper.tsx
  web/public/empty-state/dashboard/project.svg
  web/public/onboarding/create-join-workspace-dark.svg
  web/public/onboarding/create-join-workspace-dark.webp
  web/public/onboarding/create-join-workspace-light.webp
  web/public/onboarding/create-join-workspace.svg
  web/public/onboarding/onboarding-pages.svg
  web/public/onboarding/onboarding-pages.webp
  web/public/onboarding/profile-setup-dark.svg
  web/public/onboarding/profile-setup-dark.webp
  web/public/onboarding/profile-setup-light.svg
  web/public/onboarding/profile-setup-light.webp
  web/public/workspace-active-cycles/cta-r-2-dark.webp
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5349 [WEB-2217] fix: drag handle positioning and action
  packages/editor/src/core/components/menus/block-menu.tsx
  packages/editor/src/core/extensions/side-menu.tsx
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/styles/drag-drop.css
Labels: 🐛bug, 🌐frontend, ✍️editor

#5353 [WEB-2222] fix: project modal shortcut
  web/core/components/command-palette/command-palette.tsx
  web/core/components/project/create-project-modal.tsx
  web/core/components/project/create/project-create-buttons.tsx
Labels: 🌐frontend, 🌟improvement

#5357 [WEB-2221] fix: app sidebar and favorites improvement
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/helper.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/root.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/hooks/use-favorite-item-details.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#5368 [WEB-2233] fix: intake issue comment
  packages/editor/src/core/extensions/enter-key-extension.tsx
  packages/editor/src/core/types/editor.ts
  space/core/components/editor/lite-text-editor.tsx
  space/core/components/editor/toolbar.tsx
  space/core/components/issues/peek-overview/comment/add-comment.tsx
  space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5371 [WEB-2047] dev: pages side menu refactor
  packages/editor/src/ce/extensions/ai-features/handle.ts
  packages/editor/src/ce/extensions/ai-features/index.ts
  packages/editor/src/ce/extensions/index.ts
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/menus/ai-menu.tsx
  packages/editor/src/core/components/menus/index.ts
  packages/editor/src/core/extensions/side-menu.tsx
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/plugins/ai-handle.ts
  packages/editor/src/core/types/ai.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/index.ts
  packages/editor/src/styles/drag-drop.css
  web/ce/components/pages/editor/ai/ask-pi-menu.tsx
  web/ce/components/pages/editor/ai/index.ts
  web/ce/components/pages/editor/ai/menu.tsx
  web/ce/components/pages/editor/index.ts
  web/ce/constants/ai.ts
  web/ce/hooks/use-editor-flagging.ts
  web/core/components/pages/editor/editor-body.tsx
  web/core/services/ai.service.ts
Labels: 🌐frontend, ✍️editor

#5373 [WEB-2238] fix: issue delete notification message updated
  packages/types/src/workspace-notifications.d.ts
  web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5374 [WEB-2200] fix: states order in filters dropdown on space app
  space/core/components/issues/filters/applied-filters/state.tsx
  space/core/components/issues/filters/state.tsx
Labels: 🐛bug, 🌐frontend

#5211 [WEB-1980] feat: user recent visited entities
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/module/base.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/bgtasks/recent_visited_task.py
  apiserver/plane/db/models/__init__.py
Labels: ⚙️backend

#5392 [WEB-2253] chore: removed continuous loading when accessing a wrong page
  apiserver/plane/app/permissions/base.py
  apiserver/plane/app/views/exporter/base.py
Labels: ⚙️backend

#5387 [WEB-1986] fix: remove the user favourites when archived a particular entity
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
  apiserver/plane/api/views/project.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/issue/archive.py
  apiserver/plane/app/views/issue/bulk_operations.py
  apiserver/plane/app/views/module/archive.py
  apiserver/plane/app/views/page/base.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/utils/error_codes.py
Labels: ⚙️backend, 🌟improvement

#5391 [WEB-2251] fix: workspace inbox read endpoint permission
  apiserver/plane/app/views/notification/base.py
Labels: 🐛bug, 🧹chore

#5401 [WEB-2256] fix: empty state comic button responsiveness
  web/core/components/empty-state/comic-box-button.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5400 [WEB-2047] refactor: editor side menu
  packages/editor/src/core/components/menus/ai-menu.tsx
  packages/editor/src/core/components/menus/index.ts
  packages/editor/src/core/extensions/side-menu.tsx
  packages/editor/src/core/types/ai.ts
  web/ce/components/pages/editor/ai/menu.tsx
  web/core/components/pages/editor/editor-body.tsx
Labels: 🌐frontend, 🛠️refactor, ✍️editor

#5395 [WEB-2133] fix : Remove inbox delete option for members
  web/core/components/inbox/content/inbox-issue-header.tsx
Labels: 🐛bug, 🌐frontend

#5413 [WEB-2289] fix: email notification settings form validation
  web/core/components/profile/notification/email-notification-form.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🧹chore

#5406 [WEB-2150] fix: issue selection redirect alert
  web/core/hooks/use-multiple-select.ts
  web/core/hooks/use-reload-confirmation.tsx
Labels: 🐛bug, 🌐frontend

#5419 [PWA-5] fix: PWA sticky issue comment
  web/core/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5402 [PWA-2] fix: pwa input zoom effect
  web/app/layout.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5407 [WEB-2263] fix: god mode wrong credentials error message banner
  admin/core/components/authentication/auth-banner.tsx
  admin/core/components/authentication/index.ts
  admin/core/components/login/sign-in-form.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5417 [WEB-2293] feat: pages version history
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/page.py
  apiserver/plane/app/views/page/version.py
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/types/src/pages.d.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/index.ts
  web/core/components/pages/version/editor.tsx
  web/core/components/pages/version/index.ts
  web/core/components/pages/version/main-content.tsx
  web/core/components/pages/version/root.tsx
  web/core/components/pages/version/sidebar-list-item.tsx
  web/core/components/pages/version/sidebar-list.tsx
  web/core/components/pages/version/sidebar-root.tsx
  web/core/hooks/use-page-description.ts
  web/core/hooks/use-query-params.ts
  web/core/services/page/index.ts
  web/core/services/page/project-page-version.service.ts
Labels: ✨feature, 🌐frontend, ⚙️backend

#5414 [WEB-1095] fix: Make quick action dropdowns use capture phase of the event to trigger closure on outside click
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/helper.tsx
  packages/ui/src/hooks/use-outside-click-detector.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
Labels: 🐛bug, 🌐frontend

#5422 [WEB-2325] fix: Creator unable to delete inbox issue
  web/core/components/inbox/content/inbox-issue-header.tsx
Labels: 🐛bug, 🌐frontend

#5428 [WEB-2243] fix: active cycle info icon overlap
  web/core/components/cycles/list/cycles-list-item.tsx
Labels: 🐛bug, 🌐frontend

#5437 [WEB-2320] fix: Redirect to issues page post issue deletion deletion
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
Labels: 🐛bug, 🌐frontend

#5434 [WEB-2237] fix: intake issue create/update modal
  web/core/components/inbox/modals/create-edit-modal/issue-properties.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5426 [PWA-11] fix: pwa kanban layout block
  web/core/components/issues/issue-layouts/kanban/block.tsx
Labels: 🌐frontend, 🧹chore

#5427 [PWA-12] chore: project analytics modal header improvement
  web/core/components/analytics/project-modal/header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5435 [WEB-2329] chore: updated UI for module and cycle detail overview
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/[moduleId]/page.tsx
  web/core/components/cycles/analytics-sidebar/root.tsx
  web/core/components/cycles/cycle-peek-overview.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
  web/core/components/modules/module-peek-overview.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5441 [WEB-2293] chore: code splitting for pages version history
  web/ce/components/pages/index.ts
  web/ce/components/pages/version/editor.tsx
  web/ce/components/pages/version/index.ts
  web/core/components/pages/version/index.ts
  web/core/components/pages/version/main-content.tsx
Labels: 🌐frontend, 🛠️refactor

#5409 [WEB-2050] dev: added new information panels to a page
  packages/editor/package.json
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/helpers/common.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/core/components/pages/dropdowns/edit-information-popover.tsx
  web/core/components/pages/dropdowns/index.ts
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/info-popover.tsx
  web/helpers/date-time.helper.ts
  yarn.lock
Labels: 🌐frontend, 🌟improvement, ✍️editor

#5425 [PWA-17] chore: project view list header improvement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/layout.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/mobile-header.tsx
  web/core/components/views/filters/order-by.tsx
  web/core/components/views/view-list-header.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#5416 [PWA-1] fix: pwa app sidebar redirection
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#5445 [WEB-2338] chore: handle untitled page breadcrumbs
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
Labels: 🌐frontend, 🌟improvement

#5454 [WEB-2293] refactor: version editor
  web/ce/components/pages/index.ts
  web/ce/components/pages/version/index.ts
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/version/editor.tsx
  web/core/components/pages/version/index.ts
  web/core/components/pages/version/main-content.tsx
  web/core/components/pages/version/root.tsx
  yarn.lock
Labels: 🌐frontend, 🛠️refactor

#5449 [WEB-2344] fix: quick action hover
  web/core/components/labels/label-block/label-item-block.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#5461 [WEB-2293] fix: version history editor overflow
  web/core/components/pages/version/main-content.tsx
Labels: 🐛bug, 🌐frontend

#5464 chore: add migration on file asset for limit svg uploads
  apiserver/plane/db/migrations/0075_alter_fileasset_asset.py
Labels: 🔄migrations

#5455 [WEB-2145] chore: added copy button for intake issues
  web/core/components/inbox/content/inbox-issue-header.tsx
Labels: ✨feature, 🌐frontend, 🧹chore

#5446 [WEB-2304] fix: increase z-index from z-20 to z-[21] in dropdown.tsx
  web/core/components/workspace/sidebar/dropdown.tsx
Labels: 🐛bug, 🌐frontend

#5456 [WEB-2316] chore: Render Tooltips and Drop downs in certain places on hover hover to improve rendering performance
  packages/ui/src/dropdowns/combo-box.tsx
  packages/ui/src/dropdowns/index.ts
  packages/ui/src/tooltip/tooltip.tsx
  web/core/components/dropdowns/cycle/index.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/dropdowns/estimate.tsx
  web/core/components/dropdowns/member/index.tsx
  web/core/components/dropdowns/module/index.tsx
  web/core/components/dropdowns/priority.tsx
  web/core/components/dropdowns/project.tsx
  web/core/components/dropdowns/state.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
Labels: 🌐frontend, 🧹chore, ⚡performance

#5451 [WEB-2341] feat: Add display filters and display properties to create/update view dialog
  web/core/components/views/form.tsx
  web/core/components/workspace/views/form.tsx
Labels: 🌟enhancement, 🌐frontend

#5453 [WEB-2316] chore: use-platform-os hook optimization to not cause re renders
  packages/ui/src/hooks/use-platform-os.ts
  web/core/hooks/use-platform-os.tsx
Labels: 🌐frontend, 🧹chore, ⚡performance

#5469 [WEB-2294] fix: remove 'Add Project' button from archives route and remove it from the dropdown in header
  web/core/components/project/card-list.tsx
  web/core/components/project/dropdowns/filters/root.tsx
  web/core/components/project/header.tsx
  web/core/components/project/root.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#5452 [WEB-2350] chore: next image config updated
  web/next.config.js
Labels: 🌐frontend, 🧹chore

#5475 [WEB-2311] fix: update the message display when deactivating/deleting project
  web/app/profile/page.tsx
  web/core/components/project/settings/delete-project-section.tsx
Labels: 🌐frontend, 🎨UI / UX

#5447 [WEB-2359] chore: resolved the bugs reported in sentry
  apiserver/plane/api/views/module.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/export_task.py
  apiserver/plane/bgtasks/page_transaction_task.py
  apiserver/plane/bgtasks/page_version_task.py
  apiserver/plane/bgtasks/webhook_task.py
Labels: ⚙️backend, 🌟improvement

#5463 [WEB-2355] fix: trigger webhook for issue create and update
  apiserver/plane/app/views/issue/base.py
Labels: ⚙️backend, 🌟improvement
