Repository makeplane/plane, pull requests merged in 2024-01, with the labels that each got.

#3276 chore: gpt modal refactor
  web/components/core/modals/gpt-assistant-modal.tsx
  web/components/core/modals/gpt-assistant-popover.tsx
  web/components/core/modals/index.ts
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/form.tsx
  web/components/pages/create-update-block-inline.tsx
  web/components/pages/index.ts
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🌐frontend, 🧹chore, 🛠️refactor

#3302 fix: migration file fixes
  apiserver/plane/db/migrations/0051_remove_issueproperty_properties_and_more.py
  apiserver/plane/db/migrations/0052_auto_20231220_1141.py
  apiserver/plane/db/migrations/0053_auto_20240102_1315.py
Labels: ⚙️backend, 🔄migrations

#3300 style: remove unnecessary vertical scroll in `All Issues Tabs`.
  web/components/workspace/views/header.tsx
Labels: 🌐frontend, 🎨UI / UX

#3306 chore: profile setting improvement
  web/pages/profile/index.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3312 dev: new create/update issue modal
  web/components/command-palette/command-palette.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/form.tsx
  web/components/issues/index.ts
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-modal/draft-issue-layout.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/index.ts
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/modal.tsx
  web/components/issues/sub-issues/root.tsx
  web/store/estimate.store.ts
Labels: 🌐frontend, 🛠️refactor

#3309 [chore]: Fixed table not being defined in getBoundingClientRect() and better TS support for tables
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
Labels: ✍️editor

#3308 fix: removing redundant env example variables from the .env.example file
  apiserver/.env.example
Labels: ⚙️config changes

#3321 fix: workspace invitations response updated
  packages/types/src/workspace.d.ts
  web/components/onboarding/invitations.tsx
  web/pages/invitations/index.tsx
  web/pages/workspace-invitations/index.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#3326 fix: estimate order not maintained in create/ update modal.
  web/components/estimates/estimates-list.tsx
  web/store/estimate.store.ts
Labels: 🐛bug, 🌐frontend

#3330 fix: breaking cycle issues and replacing router.push with Links
  web/components/command-palette/actions/workspace-settings-actions.tsx
  web/components/core/sidebar/progress-chart.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/notifications/notification-card.tsx
  web/components/notifications/notification-popover.tsx
  web/components/project/card.tsx
  web/components/ui/empty-space.tsx
  web/layouts/settings-layout/project/layout.tsx
  web/pages/create-workspace.tsx
  web/pages/workspace-invitations/index.tsx
  web/store/cycle.store.ts
Labels: 🌐frontend, 🌐web

#3328 chore: mobile configs
  apiserver/plane/app/urls/config.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/config.py
Labels: ⚙️backend, 🧹chore

#3325 fix: security warnings related to information exposure and regex validations
  apiserver/plane/api/views/base.py
  apiserver/plane/app/views/base.py
  apiserver/plane/space/views/base.py
  apiserver/plane/utils/issue_search.py
  apiserver/plane/utils/paginator.py
Labels: 🛡️security

#3323 fix: jira importer validations
  .github/workflows/codeql.yml
  apiserver/plane/app/views/importer.py
  apiserver/plane/utils/importers/jira.py
  web/components/integration/single-integration-card.tsx
  web/services/project/project.service.ts
Labels: ⚙️backend, 🧹chore

#3333 fix: update jira summary endpoints
  apiserver/plane/utils/importers/jira.py
Labels: ⚙️backend

#3332 chore: modal and dropdown improvement
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/dropdowns/custom-select.tsx
  packages/ui/src/dropdowns/helper.tsx
  packages/ui/src/hooks/use-dropdown-key-down.tsx
  packages/ui/src/hooks/use-outside-click-detector.tsx
  web/components/core/image-picker-popover.tsx
  web/components/cycles/form.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/types.d.ts
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/emoji-icon-picker/types.d.ts
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/select/label.tsx
  web/components/modules/form.tsx
  web/components/modules/select/status.tsx
  web/components/pages/page-form.tsx
  web/components/project/create-project-modal.tsx
  web/components/views/form.tsx
  web/hooks/use-dropdown-key-down.tsx
  web/store/page.store.ts
  web/store/project-page.store.ts
  web/store/root.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3329 chore: instance api urls
  apiserver/plane/license/urls.py
  apiserver/plane/urls.py
  web/services/auth.service.ts
  web/services/instance.service.ts
Labels: 🧹chore

#3296 Fix env substitute issue in websocket docker setup
  docker-compose-local.yml
  nginx/env.sh
  nginx/nginx.conf.dev
Labels: ⚙️config changes

#3339 fix: smtp configuration
  apiserver/plane/app/views/config.py
Labels: ⚙️backend, ⚙️config changes

#3318 fix: inline code blocks, code blocks and links have saner behaviour
  packages/editor/core/package.json
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/ui/extensions/code-inline/index.tsx
  packages/editor/core/src/ui/extensions/code/index.tsx
  packages/editor/core/src/ui/extensions/custom-link/helpers/autolink.ts
  packages/editor/core/src/ui/extensions/custom-link/helpers/clickHandler.ts
  packages/editor/core/src/ui/extensions/custom-link/helpers/pasteHandler.ts
  packages/editor/core/src/ui/extensions/custom-link/index.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/read-only/extensions.tsx
  web/services/file.service.ts
  yarn.lock
Labels: 🐛bug, ✍️editor

#3353 fix: create sync action
  .github/workflows/create-sync-pr.yml
Labels: 🔄workflows

#3356 fix: project loaders for mobx store
  web/components/cycles/active-cycle-details.tsx
  web/components/inbox/modals/select-duplicate.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/select/label.tsx
  web/store/cycle.store.ts
  web/store/label/project-label.store.ts
  web/store/member/project-member.store.ts
  web/store/module.store.ts
  web/store/project-view.store.ts
  web/store/state.store.ts
Labels: 🌐frontend, 🌐web

#3361 fix: enable spreadsheet peek overview
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
Labels: 🌐frontend, 🌐web

#3375 chore: update in sub-issues component and property validation and issue loaders
  apiserver/plane/app/views/issue.py
  packages/types/src/issues/issue_sub_issues.d.ts
  web/components/core/sidebar/progress-chart.tsx
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-detail/label/label-list-item.tsx
  web/components/issues/issue-detail/links/root.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-detail/parent/siblings.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/components/issues/issue-layouts/roots/module-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-layout-root.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/peek-overview/issue-detail.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/issue.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/properties.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/modules/sidebar.tsx
  web/store/issue/cycle/filter.store.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/issue-details/sub_issues.store.ts
  web/store/issue/project/issue.store.ts
Labels: 🌐frontend, 🧹chore

#3376 chore webhook create page removed
  web/components/web-hooks/create-webhook-modal.tsx
  web/components/web-hooks/form/form.tsx
  web/pages/[workspaceSlug]/settings/webhooks/create.tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
Labels: 🌐frontend, 🧹chore

#3379 fix: drag and delete issue
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
Labels: 🐛bug, 🎨UI / UX

#3380 chore: esc to close peek overview
  web/components/issues/peek-overview/view.tsx
Labels: 🌐frontend, 🌟improvement

#3377 dev: remove slack ping
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/bgtasks/user_welcome_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
  apiserver/plane/db/models/user.py
  apiserver/plane/settings/common.py
Labels: 🧹chore

#3378 dev: workspace active cycles
  apiserver/plane/app/urls/cycle.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle.py
  packages/types/src/cycles.d.ts
  packages/types/src/projects.d.ts
  web/components/cycles/active-cycle-info.tsx
  web/components/cycles/index.ts
  web/components/headers/index.ts
  web/components/headers/workspace-active-cycle.tsx
  web/components/issues/label.tsx
  web/components/workspace/index.ts
  web/components/workspace/sidebar-menu.tsx
  web/components/workspace/workspace-active-cycles-list.tsx
  web/constants/cycle.ts
  web/pages/[workspaceSlug]/active-cycles.tsx
  web/services/cycle.service.ts
  web/store/workspace/index.ts
Labels: ✨feature, 🌐frontend, ⚙️backend

#3382 chore: filter and display properties popover improvement
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
Labels: 🌐frontend, 🌟improvement

#3384 fix: refactor related bugs
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/issues/issue-layouts/save-filter-view.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/root.tsx
  web/components/views/form.tsx
  web/components/views/view-list-item.tsx
  web/store/issue/issue-details/relation.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/issue-details/sub_issues.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project-views/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🌐web

#3387 fix: error message on successful creation of cycle issues
  web/components/issues/issue-layouts/roots/cycle-layout-root.tsx
  web/store/issues/project-issues/cycle/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🌐web

#3389 fix: self-hosting docker-compose doc link update
  README.md
Labels: 📖docs

#3390 fix: updated env variables at root
  .env.example
Labels: ⚙️config changes

#3388 [chore]: Removed explicit dependencies and cleaned up turbo config
  package.json
  turbo.json
  yarn.lock
Labels: 🚀CI/CD, ⚙️config changes, :card_file_box: packaging

#3391 fix: project views bugs related to store refactor.
  web/components/issues/issue-layouts/calendar/roots/project-view-root.tsx
  web/components/issues/issue-layouts/gantt/project-view-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
  web/components/issues/issue-layouts/list/roots/project-view-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/project-view-root.tsx
  web/components/views/form.tsx
  web/components/views/modal.tsx
  web/store/project-view.store.ts
Labels: 🐛bug, 🌐frontend

#3358 dev: self host local build for other arch cpu
  deploy/selfhost/build.yml
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install.sh
Labels: 🐳docker

#3396 chore: workspace active cycles improvement
  web/components/headers/workspace-active-cycle.tsx
  web/components/workspace/sidebar-menu.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3402 fix: stack integration disable button mutation issue in project settings.
  web/components/integration/slack/select-channel.tsx
Labels: 🐛bug

#3404 chore: update issue template to auto assign and update labels
  .github/ISSUE_TEMPLATE/--bug-report.yaml
  .github/ISSUE_TEMPLATE/--feature-request.yaml
Labels: 🧹chore

#3395 refactor: update `create/update issue` modal to use currently active store's create/update method.
  web/components/command-palette/command-palette.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-root.tsx
  web/components/issues/issue-layouts/kanban/roots/project-view-root.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/roots/draft-issue-root.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/list/roots/project-root.tsx
  web/components/issues/issue-layouts/list/roots/project-view-root.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
Labels: 🛠️refactor

#3405 fix: enable global/ all issues
  web/components/headers/global-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/members.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/project-view-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/workspace/views/form.tsx
  web/components/workspace/views/header.tsx
  web/components/workspace/views/modal.tsx
  web/components/workspace/views/view-list-item.tsx
  web/helpers/filter.helper.ts
  web/pages/[workspaceSlug]/workspace-views/all-issues.tsx
  web/pages/[workspaceSlug]/workspace-views/assigned.tsx
  web/pages/[workspaceSlug]/workspace-views/created.tsx
  web/pages/[workspaceSlug]/workspace-views/subscribed.tsx
  web/store/issue/helpers/issue-filter-helper.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/workspace/filter.store.ts
  web/store/issue/workspace/issue.store.ts
Labels: 🌐frontend, 🌐web

#3403 fix: key validation in email check endpoint
  apiserver/plane/app/views/authentication.py
Labels: 🐛bug, ⚙️backend

#3406 chore: issue filter loader improvement
  web/store/issue/archived/filter.store.ts
  web/store/issue/cycle/filter.store.ts
  web/store/issue/draft/filter.store.ts
  web/store/issue/module/filter.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project/filter.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🌐frontend, 🌟improvement

#3410 fix: update global issues filter and enable profile issues
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/profile/profile-issues.tsx
  web/constants/common.ts
  web/store/issue/helpers/issue-filter-helper.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/profile/issue.store.ts
  web/store/issue/root.store.ts
Labels: 🌐frontend, 🌐web

#3414 refactor: move all sidebar links to constant file.
  web/components/command-palette/actions/workspace-settings-actions.tsx
  web/components/headers/workspace-active-cycle.tsx
  web/components/workspace/sidebar-menu.tsx
  web/constants/dashboard.ts
  web/constants/profile.ts
  web/constants/project.ts
  web/constants/workspace.ts
  web/layouts/settings-layout/profile/sidebar.tsx
  web/layouts/settings-layout/project/sidebar.tsx
  web/layouts/settings-layout/workspace/sidebar.tsx
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#3412 dev: update apiserver .env.example
  apiserver/.env.example
Labels: ⚙️backend, 🐳docker

#3407 chore: workspace active cycle revamp, project active cycle bug fixes and improvement.
  apiserver/plane/app/views/cycle.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/utils/analytics_plot.py
  packages/types/src/cycles.d.ts
  packages/types/src/workspace.d.ts
  packages/ui/src/progress/linear-progress-indicator.tsx
  web/components/core/sidebar/single-progress-stats.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/active-cycle-info.tsx
  web/components/cycles/active-cycle-stats.tsx
  web/components/cycles/form.tsx
  web/components/headers/workspace-active-cycle.tsx
  web/components/modules/form.tsx
  web/components/workspace/workspace-active-cycles-list.tsx
  web/constants/cycle.ts
  web/constants/fetch-keys.ts
  web/services/cycle.service.ts
  web/store/workspace/index.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, ⚙️backend, 🌟improvement, 🧹chore

#3417 fix: project store computed function filtering logic
  web/components/account/o-auth/o-auth-options.tsx
  web/store/project/project.store.ts
Labels: 🐛bug, 🌐frontend

#3424 fix: docker branch builds
  .github/workflows/build-branch.yml
Labels: 🚀CI/CD, 🧹chore

#3423 chore: remove active cycle link from dashboard sidebar.
  web/constants/dashboard.ts
Labels: 🧹chore

#3426 ⏮️ Regression: Added drag handle hide behavior to Pages/Document Editor
  packages/editor/document-editor/src/ui/components/page-renderer.tsx
  packages/editor/document-editor/src/ui/extensions/index.tsx
  packages/editor/document-editor/src/ui/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
Labels: 🐛bug, 🌐frontend, ✍️editor, pages

#3427 chore: project cycle bug fixes and improvement
  apiserver/plane/db/models/issue.py
  apiserver/plane/utils/analytics_plot.py
  packages/types/src/cycles.d.ts
  packages/ui/src/progress/linear-progress-indicator.tsx
  web/components/core/sidebar/single-progress-stats.tsx
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/active-cycle-stats.tsx
  web/components/cycles/form.tsx
  web/components/issues/label.tsx
  web/components/modules/form.tsx
  web/constants/cycle.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3433 chore: drop-downs improvements and bug fixes
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/dropdowns/custom-select.tsx
  packages/ui/src/dropdowns/helper.tsx
  web/components/analytics/custom-analytics/select/project.tsx
  web/components/analytics/custom-analytics/select/segment.tsx
  web/components/analytics/custom-analytics/select/x-axis.tsx
  web/components/analytics/custom-analytics/select/y-axis.tsx
  web/components/automation/auto-archive-automation.tsx
  web/components/automation/auto-close-automation.tsx
  web/components/core/activity.tsx
  web/components/core/theme/theme-switch.tsx
  web/components/cycles/cycles-board-card.tsx
  web/components/cycles/cycles-list-item.tsx
  web/components/cycles/sidebar.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/types.d.ts
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/dropdowns/types.d.ts
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/integration/jira/give-details.tsx
  web/components/integration/jira/import-users.tsx
  web/components/issues/issue-detail/cycle-select.tsx
  web/components/issues/issue-detail/module-select.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/view-select/estimate.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/sidebar.tsx
  web/components/notifications/select-snooze-till-modal.tsx
  web/components/pages/pages-list/list-item.tsx
  web/components/project/member-select.tsx
  web/components/project/send-project-invitation-modal.tsx
  web/components/states/create-state-modal.tsx
  web/components/views/view-list-item.tsx
  web/components/workspace/create-workspace-form.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/components/workspace/views/view-list-item.tsx
  web/pages/profile/index.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3440 dev: migration check
  apiserver/Dockerfile.dev
  apiserver/bin/beat
  apiserver/bin/takeoff
  apiserver/bin/takeoff.local
  apiserver/bin/worker
  apiserver/plane/db/management/commands/wait_for_migrations.py
  deploy/selfhost/docker-compose.yml
  docker-compose-local.yml
Labels: 🐳docker, devops

#3437 fix: sync action
  .github/workflows/create-sync-pr.yml
Labels: devops

#3435 chore: module and cycle bug fixes
  web/components/cycles/active-cycle-details.tsx
  web/constants/cycle.ts
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#3436 fix: Kanban related issues
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/helpers/state.helper.ts
  web/store/issue/helpers/issue-helper.store.ts
  web/store/issue/issue_kanban_view.store.ts
  web/store/state.store.ts
Labels: 🌐frontend, 🌐web

#3439 chore: fix authorization for new projects in the peek overview
  web/components/issues/peek-overview/root.tsx
  web/components/project/card-list.tsx
  web/store/project/project.store.ts
Labels: 🐛bug, 🌐frontend

#3442 chore: sub issue mutation for state and project change
  web/components/issues/sub-issues/issue-list-item.tsx
  web/components/issues/sub-issues/issues-list.tsx
  web/components/issues/sub-issues/properties.tsx
  web/components/issues/sub-issues/root.tsx
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/issue-details/sub_issues.store.ts
  web/store/issue/root.store.ts
  web/store/state.store.ts
Labels: 🌐frontend, 🧹chore

#3421 dev: email notifications
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/notification.py
  apiserver/plane/app/urls/notification.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/app/views/module.py
  apiserver/plane/app/views/notification.py
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/importer_task.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/bgtasks/issue_automation_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/celery.py
  apiserver/plane/db/migrations/0056_usernotificationpreference_emailnotificationlog.py
  apiserver/plane/db/migrations/0057_auto_20240122_0901.py
  apiserver/plane/db/models/__init__.py
  apiserver/plane/db/models/notification.py
  apiserver/plane/db/models/user.py
  apiserver/plane/settings/common.py
  apiserver/templates/emails/notifications/issue-updates.html
  packages/types/src/users.d.ts
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-detail/subscription.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/profile/preferences/email-notification-form.tsx
  web/components/profile/preferences/index.ts
  web/constants/profile.ts
  web/layouts/settings-layout/profile/preferences/index.ts
  web/layouts/settings-layout/profile/preferences/layout.tsx
  web/layouts/settings-layout/profile/preferences/sidebar.tsx
  web/pages/profile/preferences/email.tsx
  web/pages/profile/preferences/theme.tsx
  web/services/user.service.ts
Labels: ✨feature, 🔄migrations

#3444 fix: minor bug fixes and quality of life improvements
  package.json
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/dropdowns/helper.tsx
  web/components/core/activity.tsx
  web/components/dashboard/widgets/recent-activity.tsx
  web/components/exporter/export-modal.tsx
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/profile/overview/activity.tsx
  web/components/workspace/sidebar-quick-action.tsx
  web/pages/profile/activity.tsx
Labels: 🌐frontend, 🌐web

#3441 fix: project issue exports
  apiserver/plane/bgtasks/export_task.py
Labels: 🐳docker, devops

#3445 fix: input field value not changing in delete import modal.
  web/components/integration/delete-import-modal.tsx
Labels: 🐛bug

#3446 fix: inline codes now exitable with right arrow key and inclusive
  packages/editor/core/package.json
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/ui/extensions/code-inline/index.tsx
  packages/editor/core/src/ui/menus/menu-items/index.tsx
Labels: 🐛bug, 🌟enhancement, ✨feature, ✍️editor

#3451 fix: archived issues and minor bug fixes
  web/components/core/activity.tsx
  web/components/issues/issue-detail/issue-activity/activity/actions/estimate.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-layouts/list/roots/archived-issue-root.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/roots/archived-issue-layout-root.tsx
  web/components/issues/peek-overview/issue-detail.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/peek-overview/view.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/issues/[issueId].tsx
  web/store/estimate.store.ts
  web/store/issue/archived/filter.store.ts
  web/store/issue/archived/issue.store.ts
  web/store/issue/cycle/filter.store.ts
  web/store/issue/draft/filter.store.ts
  web/store/issue/helpers/issue-filter-helper.store.ts
  web/store/issue/issue_kanban_view.store.ts
  web/store/issue/module/filter.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project/filter.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🐛bug, 🌐frontend

#3452 fix: delete and restore for dynamic urls for minio hosted images fix…
  space/components/issues/peek-overview/comment/add-comment.tsx
  space/components/issues/peek-overview/comment/comment-detail-card.tsx
  space/services/file.service.ts
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/issues/comment/add-comment.tsx
  web/components/issues/comment/comment-card.tsx
  web/components/issues/description-form.tsx
  web/components/issues/draft-issue-form.tsx
  web/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/peek-overview/activity/comment-card.tsx
  web/components/issues/peek-overview/activity/comment-editor.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/services/file.service.ts
Labels: 🧹chore, ✍️editor

#3450 fix: date dropdown not getting closed on clicking outside
  web/components/dropdowns/date.tsx
Labels: 🐛bug, 🌐frontend

#3447 style: peek overview and issue details properties
  packages/ui/src/dropdowns/custom-search-select.tsx
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/buttons.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/types.d.ts
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/dropdowns/types.d.ts
  web/components/issues/issue-detail/cycle-select.tsx
  web/components/issues/issue-detail/module-select.tsx
  web/components/issues/issue-detail/parent-select.tsx
  web/components/issues/issue-detail/relation-select.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/view-select/estimate.tsx
  web/store/issue/issue-details/root.store.ts
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3454 chore: workspace active cycles upgrade page implementation
  web/components/headers/index.ts
  web/components/headers/workspace-active-cycles.tsx
  web/components/workspace/index.ts
  web/components/workspace/sidebar-menu.tsx
  web/components/workspace/workspace-active-cycles-upgrade.tsx
  web/constants/cycle.ts
  web/constants/dashboard.ts
  web/pages/[workspaceSlug]/active-cycles.tsx
  web/public/workspace-active-cycles/cta-l-1-dark.webp
  web/public/workspace-active-cycles/cta-l-1-light.webp
  web/public/workspace-active-cycles/cta-r-1-dark.webp
  web/public/workspace-active-cycles/cta-r-1-light.webp
  web/public/workspace-active-cycles/cta-r-2-dark.webp
  web/public/workspace-active-cycles/cta-r-2-light.webp
Labels: 🌐frontend, 🎨UI / UX

#3455 chore: dashboard empty states, fetching logic
  web/components/dashboard/widgets/assigned-issues.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/empty-states/assigned-issues.tsx
  web/components/dashboard/widgets/empty-states/created-issues.tsx
  web/components/dashboard/widgets/empty-states/issues-by-priority.tsx
  web/components/dashboard/widgets/empty-states/issues-by-state-group.tsx
  web/components/dashboard/widgets/empty-states/recent-activity.tsx
  web/components/dashboard/widgets/empty-states/recent-collaborators.tsx
  web/components/dashboard/widgets/issue-panels/issues-list.tsx
  web/components/dashboard/widgets/issues-by-priority.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/components/dashboard/widgets/overview-stats.tsx
  web/components/dashboard/widgets/recent-activity.tsx
  web/components/dashboard/widgets/recent-collaborators.tsx
  web/components/dashboard/widgets/recent-projects.tsx
  web/constants/dashboard.ts
  web/public/empty-state/dashboard/dark/completed-assigned-issues.svg
  web/public/empty-state/dashboard/dark/completed-created-issues.svg
  web/public/empty-state/dashboard/dark/completed-issues.svg
  web/public/empty-state/dashboard/dark/issues-by-priority.svg
  web/public/empty-state/dashboard/dark/issues-by-state-group.svg
  web/public/empty-state/dashboard/dark/overdue-assigned-issues.svg
  web/public/empty-state/dashboard/dark/overdue-created-issues.svg
  web/public/empty-state/dashboard/dark/overdue-issues.svg
  web/public/empty-state/dashboard/dark/recent-activity.svg
  web/public/empty-state/dashboard/dark/recent-collaborators-1.svg
  web/public/empty-state/dashboard/dark/recent-collaborators-2.svg
  web/public/empty-state/dashboard/dark/recent-collaborators-3.svg
  web/public/empty-state/dashboard/dark/recent-collaborators.svg
  web/public/empty-state/dashboard/dark/upcoming-assigned-issues.svg
  web/public/empty-state/dashboard/dark/upcoming-created-issues.svg
  web/public/empty-state/dashboard/dark/upcoming-issues.svg
  web/public/empty-state/dashboard/light/completed-assigned-issues.svg
  web/public/empty-state/dashboard/light/completed-created-issues.svg
  web/public/empty-state/dashboard/light/completed-issues.svg
  web/public/empty-state/dashboard/light/issues-by-priority.svg
  web/public/empty-state/dashboard/light/issues-by-state-group.svg
  web/public/empty-state/dashboard/light/overdue-assigned-issues.svg
  web/public/empty-state/dashboard/light/overdue-created-issues.svg
  web/public/empty-state/dashboard/light/overdue-issues.svg
  web/public/empty-state/dashboard/light/recent-activity.svg
  web/public/empty-state/dashboard/light/recent-collaborators-1.svg
  web/public/empty-state/dashboard/light/recent-collaborators-2.svg
  web/public/empty-state/dashboard/light/recent-collaborators-3.svg
  web/public/empty-state/dashboard/light/recent-collaborators.svg
  web/public/empty-state/dashboard/light/upcoming-assigned-issues.svg
  web/public/empty-state/dashboard/light/upcoming-created-issues.svg
  web/public/empty-state/dashboard/light/upcoming-issues.svg
Labels: 🌐frontend, 🌟improvement

#3458 Chore: change kanban layout and issue activity fixes
  web/components/core/activity.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/peek-overview/activity/card.tsx
  web/pages/profile/activity.tsx
Labels: 🐛bug, 🌐frontend

#3456 chore: inbox issue restructure the components and store
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/base.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/project.py
  packages/types/src/inbox/inbox-issue.d.ts
  packages/types/src/inbox/inbox.d.ts
  packages/types/src/inbox/root.d.ts
  packages/types/src/index.d.ts
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issues.tsx
  web/components/inbox/actions-header.tsx
  web/components/inbox/inbox-issue-actions.tsx
  web/components/inbox/inbox-issue-status.tsx
  web/components/inbox/index.ts
  web/components/inbox/issue-activity.tsx
  web/components/inbox/issue-card.tsx
  web/components/inbox/issues-list-sidebar.tsx
  web/components/inbox/main-content.tsx
  web/components/inbox/modals/accept-issue-modal.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/inbox/modals/decline-issue-modal.tsx
  web/components/inbox/modals/delete-issue-modal.tsx
  web/components/inbox/sidebar/filter/applied-filters.tsx
  web/components/inbox/sidebar/filter/filter-selection.tsx
  web/components/inbox/sidebar/inbox-list-item.tsx
  web/components/inbox/sidebar/inbox-list.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-detail/cycle-select.tsx
  web/components/issues/issue-detail/inbox/index.ts
  web/components/issues/issue-detail/inbox/main-content.tsx
  web/components/issues/issue-detail/inbox/root.tsx
  web/components/issues/issue-detail/inbox/sidebar.tsx
  web/components/issues/issue-detail/module-select.tsx
  web/components/issues/issue-detail/root.tsx
  web/constants/inbox.ts
  web/constants/inbox.tsx
  web/hooks/store/index.ts
  web/hooks/store/use-inbox-filters.ts
  web/hooks/store/use-inbox-issues.ts
  web/hooks/store/use-inbox.ts
  web/layouts/auth-layout/project-wrapper.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/[inboxId].tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
  web/services/inbox/inbox-issue.service.ts
  web/services/inbox/inbox.service.ts
  web/services/inbox/index.ts
  web/store/inbox/inbox.store.ts
  web/store/inbox/inbox_filter.store.ts
  web/store/inbox/inbox_issue.store.ts
  web/store/inbox/index.ts
  web/store/inbox/root.store.ts
  web/store/root.store.ts
Labels: 🌐frontend, ⚙️backend, 🧹chore

#3457 fix: email notifications
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/notification_task.py
  apiserver/plane/celery.py
  apiserver/templates/emails/notifications/issue-updates.html
  web/components/profile/preferences/email-notification-form.tsx
Labels: 🌐frontend, ⚙️backend, 🌟improvement

#3459 fix: page archive and unarchive
  apiserver/plane/app/views/page.py
Labels: 🐛bug, ⚙️backend

#3461 fix: project pages loader
  web/components/pages/pages-list/archived-pages-list.tsx
  web/store/project-page.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement

#3462 chore: added tooltip to dropdowns
  web/components/dashboard/widgets/issues-by-priority.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/member/buttons.tsx
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/dropdowns/types.d.ts
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/public/empty-state/dashboard/light/overdue-issues.svg
Labels: 🌐frontend, 🌟improvement

#3463 fix: issues list modal not closing on escape key
  web/components/core/modals/existing-issues-list-modal.tsx
Labels: 🐛bug, 🌐frontend

#3466 fix: resolve module and cycle mutation issues in peek overview, issue sidebar and empty state
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/peek-overview/root.tsx
Labels: 🐛bug, 🌐frontend

#3467 fix: add issue to store only if the issue doesn't exist
  web/components/dropdowns/types.d.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3468 chore: bug fixes and ui improvements
  web/components/empty-state/empty-state.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/workspace/help-section.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3464 chore: applying query params to the global issues filters in the global views
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/issues/issue-detail/label/create-label.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/hooks/use-workspace-issue-properties.ts
  web/store/estimate.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🌐frontend, 🧹chore

#3470 fix: updating the global issue store while removing the issue from bulk delete.
  web/components/core/modals/bulk-delete-issues-modal.tsx
  web/store/issue/project/issue.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🌐frontend, 🧹chore

#3471 chore: update python version
  apiserver/runtime.txt
Labels: 🧹chore

#3474 feat: One Click Deployment
  deploy/1-click/install.sh
Labels: 🏠self-hosted, 🐳docker, ⚙️config changes

#3476 fix: one click install fixes
  deploy/1-click/install.sh
  deploy/1-click/plane-app
Labels: 🏠self-hosted, 🐳docker

#3479 chore: add more guards against exception in member-list
  web/components/project/member-list.tsx
Labels: 🌐frontend

#3483 chore: spreadsheet layout improvement
  web/store/issue/archived/filter.store.ts
  web/store/issue/cycle/filter.store.ts
  web/store/issue/draft/filter.store.ts
  web/store/issue/module/filter.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project/filter.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#3482 chore: issue relation modal and issue peek overview mutation fix
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/issues/issue-detail/relation-select.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-layouts/empty-states/cycle.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/issues/sub-issues/root.tsx
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#3485 fix: handled attachment upload filename size error in the issue detail
  web/components/issues/attachment/attachment-detail.tsx
  web/components/issues/attachment/attachment-upload.tsx
  web/components/profile/sidebar.tsx
  web/helpers/attachment.helper.ts
  web/store/issue/issue-details/attachment.store.ts
Labels: 🐛bug, 🌐frontend

#3491 fix: issue preload data in issue create update modal
  web/components/issues/issue-modal/modal.tsx
Labels: 🌐frontend

#3493 fix: Filters in all issues and enable dnd in kanban based on roles
  web/components/issues/issue-layouts/filters/header/filters/labels.tsx
  web/components/issues/issue-layouts/filters/header/filters/project.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/store/issue/helpers/issue-filter-helper.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: 🐛bug, 🌐frontend

#3489 chore: update time in real-time in dashboard and profile sidebar
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
  web/components/profile/index.ts
  web/components/profile/sidebar.tsx
  web/components/profile/time.tsx
  web/components/user/user-greetings.tsx
  web/hooks/use-current-time.tsx
Labels: 🌐frontend, 🌟improvement

#3497 fix: Add missing project and subscriber filters to the list of filter params
  web/components/notifications/notification-header.tsx
  web/constants/issue.ts
  web/hooks/use-user-notifications.tsx
  web/store/issue/helpers/issue-filter-helper.store.ts
Labels: 🐛bug, 🌐frontend

#3496 fix: profile issue application error
  web/components/issues/issue-layouts/kanban/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/list/roots/profile-issues-root.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
  web/components/project/sidebar-list.tsx
Labels: 🐛bug, 🌐frontend

#3500 fix: unique key errors
  web/components/dashboard/home-dashboard-widgets.tsx
  web/components/dashboard/widgets/created-issues.tsx
  web/components/dashboard/widgets/recent-projects.tsx
Labels: 🐛bug, 🌐frontend

#3501 chore: empty state theme improvement
  web/components/cycles/active-cycle-details.tsx
  web/components/cycles/cycles-board.tsx
  web/components/cycles/cycles-list.tsx
  web/components/issues/issue-layouts/empty-states/archived-issues.tsx
  web/components/issues/issue-layouts/empty-states/draft-issues.tsx
  web/components/issues/issue-layouts/empty-states/project-issues.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/modules/modules-list-view.tsx
  web/components/page-views/workspace-dashboard.tsx
  web/components/pages/pages-list/list-view.tsx
  web/components/pages/pages-list/recent-pages-list.tsx
  web/components/profile/profile-issues.tsx
  web/components/project/card-list.tsx
  web/components/views/views-list.tsx
  web/pages/[workspaceSlug]/analytics.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#3502 fix: project id update in create update cycle modal
  web/components/cycles/form.tsx
  web/components/cycles/modal.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#3503 chore: unused var removed
  web/components/headers/global-issues.tsx
  web/components/issues/description-form.tsx
  web/components/issues/issue-detail/parent/siblings.tsx
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/empty-states/archived-issues.tsx
  web/components/issues/issue-layouts/empty-states/draft-issues.tsx
  web/components/issues/issue-layouts/empty-states/project-issues.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/select/label.tsx
  web/components/pages/create-update-page-modal.tsx
  web/pages/profile/activity.tsx
Labels: 🌐frontend, 🧹chore

#3504 chore: project active cycle and linear progress indicator improvement
  packages/ui/src/progress/linear-progress-indicator.tsx
  web/components/cycles/active-cycle-details.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3487 feat: show all issues on the gantt chart
  packages/types/src/view-props.d.ts
  web/components/core/activity.tsx
  web/components/dashboard/widgets/overview-stats.tsx
  web/components/dnd/StrictModeDroppable.tsx
  web/components/gantt-chart/blocks/blocks-display.tsx
  web/components/gantt-chart/chart/index.tsx
  web/components/gantt-chart/chart/month.tsx
  web/components/gantt-chart/helpers/add-block.tsx
  web/components/gantt-chart/helpers/block-structure.tsx
  web/components/gantt-chart/helpers/draggable.tsx
  web/components/gantt-chart/helpers/index.ts
  web/components/gantt-chart/root.tsx
  web/components/gantt-chart/sidebar/cycle-sidebar.tsx
  web/components/gantt-chart/sidebar/module-sidebar.tsx
  web/components/gantt-chart/sidebar/project-view-sidebar.tsx
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/gantt-chart/types/index.ts
  web/components/gantt-chart/views/month-view.ts
  web/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/constants/fetch-keys.ts
  web/helpers/issue.helper.ts
  web/store/issue/archived/filter.store.ts
  web/store/issue/cycle/filter.store.ts
  web/store/issue/draft/filter.store.ts
  web/store/issue/helpers/issue-filter-helper.store.ts
  web/store/issue/module/filter.store.ts
  web/store/issue/profile/filter.store.ts
  web/store/issue/project-views/filter.store.ts
  web/store/issue/project/filter.store.ts
  web/store/issue/workspace/filter.store.ts
Labels: ✨feature, 🌐frontend

#3505 style/responsive sidebar
  web/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
  web/components/dashboard/widgets/overview-stats.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/cycles.tsx
  web/components/headers/global-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/page-details.tsx
  web/components/headers/pages.tsx
  web/components/headers/project-archived-issue-details.tsx
  web/components/headers/project-archived-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-inbox.tsx
  web/components/headers/project-issue-details.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/project-view-issues.tsx
  web/components/headers/project-views.tsx
  web/components/headers/projects.tsx
  web/components/headers/user-profile.tsx
  web/components/headers/workspace-active-cycles.tsx
  web/components/headers/workspace-analytics.tsx
  web/components/headers/workspace-dashboard.tsx
  web/components/headers/workspace-settings.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/components/workspace/sidebar-menu.tsx
  web/layouts/app-layout/sidebar.tsx
Labels: 🎨UI / UX

#3484 chore: implemented multiple modules select in the issues
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/urls/module.py
  apiserver/plane/app/views/cycle.py
  apiserver/plane/app/views/dashboard.py
  apiserver/plane/app/views/inbox.py
  apiserver/plane/app/views/issue.py
  apiserver/plane/app/views/module.py
  apiserver/plane/app/views/search.py
  apiserver/plane/app/views/view.py
  apiserver/plane/app/views/workspace.py
  apiserver/plane/bgtasks/issue_activites_task.py
  apiserver/plane/db/migrations/0058_alter_moduleissue_issue_and_more.py
  apiserver/plane/db/models/module.py
  packages/types/src/issues/issue.d.ts
  packages/types/src/projects.d.ts
  web/components/command-palette/command-palette.tsx
  web/components/dropdowns/index.ts
  web/components/dropdowns/module-select/button.tsx
  web/components/dropdowns/module-select/index.ts
  web/components/dropdowns/module-select/select.tsx
  web/components/dropdowns/module-select/types.d.ts
  web/components/issues/draft-issue-form.tsx
  web/components/issues/draft-issue-modal.tsx
  web/components/issues/issue-detail/issue-activity/activity/actions/module.tsx
  web/components/issues/issue-detail/module-select.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/empty-states/module.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/kanban/roots/module-root.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/headers/group-by-card.tsx
  web/components/issues/issue-layouts/list/roots/module-root.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/peek-overview/root.tsx
  web/lib/app-provider.tsx
  web/services/module.service.ts
  web/store/issue/issue-details/issue.store.ts
  web/store/issue/issue-details/root.store.ts
  web/store/issue/module/issue.store.ts
Labels: ✨feature, 🌐frontend, ⚙️backend

#3511 fix: Quick add fix for cycles
  web/store/issue/cycle/issue.store.ts
Labels: 🐛bug, 🌐frontend

#3514 feat: issue highlighting
  web/components/gantt-chart/blocks/blocks-display.tsx
  web/components/gantt-chart/sidebar/sidebar.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#3494 chore: email-template changes overview
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/templates/emails/notifications/issue-updates.html
Labels: 🎨UI / UX, ⚙️backend, 🌟improvement

#3517 fix: all issues custom views by defining list layout for my-issue
  web/constants/issue.ts
Labels: 🐛bug, 🌐frontend

#3508 refactor: dropdown button components
  web/components/core/image-picker-popover.tsx
  web/components/dropdowns/buttons.tsx
  web/components/dropdowns/constants.ts
  web/components/dropdowns/cycle.tsx
  web/components/dropdowns/date.tsx
  web/components/dropdowns/estimate.tsx
  web/components/dropdowns/index.ts
  web/components/dropdowns/member/avatar.tsx
  web/components/dropdowns/member/buttons.tsx
  web/components/dropdowns/member/index.ts
  web/components/dropdowns/member/project-member.tsx
  web/components/dropdowns/member/workspace-member.tsx
  web/components/dropdowns/module-select/button.tsx
  web/components/dropdowns/module-select/index.ts
  web/components/dropdowns/module-select/select.tsx
  web/components/dropdowns/module-select/types.d.ts
  web/components/dropdowns/module.tsx
  web/components/dropdowns/priority.tsx
  web/components/dropdowns/project.tsx
  web/components/dropdowns/state.tsx
  web/components/dropdowns/types.d.ts
  web/components/issues/draft-issue-form.tsx
  web/components/issues/issue-detail/module-select.tsx
  web/components/issues/issue-detail/parent-select.tsx
  web/components/issues/issue-detail/relation-select.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/peek-overview/properties.tsx
  web/components/issues/select/label.tsx
  web/hooks/use-dropdown-key-down.tsx
Labels: 🌐frontend, 🛠️refactor

#3520 Style/workspace project settings layout
  web/components/account/o-auth/google-sign-in.tsx
  web/components/dashboard/widgets/issue-panels/issues-list.tsx
  web/components/dashboard/widgets/issues-by-state-group.tsx
  web/components/headers/project-settings.tsx
  web/components/headers/workspace-settings.tsx
  web/components/project/form.tsx
  web/components/workspace/sidebar-dropdown.tsx
  web/layouts/settings-layout/project/layout.tsx
  web/layouts/settings-layout/workspace/layout.tsx
Labels: 🎨UI / UX

#3521 fix: cycle and module sidebar mutation fix
  web/components/cycles/sidebar.tsx
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/root.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#3522 fix: draft issue modal
  web/components/issues/draft-issue-form.tsx
Labels: 🐛bug, 🌐frontend

#3523 chore: added validation to cloud hostname field
  web/components/integration/jira/give-details.tsx
Labels: 🌐frontend, 🌟improvement

#3525 fix: email-template heading overview
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/templates/emails/notifications/issue-updates.html
Labels: 🐛bug
