Repository makeplane/plane, pull requests merged in 2024-04, with the labels that each got.

#4092 [WEB-876] fix: Multiple editor instances cause weird issues with Tippy
  packages/editor/core/src/ui/components/editor-container.tsx
  packages/editor/core/src/ui/mentions/suggestion.ts
  packages/editor/extensions/src/extensions/slash-commands.tsx
  yarn.lock
Labels: 🐛bug

#4099 [WEB-839] fix: display error message in project settings page.
  web/components/project/create-project-form.tsx
  web/components/project/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#4104 [WEB-879] fix: draft issue title logic
  web/components/issues/issue-modal/draft-issue-layout.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4105 chore: add `Get started` button to redirect to `/god-mode` to set up instance.
  web/components/instance/not-ready-view.tsx
Labels: 🌐frontend, 🎨UI / UX

#4103 [WEB-848] fix: issue with parent child relation not being removed from update issue modal.
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#4069 [WEB-830] chore: project filter dropdown custom date select option improvement
  web/components/headers/projects.tsx
  web/components/project/dropdowns/filters/created-at.tsx
  web/helpers/date-time.helper.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4059 [WEB-822] fix: sub issue peek overview mutation
  web/components/issues/issue-detail/parent-select.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4106 [WEB-652] fix: issue activities alignment in dashboard.
  web/components/core/activity.tsx
Labels: 🌐frontend, 🎨UI / UX

#4093 [WEB-845] chore: list layout improvement
  web/components/issues/issue-layouts/list/block.tsx
Labels: 🌐frontend

#4100 [WEB-874] chore: archival of modules, cycles and issues enhancement.
  web/components/cycles/archived-cycles/modal.tsx
  web/components/cycles/quick-actions.tsx
  web/components/cycles/sidebar.tsx
  web/components/issues/archive-issue-modal.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/peek-overview/root.tsx
  web/components/modules/archived-modules/modal.tsx
  web/components/modules/quick-actions.tsx
  web/components/modules/sidebar.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/archives/issues/[archivedIssueId].tsx
Labels: 🌐frontend, 🎨UI / UX

#4094 [WEB-850] chore: calendar layout add existing issue
  web/components/issues/issue-layouts/calendar/quick-add-issue-form.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4112 [WEB-756] chore: module and cycle feature toggle validation
  web/components/cycles/cycle-mobile-header.tsx
  web/components/headers/cycle-issues.tsx
  web/components/headers/module-issues.tsx
  web/components/headers/project-draft-issues.tsx
  web/components/headers/project-issues.tsx
  web/components/headers/project-view-issues.tsx
  web/components/issues/archived-issues-header.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-properties.tsx
  web/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issues-mobile-header.tsx
  web/components/modules/module-mobile-header.tsx
  web/components/views/form.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4113 [WEB-869] chore: fix assignee and parent UI inconsistency in create issue modal.
  web/components/issues/issue-modal/form.tsx
Labels: 🌐frontend, 🎨UI / UX

#4120 [WEB-848] fix: issue with parent child relation not being removed parent select dropwdown.
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#4121 [WEB-756] chore: spreadsheet layout cycle and module feature toggle validation
  web/components/analytics/custom-analytics/select-bar.tsx
  web/components/analytics/custom-analytics/select/segment.tsx
  web/components/analytics/custom-analytics/select/x-axis.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
Labels: 🌐frontend, 🌟improvement

#4122 [WEB-899] fix: issue description was not rendering in the issue create/edit modal
  web/components/issues/issue-modal/form.tsx
  web/components/issues/issue-modal/modal.tsx
Labels: 🐛bug, 🌐frontend

#4124 [WEB - 908] chore: remove user dependency in dockerfile
  Dockerfile
  apiserver/Dockerfile.api
  apiserver/Dockerfile.dev
  apiserver/plane/settings/production.py
  space/Dockerfile.space
  web/Dockerfile.web
Labels: 🐳docker

#4138 [WEB-854] style: update height of sidebar help section and quick add across all layout for consistency.
  web/components/issues/issue-layouts/gantt/quick-add-issue-form.tsx
  web/components/issues/issue-layouts/kanban/quick-add-issue-form.tsx
  web/components/workspace/help-section.tsx
Labels: 🌐frontend, 🎨UI / UX

#4135 [WEB-905] chore: issue peek overview and kanban layout improvement
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/gantt/blocks.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/peek-overview/view.tsx
  web/components/issues/sub-issues/issue-list-item.tsx
  web/hooks/use-peek-overview-outside-click.tsx
Labels: 🌐frontend

#4125 [WEB-912] chore: remove placeholder from estimate property if no estimates are selected.
  web/components/dropdowns/estimate.tsx
  web/components/issues/issue-layouts/spreadsheet/columns/estimate-column.tsx
Labels: 🌐frontend, 🎨UI / UX

#4142 [WEB-881] fix: Sentry errors from previous build
  packages/editor/core/src/ui/extensions/table/table/table-view.tsx
  space/components/issues/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/display-filters-selection.tsx
  web/components/issues/issue-layouts/filters/header/display-filters/group-by.tsx
  web/components/project/applied-filters/root.tsx
  web/components/project/create-project-form.tsx
  web/components/project/form.tsx
  web/constants/fetch-keys.ts
  web/helpers/string.helper.ts
  web/hooks/use-reload-confirmation.tsx
  web/pages/installations/[provider]/index.tsx
Labels: 🐛bug, 🌐frontend

#4146 [WEB-917] style: update urgent priority icon design.
  packages/ui/src/icons/priority-icon.tsx
  web/components/dropdowns/priority.tsx
Labels: 🌐frontend, 🎨UI / UX

#4145 [WEB-904] chore: feature validation empty state
  web/constants/empty-state.ts
  web/pages/[workspaceSlug]/projects/[projectId]/cycles/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/views/index.tsx
  web/public/empty-state/disabled-feature/cycles-dark.webp
  web/public/empty-state/disabled-feature/cycles-light.webp
  web/public/empty-state/disabled-feature/modules-dark.webp
  web/public/empty-state/disabled-feature/modules-light.webp
  web/public/empty-state/disabled-feature/pages-dark.webp
  web/public/empty-state/disabled-feature/pages-light.webp
  web/public/empty-state/disabled-feature/views-dark.webp
  web/public/empty-state/disabled-feature/views-light.webp
Labels: 🌐frontend, 🌟improvement

#4144 [WEB-918] style: update size of `state` dropdown button for consistency.
  web/components/modules/select/status.tsx
Labels: 🌐frontend, 🎨UI / UX

#4149 [WEB-903] fix: issue subscription button mutation.
  web/store/issue/issue-details/subscription.store.ts
Labels: 🐛bug, 🌐frontend

#4152 [WEB-920] chore: workspace invite loader improvement
  web/layouts/auth-layout/workspace-wrapper.tsx
  web/pages/invitations/index.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4153 [WEB-924] chore: remove `Add Issues` button from completed cycles header.
  web/components/headers/cycle-issues.tsx
Labels: 🌐frontend, 🎨UI / UX

#4151 [WEB-406] chore: project inbox improvement
  apiserver/plane/app/serializers/inbox.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/utils/issue_filters.py
  packages/types/src/inbox.d.ts
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/content/issue-properties.tsx
  web/components/inbox/content/issue-root.tsx
  web/components/inbox/content/root.tsx
  web/components/inbox/inbox-filter/applied-filters/date.tsx
  web/components/inbox/inbox-filter/applied-filters/label.tsx
  web/components/inbox/inbox-filter/applied-filters/root.tsx
  web/components/inbox/inbox-filter/applied-filters/status.tsx
  web/components/inbox/inbox-filter/filters/date.tsx
  web/components/inbox/inbox-filter/filters/filter-selection.tsx
  web/components/inbox/inbox-filter/filters/labels.tsx
  web/components/inbox/inbox-filter/filters/status.tsx
  web/components/inbox/inbox-issue-status.tsx
  web/components/inbox/root.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-detail/label/create-label.tsx
  web/helpers/inbox.helper.ts
  web/store/inbox/inbox-issue.store.ts
  web/store/inbox/project-inbox.store.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4156 [WEB-905] chore: kanban card icon color improvement
  web/components/dropdowns/date.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/properties/all-properties.tsx
  web/components/issues/issue-layouts/properties/labels.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4159 [WEB-926] fix: issue description component update handled in peek overview, issue detail, and inbox issues
  web/components/inbox/content/issue-root.tsx
  web/components/issues/description-input.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-detail/parent/root.tsx
  web/store/issue/issue-details/issue.store.ts
Labels: 🐛bug

#4160 [WEB-927, WEB-928] fix: inbox issue bug fixes and improvement
  web/components/inbox/content/issue-properties.tsx
  web/components/inbox/content/issue-root.tsx
  web/components/inbox/content/root.tsx
  web/components/inbox/inbox-filter/filters/date.tsx
  web/components/inbox/modals/create-issue-modal.tsx
  web/components/inbox/modals/select-duplicate.tsx
  web/components/inbox/sidebar/inbox-list-item.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/issue-detail/sidebar.tsx
  web/components/issues/peek-overview/root.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
  web/store/inbox/inbox-issue.store.ts
  web/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌟enhancement, 🌐frontend, 🧹chore

#4162 [WEB-931] chore: kanban card padding improvement
  web/components/issues/issue-layouts/kanban/block.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4163 [WEB-929] chore: issue comment mention user improvement
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4161 fix: email ssl setting not getting saved
  apiserver/plane/license/management/commands/configure_instance.py
Labels: 🐛bug

#4165 [WEB-932] fix: api token expiry time
  web/components/api-token/modal/form.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4167 [WEB-935] fix: drag handle position in the issue modal overview
  web/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend

#4168 [WEB-937] fix: inbox issue hook render issue and code refactor
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#4175 [WEB-905] fix: make entire Kanban issue block clickable
  web/components/issues/issue-layouts/kanban/block.tsx
Labels: 🐛bug, 🌐frontend

#4172 [WEB-943] chore: inbox cancelled issue header action improvement
  web/components/inbox/content/inbox-issue-header.tsx
Labels: 🌐frontend, 🧹chore

#4173 [WEB-983] chore: dummy data script
  apiserver/plane/api/views/state.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/app/views/state/base.py
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/db/management/commands/create_dummy_data.py
  apiserver/plane/settings/common.py
Labels: ⚙️backend

#4185 [WEB-1000] fix: handled edge case for color on custom analytics state_group
  web/helpers/analytics.helper.ts
Labels: 🐛bug

#4182 [WEB-984] feat: integrated state filter in inbox issues filter
  packages/types/src/inbox.d.ts
  web/components/inbox/inbox-filter/applied-filters/index.ts
  web/components/inbox/inbox-filter/applied-filters/root.tsx
  web/components/inbox/inbox-filter/applied-filters/state.tsx
  web/components/inbox/inbox-filter/filters/filter-selection.tsx
  web/components/inbox/inbox-filter/filters/index.ts
  web/components/inbox/inbox-filter/filters/state.tsx
  web/store/inbox/project-inbox.store.ts
Labels: ✨feature

#4180 [WEB-999] chore: updated UI improvements and workflow updates in the project inbox
  apiserver/plane/app/views/inbox/base.py
  web/components/headers/project-inbox.tsx
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/content/issue-properties.tsx
  web/components/inbox/content/issue-root.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/inbox/modals/create-edit-modal/index.ts
  web/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/components/inbox/modals/create-edit-modal/issue-properties.tsx
  web/components/inbox/modals/create-edit-modal/issue-title.tsx
  web/components/inbox/modals/create-edit-modal/modal.tsx
  web/components/inbox/modals/index.ts
  web/components/inbox/root.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/issues/select/label.tsx
  web/hooks/store/use-inbox-issues.ts
  web/package.json
  web/store/inbox/inbox-issue.store.ts
  web/store/inbox/project-inbox.store.ts
  yarn.lock
Labels: 🌐frontend, ⚙️backend, 🧹chore

#4177 [WEB-990] fix: pages and Inbox issues in dummy data script
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/db/management/commands/create_dummy_data.py
Labels: ⚙️backend, 🧹chore

#4179 [WEB-994] fix: pages list mutation between projects
  web/components/pages/list/root.tsx
  web/components/pages/list/tab-navigation.tsx
  web/components/pages/pages-list-main-content.tsx
  web/components/pages/pages-list-view.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
  web/store/pages/project-page.store.ts
Labels: 🐛bug, 🌐frontend

#4189 [WEB-1004] feat: Pragmatic dnd implementation for Kanban
  packages/types/src/index.d.ts
  packages/types/src/pragmatic.d.ts
  packages/ui/src/drop-indicator.tsx
  packages/ui/src/index.ts
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/kanban/utils.ts
  web/package.json
  web/store/issue/cycle/issue.store.ts
  web/store/issue/draft/issue.store.ts
  web/store/issue/helpers/issue-helper.store.ts
  web/store/issue/issue_kanban_view.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/profile/issue.store.ts
  web/store/issue/project-views/issue.store.ts
  web/store/issue/project/issue.store.ts
  yarn.lock
Labels: 🌐frontend

#4188 [WEB-999] chore: inbox issue bug fixes and improvement
  apiserver/plane/app/views/inbox/base.py
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/issue-title.tsx
  web/components/issues/description-input.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/inbox/index.tsx
  web/store/inbox/inbox-issue.store.ts
  web/store/inbox/project-inbox.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#4191 [WEB-989] chore: archived module and cycle sidebar details
  apiserver/plane/api/urls/cycle.py
  apiserver/plane/api/views/cycle.py
  apiserver/plane/api/views/module.py
  apiserver/plane/app/urls/cycle.py
  apiserver/plane/app/urls/module.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/module/base.py
  web/components/cycles/cycle-peek-overview.tsx
  web/components/modules/module-peek-overview.tsx
  web/services/cycle_archive.service.ts
  web/services/module_archive.service.ts
  web/store/cycle.store.ts
  web/store/module.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4192 [WEB - 1006] fix: remove caching when joining workspace
  apiserver/plane/app/views/workspace/invite.py
Labels: 🐛bug

#4190 [WEB-939] chore: inbox issue attachment
  web/components/inbox/content/issue-root.tsx
  web/store/inbox/project-inbox.store.ts
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4195 chore: cycle list page improvement
  web/components/cycles/list/root.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4194 [WEB-735] chore: added a custom placeholder prop to all the editors
  packages/editor/core/package.json
  packages/editor/core/src/hooks/use-editor.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/document-editor/package.json
  packages/editor/document-editor/src/ui/extensions/index.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/index.tsx
  packages/editor/rich-text-editor/package.json
  packages/editor/rich-text-editor/src/ui/extensions/index.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  web/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/components/issues/description-input.tsx
  web/components/issues/issue-modal/form.tsx
  yarn.lock
Labels: 🌐frontend, 🌟improvement, ✍️editor

#4201 [WEB-837] chore: member invite modal improvement
  web/components/project/send-project-invitation-modal.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4202 [WEB-863] chore: issue comment empty state added
  web/components/issues/issue-detail/issue-activity/comments/root.tsx
  web/constants/empty-state.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4203 chore: created a global mark as favorite component
  web/components/core/favorite-star.tsx
  web/components/core/index.ts
  web/components/cycles/active-cycle/upcoming-cycles-list-item.tsx
  web/components/cycles/board/cycles-board-card.tsx
  web/components/cycles/list/cycles-list-item.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
  web/components/pages/list/block.tsx
  web/components/project/card.tsx
  web/components/project/sidebar-list-item.tsx
  web/components/views/view-list-item.tsx
Labels: 🌐frontend, 🌟improvement

#4207 [WEB-1012] fix: empty blocks due to virtualization in rare cases
  web/components/core/render-if-visible-HOC.tsx
Labels: 🐛bug, 🌐frontend

#4200 [WEB - 480] fix: horizontal rule drag and drop
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/ui/extensions/horizontal-rule/horizontal-rule.ts
  packages/editor/document-editor/src/ui/menu/block-menu.tsx
  packages/editor/extensions/src/extensions/drag-drop.tsx
Labels: ✍️editor

#4187 [WEB-480] fix: image uploading with swr sync fixed for pages
  packages/editor/core/src/hooks/use-editor.tsx
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/ui/extensions/drop.tsx
  packages/editor/core/src/ui/extensions/image/index.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/core/src/ui/plugins/upload-image.tsx
  packages/editor/core/src/ui/props.tsx
Labels: ✍️editor

#4209 [WEB-1013] fix spreadsheet labels dropdown keyboard navigation
  web/components/issues/issue-layouts/properties/labels.tsx
Labels: 🐛bug, 🌐frontend

#4210 [WEB-1017] chore: instance admin script
  apiserver/plane/db/management/commands/create_instance_admin.py
Labels: ⚙️backend

#4212 [WEB-999] chore: issue kanban block improvement
  web/components/issues/issue-layouts/kanban/block.tsx
Labels: 🌐frontend, 🌟improvement

#4211 [WEB-929] fix: issue comment validation
  web/components/issues/issue-detail/issue-activity/comments/comment-create.tsx
Labels: 🌐frontend

#4214 [WEB-1000] fix: profile activity application error
  web/components/profile/overview/priority-distribution.tsx
  web/components/profile/overview/state-distribution.tsx
Labels: 🐛bug, 🌐frontend

#4219 [WEB-1019] chore: error state for unauthorized pages
  apiserver/plane/app/views/page/base.py
  web/components/pages/dropdowns/quick-actions.tsx
  web/components/pages/editor/header/options-dropdown.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/[pageId].tsx
  web/store/pages/page.store.ts
  web/store/pages/project-page.store.ts
  yarn.lock
Labels: 🐛bug, 🌐frontend, ⚙️backend, 🌟improvement, 🛠️refactor

#4218 [WEB-1020] fix: draft issue parent select query params
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#4222 [WEB-1023] chore: page mention transactions
  apiserver/plane/app/views/page/base.py
  apiserver/plane/bgtasks/page_transaction_task.py
Labels: ⚙️backend, 🌟improvement

#4221 [WEB-1024] fix: textarea component auto-resize
  packages/ui/src/form-fields/textarea.tsx
  packages/ui/src/hooks/use-auto-resize-textarea.ts
  web/components/pages/editor/editor-body.tsx
  web/components/pages/editor/title.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#4208 [WEB-987] fix: inbox issue activity
  apiserver/plane/api/views/inbox.py
  apiserver/plane/app/views/inbox/base.py
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/bgtasks/issue_activites_task.py
  web/components/issues/issue-detail/issue-activity/activity/actions/inbox.tsx
  web/components/issues/issue-detail/issue-activity/activity/actions/index.ts
  web/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
Labels: ✨feature, ⚙️backend

#4224 chore: sign in page improvement
  web/components/account/index.ts
  web/components/account/sign-in-forms/root.tsx
  web/components/account/sign-up-forms/root.tsx
  web/components/account/terms-and-conditions.tsx
Labels: 🌐frontend, 🌟improvement

#4226 [WEB-999] fix: inbox sentry error and accept modal fix
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/inbox/modals/create-edit-modal/issue-properties.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4225 [WEB-1026] chore: clear search query on project change
  web/components/cycles/quick-actions.tsx
  web/components/headers/projects.tsx
  web/components/inbox/inbox-filter/sorting/order-by.tsx
  web/components/modules/dropdowns/order-by.tsx
  web/components/modules/modules-list-view.tsx
  web/components/modules/quick-actions.tsx
  web/components/pages/list/order-by.tsx
  web/components/project/dropdowns/order-by.tsx
  web/store/cycle_filter.store.ts
  web/store/module_filter.store.ts
  web/store/pages/project-page.store.ts
  web/store/project/project_filter.store.ts
Labels: 🐛bug, 🌐frontend

#4231 [WEB-1028] fix: enable comments and issue reactions for guest/ viewer.
  web/components/issues/issue-detail/main-content.tsx
  web/components/issues/issue-detail/root.tsx
  web/components/issues/peek-overview/issue-detail.tsx
  web/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend

#4229 [WEB-872] chore: add tooltip to peek overview header icons.
  web/components/issues/peek-overview/header.tsx
Labels: 🌐frontend, 🎨UI / UX

#4230 [WEB-871] chore: update leave project modal message in members settings page.
  web/components/project/confirm-project-member-remove.tsx
Labels: 🌐frontend, 🎨UI / UX

#4232 [WEB-643] chore: update issue activity tabs.
  web/components/issues/issue-detail/issue-activity/activity/root.tsx
  web/components/issues/issue-detail/issue-activity/index.ts
  web/components/issues/issue-detail/issue-activity/root.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#4234 [WEB-1027] fix: overflow & alignment fixes
  packages/ui/src/form-fields/textarea.tsx
  web/components/dropdowns/project.tsx
  web/components/issues/issue-layouts/filters/applied-filters/cycle.tsx
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
  web/components/issues/issue-layouts/filters/applied-filters/module.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/project/project-feature-update.tsx
  web/components/project/sidebar-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement, 🧹chore

#4235 [WEB-857] chore: update issue priority text color for custom theme in spreadsheet layout.
  web/components/dropdowns/priority.tsx
Labels: 🌐frontend, 🎨UI / UX

#4241 [WEB-853] chore: list layout improvement
  web/components/issues/issue-layouts/list/blocks-list.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement, 🧹chore

#4243 [WEB-911] chore: kanban layout sub-grouping ui improvement
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/headers/sub-group-by-card.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
Labels: 🌐frontend, 🎨UI / UX, 🌟improvement

#4244 [WEB-1022] fix: filters custom date selection improvement
  web/components/cycles/archived-cycles/header.tsx
  web/components/cycles/cycles-view-header.tsx
  web/components/cycles/dropdowns/filters/end-date.tsx
  web/components/cycles/dropdowns/filters/start-date.tsx
  web/components/headers/modules-list.tsx
  web/components/modules/archived-modules/header.tsx
  web/components/modules/dropdowns/filters/start-date.tsx
  web/components/modules/dropdowns/filters/target-date.tsx
  web/components/pages/list/filters/created-at.tsx
  web/components/pages/list/filters/root.tsx
  web/components/project/dropdowns/filters/created-at.tsx
  web/helpers/date-time.helper.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4245 [WEB-1031] fix: workspace not found flicker
  web/hooks/use-sign-in-redirection.ts
Labels: 🌐frontend

#4246 [WEB-1035] fix: peek module auto closing
  apiserver/plane/app/serializers/module.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/cycle/archive.py
  apiserver/plane/app/views/cycle/base.py
  apiserver/plane/app/views/issue/draft.py
  apiserver/plane/app/views/module/archive.py
  apiserver/plane/app/views/module/base.py
  web/store/module.store.ts
Labels: 🐛bug, 🌐frontend

#4249 [WEB-1032] fix: calendar header action alignment
  web/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
Labels: 🌐frontend, 🎨UI / UX, 🧹chore

#4250 [WEB-929] fix: comment text editor user mention validation added
  space/components/editor/lite-text-editor.tsx
  web/components/editor/lite-text-editor/lite-text-editor.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#4251 [WEB-1034] fix: inbox issue user activity
  web/components/core/activity.tsx
  web/store/label.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#4254 [WEB - 1039] fix: workspace redirection when logging in
  apiserver/plane/app/views/user/base.py
Labels: 🐛bug, ⚙️backend

#4255 [WEB-1038] fix: kanban layout drag permission validation
  web/components/issues/issue-layouts/kanban/block.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4256 [WEB-1042] fix: dashboard collaborators active issue count
  apiserver/plane/app/views/dashboard/base.py
  apiserver/plane/db/management/commands/test_email.py
Labels: 🐛bug, ⚙️backend

#4252 [WEB-1015] fix: kanban layout cycle and module quick add
  web/store/issue/cycle/issue.store.ts
  web/store/issue/module/issue.store.ts
  web/store/issue/project-views/issue.store.ts
  web/store/issue/project/issue.store.ts
Labels: 🐛bug, 🌐frontend

#4258 [WEB-1041] fix: preserve initial value on create more issues
  web/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4259 [WEB- 1045] dev: update python runtime
  apiserver/runtime.txt
Labels: 📦dependencies, ⚙️backend

#4266 [WEB-1047] chore: create page modal improvement
  web/components/pages/modals/page-form.tsx
Labels: 🌟enhancement, 🌐frontend

#4261 [WEB-988] chore: issue filter member options improvement
  web/components/inbox/inbox-filter/filters/members.tsx
  web/components/issues/issue-layouts/filters/header/filters/assignee.tsx
  web/components/issues/issue-layouts/filters/header/filters/created-by.tsx
  web/components/issues/issue-layouts/filters/header/filters/mentions.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4263 [WEB-1049] chore: applied filter responsiveness
  web/components/issues/issue-layouts/filters/applied-filters/filters-list.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4265 [WEB-1048] fix: module delete modal outside click event propagation
  web/components/modules/module-list-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4268 [WEB-1009] chore: active cycle stats improvement
  web/components/core/sidebar/single-progress-stats.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4271 [WEB-1030] chore: input error message improvement
  packages/ui/src/form-fields/input.tsx
  web/components/cycles/form.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/modals/create-edit-modal/edit-root.tsx
  web/components/inbox/modals/create-edit-modal/issue-title.tsx
  web/components/issues/issue-modal/form.tsx
  web/components/modules/form.tsx
  web/components/project/form.tsx
  web/components/views/form.tsx
  web/components/workspace/create-workspace-form.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4274 [WEB-1021] fix: empty state action button permission
  web/components/empty-state/empty-state.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4277 [WEB-1050] chore: triage state filter in workspace level
  apiserver/plane/app/views/workspace/base.py
  apiserver/plane/app/views/workspace/state.py
Labels: 🐛bug, ⚙️backend

#4276 [WEB-870] chore: delete label modal content updated
  web/components/labels/delete-label-modal.tsx
Labels: 🌐frontend, 🧹chore

#4278 [WEB-1052] fix: list layout issue block border color
  web/components/issues/issue-layouts/list/blocks-list.tsx
Labels: 🐛bug, 🌐frontend

#4281 [WEB-1054] fix: existing and parent issue modal empty state flicker
  web/components/core/modals/existing-issues-list-modal.tsx
  web/components/issues/parent-issues-list-modal.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4284 [WEB-1051] fix: filter state option order
  web/components/issues/issue-layouts/filters/header/filters/state.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4286 [WEB-1053] chore: module and cycle sidebar stats item filter implementation
  web/components/core/sidebar/sidebar-progress-stats.tsx
  web/components/cycles/sidebar.tsx
  web/components/modules/sidebar.tsx
Labels: 🌟enhancement, 🌐frontend, 🧹chore

#4285 [WEB-1057] chore: updated member filter option ordering
  web/components/modules/dropdowns/filters/lead.tsx
  web/components/modules/dropdowns/filters/members.tsx
  web/components/pages/list/filters/created-by.tsx
  web/components/project/dropdowns/filters/lead.tsx
  web/components/project/dropdowns/filters/members.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4293 [WEB-1048] fix: cycle and module quick action z-index
  web/components/cycles/board/cycles-board-card.tsx
  web/components/cycles/list/cycles-list-item.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item.tsx
Labels: 🐛bug, 🌐frontend

#4289 [WEB-1074] chore: clear search term on escape key
  web/components/command-palette/command-modal.tsx
Labels: 🌐frontend, 🌟improvement

#4294 [WEB-1072] fix: pages UI improvements
  packages/ui/src/form-fields/textarea.tsx
  packages/ui/src/hooks/use-auto-resize-textarea.ts
  web/components/pages/editor/summary/heading-components.tsx
  web/components/pages/editor/title.tsx
  web/components/pages/list/block.tsx
Labels: 🌐frontend, 🌟improvement

#4295 [WEB-1071] chore: show sub-issue option added to profile display filter
  web/constants/issue.ts
Labels: 🌐frontend, 🌟improvement

#4296 [WEB-1070] chore: project active cycle linear progress and state list color consistency
  web/constants/cycle.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4298 [WEB-1075] fix: double slashes in the global issues layout routes
  web/components/headers/global-issues.tsx
Labels: 🐛bug, 🌐frontend

#4301 [WEB-1073] fix: Kanban dnd to work as tested on Chrome, Safari and Firefox
  packages/ui/src/control-link/control-link.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
Labels: 🐛bug, 🌐frontend

#4299 [WEB-1076] fix: authorization bugs across the platform
  web/components/cycles/sidebar.tsx
  web/components/issues/issue-layouts/empty-states/project-view.tsx
  web/components/issues/issue-layouts/kanban/roots/cycle-root.tsx
  web/components/issues/issue-layouts/list/roots/cycle-root.tsx
  web/components/issues/issue-layouts/spreadsheet/roots/cycle-root.tsx
  web/components/modules/sidebar.tsx
  web/components/pages/editor/header/options-dropdown.tsx
Labels: 🐛bug, 🌐frontend

#4279 [WEB-708] style: projects list responsiveness
  web/components/headers/projects.tsx
  web/components/project/dropdowns/order-by.tsx
  web/components/project/projects-mobile-header.tsx
  web/pages/[workspaceSlug]/projects/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#4275 [WEB-704] fix: inbox responsiveness
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/content/inbox-issue-mobile-header.tsx
  web/components/inbox/content/index.ts
  web/components/inbox/content/root.tsx
  web/components/inbox/root.tsx
  web/components/inbox/sidebar/inbox-list-item.tsx
  web/components/inbox/sidebar/inbox-list.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-layouts/filters/header/helpers/dropdown.tsx
Labels: 🌟enhancement, 🌐frontend

#4047 [WEB-808] style: workspace settings mobile responsiveness
  web/components/api-token/modal/create-token-modal.tsx
  web/components/api-token/modal/generated-token-details.tsx
  web/components/headers/workspace-settings.tsx
  web/components/web-hooks/create-webhook-modal.tsx
  web/components/web-hooks/form/secret-key.tsx
  web/components/workspace/send-workspace-invitation-modal.tsx
  web/components/workspace/settings/members-list-item.tsx
  web/components/workspace/settings/mobile-workspace-settings-tabs.tsx
  web/components/workspace/settings/workspace-details.tsx
  web/layouts/settings-layout/workspace/layout.tsx
  web/pages/[workspaceSlug]/settings/api-tokens.tsx
  web/pages/[workspaceSlug]/settings/billing.tsx
  web/pages/[workspaceSlug]/settings/exports.tsx
  web/pages/[workspaceSlug]/settings/members.tsx
  web/pages/[workspaceSlug]/settings/webhooks/[webhookId].tsx
  web/pages/[workspaceSlug]/settings/webhooks/index.tsx
Labels: 🌐frontend, 🎨UI / UX

#4022 [WEB-711] style: profile and its settings pages responsiveness
  web/components/profile/preferences/preferences-mobile-header.tsx
  web/components/profile/profile-issues-mobile-header.tsx
  web/layouts/settings-layout/profile/preferences/layout.tsx
  web/layouts/user-profile-layout/layout.tsx
  web/pages/[workspaceSlug]/profile/[userId]/assigned.tsx
  web/pages/[workspaceSlug]/profile/[userId]/created.tsx
  web/pages/[workspaceSlug]/profile/[userId]/subscribed.tsx
  web/pages/profile/change-password.tsx
  web/pages/profile/index.tsx
  web/pages/profile/preferences/email.tsx
  web/pages/profile/preferences/theme.tsx
Labels: 🌐frontend, 🎨UI / UX

#4304 [WEB-436] chore: added h4 to h6 heading options
  packages/editor/core/src/hooks/use-editor.tsx
  packages/editor/core/src/lib/editor-commands.ts
  packages/editor/core/src/styles/editor.css
  packages/editor/core/src/ui/menus/menu-items/index.tsx
  packages/editor/document-editor/src/ui/menu/block-menu.tsx
  packages/editor/extensions/src/extensions/drag-drop.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/index.tsx
  packages/editor/rich-text-editor/src/ui/menus/bubble-menu/node-selector.tsx
  space/constants/editor.ts
  web/components/pages/editor/header/toolbar.tsx
  web/constants/editor.ts
Labels: ✨feature, 🌐frontend, ✍️editor

#4307 [WEB-1085] chore: pages order by options
  web/constants/page.ts
Labels: 🌐frontend

#4310 [WEB-1078] fix: view, api token and estimate modal description height
  web/components/api-token/modal/form.tsx
  web/components/estimates/create-update-estimate-modal.tsx
  web/components/views/form.tsx
  web/components/workspace/views/form.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#4311 [WEB-1090] fix: toggle switch component off state appearance
  packages/ui/src/button/toggle-switch.tsx
Labels: 🐛bug, 🌐frontend

#4309 [WEB-1094] chore: inbox sidebar mobile responsiveness
  web/components/inbox/content/inbox-issue-header.tsx
  web/components/inbox/content/inbox-issue-mobile-header.tsx
  web/components/inbox/content/root.tsx
  web/components/inbox/root.tsx
  web/components/inbox/sidebar/inbox-list-item.tsx
  web/components/inbox/sidebar/inbox-list.tsx
  web/components/inbox/sidebar/root.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#4308 [WEB-1065] chore: workspace view and empty filter improvement
  web/components/headers/global-issues.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/components/issues/issue-layouts/filters/applied-filters/roots/project-view-root.tsx
  web/pages/[workspaceSlug]/workspace-views/[globalViewId].tsx
  web/pages/[workspaceSlug]/workspace-views/index.tsx
Labels: 🐛bug, 🧹chore

#4315 [WEB-1093] chore: padding and borders consistency
  web/components/core/list/index.ts
  web/components/core/list/list-item.tsx
  web/components/core/list/list-root.tsx
  web/components/cycles/cycles-view-header.tsx
  web/components/cycles/list/cycle-list-item-action.tsx
  web/components/cycles/list/cycles-list-item.tsx
  web/components/cycles/list/index.ts
  web/components/cycles/list/root.tsx
  web/components/cycles/quick-actions.tsx
  web/components/headers/cycles.tsx
  web/components/headers/modules-list.tsx
  web/components/headers/project-issues.tsx
  web/components/inbox/modals/create-edit-modal/create-root.tsx
  web/components/inbox/sidebar/inbox-list-item.tsx
  web/components/inbox/sidebar/root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/modules/index.ts
  web/components/modules/module-list-item-action.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/module-view-header.tsx
  web/components/modules/modules-list-view.tsx
  web/components/pages/header/root.tsx
  web/components/pages/list/block-item-action.tsx
  web/components/pages/list/block.tsx
  web/components/pages/list/filters/index.ts
  web/components/pages/list/filters/labels.tsx
  web/components/pages/list/filters/root.tsx
  web/components/pages/list/index.ts
  web/components/pages/list/root.tsx
  web/components/views/index.ts
  web/components/views/view-list-item-action.tsx
  web/components/views/view-list-item.tsx
  web/components/views/views-list.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/modules/index.tsx
Labels: 🌟enhancement, 🌐frontend, 🎨UI / UX, 🌟improvement

#4312 [WEB-1115] fix: issue description placeholder
  packages/editor/core/src/hooks/use-editor.tsx
  packages/editor/core/src/ui/extensions/index.tsx
  packages/editor/document-editor/src/ui/index.tsx
  packages/editor/lite-text-editor/src/ui/index.tsx
  packages/editor/rich-text-editor/src/ui/index.tsx
  web/components/inbox/modals/create-edit-modal/issue-description.tsx
  web/components/issues/description-input.tsx
  web/components/issues/issue-modal/form.tsx
  web/helpers/issue.helper.ts
Labels: 🌐frontend, 🌟improvement

#4267 [WEB-1110] dev: custom context menu for issues, cycles, modules, views, pages and projects
  packages/ui/src/dropdowns/context-menu/index.ts
  packages/ui/src/dropdowns/context-menu/item.tsx
  packages/ui/src/dropdowns/context-menu/root.tsx
  packages/ui/src/dropdowns/index.ts
  space/pages/_document.tsx
  web/components/core/list/list-item.tsx
  web/components/cycles/active-cycle/upcoming-cycles-list-item.tsx
  web/components/cycles/board/cycles-board-card.tsx
  web/components/cycles/list/cycle-list-item-action.tsx
  web/components/cycles/list/cycles-list-item.tsx
  web/components/cycles/list/cycles-list-map.tsx
  web/components/cycles/list/root.tsx
  web/components/cycles/quick-actions.tsx
  web/components/issues/issue-layouts/calendar/base-calendar-root.tsx
  web/components/issues/issue-layouts/calendar/calendar.tsx
  web/components/issues/issue-layouts/calendar/day-tile.tsx
  web/components/issues/issue-layouts/calendar/issue-block-root.tsx
  web/components/issues/issue-layouts/calendar/issue-block.tsx
  web/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/components/issues/issue-layouts/calendar/week-days.tsx
  web/components/issues/issue-layouts/kanban/base-kanban-root.tsx
  web/components/issues/issue-layouts/kanban/block.tsx
  web/components/issues/issue-layouts/kanban/blocks-list.tsx
  web/components/issues/issue-layouts/kanban/default.tsx
  web/components/issues/issue-layouts/kanban/kanban-group.tsx
  web/components/issues/issue-layouts/kanban/swimlanes.tsx
  web/components/issues/issue-layouts/list/base-list-root.tsx
  web/components/issues/issue-layouts/list/block.tsx
  web/components/issues/issue-layouts/list/blocks-list.tsx
  web/components/issues/issue-layouts/list/default.tsx
  web/components/issues/issue-layouts/list/list-view-types.d.ts
  web/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/components/issues/issue-layouts/spreadsheet/base-spreadsheet-root.tsx
  web/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-table.tsx
  web/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/components/modules/archived-modules/view.tsx
  web/components/modules/module-card-item.tsx
  web/components/modules/module-list-item-action.tsx
  web/components/modules/module-list-item.tsx
  web/components/modules/quick-actions.tsx
  web/components/pages/dropdowns/quick-actions.tsx
  web/components/pages/list/block-item-action.tsx
  web/components/pages/list/block.tsx
  web/components/project/card.tsx
  web/components/views/index.ts
  web/components/views/quick-actions.tsx
  web/components/views/view-list-item-action.tsx
  web/components/views/view-list-item.tsx
  web/pages/_document.tsx
Labels: ✨feature, 🌐frontend

#4318 [WEB-1100] fix: bug fixes and enhancement
  web/components/inbox/content/issue-root.tsx
  web/components/inbox/content/root.tsx
  web/components/issues/issue-modal/modal.tsx
  web/components/labels/label-block/label-item-block.tsx
  web/components/pages/editor/summary/content-browser.tsx
  web/pages/[workspaceSlug]/projects/[projectId]/pages/index.tsx
Labels: 🐛bug, 🌐frontend

#4319 [WEB-1121] fix: project view application error
  web/components/views/views-list.tsx
Labels: 🐛bug, 🌐frontend
