Repository makeplane/plane, pull requests merged in 2025-02, with the labels that each got.

#6535 [WEB-3184]fix: links validations messages
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
Labels: 🐛bug, 🌐frontend

#6537 [WEB-3195]fix: view delete toast message
  web/core/components/workspace/views/delete-view-modal.tsx
Labels: 🐛bug, 🌐frontend

#6553 fix: langauge support keys
  packages/i18n/src/locales/en/translations.json
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
  web/core/components/issues/create-issue-toast-action-items.tsx
  web/core/components/modules/form.tsx
  web/core/components/modules/quick-actions.tsx
Labels: 🐛bug

#6555 chore: platform ux improvement
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/workspace-menu-header.tsx
Labels: 🌐frontend, 🧹chore

#6558 fix: language support keys
  packages/i18n/src/locales/en/translations.json
  space/app/layout.tsx
  space/app/provider.tsx
  space/core/components/account/auth-forms/auth-header.tsx
  space/core/components/instance/instance-failure-view.tsx
  space/core/components/issues/issue-layouts/issue-layout-HOC.tsx
  space/core/components/issues/issue-layouts/properties/all-properties.tsx
  space/core/components/issues/issue-layouts/utils.tsx
  space/core/components/issues/peek-overview/header.tsx
  space/core/components/issues/peek-overview/issue-properties.tsx
  space/public/site.webmanifest.json
  web/core/components/inbox/modals/delete-issue-modal.tsx
  web/core/components/inbox/root.tsx
  web/core/components/issues/archive-issue-modal.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-actions.tsx
  web/core/components/issues/issue-modal/draft-issue-layout.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
  web/core/components/modules/module-card-item.tsx
  web/core/components/project/form.tsx
  web/core/components/workspace/views/default-view-quick-action.tsx
Labels: 🌐frontend

#6564 [WEB-3319] chore: app sidebar section header improvement
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/workspace-menu-header.tsx
Labels: 🌐frontend, 🧹chore

#6543 [WEB-3292] feat: workspace switcher redesign
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/views/workspace/base.py
  packages/types/src/workspace.d.ts
  web/ce/components/common/subscription-pill.tsx
  web/core/components/workspace/sidebar/dropdown-item.tsx
  web/core/components/workspace/sidebar/dropdown.tsx
  web/ee/components/common/subscription-pill.tsx
Labels: 🌟enhancement, 🌐frontend, ⚙️backend

#6565 [WEB-3329] dev: new chart components
  packages/constants/src/chart.ts
  packages/constants/src/index.ts
  packages/propel/.prettierignore
  packages/propel/.prettierrc
  packages/propel/package.json
  packages/propel/src/charts/area-chart/index.ts
  packages/propel/src/charts/area-chart/root.tsx
  packages/propel/src/charts/bar-chart/bar.tsx
  packages/propel/src/charts/bar-chart/index.ts
  packages/propel/src/charts/bar-chart/root.tsx
  packages/propel/src/charts/line-chart/index.ts
  packages/propel/src/charts/line-chart/root.tsx
  packages/propel/src/charts/pie-chart/index.ts
  packages/propel/src/charts/pie-chart/root.tsx
  packages/propel/src/charts/pie-chart/tooltip.tsx
  packages/propel/src/charts/tick.tsx
  packages/propel/src/charts/tooltip.tsx
  packages/propel/src/charts/tree-map/index.ts
  packages/propel/src/charts/tree-map/map-content.tsx
  packages/propel/src/charts/tree-map/root.tsx
  packages/propel/src/charts/tree-map/tooltip.tsx
  packages/propel/src/globals.css
  packages/propel/src/index.ts
  packages/propel/src/ui/button.tsx
  packages/tailwind-config/tailwind.config.js
  packages/types/src/charts.d.ts
  web/core/components/core/charts/stacked-bar-chart/bar.tsx
  web/core/components/core/charts/stacked-bar-chart/root.tsx
  web/core/components/core/charts/stacked-bar-chart/tooltip.tsx
  web/next.config.js
  web/package.json
  yarn.lock
Labels: 🌐frontend

#6549 [WEB-3235]fix: transfer issues button mutation
  apiserver/plane/app/views/cycle/base.py
  packages/types/src/cycle/cycle.d.ts
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/quick-actions.tsx
Labels: 🐛bug, 🌐frontend

#6541 [WEB-3287]fix: label creation in global views
  web/core/components/issues/issue-detail/label/select/label-select.tsx
  web/core/components/issues/issue-layouts/properties/label-dropdown.tsx
Labels: 🐛bug, 🌐frontend

#6587 fix: cache invalidation for workspace labels endpoint
  apiserver/plane/app/views/issue/label.py
Labels: ⚙️backend

#6588 [WEB-3345] fix: work item form tab index
  web/core/components/issues/issue-modal/components/title-input.tsx
Labels: 🌐frontend

#6599 [WEB-3367]fix: updated i18n key for defaults
  web/core/components/project/project-settings-member-defaults.tsx
Labels: 🐛bug

#6603 [WEB-3362] fix: create sub work item operation
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/sub-issues/root.tsx
Labels: 🐛bug, 🌐frontend

#6602 [WEB-3375] fix: project cover image
  web/core/components/project/form.tsx
Labels: 🌐frontend

#6600 [WEB-3357 | WEB-3363 | WEB-3370] chore: command-k enhancement and fixes
  web/core/components/command-palette/actions/issue-actions/actions-list.tsx
  web/core/components/command-palette/actions/issue-actions/change-assignee.tsx
  web/core/components/command-palette/actions/issue-actions/change-priority.tsx
  web/core/components/command-palette/actions/issue-actions/change-state.tsx
  web/core/components/command-palette/command-modal.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#6546 [WEB-3268] feat: url pattern
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/issue/base.py
  packages/types/src/issues/activity/base.d.ts
  web/app/[workspaceSlug]/(projects)/browse/[workItem]/header.tsx
  web/app/[workspaceSlug]/(projects)/browse/[workItem]/layout.tsx
  web/app/[workspaceSlug]/(projects)/browse/[workItem]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/layout.tsx
  web/ce/layouts/project-wrapper.tsx
  web/core/components/command-palette/helpers.tsx
  web/core/components/core/activity.tsx
  web/core/components/core/modals/existing-issues-list-modal.tsx
  web/core/components/dashboard/widgets/issue-panels/issue-list-item.tsx
  web/core/components/home/widgets/recents/issue.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/inbox-issue-mobile-header.tsx
  web/core/components/inbox/content/issue-properties.tsx
  web/core/components/issues/create-issue-toast-action-items.tsx
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/helpers/issue-link.tsx
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
  web/core/components/issues/issue-detail/parent/root.tsx
  web/core/components/issues/issue-detail/parent/sibling-item.tsx
  web/core/components/issues/issue-detail/relation-select.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-layouts/calendar/issue-block.tsx
  web/core/components/issues/issue-layouts/gantt/blocks.tsx
  web/core/components/issues/issue-layouts/kanban/block.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/parent-issues-list-modal.tsx
  web/core/components/issues/peek-overview/header.tsx
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
  web/core/components/issues/sub-issues/root.tsx
  web/core/components/workspace/sidebar/project-navigation.tsx
  web/core/hooks/use-issue-peek-overview-redirection.tsx
  web/core/layouts/auth-layout/project-wrapper.tsx
  web/core/services/issue/issue.service.ts
  web/core/store/issue/issue-details/issue.store.ts
  web/core/store/issue/issue-details/root.store.ts
  web/core/store/issue/issue.store.ts
  web/helpers/issue.helper.ts
  web/helpers/string.helper.ts
Labels: 🌟enhancement, 🌐frontend, ⚙️backend, 🧹chore

#6620 [WEB-3404] fix: telemetry url
  admin/app/general/form.tsx
Labels: 🌐frontend, 🧹chore

#6627 [WEB-3415] chore: work item url redirection improvement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
Labels: 🌐frontend, 🌟improvement

#6629 chore: add `hslToHex` and `hexToHsl` color helpers
  packages/utils/src/color.ts
Labels: 🌐frontend

#6634 [WEB-3422] fix: app sidebar improvements
  web/core/components/workspace/sidebar/projects-list.tsx
Labels: 🌐frontend, 🌟improvement, 🧹chore

#6635 [WEB-3426] fix: inbox count
  web/ce/components/workspace/sidebar/sidebar-item.tsx
Labels: 🐛bug, 🌐frontend

#6636 [WEB-3425] fix: undefined workspaceslug
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/[cycleId]/page.tsx
  web/core/components/core/activity.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/issues/issue-modal/form.tsx
Labels: 🐛bug, 🌐frontend

#6631 fix: removing self from private project error 404
  web/core/components/project/member-list-item.tsx
Labels: 🌐web

#6640 fix: app header layer
  web/app/[workspaceSlug]/(projects)/extended-project-sidebar.tsx
  web/app/[workspaceSlug]/(projects)/extended-sidebar.tsx
  web/core/components/core/sidebar/sidebar-menu-hamburger-toggle.tsx
Labels: 🐛bug, 🌐frontend

#6625 Fix: date range selector
  packages/ui/src/calendar.tsx
  packages/ui/src/index.ts
  web/core/components/core/filters/date-filter-modal.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/inbox/modals/snooze-issue-modal.tsx
  web/package.json
  yarn.lock
Labels: 🌟enhancement, 🎨UI / UX

#6439 [PE-239] chore: add `strictNullCheck` flag to the editor package
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/read-only-editor.tsx
  packages/editor/src/core/components/menus/ai-menu.tsx
  packages/editor/src/core/components/menus/block-menu.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/custom-color.ts
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/extensions/typography/index.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/tsconfig.json
Labels: 🌐frontend, ✍️editor

#6645 regression: add node id check for image upload status
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#6646 [regression]: space app editor helpers
  packages/editor/src/core/extensions/custom-image/components/upload-status.tsx
  space/helpers/editor.helper.ts
Labels: 🐛bug, 🌐frontend

#6409 [PE-238] refactor: page store hooks
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/page.tsx
  web/ce/components/command-palette/modals/project-level.tsx
  web/ce/hooks/store/index.ts
  web/ce/hooks/store/use-page-store.ts
  web/ce/hooks/store/use-page.ts
  web/core/components/pages/dropdowns/actions.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/pages/editor/header/mobile-root.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/editor/header/root.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/header/root.tsx
  web/core/components/pages/list/block-item-action.tsx
  web/core/components/pages/list/block.tsx
  web/core/components/pages/list/root.tsx
  web/core/components/pages/modals/create-page-modal.tsx
  web/core/components/pages/modals/delete-page-modal.tsx
  web/core/components/pages/pages-list-main-content.tsx
  web/core/components/pages/pages-list-view.tsx
  web/core/hooks/store/index.ts
  web/core/hooks/store/pages/index.ts
  web/core/hooks/store/pages/use-page.ts
  web/core/hooks/store/pages/use-project-page.ts
  web/core/hooks/use-favorite-item-details.tsx
  web/core/store/pages/base-page.ts
  web/core/store/pages/project-page.store.ts
  web/ee/hooks/store/index.ts
Labels: 🌐frontend, 🛠️refactor, pages

#6650 [WEB-3377] fix: attachment item avatar
  packages/types/src/issues/issue_attachment.d.ts
  web/core/components/issues/attachment/attachment-list-item.tsx
Labels: 🐛bug, 🌐frontend

#6648 [WEB-3361] fix: home recent n progress
  web/core/components/core/list/list-item.tsx
  web/core/components/home/widgets/recents/issue.tsx
Labels: 🐛bug, 🌐frontend

#6649 Fix: project settings pages permissions
  web/core/components/labels/label-drag-n-drop-HOC.tsx
  web/core/components/project-states/group-item.tsx
Labels: permissions

#6652 [WEB-3435]fix: add favorites
  web/core/hooks/use-favorite-item-details.tsx
Labels: 🐛bug

#6654 [WEB-3436] fix: work item delete permission and header translation
  web/app/[workspaceSlug]/(projects)/browse/[workItem]/header.tsx
  web/core/components/issues/delete-issue-modal.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6655 [WEB-3439] fix: work item attachment mutation
  apiserver/plane/app/serializers/issue.py
  web/core/store/issue/issue-details/attachment.store.ts
Labels: 🌐frontend, 🧹chore

#6656 regression: add month and year picker
  packages/ui/package.json
  packages/ui/src/calendar.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/package.json
  yarn.lock
Labels: 🐛bug, 🌐frontend

#6657 chore: error handling
  apiserver/plane/app/views/external/base.py
  apiserver/plane/app/views/intake/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/module/issue.py
  apiserver/plane/authentication/views/app/password_management.py
  apiserver/plane/bgtasks/issue_activities_task.py
  apiserver/plane/utils/valid_uuid.py
  apiserver/requirements/base.txt
  apiserver/requirements/local.txt
Labels: 🐛bug, ⚙️backend

#6406 feat: Add support for Plane Swarm in self-hosting methods
  .github/workflows/build-branch.yml
  deploy/selfhost/README.md
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/install.sh
  deploy/selfhost/swarm.sh
  deploy/selfhost/variables.env
Labels: 🏠self-hosted, 🐳docker

#6668 fix: issue activity for project id validation
  apiserver/plane/bgtasks/issue_activities_task.py
Labels: 🐛bug

#6669 updated the action to modify the release build assets
  .github/workflows/build-branch.yml
Labels: 🏠self-hosted, 🐳docker

#6676 fix: date range picker on cycles and modules list
  web/core/components/cycles/analytics-sidebar/sidebar-header.tsx
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
  web/core/components/modules/module-card-item.tsx
  web/core/components/modules/module-list-item-action.tsx
Labels: 🐛bug, 🌟enhancement, 🌐frontend
