Repository makeplane/plane, pull requests merged in 2025-01, with the labels that each got.

#6296 [WEB-2941]chore: added transfer issues button to cycles
  packages/ui/src/icons/transfer-icon.tsx
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/transfer-issues-modal.tsx
  web/core/components/issues/issue-layouts/roots/cycle-layout-root.tsx
Labels: 🌟enhancement, 🌐frontend

#6298 [WEB-1964]chore: cycles actions restructuring
  web/ce/components/cycles/additional-actions.tsx
  web/ce/components/cycles/end-cycle/index.ts
  web/ce/components/cycles/end-cycle/modal.tsx
  web/ce/components/cycles/end-cycle/use-end-cycle.tsx
  web/ce/components/cycles/index.ts
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/list/cycles-list-item.tsx
  web/core/components/cycles/quick-actions.tsx
  web/ee/components/cycles/end-cycle/index.ts
  web/ee/components/cycles/index.ts
Labels: 🌐frontend, 🧹chore

#6306 [WEB-3033] fix: active cycle graph tooltip and endpoint validation
  web/core/components/cycles/active-cycle/use-cycles-details.ts
Labels: 🐛bug, 🌐frontend

#6307 feat: add issue attachment v1 endpoint
  apiserver/plane/api/views/issue.py
Labels: ⚙️backend

#6303 [PE-97] chore: re-order pages options
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/components/pages/list/block-item-action.tsx
Labels: 🌟enhancement, 🌐frontend, pages

#6295 [WEB-2937] feat: home recent activies list endpoint
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/favorite.py
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/urls/workspace.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/workspace/recent_visit.py
Labels: ⚙️backend, 📡api

#6304 [PE-88] fix: remove emoji edit for uneditable pages
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
Labels: 🐛bug, 🌐frontend, pages

#6300 feat: workspace home preference model
  apiserver/plane/db/migrations/0089_workspacehomepreference_and_more.py
  apiserver/plane/db/models/page.py
  apiserver/plane/db/models/sticky.py
  apiserver/plane/db/models/workspace.py
Labels: ⚙️backend, 🔄migrations

#6320 [WEB-2926]fix: added tooltips for favorites
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
Labels: 🐛bug, 🌐frontend

#6326 fix: user config dependencies
  web/core/components/pages/editor/editor-body.tsx
Labels: 🐛bug, 🌐frontend, pages

#6308 [WEB-3038]feat: home preferences
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/workspace.py
  apiserver/plane/app/urls/workspace.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/workspace/preference.py
  apiserver/plane/db/models/__init__.py
Labels: 📡api

#6322 [WEB-3040] chore: project breadcrumb improvement
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/settings/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/ce/components/breadcrumbs/index.ts
  web/ce/components/breadcrumbs/project.tsx
  web/ce/components/issues/header.tsx
  web/ce/components/projects/settings/intake/header.tsx
  web/ee/components/breadcrumbs/index.ts
Labels: 🌐frontend, 🌟improvement, 🧹chore

#6324 [WEB-2370]chore: activity filters
  web/ce/store/issue/issue-details/activity.store.ts
  web/core/components/issues/issue-detail/issue-activity/activity-comment-root.tsx
  web/core/components/issues/issue-detail/issue-activity/activity-filter.tsx
  web/core/components/issues/issue-detail/issue-activity/root.tsx
  web/core/components/issues/issue-detail/issue-activity/sort-root.tsx
  web/core/constants/common.ts
Labels: 🌟enhancement, 🌐frontend

#6325 [WEB-2915] fix: Modules reordering through drag and drop
  web/core/components/gantt-chart/sidebar/modules/sidebar.tsx
Labels: 🐛bug

#6327 [PE-97] refactor: page actions
  web/ce/constants/index.ts
  web/ce/constants/page.ts
  web/core/components/pages/dropdowns/actions.tsx
  web/core/components/pages/editor/header/options-dropdown.tsx
  web/core/services/page/project-page.service.ts
  web/core/store/pages/project-page.store.ts
  web/ee/constants/page.ts
Labels: 🌐frontend, pages

#6330 [WEB-3042]fix: added tooltips for truncated favorites
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-title.tsx
Labels: 🐛bug, 🌐frontend

#6333 [WEB-3049] fix: Resolve start and end date comparison issue in cycle create and update
  apiserver/plane/api/serializers/cycle.py
  apiserver/plane/app/serializers/cycle.py
  apiserver/plane/app/views/cycle/base.py
Labels: 🐛bug, ⚙️backend

#6338 [WEB-2226]chore: updated 'Issue states' settings ui
  web/core/components/project-states/create-update/form.tsx
  web/core/components/project-states/group-item.tsx
  web/core/components/project-states/group-list.tsx
  web/core/components/project-states/state-item-title.tsx
  web/core/components/project-states/state-item.tsx
Labels: 🌟enhancement, 🌐frontend

#6336 [PE-83] fix: reset text and background color in issue description
  packages/editor/src/core/components/menus/bubble-menu/color-selector.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#6346 [PE-219] chore: add missing tiptap/html package to the editor
  packages/editor/package.json
Labels: 🐛bug, 🌐frontend, ✍️editor

#6350 [WEB-2943] chore: issue reaction and code refactor
  web/core/components/issues/issue-detail/reactions/issue.tsx
  web/core/store/project/project.store.ts
Labels: 🌐frontend, 🧹chore

#6329 [WEB-2783]fix: dropdown visibility in onboarding
  web/core/components/onboarding/invite-members.tsx
Labels: 🐛bug, 🌐frontend

#6345 [PE-47] fix: update fallback logic for newly created pages
  web/core/hooks/use-page-fallback.ts
Labels: 🐛bug, 🌐frontend, pages

#6354 [PE-97] chore: add page flag hook for authorization
  web/ce/constants/page.ts
  web/ce/hooks/use-page-flag.ts
  web/core/components/pages/dropdowns/actions.tsx
  web/ee/constants/page.ts
  web/ee/hooks/use-page-flag.ts
Labels: 🌐frontend, 🛠️refactor, pages

#6362 [WEB-3079]fix: copy module link
  web/core/components/modules/links/list-item.tsx
Labels: 🐛bug

#6364 [PE-228] chore: update `@tiptap/extension-task-item` version and required css
  packages/editor/package.json
  packages/editor/src/styles/editor.css
  yarn.lock
Labels: 🌐frontend, 🌟improvement, ✍️editor

#6368 [PE-208] fix: floating toolbar content
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor

#6367 [WEB-3090]fix: added missing translation
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  web/core/components/home/widgets/recents/index.tsx
Labels: 🐛bug, 🌐frontend

#6352 [WEB-2944]fix: prevented multiple API calls while updating comment
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
Labels: 🐛bug, 🌐frontend

#6356 [WEB-2943] chore: app theme store
  web/core/store/theme.store.ts
Labels: 🌐frontend, 🧹chore

#6341 [WEB-2245]fix: workspace views update
  web/core/components/workspace/views/form.tsx
Labels: 🐛bug, 🌐frontend

#6371 fix: quick links error in home
  apiserver/plane/app/views/workspace/quick_link.py
Labels: 🐛bug, ⚙️backend

#6375 [WEB-3100] chore: no load improvement
  web/core/store/issue/issue.store.ts
Labels: 🌐frontend

#6397 [WEB-3078] chore: empty state config
  web/core/components/core/charts/tree-map/map-content.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/constants/empty-state.ts
Labels: 🌐frontend, 🧹chore

#6376 [WEB-1964]chore: added current cycle to cycle dropdown
  web/core/components/dropdowns/cycle/cycle-options.tsx
  web/core/components/dropdowns/cycle/index.tsx
Labels: 🌐frontend, 🧹chore

#6388 [WEB-2877]fix: removed redundant custom menu
  web/core/components/workspace/views/quick-action.tsx
Labels: 🐛bug, 🌐frontend

#6402 [WEB-3043]chore: removed guest assignees from issue filters
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/core/components/issues/filters.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
Labels: 🌐frontend, 🧹chore

#6269 [PE-210] feat: editor performance
  live/package.json
  packages/editor/package.json
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/helpers/insert-content-at-cursor-position.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  yarn.lock
Labels: 🛫plane

#6405 [WEB-1964]chore: cycle store restructuring
  web/ce/components/cycles/end-cycle/modal.tsx
  web/ce/store/cycle/index.ts
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/quick-actions.tsx
  web/core/hooks/store/use-cycle.ts
  web/ee/store/cycle/index.ts
Labels: 🌐frontend, 🧹chore

#6408 fix: page open in new tab action
  web/core/hooks/use-page-operations.ts
Labels: 🐛bug, 🌐frontend, pages

#6410 [WEB-3139] fix: sub-issue visibility
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
Labels: 🌐frontend, 🧹chore

#6380 [WEB-3096] feat: stickies page
  apiserver/plane/app/views/workspace/sticky.py
  apiserver/plane/db/models/sticky.py
  packages/constants/src/index.ts
  packages/constants/src/stickies.ts
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/variables.css
  packages/types/src/stickies.d.ts
  web/app/[workspaceSlug]/(projects)/stickies/header.tsx
  web/app/[workspaceSlug]/(projects)/stickies/layout.tsx
  web/app/[workspaceSlug]/(projects)/stickies/page.tsx
  web/core/components/core/content-overflow-HOC.tsx
  web/core/components/editor/sticky-editor/color-palette.tsx
  web/core/components/editor/sticky-editor/color-pallete.tsx
  web/core/components/editor/sticky-editor/editor.tsx
  web/core/components/editor/sticky-editor/toolbar.tsx
  web/core/components/empty-state/empty-state.tsx
  web/core/components/home/home-dashboard-widgets.tsx
  web/core/components/home/root.tsx
  web/core/components/home/user-greetings.tsx
  web/core/components/home/widgets/empty-states/links.tsx
  web/core/components/home/widgets/empty-states/recents.tsx
  web/core/components/home/widgets/empty-states/root.tsx
  web/core/components/home/widgets/empty-states/stickies.tsx
  web/core/components/home/widgets/links/link-detail.tsx
  web/core/components/home/widgets/links/links.tsx
  web/core/components/home/widgets/links/use-links.tsx
  web/core/components/home/widgets/manage/widget-item.tsx
  web/core/components/home/widgets/recents/index.tsx
  web/core/components/stickies/action-bar.tsx
  web/core/components/stickies/empty.tsx
  web/core/components/stickies/index.ts
  web/core/components/stickies/layout/index.ts
  web/core/components/stickies/layout/stickies-infinite.tsx
  web/core/components/stickies/layout/stickies-list.tsx
  web/core/components/stickies/layout/stickies-truncated.tsx
  web/core/components/stickies/layout/sticky-dnd-wrapper.tsx
  web/core/components/stickies/layout/sticky.helpers.ts
  web/core/components/stickies/modal/search.tsx
  web/core/components/stickies/modal/stickies.tsx
  web/core/components/stickies/stickies-layout.tsx
  web/core/components/stickies/sticky/inputs.tsx
  web/core/components/stickies/sticky/root.tsx
  web/core/components/stickies/sticky/sticky-item-drag-handle.tsx
  web/core/components/stickies/sticky/use-operations.tsx
  web/core/components/stickies/widget.tsx
  web/core/constants/empty-state.tsx
  web/core/services/sticky.service.ts
  web/core/store/sticky/sticky.store.ts
  web/core/store/workspace/home.ts
  web/public/empty-state/dashboard/widgets-dark.webp
  web/public/empty-state/dashboard/widgets-light.webp
  web/public/empty-state/stickies/stickies-dark.webp
  web/public/empty-state/stickies/stickies-light.webp
  web/public/empty-state/stickies/stickies-search-dark.webp
  web/public/empty-state/stickies/stickies-search-light.webp
  web/styles/globals.css
Labels: 🌐frontend, 🌟improvement, 🛠️refactor

#6399 [WEB-3133] fix: admin login when the user is not present
  apiserver/plane/license/api/views/admin.py
Labels: 🐛bug, ⚙️backend

#6416 [WEB-3168] fix: draft issue fetch
  web/core/components/issues/workspace-draft/root.tsx
  web/core/store/issue/workspace-draft/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore

#6414 [WEB-3166] chore: global empty state components
  web/core/components/empty-state/detailed-empty-state-root.tsx
  web/core/components/empty-state/index.ts
  web/core/components/empty-state/section-empty-state-root.tsx
  web/core/components/empty-state/simple-empty-state-root.tsx
  web/core/hooks/use-resolved-asset-path.tsx
Labels: 🌐frontend, 🧹chore

#6419 [WEB 3132] chore: progress helper function and code refactor
  web/ce/components/issues/issue-layouts/issue-stats.tsx
  web/core/components/issues/issue-layouts/list/block.tsx
  web/helpers/common.helper.ts
Labels: 🌐frontend

#6420 [WEB-3172]fix: issue create in layouts.
  web/core/components/issues/issue-modal/base.tsx
Labels: 🌟enhancement, 🌐frontend

#6424 [WEB-3152]fix: padding issue cycles menu
  web/core/components/cycles/quick-actions.tsx
Labels: 🐛bug, 🌐frontend

#6423 [WEB-3176] chore: workspace view loading state improvement
  web/app/[workspaceSlug]/(projects)/workspace-views/[globalViewId]/page.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/core/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
Labels: 🌐frontend, 🧹chore

#6430 [PE-237] fix: editor placeholder and muted text color
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/variables.css
Labels: 🌐frontend, 🌟improvement, ✍️editor

#6433 [WEB-3045] fix: stickies bugs
  web/core/components/stickies/delete-modal.tsx
  web/core/components/stickies/layout/stickies-list.tsx
  web/core/components/stickies/layout/stickies-loader.tsx
  web/core/components/stickies/layout/sticky-dnd-wrapper.tsx
  web/core/components/stickies/modal/stickies.tsx
  web/core/components/stickies/sticky/inputs.tsx
  web/core/components/stickies/sticky/root.tsx
Labels: 🐛bug, 🌐frontend, 🌟improvement

#6436 [WEB-3045] fix: sticky placeholder, gray color value
  web/core/components/editor/sticky-editor/color-palette.tsx
  web/core/components/editor/sticky-editor/editor.tsx
  web/core/components/stickies/sticky/inputs.tsx
Labels: 🌐frontend, 🌟improvement

#6434 [WEB-3186] chore: added endpoints for issue and issue description versioning
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/issue/version.py
Labels: ⚙️backend, 🧹chore, 📡api

#6440 [WEB-3194]fix: stickies modal close while redirection
  web/core/components/stickies/layout/stickies-truncated.tsx
  web/core/components/stickies/modal/stickies.tsx
Labels: 🐛bug

#6446 [PE-244] fix: space app editor colors
  space/styles/globals.css
Labels: 🌐frontend, 🚀space, ✍️editor

#6451 [WEB-3198]fix: handled label overflow in modules
  web/core/components/core/sidebar/single-progress-stats.tsx
  web/core/components/modules/analytics-sidebar/progress-stats.tsx
Labels: 🐛bug, 🌐frontend

#6456 [PE-248] regression: recent widgets refactor for scalability
  packages/types/src/home.d.ts
  web/core/components/home/widgets/recents/index.tsx
  web/core/components/home/widgets/recents/page.tsx
Labels: 🌐frontend, 🌟improvement

#6459 chore: migrated filters.ts to packages
  packages/constants/src/filter.ts
  web/core/components/common/applied-filters/date.tsx
  web/core/components/common/filters/created-at.tsx
  web/core/components/cycles/applied-filters/date.tsx
  web/core/components/cycles/dropdowns/filters/end-date.tsx
  web/core/components/cycles/dropdowns/filters/start-date.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/date.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/start-date.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/target-date.tsx
  web/core/components/modules/applied-filters/date.tsx
  web/core/components/modules/dropdowns/filters/start-date.tsx
  web/core/components/modules/dropdowns/filters/target-date.tsx
  web/core/components/pages/header/root.tsx
  web/core/components/project/applied-filters/date.tsx
  web/core/components/project/dropdowns/filters/created-at.tsx
  web/core/constants/filters.ts
Labels: 🌟enhancement, 🧹chore

#6462 feat: workspace constant language support and refactor
  packages/constants/src/workspace.ts
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  web/app/[workspaceSlug]/(projects)/settings/mobile-header-tabs.tsx
  web/app/[workspaceSlug]/(projects)/settings/sidebar.tsx
  web/app/[workspaceSlug]/(projects)/workspace-views/[globalViewId]/page.tsx
  web/app/[workspaceSlug]/(projects)/workspace-views/page.tsx
  web/app/invitations/page.tsx
  web/ce/constants/index.ts
  web/ce/constants/workspace.ts
  web/core/components/command-palette/actions/workspace-settings-actions.tsx
  web/core/components/editor/embeds/mentions/user.tsx
  web/core/components/exporter/guide.tsx
  web/core/components/integration/guide.tsx
  web/core/components/integration/single-import.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/global-view-root.tsx
  web/core/components/onboarding/invitations.tsx
  web/core/components/onboarding/invite-members.tsx
  web/core/components/profile/form.tsx
  web/core/components/project/send-project-invitation-modal.tsx
  web/core/components/project/settings/member-columns.tsx
  web/core/components/workspace/send-workspace-invitation-modal.tsx
  web/core/components/workspace/settings/invitations-list-item.tsx
  web/core/components/workspace/settings/member-columns.tsx
  web/core/components/workspace/views/default-view-list-item.tsx
  web/core/components/workspace/views/default-view-quick-action.tsx
  web/core/components/workspace/views/header.tsx
  web/core/constants/workspace.ts
  web/ee/constants/workspace.ts
Labels: 🌐frontend, 🧹chore

#6391 [WEB-3238] dev: datepicker with month and year selection dropdowns
  web/core/components/core/filters/date-filter-modal.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/inbox/modals/snooze-issue-modal.tsx
  web/package.json
  web/styles/react-day-picker.css
Labels: 🌐frontend, 🌟improvement

#6484 [WEB-3203] fix: stickies height, overflow
  web/core/components/editor/sticky-editor/editor.tsx
  web/core/components/editor/sticky-editor/toolbar.tsx
  web/core/components/stickies/layout/sticky-dnd-wrapper.tsx
  web/core/components/stickies/sticky/inputs.tsx
  web/core/components/stickies/sticky/root.tsx
Labels: 🐛bug, 🌐frontend

#6485 chore: drafts language support
  packages/i18n/src/locales/en/translations.json
  web/app/[workspaceSlug]/(projects)/drafts/header.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/draft-issue.tsx
  web/core/components/issues/issue-modal/form.tsx
  web/core/components/issues/workspace-draft/delete-modal.tsx
  web/core/components/issues/workspace-draft/draft-issue-block.tsx
  web/core/components/issues/workspace-draft/quick-action.tsx
Labels: 🌐frontend

#6470 [WEB-3237, 3238] dev: date picker enhancements
  web/core/components/core/filters/date-filter-modal.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/inbox/modals/snooze-issue-modal.tsx
  web/package.json
  web/styles/react-day-picker.css
Labels: 🐛bug, 🌐frontend, 🎨UI / UX, 🌟improvement

#6480 refactor: page constants
  packages/constants/src/index.ts
  packages/constants/src/page.ts
  packages/constants/src/views.ts
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/core/components/pages/dropdowns/actions.tsx
  web/core/components/pages/list/order-by.tsx
  web/core/components/pages/modals/create-page-modal.tsx
  web/core/components/pages/modals/page-form.tsx
  web/core/components/pages/pages-list-main-content.tsx
  web/core/constants/page.ts
  web/core/store/base-command-palette.store.ts
  web/core/store/pages/base-page.ts
  web/core/store/pages/project-page.ts
Labels: 🧹chore

#6491 [WEB-3179, 3247] fix: page name and recents empty state
  web/core/components/home/widgets/recents/index.tsx
  web/core/components/home/widgets/recents/page.tsx
Labels: 🐛bug, 🌐frontend

#6489 refactor: spredsheets constants
  packages/constants/src/index.ts
  packages/constants/src/spreadsheet.ts
  packages/i18n/src/locales/en/translations.json
  web/core/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-view.tsx
  web/core/constants/spreadsheet.ts
Labels: 🌐frontend, 🧹chore

#6493 feat: language translation - projects list
  packages/i18n/src/locales/en/translations.json
  web/ce/components/projects/mobile-header.tsx
  web/core/components/project/applied-filters/root.tsx
  web/core/components/project/card-list.tsx
  web/core/components/project/filters.tsx
  web/core/components/project/header.tsx
  web/core/components/project/project-feature-update.tsx
  web/core/components/project/root.tsx
  web/core/components/project/search-projects.tsx
Labels: 🌟enhancement, 🌐frontend

#6445 [PE-240] fix: disable comment submit while uploading an image
  web/core/components/editor/lite-text-editor/toolbar.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-card.tsx
Labels: 🐛bug, 🌐frontend

#6504 [WEB-3177] fix: resolve cycle creation issue for equal start_date and completed_date
  apiserver/plane/utils/timezone_converter.py
Labels: ⚙️backend

#6507 chore: board layout padding improvement
  web/core/components/issues/issue-layouts/kanban/default.tsx
Labels: 🌐frontend, 🧹chore

#6501 feat: language support issues
  packages/i18n/src/locales/en/translations.json
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/[issueId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(list)/page.tsx
  web/ce/components/issues/header.tsx
  web/ce/components/relations/index.tsx
  web/core/components/dropdowns/cycle/cycle-options.tsx
  web/core/components/dropdowns/cycle/index.tsx
  web/core/components/dropdowns/module/index.tsx
  web/core/components/dropdowns/module/module-options.tsx
  web/core/components/home/widgets/links/use-links.tsx
  web/core/components/issues/archive-issue-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
  web/core/components/issues/issue-detail-widgets/relations/content.tsx
  web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
  web/core/components/issues/issue-detail/issue-activity/root.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/parent-select.tsx
  web/core/components/issues/issue-detail/parent/root.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/issue-layouts/filters/header/display-filters/issue-grouping.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/priority.tsx
  web/core/components/issues/issue-layouts/properties/all-properties.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
  web/core/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  web/core/components/issues/issue-layouts/quick-add/form/list.tsx
  web/core/components/issues/issue-layouts/quick-add/root.tsx
  web/core/components/issues/issue-modal/components/default-properties.tsx
  web/core/components/issues/parent-issues-list-modal.tsx
  web/core/components/issues/title-input.tsx
Labels: 🌟enhancement, 🌐frontend

#6512 [WEB-3095] fix: recents widget title truncate
  web/core/components/home/widgets/recents/issue.tsx
  web/core/components/home/widgets/recents/page.tsx
  web/core/components/home/widgets/recents/project.tsx
Labels: 🐛bug, 🌐frontend

#6513 feat: language support for issues
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/issues/(detail)/header.tsx
  web/ce/components/issues/header.tsx
  web/ce/constants/project/settings/tabs.ts
  web/core/components/core/modals/existing-issues-list-modal.tsx
  web/core/components/dropdowns/state.tsx
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/editor/lite-text-editor/toolbar.tsx
  web/core/components/gantt-chart/chart/header.tsx
  web/core/components/gantt-chart/data/index.ts
  web/core/components/gantt-chart/sidebar/root.tsx
  web/core/components/gantt-chart/types/index.ts
  web/core/components/issues/attachment/attachment-item-list.tsx
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/core/components/issues/attachment/delete-attachment-modal.tsx
  web/core/components/issues/delete-issue-modal.tsx
  web/core/components/issues/issue-detail-widgets/attachments/title.tsx
  web/core/components/issues/issue-detail-widgets/links/title.tsx
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail-widgets/relations/title.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/issue-detail/cycle-select.tsx
  web/core/components/issues/issue-detail/issue-detail-quick-actions.tsx
  web/core/components/issues/issue-detail/label/root.tsx
  web/core/components/issues/issue-detail/label/select/label-select.tsx
  web/core/components/issues/issue-detail/links/create-update-link-modal.tsx
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/components/issues/issue-detail/module-select.tsx
  web/core/components/issues/issue-detail/subscription.tsx
  web/core/components/issues/issue-layouts/calendar/dropdowns/options-dropdown.tsx
  web/core/components/issues/issue-layouts/calendar/header.tsx
  web/core/components/issues/issue-layouts/calendar/issue-blocks.tsx
  web/core/components/issues/issue-layouts/calendar/quick-add-issue-actions.tsx
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/properties/label-dropdown.tsx
  web/core/components/issues/issue-layouts/quick-add/button/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/button/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/button/list.tsx
  web/core/components/issues/issue-layouts/quick-add/button/spreadsheet.tsx
  web/core/components/issues/issue-layouts/quick-add/form/gantt.tsx
  web/core/components/issues/issue-layouts/quick-add/form/kanban.tsx
  web/core/components/issues/issue-layouts/quick-add/form/spreadsheet.tsx
  web/core/components/issues/issue-layouts/quick-add/root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/columns/header-column.tsx
  web/core/components/issues/peek-overview/header.tsx
  web/core/components/issues/peek-overview/properties.tsx
  web/core/components/issues/peek-overview/root.tsx
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/sub-issues/issue-list-item.tsx
  web/helpers/issue.helper.ts
Labels: 🌟enhancement, 🌐frontend

#6519 feat: language support description
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  web/core/components/home/home-dashboard-widgets.tsx
  web/core/components/inbox/modals/create-modal/issue-description.tsx
  web/core/components/issues/description-input.tsx
  web/core/components/issues/issue-modal/components/description-editor.tsx
  web/helpers/issue.helper.ts
Labels: 🌟enhancement

#6520 [PE-269] fix: table flicker during resize
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/table.css
Labels: 🐛bug, 🌐frontend, ✍️editor

#6517 [PE-265] fix: adding link to editor via floating toolbar
  packages/editor/src/core/components/menus/bubble-menu/link-selector.tsx
Labels: 🌐frontend, 🌟improvement, ✍️editor

#6524 [PE-269] fix: table flicker on resize
  packages/editor/src/styles/editor.css
Labels: 🐛bug, 🌐frontend, ✍️editor

#6531 [WEB-3271] fix: adjust z-index to prevent overlap issue with version history panel
  web/core/components/pages/version/root.tsx
Labels: 🐛bug, 🌐frontend

#6529 [PE-272] fix: prevent error on reload when page version history panel is open
  packages/editor/src/core/hooks/use-editor.ts
Labels: 🐛bug, 🌐frontend

#6526 [WEB-3230]fix: cycle labels overflow issue
  web/core/components/cycles/active-cycle/cycle-stats.tsx
  web/core/components/cycles/analytics-sidebar/progress-stats.tsx
Labels: 🐛bug, 🌐frontend

#6534 fix: updated keys
  packages/i18n/src/locales/en/translations.json
  web/ce/constants/project/settings/tabs.ts
  web/core/components/exporter/export-modal.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
  web/core/components/workspace/views/delete-view-modal.tsx
Labels: 🐛bug

#6523 chore: webhook, comments migration
  apiserver/plane/app/views/webhook/base.py
  apiserver/plane/bgtasks/webhook_task.py
  apiserver/plane/db/migrations/0091_issuecomment_edited_at_and_more.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/db/models/recent_visit.py
  apiserver/plane/db/models/user.py
  apiserver/plane/db/models/webhook.py
Labels: ⚙️backend, 🔄migrations
