Repository makeplane/plane, pull requests merged in 2025-08, with the labels that each got.

#7532 [WEB-4628] chore: return 200 response for work item comment
  apps/api/plane/api/views/issue.py
Labels: ready to merge

#7527 [WIKI-576] fix: trail node
  apps/space/ce/hooks/use-editor-flagging.ts
  apps/space/core/components/editor/lite-text-editor.tsx
  apps/space/core/components/editor/rich-text-editor.tsx
  apps/web/core/store/pages/base-page.ts
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/extensions/slash-commands/command-menu-item.tsx
  packages/editor/src/core/types/slash-commands-suggestion.ts
  packages/types/src/page/core.ts
Labels: 🐛bug, ✍️editor, ready to merge

#7536 [WIKI-578] refactor: editor types structure
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/editor-content.tsx
  packages/editor/src/core/components/editors/link-view-container.tsx
  packages/editor/src/core/components/links/link-edit-view.tsx
  packages/editor/src/core/components/links/link-view.tsx
  packages/editor/src/core/components/menus/block-menu.tsx
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
  packages/editor/src/core/extensions/code-inline/index.tsx
  packages/editor/src/core/extensions/code/code-block-lowlight.ts
  packages/editor/src/core/extensions/code/code-block-node-view.tsx
  packages/editor/src/core/extensions/code/code-block.ts
  packages/editor/src/core/extensions/custom-link/extension.tsx
  packages/editor/src/core/extensions/emoji/components/emojis-list.tsx
  packages/editor/src/core/extensions/emoji/emoji.ts
  packages/editor/src/core/extensions/headings-list.ts
  packages/editor/src/core/extensions/horizontal-rule.ts
  packages/editor/src/core/extensions/table/table-cell.ts
  packages/editor/src/core/extensions/table/table-header.ts
  packages/editor/src/core/extensions/table/table-row.ts
  packages/editor/src/core/extensions/table/table/table.ts
  packages/editor/src/core/extensions/table/table/utilities/create-cell.ts
  packages/editor/src/core/extensions/table/table/utilities/delete-key-shortcut.ts
  packages/editor/src/core/extensions/table/table/utilities/helpers.ts
  packages/editor/src/core/extensions/typography/inputRules.ts
  packages/editor/src/core/extensions/utility.ts
  packages/editor/src/core/extensions/work-item-embed/extension.tsx
  packages/editor/src/core/helpers/common.ts
  packages/editor/src/core/helpers/scroll-to-node.ts
  packages/editor/src/core/types/editor.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready to merge

#7538 [WEB-4634]chore: refactor for work items store
  apps/web/ce/components/issues/issue-layouts/empty-states/index.ts
  apps/web/ce/components/issues/issue-layouts/empty-states/team-project.tsx
  apps/web/ce/helpers/issue-action-helper.ts
  apps/web/ce/store/issue/team-project/filter.store.ts
  apps/web/ce/store/issue/team-project/index.ts
  apps/web/ce/store/issue/team-project/issue.store.ts
  apps/web/core/components/issues/issue-layouts/empty-states/index.tsx
  apps/web/core/hooks/store/use-issues.ts
  apps/web/core/hooks/use-group-dragndrop.ts
  apps/web/core/hooks/use-issue-layout-store.ts
  apps/web/core/hooks/use-issues-actions.tsx
  apps/web/core/store/issue/root.store.ts
  packages/constants/src/issue/common.ts
  packages/types/src/issues/issue.ts
  packages/utils/src/work-item/base.ts
Labels: 🛠️refactor, ready to merge, changes required

#7578 [WEB-4693] fix: remove initial load flicker on auto-archive and auto-close automation page
  apps/web/core/components/automation/auto-archive-automation.tsx
  apps/web/core/components/automation/auto-close-automation.tsx
Labels: 🐛bug, ready to merge

#7601 [SILO-449] fix: add missing methods in external APIs
  apps/api/plane/api/serializers/project.py
  apps/api/plane/api/urls/member.py
Labels: ready to merge

#7627 [WEB-4748] chore: placement helper fn added and code refactor
  packages/propel/src/popover/root.tsx
  packages/propel/src/tooltip/root.tsx
  packages/propel/src/utils/placement.ts
Labels: ready to merge

#7626 [WEB-4747]chore: rendering cycle progress from snaposhot
  apps/web/core/components/cycles/list/cycles-list-item.tsx
Labels: ready to merge

#7624 [WIKI-498] [WIKI-567] feat: ability to rearrange columns and rows in table
  packages/editor/src/core/constants/meta.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/actions.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/color-selector.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/column/drag-handle.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/column/dropdown.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/column/plugin.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/column/utils.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/marker-utils.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/row/drag-handle.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/row/dropdown.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/row/plugin.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/row/utils.ts
  packages/editor/src/core/extensions/table/plugins/drag-handles/utils.ts
  packages/editor/src/core/extensions/table/plugins/insert-handlers/plugin.ts
  packages/editor/src/core/extensions/table/plugins/insert-handlers/utils.ts
  packages/editor/src/core/extensions/table/table-cell.ts
  packages/editor/src/core/extensions/table/table-header.ts
  packages/editor/src/core/extensions/table/table/table-controls.ts
  packages/editor/src/core/extensions/table/table/table.ts
  packages/editor/src/core/extensions/table/table/utilities/helpers.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/styles/table.css
Labels: 🌐frontend, 🌟improvement, ✍️editor, ready to merge

#7622 [WEB-4751] refactor: added tld validation for urls
  packages/propel/src/command/command.tsx
  packages/utils/package.json
  packages/utils/src/url.ts
  pnpm-lock.yaml
Labels: ready to merge

#7633 refactor: remove few barrel exports
  apps/web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/intake/layout.tsx
  apps/web/app/(all)/[workspaceSlug]/(settings)/settings/projects/[projectId]/members/page.tsx
  apps/web/ce/components/breadcrumbs/project-feature.tsx
  apps/web/ce/components/common/index.ts
  apps/web/ce/components/common/subscription/index.ts
  apps/web/ce/components/de-dupe/index.ts
  apps/web/ce/components/de-dupe/issue-block/index.ts
  apps/web/ce/components/epics/index.ts
  apps/web/ce/components/projects/navigation/index.ts
  apps/web/ce/components/projects/settings/intake/index.ts
  apps/web/ce/components/projects/teamspaces/index.ts
  apps/web/core/components/core/app-header.tsx
  apps/web/core/components/inbox/content/issue-root.tsx
  apps/web/core/components/inbox/modals/create-modal/create-root.tsx
  apps/web/core/components/issues/issue-detail-widgets/relations/content.tsx
  apps/web/core/components/issues/issue-detail/main-content.tsx
  apps/web/core/components/issues/issue-modal/form.tsx
  apps/web/core/components/issues/peek-overview/issue-detail.tsx
  apps/web/core/components/settings/sidebar/header.tsx
  apps/web/core/components/workspace/sidebar/dropdown-item.tsx
  apps/web/ee/components/de-dupe/index.ts
  apps/web/ee/components/epics/index.ts
  apps/web/ee/components/projects/settings/intake/index.ts
Labels: ready to merge

#7636 [WEB-4751] chore: enhance URL utility functions with IP address validation and cleaned up url extraction
  packages/utils/src/url.ts
Labels: ready to merge

#7644 [WEB-4438] fix: epics label in y axis of epics(analytics-modal)
  apps/web/core/components/analytics/select/analytics-params.tsx
  apps/web/core/components/analytics/work-items/customized-insights.tsx
  apps/web/core/components/analytics/work-items/modal/content.tsx
  apps/web/core/components/analytics/work-items/modal/index.tsx
  packages/constants/src/analytics/common.ts
  packages/types/src/analytics.ts
Labels: requires approval

#7642 [WIKI-602] chore: disable image alignment tooltip for touch devices
  packages/editor/src/core/extensions/custom-image/components/toolbar/alignment.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/root.tsx
  packages/editor/src/styles/editor.css
Labels: ✍️editor, ready to merge

#7152 [WIKI-345] chore: pass disabled and flagged extensions to block menu
  apps/live/src/core/services/api.service.ts
  apps/space/helpers/string.helper.ts
  apps/web/core/components/editor/lite-text/editor.tsx
  apps/web/core/components/editor/sticky-editor/editor.tsx
  apps/web/next.config.js
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/link-view-container.tsx
  packages/editor/src/core/components/menus/block-menu.tsx
  packages/editor/src/core/extensions/custom-link/extension.tsx
  packages/editor/src/core/extensions/extensions.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/hook.ts
  packages/utils/src/string.ts
Labels: ready to merge

#7647 [WIKI-345] regression: update block menu options
  packages/editor/src/ce/extensions/core/extensions.ts
  packages/editor/src/core/components/editors/document/editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
Labels: ✍️editor, ready to merge

#7653 [WEB-4761] fix: resolve circular import between IssueService and local db
  apps/web/core/services/issue/issue.service.ts
Labels: ready to merge

#7648 [WEB-4780] chore: changed the html validation
  apps/api/plane/api/serializers/issue.py
  apps/api/plane/api/serializers/project.py
  apps/api/plane/app/serializers/draft.py
  apps/api/plane/app/serializers/issue.py
  apps/api/plane/app/serializers/page.py
  apps/api/plane/app/serializers/project.py
  apps/api/plane/app/serializers/workspace.py
  apps/api/plane/space/serializer/issue.py
  apps/api/plane/utils/content_validator.py
  apps/api/requirements/base.txt
Labels: ready to merge

#7663 [WEB-4722]fix: fixed draft state update
  apps/api/plane/app/views/workspace/draft.py
Labels: 🐛bug, ⚙️backend, ready to merge

#7662 [WEB-4748] chore: propel utils
  packages/propel/package.json
  packages/propel/src/avatar/avatar.tsx
  packages/propel/src/card/card.tsx
  packages/propel/src/charts/bar-chart/bar.tsx
  packages/propel/src/charts/components/legend.tsx
  packages/propel/src/charts/components/tooltip.tsx
  packages/propel/src/charts/tree-map/map-content.tsx
  packages/propel/src/charts/tree-map/root.tsx
  packages/propel/src/combobox/combobox.tsx
  packages/propel/src/command/command.tsx
  packages/propel/src/dialog/root.tsx
  packages/propel/src/menu/menu.tsx
  packages/propel/src/switch/root.tsx
  packages/propel/src/table/core.tsx
  packages/propel/src/tabs/list.tsx
  packages/propel/src/tabs/tabs.tsx
  packages/propel/src/tooltip/root.tsx
  packages/propel/src/utils/classname.tsx
  pnpm-lock.yaml
Labels: 🌐frontend, 🌟improvement, ready to merge

#7618 [SILO-454] chore: refactor decorator, logger packages
  apps/admin/package.json
  apps/space/package.json
  apps/web/package.json
  packages/decorators/.prettierrc
  packages/decorators/README.md
  packages/decorators/package.json
  packages/decorators/src/controller.ts
  packages/decorators/src/index.ts
  packages/decorators/src/rest.ts
  packages/decorators/src/websocket-controller.ts
  packages/decorators/tsconfig.json
  packages/i18n/package.json
  packages/logger/package.json
  packages/logger/src/config.ts
  packages/logger/src/middleware.ts
  packages/ui/package.json
  packages/utils/package.json
  pnpm-lock.yaml
Labels: ready to merge

#7667 feat: added support for expanding `updated_by` in work item
  apps/api/plane/api/serializers/base.py
Labels: ready to merge

#7673 [WIKI-619] chore: added sort order migration for page model
  apps/api/plane/db/migrations/0102_page_sort_order_pagelog_entity_type_and_more.py
  apps/api/plane/db/models/page.py
Labels: 🔄migrations, ready to merge
