Repository makeplane/plane, pull requests merged in 2025-06, with the labels that each got.

#7156 [WIKI-410] chore: editor translation files
  packages/i18n/src/constants/language.ts
  packages/i18n/src/locales/cs/editor.json
  packages/i18n/src/locales/de/editor.json
  packages/i18n/src/locales/en/editor.json
  packages/i18n/src/locales/es/editor.json
  packages/i18n/src/locales/fr/editor.json
  packages/i18n/src/locales/id/editor.json
  packages/i18n/src/locales/it/editor.json
  packages/i18n/src/locales/ja/editor.json
  packages/i18n/src/locales/ko/editor.json
  packages/i18n/src/locales/pl/editor.json
  packages/i18n/src/locales/pt-BR/editor.json
  packages/i18n/src/locales/ro/editor.json
  packages/i18n/src/locales/ru/editor.json
  packages/i18n/src/locales/sk/editor.json
  packages/i18n/src/locales/tr-TR/editor.json
  packages/i18n/src/locales/ua/editor.json
  packages/i18n/src/locales/vi-VN/editor.json
  packages/i18n/src/locales/zh-CN/editor.json
  packages/i18n/src/locales/zh-TW/editor.json
Labels: 🌐frontend, ✍️editor, ready to merge

#7158 [WIKI-412] chore: improved rich text editor extensions handling
  packages/editor/src/ce/extensions/document-extensions.tsx
  packages/editor/src/ce/extensions/rich-text/extensions.tsx
  packages/editor/src/ce/extensions/rich-text/read-only-extensions.tsx
  packages/editor/src/core/components/editors/read-only-editor-wrapper.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/components/editors/rich-text/read-only-editor.tsx
  packages/editor/src/core/extensions/extensions.ts
  packages/editor/src/core/extensions/read-only-extensions.ts
  packages/editor/src/core/extensions/utility.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/plugins/drop.ts
  packages/editor/src/core/types/editor.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready to merge

#7161 [WIKI-412] regression: drop plugin logic
  packages/editor/src/core/plugins/drop.ts
Labels: 🌐frontend, ✍️editor, ready to merge

#7165 [WEB-4256] chore: add og image and update meta tags for social media compatibility
  web/app/layout.tsx
  web/public/og-image.png
Labels: 🌐frontend, ready to merge

#7174 [WEB-4272] fix: remove duplicate CommandPalette instances from settings layouts to prevent modal conflicts
  web/app/(all)/[workspaceSlug]/(settings)/settings/(workspace)/layout.tsx
Labels: ready to merge

#7175 [WEB-4274] fix: metadata base url warning
  web/app/layout.tsx
Labels: 🌐frontend

#7166 [WEB-4257] chore: user profile setting options updated
  web/core/components/profile/form.tsx
Labels: 🌐frontend, 🧹chore, ready to merge

#7173 [WEB 4252] chore: updated the favicon request for work item link
  apiserver/plane/api/views/issue.py
  apiserver/plane/app/views/issue/link.py
  apiserver/plane/bgtasks/work_item_link_task.py
Labels: ready to merge

#7171 [WIKI-391] chore: handle deactivated user display name in version history
  web/core/components/core/description-versions/dropdown-item.tsx
  web/core/components/core/description-versions/dropdown.tsx
  web/core/components/pages/version/sidebar-list-item.tsx
Labels: 🐛bug, 🌐frontend, requires approval

#7044 [WEB-4063]chore: updated work item email template
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/templates/emails/notifications/issue-updates.html
Labels: 🌟enhancement, 🧹chore, ready to merge

#7182 [SILO-303] Add external id and external source in project model
  apiserver/plane/db/migrations/0097_project_external_id_project_external_source.py
  apiserver/plane/db/models/project.py
Labels: ⚙️backend, requires approval

#7189 [WEB-4288] fix: auth page tab index
  space/core/components/account/auth-forms/email.tsx
  web/core/components/account/auth-forms/email.tsx
Labels: 🌐frontend

#7194 [WEB-4246] Analytics minor improvements
  packages/constants/src/module.ts
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/propel/src/charts/line-chart/root.tsx
  packages/propel/src/charts/scatter-chart/root.tsx
  packages/types/src/analytics.d.ts
  packages/types/src/charts/index.d.ts
  packages/ui/src/icons/cycle/helper.tsx
  packages/ui/src/icons/cycle/index.ts
  web/ce/components/analytics/tabs.ts
  web/core/components/analytics/config.ts
  web/core/components/analytics/empty-state.tsx
  web/core/components/analytics/export.ts
  web/core/components/analytics/insight-table/data-table.tsx
  web/core/components/analytics/insight-table/root.tsx
  web/core/components/analytics/overview/project-insights.tsx
  web/core/components/analytics/trend-piece.tsx
  web/core/components/analytics/work-items/created-vs-resolved.tsx
  web/core/components/analytics/work-items/priority-chart.tsx
  web/core/components/analytics/work-items/workitems-insight-table.tsx
Labels: ready to merge

#7205 [WEB-4311] fix: membership data handling and state reversal on error
  web/core/store/member/base-project-member.store.ts
  web/core/store/member/workspace-member.store.ts
Labels: ready to merge

#7192 [WEB-4231] Pie chart tooltip
  packages/propel/src/charts/pie-chart/root.tsx
Labels: ready to merge

#7238 [WEB-4339] fix: projects dropdown shows all projects
  web/app/(all)/[workspaceSlug]/(projects)/analytics/header.tsx
  web/core/components/analytics/analytics-filter-actions.tsx
Labels: 🐛bug, 🌐frontend, ready to merge

#7235 [WIKI-384] chore: editor core refactor
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/ce/components/pages/extra-actions.tsx
  web/ce/components/pages/header/share-control.tsx
  web/ce/hooks/use-page-flag.ts
  web/core/components/pages/header/actions.tsx
Labels: ready to merge

#7228 [WIKI-458] refactor: base page instance for additional properties
  packages/types/src/index.d.ts
  packages/types/src/page/core.d.ts
  packages/types/src/page/extended.d.ts
  packages/types/src/page/index.d.ts
  packages/types/src/search.d.ts
  web/ce/store/pages/extended-base-page.ts
  web/core/store/pages/base-page.ts
Labels: 🌐frontend, 🛠️refactor, pages, ready to merge

#7214 [WEB-4321]chore: workspace views refactor
  apiserver/plane/app/views/issue/base.py
  packages/types/src/layout/gantt.d.ts
  packages/utils/src/work-item/base.ts
  web/app/(all)/[workspaceSlug]/(projects)/workspace-views/header.tsx
  web/ce/components/views/helper.tsx
  web/ce/store/issue/workspace/issue.store.ts
  web/ce/store/timeline/base-timeline.store.ts
  web/core/components/gantt-chart/blocks/block.tsx
  web/core/components/gantt-chart/blocks/blocks-list.tsx
  web/core/components/gantt-chart/chart/main-content.tsx
  web/core/components/gantt-chart/chart/root.tsx
  web/core/components/gantt-chart/helpers/draggable.tsx
  web/core/components/gantt-chart/root.tsx
  web/core/components/issues/issue-layouts/gantt/base-gantt-root.tsx
  web/core/components/issues/issue-layouts/properties/labels.tsx
  web/core/components/issues/issue-layouts/roots/all-issue-layout-root.tsx
  web/core/components/issues/issue-layouts/spreadsheet/roots/workspace-root.tsx
  web/core/components/views/helper.tsx
  web/core/hooks/store/use-issues.ts
  web/core/services/workspace.service.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/issue-details/relation.store.ts
  web/core/store/issue/root.store.ts
  web/core/store/issue/workspace/filter.store.ts
Labels: 🛠️refactor, ready to merge

#7188 [WEB-4050] feat: breadcrumbs revamp
  admin/core/components/auth-header.tsx
  packages/constants/src/project.ts
  packages/ui/src/breadcrumbs/breadcrumbs.stories.tsx
  packages/ui/src/breadcrumbs/breadcrumbs.tsx
  packages/ui/src/breadcrumbs/index.ts
  packages/ui/src/breadcrumbs/navigation-dropdown.tsx
  packages/ui/src/breadcrumbs/navigation-search-dropdown.tsx
  packages/ui/src/dropdowns/custom-search-select.tsx
  packages/ui/src/header/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/active-cycles/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/analytics/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/browse/[workItem]/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/drafts/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/profile/[userId]/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/archives/issues/(detail)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(list)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(list)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(list)/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/stickies/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/workspace-views/[globalViewId]/page.tsx
  web/app/(all)/[workspaceSlug]/(projects)/workspace-views/header.tsx
  web/ce/components/breadcrumbs/common.tsx
  web/ce/components/breadcrumbs/index.ts
  web/ce/components/breadcrumbs/project-feature.tsx
  web/ce/components/breadcrumbs/project.tsx
  web/ce/components/issues/header.tsx
  web/ce/components/projects/navigation/helper.tsx
  web/ce/components/projects/navigation/index.ts
  web/ce/components/projects/settings/intake/header.tsx
  web/core/components/common/breadcrumb-link.tsx
  web/core/components/common/switcher-label.tsx
  web/core/components/project/header.tsx
  web/core/components/workspace-notifications/sidebar/header/root.tsx
  web/core/components/workspace/views/default-view-quick-action.tsx
  web/core/components/workspace/views/header.tsx
  web/core/components/workspace/views/quick-action.tsx
Labels: ready to merge

#7063 [WIKI-465] fix : Add new node on click of doc end
  packages/editor/src/core/components/editors/editor-container.tsx
Labels: ready to merge

#7246 [WEB-4361] fix: add onChange to collaborative editor
  packages/editor/src/core/hooks/use-collaborative-editor.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7255 [WIKI-421] fix: Toolbar not reflecting strikethrough state
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7248 [WEB-4363]: Analytics tab improvements
  web/app/(all)/[workspaceSlug]/(projects)/analytics/[tabId]/header.tsx
  web/app/(all)/[workspaceSlug]/(projects)/analytics/[tabId]/layout.tsx
  web/app/(all)/[workspaceSlug]/(projects)/analytics/[tabId]/page.tsx
  web/next.config.js
Labels: ready to merge

#7260 [WEB-4363] regression: analytics tabs improvements
  web/app/(all)/[workspaceSlug]/(projects)/analytics/[tabId]/page.tsx
Labels: 🐛bug, 🌐frontend, ready to merge

#7259 [WIKI-74] fix: peek overview closing on escape key
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen.tsx
  web/core/components/issues/peek-overview/view.tsx
Labels: 🐛bug, 🌐frontend, ready to merge

#7267 [WEB-4373]: optimize backend query for workspace views and Project gantt view
  apiserver/plane/app/serializers/__init__.py
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/serializers/view.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/view/base.py
  apiserver/plane/utils/order_queryset.py
  apiserver/plane/utils/paginator.py
Labels: ready to merge

#7268 [WEB-4371] feat: bar chart component with lollipop shape variant
  packages/propel/src/charts/bar-chart/bar.tsx
  packages/propel/src/charts/bar-chart/root.tsx
  packages/types/src/charts/index.d.ts
Labels: ready to merge
