Repository makeplane/plane, pull requests merged in 2025-07, with the labels that each got.

#7297 [WEB-4416]fix: Unnecessary border on Intake header
  web/ce/components/projects/settings/intake/header.tsx
Labels: 🐛bug

#7274 [WIKI-491] [WIKI-496] [WIKI-499] refactor: tables width and selection UI
  packages/editor/src/core/extensions/side-menu.ts
  packages/editor/src/core/extensions/table/plugins/table-selection-outline/plugin.ts
  packages/editor/src/core/extensions/table/plugins/table-selection-outline/utils.ts
  packages/editor/src/core/extensions/table/table-cell.ts
  packages/editor/src/core/extensions/table/table-header.ts
  packages/editor/src/core/extensions/table/table/index.ts
  packages/editor/src/core/extensions/table/table/table-view.tsx
  packages/editor/src/core/extensions/table/table/table.ts
  packages/editor/src/core/extensions/table/table/utilities/create-table.ts
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/styles/drag-drop.css
  packages/editor/src/styles/table.css
  packages/editor/src/styles/variables.css
Labels: 🌐frontend, 🌟improvement, ✍️editor, ready to merge

#7283 [WIKI-506] fix: close the link view after 300ms of hovering out
  packages/editor/src/core/components/editors/link-view-container.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7275 [WIKI-402] feat: emoji support for all editors
  packages/editor/package.json
  packages/editor/src/ce/types/storage.ts
  packages/editor/src/ce/types/utils.ts
  packages/editor/src/core/constants/extension.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/emoji/components/emojis-list.tsx
  packages/editor/src/core/extensions/emoji/extension.ts
  packages/editor/src/core/extensions/emoji/suggestion.ts
  packages/editor/src/core/extensions/enter-key.ts
  packages/editor/src/core/extensions/extensions.ts
  packages/editor/src/core/extensions/mentions/extension-config.ts
  packages/editor/src/core/extensions/mentions/utils.ts
  packages/editor/src/core/extensions/slash-commands/command-items-list.tsx
  packages/editor/src/core/extensions/utility.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/styles/editor.css
  yarn.lock
Labels: ✨feature, 🌐frontend, ✍️editor, ready to merge

#7254 [WIKI-449] feat: image block download and alignment options
  packages/editor/package.json
  packages/editor/src/core/extensions/custom-image/components/block.tsx
  packages/editor/src/core/extensions/custom-image/components/node-view.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/alignment.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/download.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen/index.ts
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen/modal.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/full-screen/root.tsx
  packages/editor/src/core/extensions/custom-image/components/toolbar/root.tsx
  packages/editor/src/core/extensions/custom-image/extension.ts
  packages/editor/src/core/extensions/custom-image/types.ts
  packages/editor/src/core/extensions/custom-image/utils.ts
  packages/editor/src/core/extensions/image/extension-config.tsx
  packages/editor/src/core/types/config.ts
  space/app/layout.tsx
  web/app/layout.tsx
  web/core/hooks/editor/use-editor-config.ts
Labels: ✨feature, 🌐frontend, ✍️editor, ready to merge

#7223 refactor: optimize Dockerfile for web and space applications by refin…
  apps/space/Dockerfile.space
  apps/web/Dockerfile.web
Labels: 🏠self-hosted, 🐳docker, devops

#7329 [WEB-4436] fix: tailwind config
  packages/tailwind-config/tailwind.config.js
Labels: 🐛bug, 🌐frontend, requires approval

#7241 [WIKI-466] refactor: remove rich text read only editor
  apps/space/core/components/editor/index.ts
  apps/space/core/components/editor/rich-text-editor.tsx
  apps/space/core/components/editor/rich-text-read-only-editor.tsx
  apps/space/core/components/issues/peek-overview/issue-details.tsx
  apps/web/ce/components/pages/editor/ai/ask-pi-menu.tsx
  apps/web/ce/components/pages/editor/ai/menu.tsx
  apps/web/core/components/core/description-versions/modal.tsx
  apps/web/core/components/core/modals/gpt-assistant-popover.tsx
  apps/web/core/components/editor/rich-text-editor/index.ts
  apps/web/core/components/editor/rich-text-editor/rich-text-editor.tsx
  apps/web/core/components/editor/rich-text-editor/rich-text-read-only-editor.tsx
  apps/web/core/components/inbox/modals/create-modal/issue-description.tsx
  apps/web/core/components/issues/description-input.tsx
  apps/web/core/components/issues/issue-modal/components/description-editor.tsx
  apps/web/core/components/profile/activity/activity-list.tsx
  apps/web/core/components/profile/activity/profile-activity-list.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/lite-text/editor.tsx
  packages/editor/src/core/components/editors/rich-text/index.ts
  packages/editor/src/core/components/editors/rich-text/read-only-editor.tsx
  packages/editor/src/core/types/editor.ts
  packages/editor/src/index.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready to merge

#7344 [WIKI-521] fix : emoji unexpectedly scroll
  packages/editor/src/core/extensions/emoji/components/emojis-list.tsx
  packages/editor/src/core/extensions/emoji/suggestion.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7360 [WIKI-530] regression: page version history dropdown item
  apps/web/core/components/pages/editor/toolbar/options-dropdown.tsx
Labels: 🌐frontend, pages, ready to merge

#7366 [WIKI-534] fix: save title input on closing
  apps/web/core/components/issues/title-input.tsx
Labels: ready to merge

#7377 [WEB-4469] fix: full screen mode visibility
  apps/web/core/components/analytics/work-items/modal/index.tsx
  apps/web/core/components/gantt-chart/chart/root.tsx
Labels: 🐛bug

#7386 [WEB-4477] fix: sidebar resize behaviour
  apps/web/core/components/sidebar/resizable-sidebar.tsx
Labels: ready to merge

#7376 [WIKI-497] refactor: table insert handles size
  packages/editor/src/styles/table.css
Labels: 🌐frontend, ✍️editor, ready to merge

#7405 [WEB-4494] fix: kanban delete modal ux
  apps/web/core/components/issues/issue-layouts/kanban/base-kanban-root.tsx
Labels: 🐛bug, 🌐frontend, ready to merge

#7345 [WIKI-542] refactor: editor extensions
  packages/editor/src/core/extensions/code/index.tsx
  packages/editor/src/core/extensions/custom-link/extension.tsx
  packages/editor/src/core/extensions/extensions.ts
  packages/editor/src/core/extensions/horizontal-rule.ts
  packages/editor/src/core/extensions/placeholder.ts
  packages/editor/src/core/extensions/read-only-extensions.ts
  packages/editor/src/core/extensions/starter-kit.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready to merge

#7389 [WIKI-277] fix: unable to delete last table column/row in editor
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
  packages/editor/src/core/extensions/table/table/table.ts
  packages/editor/src/core/extensions/table/table/utilities/delete-column.ts
  packages/editor/src/core/extensions/table/table/utilities/delete-row.ts
  packages/editor/src/core/extensions/table/table/utilities/delete-table-when-all-cells-selected.ts
  packages/editor/src/core/extensions/table/table/utilities/helpers.ts
  packages/editor/src/core/extensions/table/table/utilities/is-cell-selection.ts
  packages/editor/src/index.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7408 [WEB-4504] chore: added migration for app rail and reactions
  apps/api/plane/db/migrations/0098_profile_is_app_rail_docked_and_more.py
  apps/api/plane/db/models/issue.py
  apps/api/plane/db/models/user.py
Labels: ⚙️backend, 🔄migrations

#7410 [WEB-4506] fix: date range modal z-index
  apps/web/core/components/core/filters/date-filter-modal.tsx
Labels: 🐛bug, 🌐frontend

#7412 [WIKI-549] fix: comment scroll logic
  packages/hooks/src/use-hash-scroll.ts
Labels: 🐛bug, 🌐frontend, requires approval

#7417 [WIKI-551] refactor: work item activity logic
  apps/web/ce/store/issue/issue-details/activity.store.ts
  apps/web/core/components/issues/issue-detail/issue-activity/activity-comment-root.tsx
  apps/web/core/components/issues/issue-detail/issue-activity/loader.tsx
Labels: 🌐frontend, 🌟improvement, requires approval

#7413 [WEB-4497] chore: reduce breadcrumb height
  apps/admin/app/(all)/(dashboard)/header.tsx
  apps/admin/app/(all)/(dashboard)/sidebar-dropdown.tsx
  apps/web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/draft-issues/header.tsx
  apps/web/core/components/core/app-header.tsx
  apps/web/core/components/ui/loader/layouts/gantt-layout-loader.tsx
  apps/web/core/components/workspace-notifications/sidebar/root.tsx
  packages/tailwind-config/tailwind.config.js
Labels: ready to merge

#7393 [WEB-4479] feat: enable/disable SMTP configuration
  apps/admin/app/(all)/(dashboard)/email/email-config-form.tsx
  apps/admin/app/(all)/(dashboard)/email/page.tsx
  apps/admin/core/store/instance.store.ts
  apps/api/plane/license/api/views/__init__.py
  apps/api/plane/license/api/views/configuration.py
  apps/api/plane/license/management/commands/configure_instance.py
  apps/api/plane/license/urls.py
  packages/services/src/instance/instance.service.ts
  packages/types/src/instance/email.ts
Labels: ready to merge

#7336 [WEB-1643] chore: support cyrillic characters in subject
  apps/api/plane/bgtasks/email_notification_task.py
Labels: ready to merge

#7422 [WEB-4510] fix: peek view ui layout
  apps/web/core/components/issues/peek-overview/view.tsx
Labels: ready to merge

#7411 [WIKI-547] fix: update find suggestion logic for emoji extension
  packages/editor/src/core/extensions/emoji/components/emojis-list.tsx
  packages/editor/src/core/extensions/emoji/emoji.ts
  packages/editor/src/core/extensions/emoji/suggestion.ts
  packages/editor/src/core/helpers/find-suggestion-match.ts
Labels: 🐛bug, ✍️editor, ready to merge

#7298 [WEB-4346] chore: refactor copy_s3_object bg task
  apps/api/plane/app/views/page/base.py
  apps/api/plane/bgtasks/copy_s3_object.py
  apps/api/plane/tests/unit/bg_tasks/test_copy_s3_objects.py
Labels: ready to merge

#7337 [WEB-4442] fix: removed the deleted labels from webhook payload
  apps/api/plane/api/serializers/issue.py
  apps/api/plane/bgtasks/webhook_task.py
Labels: ready to merge, tests required

#7435 [WEB-4192]fix: inactive member is hidden in created by
  apps/api/plane/app/views/workspace/member.py
  apps/web/core/components/workspace/settings/members-list.tsx
  apps/web/core/store/member/workspace-member.store.ts
  packages/types/src/workspace.ts
Labels: 🐛bug, 🌐frontend, ready to merge

#7424 [WEB-4507] fix: webhooks translation
  apps/web/core/components/web-hooks/generated-hook-details.tsx
Labels: 🌐frontend, ready to merge

#7265 [WIKI-484] chore: update editor packages
  apps/live/package.json
  package.json
  packages/editor/package.json
  packages/editor/src/core/extensions/callout/block.tsx
  packages/editor/src/core/extensions/callout/extension.tsx
  packages/editor/src/core/extensions/callout/read-only-extension.tsx
  packages/editor/src/core/extensions/custom-image/extension.tsx
  packages/editor/src/core/extensions/extensions.ts
  packages/editor/src/core/extensions/image/extension.tsx
  packages/editor/src/core/extensions/mentions/extension.tsx
  packages/editor/src/core/extensions/mentions/mention-node-view.tsx
  packages/editor/src/core/extensions/read-only-extensions.ts
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/helpers/yjs-utils.ts
  packages/editor/src/core/plugins/drag-handle.ts
  yarn.lock
Labels: 🌐frontend, ✍️editor, ready to merge

#7464 [WEB-4558] fix: project test cases
  apps/api/plane/tests/contract/app/test_project_app.py
Labels: ready to merge

#7444 [WIKI-563] refactor: subscription styles
  apps/web/ce/components/workspace/billing/comparison/frequency-toggle.tsx
  apps/web/ce/components/workspace/billing/comparison/plan-detail.tsx
  apps/web/ce/components/workspace/billing/root.tsx
  apps/web/core/components/license/modal/card/base-paid-plan-card.tsx
  apps/web/core/components/license/modal/card/checkout-button.tsx
  apps/web/core/components/license/modal/card/plan-upgrade.tsx
  apps/web/core/components/license/modal/card/talk-to-sales.tsx
  apps/web/core/components/workspace/billing/comparison/feature-detail.tsx
  packages/ui/src/billing/index.ts
  packages/ui/src/billing/subscription.ts
  packages/ui/src/index.ts
Labels: 🌐web, :card_file_box: packaging, ready to merge

#7473 [WEB-4536] fix: remove inactive workspace members from lists and dropdowns
  apps/web/core/components/workspace/settings/members-list.tsx
  apps/web/core/store/member/workspace-member.store.ts
Labels: 🐛bug, requires approval

#7474 [WEB-4523]fix: sub issues loader
  apps/web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
Labels: 🐛bug, ready to merge

#7462 [WEB-4513] refactor: consolidate password strength meter into shared ui package
  apps/admin/core/components/common/password-strength-meter.tsx
  apps/admin/core/components/instance/setup-form.tsx
  apps/admin/package.json
  apps/space/core/components/account/auth-forms/password.tsx
  apps/space/core/components/account/helpers/index.ts
  apps/space/core/components/account/helpers/password-strength-meter.tsx
  apps/space/core/components/account/index.ts
  apps/space/helpers/password.helper.ts
  apps/space/package.json
  apps/web/app/(all)/[workspaceSlug]/(settings)/settings/account/security/page.tsx
  apps/web/app/(all)/accounts/reset-password/page.tsx
  apps/web/app/(all)/accounts/set-password/page.tsx
  apps/web/app/(all)/profile/security/page.tsx
  apps/web/core/components/account/auth-forms/password.tsx
  apps/web/core/components/account/index.ts
  apps/web/core/components/account/password-strength-meter.tsx
  apps/web/core/components/onboarding/profile-setup.tsx
  apps/web/package.json
  packages/ui/src/form-fields/index.ts
  packages/ui/src/form-fields/password/helper.tsx
  packages/ui/src/form-fields/password/index.ts
  packages/ui/src/form-fields/password/indicator.tsx
  packages/utils/package.json
  packages/utils/src/auth.ts
  yarn.lock
Labels: 🌐frontend, 🧹chore, ready to merge

#7453 [WEB-4533] feat: read replica functionality
  apps/api/plane/api/views/asset.py
  apps/api/plane/api/views/base.py
  apps/api/plane/api/views/cycle.py
  apps/api/plane/api/views/intake.py
  apps/api/plane/api/views/issue.py
  apps/api/plane/api/views/member.py
  apps/api/plane/api/views/module.py
  apps/api/plane/api/views/project.py
  apps/api/plane/api/views/state.py
  apps/api/plane/app/views/base.py
  apps/api/plane/app/views/issue/activity.py
  apps/api/plane/app/views/notification/base.py
  apps/api/plane/app/views/project/base.py
  apps/api/plane/app/views/project/member.py
  apps/api/plane/app/views/user/base.py
  apps/api/plane/app/views/workspace/base.py
  apps/api/plane/app/views/workspace/estimate.py
  apps/api/plane/app/views/workspace/favorite.py
  apps/api/plane/app/views/workspace/label.py
  apps/api/plane/app/views/workspace/member.py
  apps/api/plane/app/views/workspace/quick_link.py
  apps/api/plane/app/views/workspace/recent_visit.py
  apps/api/plane/app/views/workspace/state.py
  apps/api/plane/app/views/workspace/sticky.py
  apps/api/plane/app/views/workspace/user_preference.py
  apps/api/plane/middleware/db_routing.py
  apps/api/plane/settings/common.py
  apps/api/plane/tests/unit/middleware/__init__.py
  apps/api/plane/tests/unit/middleware/test_db_routing.py
  apps/api/plane/utils/core/__init__.py
  apps/api/plane/utils/core/dbrouters.py
  apps/api/plane/utils/core/mixins/__init__.py
  apps/api/plane/utils/core/mixins/view.py
  apps/api/plane/utils/core/request_scope.py
Labels: ✨feature, ready to merge

#7455 chore: misc editor updates and utility functions
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/components/editors/document/read-only-editor.tsx
  packages/editor/src/core/components/editors/editor-wrapper.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/components/menus/menu-items.ts
  packages/editor/src/core/extensions/custom-image/components/node-view.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/hooks/use-collaborative-editor.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/types/config.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/hook.ts
  packages/editor/src/styles/variables.css
Labels: 🧹chore, ✍️editor, requires approval

#7481 [WIKI-539] refactor: remove lite text read only editor
  apps/space/core/components/editor/index.ts
  apps/space/core/components/editor/lite-text-editor.tsx
  apps/space/core/components/editor/lite-text-read-only-editor.tsx
  apps/space/core/components/issues/peek-overview/comment/add-comment.tsx
  apps/space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
  apps/web/core/components/comments/card/display.tsx
  apps/web/core/components/comments/card/edit-form.tsx
  apps/web/core/components/comments/card/root.tsx
  apps/web/core/components/comments/comment-create.tsx
  apps/web/core/components/editor/lite-text/editor.tsx
  apps/web/core/components/editor/lite-text/index.ts
  apps/web/core/components/editor/lite-text/read-only-editor.tsx
  apps/web/core/components/editor/rich-text/editor.tsx
  apps/web/core/components/editor/sticky-editor/editor.tsx
  apps/web/core/hooks/editor/use-editor-config.ts
  packages/editor/src/ce/extensions/core/index.ts
  packages/editor/src/ce/extensions/core/read-only-extensions.ts
  packages/editor/src/ce/extensions/rich-text-extensions.tsx
  packages/editor/src/ce/extensions/rich-text/read-only-extensions.tsx
  packages/editor/src/core/components/editors/index.ts
  packages/editor/src/core/components/editors/lite-text/editor.tsx
  packages/editor/src/core/components/editors/lite-text/index.ts
  packages/editor/src/core/components/editors/lite-text/read-only-editor.tsx
  packages/editor/src/core/components/editors/read-only-editor-wrapper.tsx
  packages/editor/src/core/components/editors/rich-text/editor.tsx
  packages/editor/src/core/extensions/callout/extension.tsx
  packages/editor/src/core/extensions/callout/index.ts
  packages/editor/src/core/extensions/callout/read-only-extension.tsx
  packages/editor/src/core/extensions/custom-image/extension.tsx
  packages/editor/src/core/extensions/image/extension.tsx
  packages/editor/src/core/extensions/index.ts
  packages/editor/src/core/extensions/read-only-extensions.ts
  packages/editor/src/core/extensions/utility.ts
  packages/editor/src/core/helpers/editor-ref.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/plugins/file/root.ts
  packages/editor/src/core/props.ts
  packages/editor/src/core/props/index.ts
  packages/editor/src/core/props/read-only.tsx
  packages/editor/src/core/types/config.ts
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/hook.ts
  packages/editor/src/core/types/mention.ts
  packages/editor/src/index.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready to merge

#7503 [WIKI-539] regression: editor build errors
  apps/space/helpers/editor.helper.ts
  apps/web/core/components/workspace-notifications/sidebar/notification-card/content.tsx
Labels: 🌐frontend, requires approval

#7515 [WEB-4602] fix: 500 error on draft wi labels update
  apps/api/plane/app/serializers/draft.py
Labels: requires approval

#7523 [INFRA-219] fix: update Dockerfile and docker-compose for proxy service
  apps/proxy/Dockerfile.ce
  deployments/cli/community/docker-compose.yml
  deployments/cli/community/install.sh
Labels: 🐳docker, devops
