Repository makeplane/plane, pull requests merged in 2025-09, with the labels that each got.

#7678 [WEB-4808] fix: joinUrlPath utility fn
  packages/utils/src/string.ts
Labels: ready to merge

#7685 [WIKI-589] fix: update project page creation flow
  apps/web/core/components/pages/pages-list-main-content.tsx
Labels: 🌐frontend, 🌟improvement, ✍️editor, pages, ready to merge

#7637 [WEB-4740] feat: add propel seperator
  packages/propel/src/separator/separator.stories.tsx
  packages/propel/src/separator/separator.tsx
Labels: ready to merge

#7611 [WEB-4809] chore: added common libs to pnpm workspace catalog
  apps/admin/package.json
  apps/live/package.json
  apps/space/package.json
  apps/web/package.json
  package.json
  packages/constants/package.json
  packages/decorators/package.json
  packages/editor/package.json
  packages/eslint-config/package.json
  packages/hooks/package.json
  packages/i18n/package.json
  packages/logger/package.json
  packages/propel/package.json
  packages/services/package.json
  packages/shared-state/package.json
  packages/types/package.json
  packages/ui/package.json
  packages/utils/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ready to merge

#7620 [WEB-4686] feat: propel tabs
  packages/propel/src/tabs/index.ts
  packages/propel/src/tabs/list.tsx
  packages/propel/src/tabs/tabs.stories.tsx
  packages/propel/src/tabs/tabs.tsx
  pnpm-lock.yaml
Labels: ready to merge

#7661 [WIKI-511] [WIKI-572] fix: extended page root and editor body
  apps/space/core/components/editor/lite-text-editor.tsx
  apps/space/core/components/editor/rich-text-editor.tsx
  apps/space/helpers/string.helper.ts
  apps/web/app/(all)/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  apps/web/ce/components/pages/modals/index.ts
  apps/web/ce/components/pages/modals/modals.tsx
  apps/web/ce/hooks/pages/index.ts
  apps/web/ce/hooks/pages/use-extended-editor-extensions.ts
  apps/web/ce/hooks/pages/use-pages-pane-extensions.ts
  apps/web/ce/hooks/use-editor-flagging.ts
  apps/web/ce/types/pages/pane-extensions.ts
  apps/web/core/components/editor/document/editor.tsx
  apps/web/core/components/editor/lite-text/editor.tsx
  apps/web/core/components/editor/rich-text/editor.tsx
  apps/web/core/components/editor/sticky-editor/editor.tsx
  apps/web/core/components/pages/editor/editor-body.tsx
  apps/web/core/components/pages/editor/header/root.tsx
  apps/web/core/components/pages/editor/page-root.tsx
  apps/web/core/components/pages/navigation-pane/index.ts
  apps/web/core/components/pages/navigation-pane/root.tsx
  apps/web/core/components/pages/navigation-pane/types/extensions.ts
  apps/web/core/components/pages/navigation-pane/types/index.ts
  apps/web/core/components/pages/version/editor.tsx
  apps/web/core/components/pages/version/main-content.tsx
  apps/web/core/components/pages/version/root.tsx
  apps/web/core/services/page/project-page-version.service.ts
  apps/web/core/store/pages/base-page.ts
  packages/editor/src/ce/components/document-editor-side-effects.ts
  packages/editor/src/ce/types/editor-extended.ts
  packages/editor/src/ce/types/index.ts
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/types/editor.ts
  packages/editor/src/core/types/index.ts
  packages/types/src/editor/editor-content.ts
  packages/types/src/editor/index.ts
  packages/types/src/index.ts
  packages/types/src/issues/activity/issue_comment.ts
  packages/types/src/page/core.ts
  packages/utils/src/string.ts
Labels: 🌐frontend, 🛠️refactor, pages

#7699 [WEB-4834] fix: range date picker weekStartsOn
  apps/web/core/components/dropdowns/date-range.tsx
Labels: 🌐frontend, ready to merge

#7688 [WEB-4196]fix: toast message for sub work item quick actions
  apps/web/core/components/issues/issue-detail-widgets/sub-issues/helper.ts
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
Labels: ready to merge

#7698 [WEB-4129] fix: work item filter
  apps/api/plane/utils/grouper.py
Labels: ready to merge

#7676 [WEB-4806] chore: improved the html validation
  apps/api/plane/utils/content_validator.py
Labels: requires approval

#7719 [WEB-4806] chore: updated html attribute validation
  apps/api/plane/utils/content_validator.py
Labels: ready to merge

#7704 [WEB-4738] feat: add Skeleton component with respective stories in propel
  packages/propel/package.json
  packages/propel/src/skeleton/index.ts
  packages/propel/src/skeleton/root.tsx
  packages/propel/src/skeleton/skeleton.stories.tsx
  packages/propel/tsdown.config.ts
Labels: ready to merge

#7728 [WEB-4839] chore: maintenance mode empty state updated
  apps/web/ce/components/instance/maintenance-message.tsx
  apps/web/core/components/instance/maintenance-view.tsx
  apps/web/ee/components/instance/maintenance-message.tsx
  apps/web/public/instance/maintenance-mode-dark.svg
  apps/web/public/instance/maintenance-mode-light.svg
  apps/web/public/maintenance-mode.webp
Labels: 🌐frontend

#7734 [WIKI-647] chore: update image path
  apps/web/ce/components/pages/navigation-pane/tab-panels/empty-states/assets.tsx
  apps/web/ce/components/pages/navigation-pane/tab-panels/empty-states/outline.tsx
  apps/web/core/components/pages/pages-list-main-content.tsx
  apps/web/public/empty-state/wiki/all-dark.webp
  apps/web/public/empty-state/wiki/all-filters-dark.svg
  apps/web/public/empty-state/wiki/all-filters-light.svg
  apps/web/public/empty-state/wiki/all-light.webp
  apps/web/public/empty-state/wiki/archived-dark.webp
  apps/web/public/empty-state/wiki/archived-light.webp
  apps/web/public/empty-state/wiki/name-filter-dark.svg
  apps/web/public/empty-state/wiki/name-filter-light.svg
  apps/web/public/empty-state/wiki/navigation-pane/assets-dark.webp
  apps/web/public/empty-state/wiki/navigation-pane/assets-light.webp
  apps/web/public/empty-state/wiki/navigation-pane/outline-dark.webp
  apps/web/public/empty-state/wiki/navigation-pane/outline-light.webp
  apps/web/public/empty-state/wiki/private-dark.webp
  apps/web/public/empty-state/wiki/private-light.webp
  apps/web/public/empty-state/wiki/public-dark.webp
  apps/web/public/empty-state/wiki/public-light.webp
Labels: 🌐frontend, 🛠️refactor, pages, ready to merge

#7669 [WEB-4800]chore: settings header component refactor
  apps/web/core/components/settings/heading.tsx
Labels: 🛠️refactor, ready to merge, current release

#7748 [WEB-4729] dev: propel scrollarea
  packages/propel/package.json
  packages/propel/src/scrollarea/index.ts
  packages/propel/src/scrollarea/scrollarea.stories.tsx
  packages/propel/src/scrollarea/scrollarea.tsx
  packages/propel/tsdown.config.ts
Labels: 🌐frontend, requires approval

#7753 [WIKI-653] fix: page content loader
  packages/editor/src/core/components/editors/document/loader.tsx
Labels: 🐛bug, 🌐frontend, pages, ready to merge

#7692 [WEB-4025] fix: external user comment and reaction
  apps/api/plane/app/serializers/issue.py
  apps/web/ce/components/comments/comment-block.tsx
  apps/web/core/components/issues/issue-detail/reactions/issue-comment.tsx
  apps/web/core/components/issues/issue-detail/reactions/issue.tsx
  packages/types/src/issues/activity/issue_comment_reaction.ts
  packages/types/src/issues/issue_reaction.ts
Labels: 🌐frontend, ready to merge, current release

#7743 [WEB-4737] dev: propel pill component
  packages/propel/package.json
  packages/propel/src/pill/index.ts
  packages/propel/src/pill/pill.stories.tsx
  packages/propel/src/pill/pill.tsx
  packages/propel/tsdown.config.ts
Labels: 🌐frontend, ready to merge

#7745 [WEB-4730] dev: propel context menu component
  packages/propel/package.json
  packages/propel/src/context-menu/context-menu.stories.tsx
  packages/propel/src/context-menu/context-menu.tsx
  packages/propel/src/context-menu/index.ts
  packages/propel/tsdown.config.ts
Labels: 🌐frontend, ready to merge

#7746 [WEB-4736] dev: propel button
  packages/propel/package.json
  packages/propel/src/button/button.stories.tsx
  packages/propel/src/button/button.tsx
  packages/propel/src/button/index.ts
  packages/propel/tsdown.config.ts
Labels: 🌐frontend, ready to merge

#7772 [WEB-4873]: Add webhook log cleanup task and update Celery schedule
  apps/api/plane/bgtasks/cleanup_task.py
  apps/api/plane/celery.py
Labels: ready to merge

#7783 [WIKI-632] chore: add extended document editor props
  packages/editor/src/core/components/editors/document/collaborative-editor.tsx
  packages/editor/src/core/components/editors/document/page-renderer.tsx
  packages/editor/src/core/types/hook.ts
Labels: 🧹chore, ✍️editor, ready to merge

#7761 [WIKI-657] refactor: the page permissions in project
  apps/api/plane/app/permissions/__init__.py
  apps/api/plane/app/permissions/page.py
  apps/api/plane/app/serializers/__init__.py
  apps/api/plane/app/serializers/page.py
  apps/api/plane/app/urls/page.py
  apps/api/plane/app/views/__init__.py
  apps/api/plane/app/views/page/base.py
  apps/api/plane/app/views/page/version.py
Labels: ready to merge

#7828 [WEB-4952]fix: published view work item description
  apps/space/core/components/issues/peek-overview/issue-details.tsx
Labels: 🐛bug, ready to merge

#7826 [WEB-4953]fix: cycle progress percentage
  apps/web/core/components/cycles/list/cycles-list-item.tsx
  packages/utils/src/cycle.ts
Labels: 🐛bug, ready to merge

#7821 [WEB-4905]fix: cycle dates update
  apps/web/core/components/cycles/modal.tsx
Labels: 🐛bug, ready to merge

#7823 [WIKI-650] fix: pane extensions close method moved into hook
  apps/web/ce/hooks/pages/use-pages-pane-extensions.ts
  apps/web/core/components/editor/lite-text/editor.tsx
  apps/web/core/components/editor/lite-text/lite-toolbar.tsx
  apps/web/core/components/pages/editor/page-root.tsx
  apps/web/core/constants/editor.ts
  packages/editor/tsdown.config.ts
Labels: ready to merge

#7841 [WIKI-638] fix: peek overview closing while dropdowns are open
  apps/web/core/components/issues/peek-overview/issue-detail.tsx
  apps/web/core/components/issues/peek-overview/view.tsx
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/column/drag-handle.tsx
  packages/editor/src/core/extensions/table/plugins/drag-handles/row/drag-handle.tsx
  packages/editor/src/core/extensions/utility.ts
  packages/editor/src/core/helpers/editor-ref.ts
  packages/editor/src/core/types/editor.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7851 [WEB-4980] dev: propel modal portal component
  packages/propel/package.json
  packages/propel/src/portal/constants.ts
  packages/propel/src/portal/index.ts
  packages/propel/src/portal/modal-portal.tsx
  packages/propel/src/portal/portal-wrapper.tsx
  packages/propel/src/portal/portal.stories.tsx
  packages/propel/src/portal/types.ts
  packages/propel/tsdown.config.ts
Labels: 🌐frontend, requires approval

#7770 [WEB-4881] feat(utils): add URL display formatter
  packages/utils/src/url.ts
Labels: ready to merge, codex

#7874 [WIKI-668] fix: comments mention
  apps/web/core/components/comments/card/edit-form.tsx
  apps/web/core/components/comments/card/root.tsx
  apps/web/core/components/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend, ready to merge

#7871 [WEB-5050] feat: updated work item urls with issues.
  apps/api/plane/api/urls/__init__.py
  apps/api/plane/api/urls/label.py
  apps/api/plane/api/urls/work_item.py
Labels: ready to merge
