Repository makeplane/plane, pull requests merged in 2025-03, with the labels that each got.

#6688 chore: add common translation keys
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
Labels: 🌐frontend

#6678 [PE-275] chore: editor line spacing variables
  packages/editor/src/core/components/editors/editor-container.tsx
  packages/editor/src/core/constants/config.ts
  packages/editor/src/core/extensions/core-without-props.ts
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/extensions/read-only-extensions.tsx
  packages/editor/src/core/types/config.ts
  packages/editor/src/styles/editor.css
  packages/editor/src/styles/variables.css
Labels: ✍️editor

#6692 feat: italian translations
  packages/i18n/src/constants/language.ts
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/store/index.ts
  packages/i18n/src/types/language.ts
  web/core/components/modules/analytics-sidebar/root.tsx
Labels: 🌟enhancement, 🌐frontend

#6714 [WEB-3493]fix: sidebar project list expand
  web/core/components/workspace/sidebar/projects-list.tsx
Labels: 🐛bug

#6716 refactor: favorites sidebar implementation
  web/ce/constants/index.ts
  web/ce/constants/sidebar-favorites.ts
  web/ce/hooks/use-additional-favorite-item-details.ts
  web/core/components/workspace/sidebar/favorites/favorite-items/common/helper.tsx
  web/core/hooks/use-favorite-item-details.tsx
  web/ee/constants/index.ts
  web/ee/constants/sidebar-favorites.ts
  web/ee/hooks/use-additional-favorite-item-details.ts
Labels: 🌐frontend, 🛠️refactor

#6726 [WEB-3505] chore: Czech translations updated
  packages/i18n/src/locales/cs/translations.json
Labels: 🌐frontend, 🌟improvement, 🧹chore

#6730 chore: make api rate limit configurable through environment variable
  .env.example
  apiserver/.env.example
  apiserver/plane/api/rate_limit.py
  deploy/selfhost/docker-compose.yml
  deploy/selfhost/variables.env
Labels: ⚙️backend

#6754 [RANTS-46] fix: modules list sidebar position
  web/core/components/modules/modules-list-view.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#6742 chore: issue filters refactor
  web/ce/components/issue-types/index.ts
  web/ce/components/issue-types/values/index.ts
  web/ce/components/issue-types/values/update.tsx
  web/ce/components/issues/issue-details/additional-properties.tsx
  web/ce/helpers/issue-filter.helper.ts
  web/ce/store/issue/helpers/base-issue.store.ts
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
  web/core/components/issues/issue-layouts/spreadsheet/issue-column.tsx
  web/core/components/issues/issue-layouts/spreadsheet/spreadsheet-header-column.tsx
  web/core/components/issues/peek-overview/properties.tsx
  web/core/store/issue/helpers/base-issues.store.ts
  web/ee/components/issue-types/index.ts
  web/ee/components/issue-types/values/index.ts
  web/ee/components/issue-types/values/update.tsx
  web/ee/components/issues/issue-details/additional-properties.tsx
  web/ee/store/issue/helpers/base-issue.store.ts
Labels: 🧹chore

#6762 [WEB-3545] feat: language translations
  packages/i18n/src/constants/language.ts
  packages/i18n/src/hooks/use-translation.ts
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/i18n/src/store/index.ts
  packages/i18n/src/types/language.ts
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(list)/page.tsx
Labels: 🌐frontend

#6767 [WEB-3580] fix: automations settings translation
  packages/constants/src/project.ts
  web/core/components/automation/auto-archive-automation.tsx
  web/core/components/automation/auto-close-automation.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6781 chore: date picker year range
  packages/ui/src/calendar.tsx
Labels: 🌐frontend, 🌟improvement

#6784 [WEB-2895]fix: space app priority icons
  space/core/components/issues/issue-layouts/properties/priority.tsx
Labels: 🐛bug

#6777 [WEB-3262]fix: incomplete activity render for activity in notifications
  web/core/components/workspace-notifications/sidebar/notification-card/content.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/index.ts
  web/core/components/workspace-notifications/sidebar/notification-card/item.tsx
Labels: 🐛bug, 🌐frontend

#6773 [WEB-3175]fix: favorites menu
  packages/constants/src/workspace.ts
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/modules/module-card-item.tsx
  web/core/components/modules/module-list-item-action.tsx
  web/core/components/pages/editor/header/extra-options.tsx
  web/core/components/project/card.tsx
  web/core/components/views/view-list-item-action.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/hooks/use-page-operations.ts
Labels: 🐛bug, 🌐frontend

#6698 fix: intake refactor
  apiserver/plane/app/serializers/issue.py
  apiserver/plane/app/views/issue/activity.py
  packages/types/src/inbox.d.ts
  packages/types/src/issues/activity/issue_activity.d.ts
  space/core/components/editor/rich-text-editor.tsx
  web/ce/components/issues/issue-details/index.ts
  web/ce/components/issues/issue-details/issue-creator.tsx
  web/ce/constants/project/settings/features.tsx
  web/ce/store/project-inbox.store.ts
  web/core/components/issues/issue-detail/issue-activity/activity/actions/default.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
  web/core/components/project/settings/features-list.tsx
  web/core/hooks/store/use-project-inbox.ts
  web/core/services/inbox/inbox-issue.service.ts
  web/core/store/inbox/project-inbox.store.ts
  web/ee/components/issues/issue-details/index.ts
  web/ee/components/issues/issue-details/issue-creator.tsx
  web/ee/store/project-inbox.store.ts
Labels: 🌟enhancement

#6780 [WEB-3590] chore: sidebar enhancements
  web/ce/components/workspace/sidebar/extended-sidebar-item.tsx
  web/core/store/workspace/index.ts
Labels: 🌐frontend

#6806 [RANTS-57] chore: replace target date with due date in work item filters dropdown
  web/core/components/issues/issue-layouts/filters/header/filters/due-date.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/filters-selection.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/index.ts
Labels: 🌐frontend, 🌟improvement

#6802 [WEB-3438] fix: transfer completed cycle issue modal
  web/core/components/cycles/transfer-issues-modal.tsx
Labels: 🐛bug, 🌐frontend

#6803 chore: issue detail refactor
  web/ce/components/issues/issue-detail-widgets/additional-widgets.tsx
  web/ce/components/issues/issue-detail-widgets/index.ts
  web/ce/store/issue/helpers/base-issue-store.ts
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-collapsibles.tsx
  web/core/components/issues/issue-detail/sidebar.tsx
Labels: 🧹chore

#6801 [WEB-3614] chore: list layout display filters
  packages/constants/src/issue/filter.ts
Labels: 🌐frontend, 🧹chore

#6805 [WEB-3560] fix: table layout issue block and code refactor
  web/core/components/issues/issue-layouts/spreadsheet/issue-row.tsx
Labels: 🌐frontend, 🧹chore

#6825 [WEB-3686] feat: romanian and indonesian language support
  packages/i18n/src/constants/language.ts
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/store/index.ts
  packages/i18n/src/types/language.ts
Labels: 🌐frontend

#6820 [WEB-3681]feat: added user timezone dates for cycle
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  web/core/components/cycles/list/cycle-list-item-action.tsx
  web/core/components/cycles/list/cycles-list-item.tsx
  web/core/components/dropdowns/date-range.tsx
  web/core/hooks/use-timezone-converter.tsx
Labels: 🌟enhancement

#6832 [WEB-3681]fix: label update for date dropdown
  web/core/components/cycles/list/cycle-list-item-action.tsx
Labels: 🐛bug

#6834 [WEB-3694]feat: added dates display in user timezone in analytics sidebar
  web/core/components/cycles/analytics-sidebar/sidebar-header.tsx
Labels: ✨feature

#6759 [WEB-3698] fix: comments refactor
  apiserver/plane/app/views/issue/comment.py
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/types/src/issues/activity/issue_comment.d.ts
  web/ce/components/comments/comment-block.tsx
  web/ce/components/comments/index.ts
  web/core/components/comments/comment-card.tsx
  web/core/components/comments/comment-create.tsx
  web/core/components/comments/comment-reaction.tsx
  web/core/components/comments/comments.tsx
  web/core/components/comments/index.ts
  web/core/components/editor/lite-text-editor/lite-text-editor.tsx
  web/core/components/editor/lite-text-editor/lite-text-read-only-editor.tsx
  web/core/components/issues/issue-detail/issue-activity/activity-comment-root.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/helpers/activity-block.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/comment-block.tsx
  web/core/components/issues/issue-detail/issue-activity/comments/index.ts
  web/core/components/issues/issue-detail/issue-activity/comments/root.tsx
  web/core/components/issues/issue-detail/issue-activity/helper.tsx
  web/core/components/issues/issue-detail/issue-activity/index.ts
  web/core/components/issues/issue-detail/issue-activity/root.tsx
  web/core/services/file.service.ts
  web/core/services/issue/issue_comment.service.ts
  web/core/store/issue/issue-details/comment.store.ts
  web/core/store/issue/issue-details/comment_reaction.store.ts
  web/ee/components/comments/index.ts
Labels: 🌟improvement

#6835 [WEB-3697] chore: chart components
  packages/constants/src/chart.ts
  packages/propel/src/charts/area-chart/root.tsx
  packages/propel/src/charts/bar-chart/bar.tsx
  packages/propel/src/charts/bar-chart/root.tsx
  packages/propel/src/charts/components/legend.tsx
  packages/propel/src/charts/components/tick.tsx
  packages/propel/src/charts/components/tooltip.tsx
  packages/propel/src/charts/line-chart/root.tsx
  packages/propel/src/charts/pie-chart/active-shape.tsx
  packages/propel/src/charts/pie-chart/root.tsx
  packages/propel/src/charts/pie-chart/tooltip.tsx
  packages/propel/src/charts/tooltip.tsx
  packages/propel/src/charts/tree-map/root.tsx
  packages/types/src/charts.d.ts
Labels: 🌐frontend, 🧹chore

#6823 [WEB-3540] dev: color picker component
  packages/ui/src/color-picker/color-picker.tsx
  packages/ui/src/color-picker/index.ts
  packages/ui/src/index.ts
  web/helpers/theme.tsx
  web/package.json
  yarn.lock
Labels: 🌐frontend, 🧹chore
