Repository makeplane/plane, pull requests merged in 2025-04, with the labels that each got.

#6858 [WEB-3273]fix: editor bubble menu z-index
  packages/editor/src/core/components/menus/bubble-menu/root.tsx
Labels: 🐛bug, ✍️editor

#6860 [WEB-3699]fix: create link modal text flicker
  web/core/components/home/widgets/links/create-update-link-modal.tsx
  web/core/components/home/widgets/links/root.tsx
Labels: 🐛bug

#6857 [WEB-3737]chore: estimates code refactor and translations
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/ui/src/dropdown/common/options.tsx
  packages/ui/src/dropdown/dropdown.d.ts
  web/ce/components/estimates/helper.tsx
  web/ce/components/estimates/index.ts
  web/ce/components/estimates/inputs/index.ts
  web/ce/components/estimates/inputs/time-input.tsx
  web/ce/components/estimates/points/delete.tsx
  web/ce/constants/estimates.ts
  web/core/components/api-token/modal/generated-token-details.tsx
  web/core/components/dropdowns/estimate.tsx
  web/core/components/estimates/create/stage-one.tsx
  web/core/components/estimates/estimate-disable-switch.tsx
  web/core/components/estimates/estimate-list-item.tsx
  web/core/components/estimates/inputs/index.ts
  web/core/components/estimates/inputs/number-input.tsx
  web/core/components/estimates/inputs/root.tsx
  web/core/components/estimates/inputs/text-input.tsx
  web/core/components/estimates/points/create.tsx
  web/core/components/estimates/points/preview.tsx
  web/core/components/estimates/points/update.tsx
Labels: 🌟improvement, 🧹chore

#6863 [WEB-3748, 3749] feat: work item description version history
  apiserver/plane/app/urls/intake.py
  apiserver/plane/app/urls/issue.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/intake/base.py
  apiserver/plane/app/views/issue/base.py
  apiserver/plane/app/views/issue/version.py
  apiserver/plane/app/views/view/base.py
  packages/constants/src/issue/common.ts
  packages/editor/src/core/hooks/use-editor.ts
  packages/editor/src/core/hooks/use-read-only-editor.ts
  packages/editor/src/core/types/editor.ts
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/types/src/description_version.d.ts
  packages/types/src/index.d.ts
  packages/types/src/issues/issue.d.ts
  web/core/components/core/description-versions/dropdown-item.tsx
  web/core/components/core/description-versions/dropdown.tsx
  web/core/components/core/description-versions/index.ts
  web/core/components/core/description-versions/modal.tsx
  web/core/components/core/description-versions/root.tsx
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/description-input.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/issue-detail/root.tsx
  web/core/components/issues/peek-overview/issue-detail.tsx
  web/core/components/issues/peek-overview/view.tsx
  web/core/services/inbox/index.ts
  web/core/services/inbox/intake-work_item_version.service.ts
  web/core/services/issue/index.ts
  web/core/services/issue/work_item_version.service.ts
Labels: ✨feature, 🌐frontend

#6877 [WEB-3728] fix: duplicate sequence ids being generated due to race condition
  apiserver/plane/bgtasks/issue_activities_task.py
  apiserver/plane/db/management/commands/fix_duplicate_sequences.py
  apiserver/plane/db/models/issue.py
  apiserver/plane/utils/uuid.py
  apiserver/plane/utils/valid_uuid.py
Labels: 🐛bug

#6871 [WEB-3737]chore: updated translations for estimates
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  web/core/components/estimates/create/modal.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/estimate.tsx
Labels: 🌟improvement

#6878 [WEB-3540] chore: icon color picker enhancements
  web/helpers/color.helper.ts
  web/helpers/theme.tsx
  web/package.json
  yarn.lock
Labels: 🌐frontend, 🧹chore

#6887 [WEB-3711] fix: relations delete issue
  web/core/components/issues/issue-detail-widgets/relations/content.tsx
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/relations/issue-list.tsx
  web/core/store/issue/issue-details/relation.store.ts
  web/core/store/issue/issue-details/root.store.ts
Labels: 🐛bug

#6885 [WEB-3794]chore: set project states to expand by default
  web/core/components/project-states/group-list.tsx
Labels: 🧹chore

#6888 [WEB-3766] fix: user avatar in description version history dropdown item
  web/core/components/core/description-versions/dropdown-item.tsx
  web/core/components/core/description-versions/modal.tsx
Labels: 🐛bug, 🌐frontend, regression

#6875 [WEB-3759] chore: header revamp for cycles, modules, pages and views
  packages/types/src/common.d.ts
  packages/ui/src/dropdowns/helper.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/layout.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/core/components/common/index.ts
  web/core/components/common/switcher-label.tsx
  web/core/components/cycles/analytics-sidebar/sidebar-header.tsx
  web/core/components/cycles/quick-actions.tsx
  web/core/components/modules/analytics-sidebar/root.tsx
  web/core/components/modules/quick-actions.tsx
  web/core/components/pages/list/root.tsx
  web/core/components/pages/pages-list-main-content.tsx
  web/core/components/views/quick-actions.tsx
  web/core/store/pages/project-page.store.ts
Labels: 🌐frontend, 🌟improvement

#6900 [WEB-3798]chore: updated language support to estimates
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/types/src/estimate.d.ts
  packages/ui/src/dropdown/common/options.tsx
  web/ce/constants/estimates.ts
  web/core/components/estimates/create/modal.tsx
  web/core/components/estimates/create/stage-one.tsx
  web/core/components/estimates/inputs/text-input.tsx
Labels: 🐛bug, 🧹chore

#6903 [WEB-3759]chore: updated module and pages detail header
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
Labels: 🐛bug, 🌟improvement

#6898 [WEB-3792, 3823] fix: intake form version history
  packages/constants/src/inbox.ts
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  packages/types/src/issues/activity/issue_activity.d.ts
  web/core/components/core/description-versions/dropdown-item.tsx
  web/core/components/core/description-versions/dropdown.tsx
  web/core/components/core/description-versions/modal.tsx
  web/core/components/core/description-versions/root.tsx
  web/core/components/inbox/content/issue-root.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/default.tsx
  web/core/components/issues/issue-detail/main-content.tsx
  web/core/components/issues/peek-overview/issue-detail.tsx
  web/core/services/inbox/inbox-issue.service.ts
  web/core/store/inbox/inbox-issue.store.ts
Labels: 🐛bug, 🌐frontend, 🌟improvement

#6905 [WEB-3829]fix: update workspace store action
  web/core/store/workspace/index.ts
Labels: 🐛bug, 🌐frontend

#6910 [WEB-3837] fix: mutation of child work item added via Cmd+K with parent context
  web/ce/components/command-palette/modals/issue-level.tsx
Labels: 🌐frontend, 🧹chore

#6906 [WEB-3826]fix: estimate dropdown formatting
  web/ce/components/issues/issue-details/issue-properties-activity/helper.tsx
  web/ce/components/issues/issue-details/issue-properties-activity/index.ts
  web/core/components/dropdowns/estimate.tsx
  web/core/components/estimates/create/stage-one.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/estimate.tsx
  web/core/components/issues/issue-detail/issue-activity/helper.tsx
  web/core/store/estimates/project-estimate.store.ts
  web/ee/components/issues/issue-details/issue-properties-activity/helper.tsx
Labels: 🐛bug

#6918 [WEB-3853] fix: untitled page name issue
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
Labels: 🐛bug

#6930 [WEB-3859] fix: work item links
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-detail-widgets/links/helper.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.tsx
Labels: 🐛bug, 🌐frontend

#6923 [WEB-3856]chore: refactor work item activity
  web/ce/components/issues/issue-details/additional-activity-root.tsx
  web/ce/components/issues/issue-details/index.ts
  web/ce/components/issues/issue-details/issue-properties-activity/helper.tsx
  web/ce/components/issues/issue-details/issue-properties-activity/index.ts
  web/core/components/issues/issue-detail/issue-activity/activity/actions/estimate.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/content.tsx
  web/ee/components/issues/issue-details/additional-activity-root.tsx
  web/ee/components/issues/issue-details/issue-properties-activity/helper.tsx
Labels: 🧹chore

#6922 [WEB-3855] feat: Turkish language support
  packages/i18n/src/constants/language.ts
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/store/index.ts
  packages/i18n/src/types/language.ts
Labels: 🌐frontend

#6933 [WEB-3868] fix: issue detail widget modals
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-detail-widgets/root.tsx
Labels: 🐛bug, 🌐frontend

#6932 [WEB-3870] fix: sidebar comment scroll
  web/core/components/comments/comments.tsx
Labels: 🐛bug, 🌐frontend

#6934 [WEB-3871] fix: sidebar label property
  web/core/components/issues/issue-detail/label/label-list-item.tsx
Labels: 🐛bug, 🌐frontend

#6940 [WEB-2561] chore: favicon icon updated #6938
  web/public/favicon/android-chrome-192x192.png
  web/public/favicon/android-chrome-512x512.png
  web/public/favicon/apple-touch-icon.png
  web/public/favicon/favicon-16x16.png
  web/public/favicon/favicon-32x32.png
  web/public/favicon/favicon.ico
Labels: 🌐frontend, 🧹chore

#6942 [WIKI-316] fix: list item overflow
  web/core/components/core/list/list-item.tsx
Labels: 🐛bug, 🌐frontend, 🧹chore

#6943 [WIKI-319] chore: remove bottom border when toolbar is hidden
  web/core/components/pages/editor/toolbar/mobile-root.tsx
  web/core/components/pages/editor/toolbar/root.tsx
  web/core/components/pages/editor/toolbar/toolbar.tsx
Labels: 🌐frontend, 🎨UI / UX, pages

#6935 [WEB-3872]chore: header switcher enhancements
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/cycles/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/modules/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/views/(detail)/[viewId]/header.tsx
  web/core/components/common/index.ts
  web/core/components/common/page-access-icon.tsx
Labels: 🌟improvement

#6944 [WEB-3892] chore: link item improvements
  packages/ui/src/index.ts
  packages/ui/src/link/block.tsx
  packages/ui/src/link/index.ts
  packages/utils/src/get-icon-for-link.ts
  web/core/components/home/widgets/links/link-detail.tsx
  web/core/components/issues/issue-detail/links/link-detail.tsx
  web/core/components/issues/issue-detail/links/link-item.tsx
  web/core/components/modules/links/list-item.tsx
Labels: 🌐frontend, 🧹chore

#6946 [WIKI-320] refactor: page header actions
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/[pageId]/page.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/pages/(detail)/header.tsx
  web/ce/components/pages/editor/ai/menu.tsx
  web/ce/components/pages/header/collaborators-list.tsx
  web/ce/components/pages/header/lock-control.tsx
  web/ce/components/pages/header/move-control.tsx
  web/core/components/pages/dropdowns/edit-information-popover.tsx
  web/core/components/pages/dropdowns/index.ts
  web/core/components/pages/editor/editor-body.tsx
  web/core/components/pages/editor/header/logo-picker.tsx
  web/core/components/pages/editor/page-root.tsx
  web/core/components/pages/editor/summary/content-browser.tsx
  web/core/components/pages/editor/title.tsx
  web/core/components/pages/editor/toolbar/extra-options.tsx
  web/core/components/pages/editor/toolbar/index.ts
  web/core/components/pages/editor/toolbar/info-popover.tsx
  web/core/components/pages/editor/toolbar/mobile-root.tsx
  web/core/components/pages/editor/toolbar/options-dropdown.tsx
  web/core/components/pages/editor/toolbar/root.tsx
  web/core/components/pages/editor/toolbar/toolbar.tsx
  web/core/components/pages/header/actions.tsx
  web/core/components/pages/header/archived-badge.tsx
  web/core/components/pages/header/copy-link-control.tsx
  web/core/components/pages/header/favorite-control.tsx
  web/core/components/pages/header/offline-badge.tsx
  web/core/hooks/use-page-operations.ts
  web/core/store/pages/base-page.ts
  web/core/store/pages/project-page.store.ts
  web/styles/globals.css
Labels: 🌐frontend, 🌟improvement, pages

#6950 [WEB-3920]fix: estimate activity
  web/core/components/issues/issue-detail/issue-activity/activity/activity-list.tsx
Labels: 🐛bug

#6957 [WEB-3923] fix: applied filters list
  web/core/components/issues/issue-layouts/filters/applied-filters/roots/project-root.tsx
Labels: 🐛bug, 🌐frontend

#6970 [WEB-3494] chore: platform ux copy changes
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  web/core/components/onboarding/tour/root.tsx
  web/core/components/onboarding/tour/sidebar.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
Labels: 🌐frontend, 🎨UI / UX

#6976 [WEB-3948] chore: recent work item improvement
  packages/types/src/home.d.ts
  web/ce/components/home/index.ts
  web/ce/components/home/peek-overviews.tsx
  web/core/components/home/root.tsx
  web/core/components/home/widgets/recents/issue.tsx
  web/ee/components/home/index.ts
Labels: 🌐frontend, 🧹chore

#6960 [WEB-3751] chore: work item state icon improvement
  apiserver/plane/api/views/project.py
  apiserver/plane/app/serializers/state.py
  apiserver/plane/app/views/project/base.py
  apiserver/plane/app/views/state/base.py
  apiserver/plane/app/views/workspace/state.py
  packages/constants/src/icon.ts
  packages/constants/src/index.ts
  packages/types/src/state.d.ts
  packages/ui/src/icons/state/backlog-group-icon.tsx
  packages/ui/src/icons/state/cancelled-group-icon.tsx
  packages/ui/src/icons/state/completed-group-icon.tsx
  packages/ui/src/icons/state/dashed-circle.tsx
  packages/ui/src/icons/state/helper.tsx
  packages/ui/src/icons/state/progress-circle.tsx
  packages/ui/src/icons/state/started-group-icon.tsx
  packages/ui/src/icons/state/state-group-icon.tsx
  packages/ui/src/icons/state/unstarted-group-icon.tsx
  packages/ui/src/icons/type.ts
  space/core/components/issues/filters/applied-filters/state.tsx
  space/core/components/issues/issue-layouts/utils.tsx
  web/ce/components/command-palette/actions/work-item-actions/change-state-list.tsx
  web/core/components/automation/auto-close-automation.tsx
  web/core/components/dropdowns/state.tsx
  web/core/components/home/widgets/recents/issue.tsx
  web/core/components/inbox/inbox-filter/applied-filters/state.tsx
  web/core/components/inbox/inbox-filter/filters/state.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/state-group.tsx
  web/core/components/issues/issue-layouts/filters/applied-filters/state.tsx
  web/core/components/issues/issue-layouts/filters/header/filters/state.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/components/project-states/group-item.tsx
  web/core/components/project-states/state-item-title.tsx
  web/core/store/state.store.ts
Labels: 🌐frontend, 🌟improvement

#6977 [WEB-3957] chore: IntakeIssues with iexact 'in-app' changed to 'IN_APP'
  apiserver/plane/db/migrations/0094_auto_20250425_0902.py
  apiserver/plane/db/models/user.py
Labels: ⚙️backend, 🔄migrations

#6967 [WEB-3838]feat:sub work items sorting
  apiserver/plane/app/views/issue/sub_issue.py
  packages/constants/src/issue/common.ts
  packages/constants/src/issue/filter.ts
  packages/types/src/issues/issue_sub_issues.d.ts
  packages/ui/src/icons/display-properties.tsx
  packages/ui/src/icons/index.ts
  web/core/components/issues/issue-detail-widgets/relations/helper.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/display-filters.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.ts
  web/core/components/issues/issue-detail-widgets/sub-issues/index.ts
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-item.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/properties.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title-actions.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/relations/issue-list-item.tsx
  web/core/components/issues/sub-issues/index.ts
  web/core/components/issues/sub-issues/issues-list.tsx
  web/core/components/issues/sub-issues/progressbar.tsx
  web/core/components/issues/sub-issues/properties.tsx
  web/core/components/issues/sub-issues/root.tsx
  web/core/services/issue/issue.service.ts
  web/core/store/issue/issue-details/sub_issues.store.ts
  web/core/store/issue/issue-details/sub_issues_filter.store.ts
Labels: ✨feature, 🧹chore
