Repository makeplane/plane, pull requests merged in 2025-10, with the labels that each got.

#7850 [WIKI-699] refactor: editor config
  apps/web/ce/hooks/editor/use-extended-editor-config.ts
  apps/web/core/hooks/editor/use-editor-config.ts
  apps/web/core/services/file.service.ts
  packages/editor/src/ce/types/config.ts
  packages/editor/src/ce/types/index.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/core/types/config.ts
Labels: ready to merge

#7885 [WIKI-569] regression: parser kit extensions mismatch
  packages/editor/src/core/extensions/core-without-props.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7886 [WIKI-621]regression: file handler types
  packages/editor/src/core/types/config.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7898 [WIKI-704] fix: hocuspocus error handling
  apps/api/plane/utils/content_validator.py
  apps/live/src/extensions/database.ts
  apps/live/src/services/page/core.service.ts
Labels: ready to merge

#7901 [WIKI-705] regression: mentions dropdown selection across editors
  packages/editor/src/core/extensions/mentions/utils.ts
  packages/editor/src/core/extensions/slash-commands/command-menu.tsx
Labels: 🐛bug, 🌐frontend, ✍️editor, requires approval

#7902 [WIKI-704] fix: disable exiting on unhandled rejection/exception
  apps/live/src/start.ts
Labels: ready to merge

#7879 [MOB-1221] dev: updated god mode ui
  apps/admin/app/(all)/(dashboard)/authentication/github/form.tsx
  apps/admin/app/(all)/(dashboard)/authentication/google/form.tsx
Labels: 🎨UI / UX

#7769 [WEB-4731] feat: add baseui input component to propel package
  packages/propel/package.json
  packages/propel/src/input/index.ts
  packages/propel/src/input/input.stories.tsx
  packages/propel/src/input/input.tsx
  packages/propel/tsdown.config.ts
  packages/ui/src/popovers/popover-menu.stories.tsx
Labels: ready to merge

#7919 [WIKI-710] [WIKI-717] fix: slash commands and mentions in comments
  packages/editor/src/core/extensions/mentions/utils.ts
  packages/editor/src/core/extensions/slash-commands/root.tsx
  packages/editor/src/core/helpers/floating-ui.ts
Labels: ready to merge

#7866 [WEB-5038] fix: cycle creation in external api endpoint
  apps/api/plane/api/serializers/cycle.py
  apps/api/plane/api/views/cycle.py
  apps/api/plane/tests/contract/api/test_cycles.py
Labels: ready to merge

#7897 [WEB-5068] fix: CustomMenu closeOnSelect behavior
  apps/web/core/components/cycles/quick-actions.tsx
  apps/web/core/components/issues/attachment/attachment-list-item.tsx
  apps/web/core/components/issues/issue-detail-widgets/relations/quick-action-button.tsx
  apps/web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-item.tsx
  apps/web/core/components/issues/issue-detail-widgets/sub-issues/quick-action-button.tsx
  apps/web/core/components/issues/issue-detail/links/link-item.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/all-issue.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/archived-issue.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/cycle-issue.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/issue-detail.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/module-issue.tsx
  apps/web/core/components/issues/issue-layouts/quick-action-dropdowns/project-issue.tsx
  apps/web/core/components/issues/workspace-draft/quick-action.tsx
  apps/web/core/components/modules/quick-actions.tsx
  apps/web/core/components/pages/dropdowns/actions.tsx
  apps/web/core/components/views/quick-actions.tsx
  apps/web/core/components/workspace/settings/invitations-list-item.tsx
  apps/web/core/components/workspace/views/default-view-quick-action.tsx
  apps/web/core/components/workspace/views/quick-action.tsx
  apps/web/core/components/workspace/views/view-list-item.tsx
Labels: ready to merge
