Repository makeplane/plane, pull requests merged in 2025-05, with the labels that each got.

#7007 [WEB-3996] fix: attachment icon rendering and added support for rar and zip icons
  apiserver/plane/settings/common.py
  web/core/components/icons/attachment/attachment-icon.tsx
  web/core/components/icons/attachment/index.ts
  web/core/components/icons/attachment/rar-file-icon.tsx
  web/core/components/icons/attachment/zip-file-icon.tsx
  web/core/components/issues/attachment/attachment-list-item.tsx
  web/public/attachment/rar-icon.png
  web/public/attachment/zip-icon.png
Labels: 🌐frontend, 🌟improvement, 🧹chore, ready_to_merge

#7020 [WEB-2508] fix: page favorite item title mutation
  web/core/hooks/use-favorite-item-details.tsx
Labels: 🐛bug, 🌐frontend, pages, ready_to_merge

#7018 [WEB-3906] fix: page table of content overlap with the page content
  packages/editor/src/styles/variables.css
Labels: 🐛bug, 🌐frontend, pages, ready_to_merge

#7024 [WEB-3877] fix: changed logic to calculate cycle duration
  apiserver/plane/utils/analytics_plot.py
Labels: ready_to_merge

#7021 [WEB-3955] chore: work item parent select modal params
  web/core/components/issues/issue-detail/parent-select.tsx
  web/core/components/issues/issue-modal/components/default-properties.tsx
Labels: 🌐frontend, 🧹chore, ready_to_merge

#7019 [WEB-4016] updated project and workitem form
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  web/core/components/project/project-feature-update.tsx
Labels: 🌐frontend, ready_to_merge

#7008 [WEB-3930] chore: change source in-app to IN_APP
  apiserver/plane/bgtasks/dummy_data_task.py
  apiserver/plane/space/views/intake.py
Labels: 🧹chore, ready_to_merge

#7006 [WEB-3942] chore: intake url pattern
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/intake/layout.tsx
  web/app/[workspaceSlug]/(projects)/projects/(detail)/[projectId]/intake/page.tsx
  web/core/components/inbox/content/inbox-issue-header.tsx
  web/core/components/inbox/content/root.tsx
  web/core/components/inbox/modals/create-modal/create-root.tsx
  web/core/components/inbox/sidebar/inbox-list-item.tsx
  web/core/components/inbox/sidebar/root.tsx
  web/core/components/workspace/sidebar/project-navigation.tsx
  web/next.config.js
Labels: 🌐frontend, 🌟improvement

#7036 [WEB-4052]fix: sub work item copy link
  web/core/components/issues/issue-detail-widgets/sub-issues/helper.ts
Labels: 🐛bug, ready_to_merge

#7025 [WEB-4057] chore: updated the logger for bgtasks
  apiserver/plane/bgtasks/analytic_plot_export.py
  apiserver/plane/bgtasks/email_notification_task.py
  apiserver/plane/bgtasks/forgot_password_task.py
  apiserver/plane/bgtasks/magic_link_code_task.py
  apiserver/plane/bgtasks/project_add_user_email_task.py
  apiserver/plane/bgtasks/project_invitation_task.py
  apiserver/plane/bgtasks/user_activation_email_task.py
  apiserver/plane/bgtasks/user_deactivation_email_task.py
  apiserver/plane/bgtasks/workspace_invitation_task.py
Labels: ready_to_merge

#6997 [WEB-4028]feat: sub work item filters and grouping
  packages/constants/src/issue/common.ts
  packages/constants/src/issue/filter.ts
  packages/types/src/issues/issue.d.ts
  packages/ui/src/collapsible/collapsible-button.tsx
  web/core/components/empty-state/section-empty-state-root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/content.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/display-filters.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/filters.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-group.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-item.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/properties.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title-actions.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/title.tsx
  web/core/components/issues/issue-layouts/utils.tsx
  web/core/store/issue/helpers/base-issues-utils.ts
  web/core/store/issue/helpers/base-issues.store.ts
  web/core/store/issue/issue-details/sub_issues.store.ts
  web/core/store/issue/issue-details/sub_issues_filter.store.ts
  web/helpers/date-time.helper.ts
Labels: ready_to_merge

#7011 [WEB-4002] fix: sidebar tab highlight
  web/core/components/workspace/sidebar/project-navigation.tsx
  web/core/store/issue/issue.store.ts
Labels: 🐛bug, 🌐frontend, 🧹chore, ready_to_merge

#7034 [WEB-4051] fix: comment editor font size
  web/core/components/comments/comment-card.tsx
  web/core/components/comments/comment-create.tsx
Labels: 🐛bug, 🌐frontend

#7002 [WEB-3987] chore: project export funtionality enhancement
  apiserver/plane/bgtasks/export_task.py
Labels: 🌟enhancement, ⚙️backend, ready_to_merge

#7047 [WEB-4074]fix: removed sub-work item filters at nested levels
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-group.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
Labels: 🐛bug, ready_to_merge

#7046 [WIKI-181] refactor: make file handling generic in editor
  packages/editor/src/ce/extensions/core/extensions.ts
  packages/editor/src/core/constants/config.ts
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/extensions/custom-image/custom-image.ts
  packages/editor/src/core/extensions/drop.ts
  packages/editor/src/core/extensions/drop.tsx
  packages/editor/src/core/extensions/extensions.tsx
  packages/editor/src/core/helpers/editor-commands.ts
  packages/editor/src/core/helpers/file.ts
  packages/editor/src/core/hooks/use-file-upload.ts
  packages/editor/src/core/plugins/drag-handle.ts
  packages/editor/src/core/plugins/image/constants.ts
  packages/editor/src/core/plugins/image/delete-image.ts
  packages/editor/src/core/plugins/image/index.ts
  packages/editor/src/core/plugins/image/utils/index.ts
  packages/utils/src/attachment.ts
  packages/utils/src/index.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor, ready_to_merge

#7033 [WEB-3523] feat: start of week preference
  packages/constants/src/profile.ts
  packages/types/src/users.d.ts
  packages/ui/src/calendar.tsx
  space/core/store/profile.store.ts
  web/app/profile/appearance/page.tsx
  web/core/components/dropdowns/date.tsx
  web/core/components/gantt-chart/chart/root.tsx
  web/core/components/gantt-chart/data/index.ts
  web/core/components/gantt-chart/views/week-view.ts
  web/core/components/issues/issue-layouts/calendar/week-days.tsx
  web/core/components/issues/issue-layouts/calendar/week-header.tsx
  web/core/components/profile/index.ts
  web/core/components/profile/start-of-week-preference.tsx
  web/core/constants/calendar.ts
  web/core/store/issue/issue_calendar_view.store.ts
  web/core/store/user/profile.store.ts
  web/helpers/calendar.helper.ts
Labels: ✨feature, 🌐frontend, ready_to_merge

#7029 [WEB-4054] chore: search-issues endpoint code refactoring
  apiserver/plane/app/views/search/issue.py
Labels: 🛠️refactor, ready_to_merge

#7048 [WEB-4051] regression: update font size of comment editor
  space/core/components/issues/peek-overview/comment/comment-detail-card.tsx
  web/core/components/comments/comment-card.tsx
  web/core/components/comments/comment-create.tsx
  web/core/components/workspace-notifications/sidebar/notification-card/content.tsx
Labels: 🐛bug, 🌐frontend, 🎨UI / UX

#7053 [WEB-4080]fix: set sub work items groups to expand by default
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/list-group.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
Labels: 🐛bug

#7072 [WEB-4041] chore: modal outside click behaviour
  web/core/components/cycles/modal.tsx
  web/core/components/inbox/modals/create-modal/modal.tsx
  web/core/components/issues/issue-modal/base.tsx
  web/core/components/modules/modal.tsx
  web/core/components/project/create-project-modal.tsx
  web/core/components/views/modal.tsx
  web/core/components/web-hooks/create-webhook-modal.tsx
Labels: ready_to_merge

#7065 [WEB-4104] fix: project loading state
  web/core/store/project/project.store.ts
Labels: ready_to_merge

#7062 [WEB-3866] fix: work item attachment activity
  web/core/components/core/activity.tsx
  web/core/components/issues/issue-detail/issue-activity/activity/actions/attachment.tsx
Labels: 🌐frontend, 🧹chore, ready_to_merge

#7060 [WEB-4056] fix: archived work item validation
  web/app/[workspaceSlug]/(projects)/browse/[workItem]/page.tsx
Labels: ready_to_merge

#7071 [WIKI-181] chore: editor extension storage utility code split
  packages/editor/src/ce/types/storage.ts
  packages/editor/src/core/extensions/custom-image/custom-image.ts
  packages/editor/src/core/extensions/custom-image/read-only-custom-image.ts
  packages/editor/src/core/helpers/get-extension-storage.ts
Labels: 🌐frontend, 🛠️refactor, ✍️editor

#7078 [WEB-4117] refactor: work item widgets code split
  packages/types/src/issues/issue.d.ts
  web/ce/components/issues/issue-detail-widgets/action-buttons.tsx
  web/ce/components/issues/issue-detail-widgets/additional-widgets.tsx
  web/ce/components/issues/issue-detail-widgets/collapsibles.tsx
  web/ce/components/issues/issue-detail-widgets/index.ts
  web/ce/components/issues/issue-detail-widgets/modals.tsx
  web/core/components/issues/issue-detail-widgets/action-buttons.tsx
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-collapsibles.tsx
  web/core/components/issues/issue-detail-widgets/issue-detail-widget-modals.tsx
  web/core/components/issues/issue-detail-widgets/root.tsx
  web/core/components/issues/issue-detail-widgets/sub-issues/root.tsx
  web/core/store/issue/issue-details/root.store.ts
Labels: 🌐frontend, 🛠️refactor

#7059 [WEB-3461] fix: profile activity rendering issue
  web/core/components/core/activity.tsx
  web/core/components/profile/activity/profile-activity-list.tsx
Labels: ready_to_merge

#7110 [WEB-3155]fix: email notification comments overflow
  apiserver/templates/emails/notifications/issue-updates.html
Labels: 🐛bug, ready_to_merge

#7106 [WEB-4159] feat: add 'restricted_entity' translation key across multiple languages
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
Labels: ready_to_merge

#7105 [WEB-4133] chore: optimised the analytics endpoints
  apiserver/plane/app/urls/analytic.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/analytic/advance.py
  apiserver/plane/app/views/analytic/project_analytics.py
  web/core/components/analytics-v2/overview/project-insights.tsx
  web/core/components/analytics-v2/total-insights.tsx
  web/core/components/analytics-v2/work-items/created-vs-resolved.tsx
  web/core/components/analytics-v2/work-items/priority-chart.tsx
  web/core/components/analytics-v2/work-items/workitems-insight-table.tsx
  web/core/services/analytics-v2.service.ts
Labels: ready_to_merge

#7104 [WEB-4146] fix: AI environment variables configuration in GodMode
  admin/app/ai/form.tsx
  apiserver/plane/license/api/views/instance.py
  packages/types/src/instance/ai.d.ts
  packages/types/src/instance/base.d.ts
  web/core/components/issues/issue-modal/components/description-editor.tsx
Labels: ready_to_merge

#7103 [WEB-4161] fix: eslint config for library config file
  packages/eslint-config/library.js
  packages/eslint-config/package.json
  yarn.lock
Labels: 🌐frontend, 🌟improvement, ready_to_merge

#7101 [WEB-4145] chore: added validation for project deletion
  apiserver/plane/app/views/project/base.py
Labels: ready_to_merge

#7099 [WEB-4144] fix: api logger to handle content decode errors
  apiserver/plane/middleware/logger.py
Labels: ready_to_merge

#7098 [WEB-4107] chore: redirect user to the newly created project view after creation
  web/core/components/views/modal.tsx
Labels: 🌐frontend, 🌟improvement, ready_to_merge

#7092 [WEB-4123]feat: language support for sub-work item empty states
  packages/i18n/src/locales/cs/translations.json
  packages/i18n/src/locales/de/translations.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/translations.json
  packages/i18n/src/locales/fr/translations.json
  packages/i18n/src/locales/id/translations.json
  packages/i18n/src/locales/it/translations.json
  packages/i18n/src/locales/ja/translations.json
  packages/i18n/src/locales/ko/translations.json
  packages/i18n/src/locales/pl/translations.json
  packages/i18n/src/locales/pt-BR/translations.json
  packages/i18n/src/locales/ro/translations.json
  packages/i18n/src/locales/ru/translations.json
  packages/i18n/src/locales/sk/translations.json
  packages/i18n/src/locales/tr-TR/translations.json
  packages/i18n/src/locales/ua/translations.json
  packages/i18n/src/locales/vi-VN/translations.json
  packages/i18n/src/locales/zh-CN/translations.json
  packages/i18n/src/locales/zh-TW/translations.json
  web/core/components/issues/issue-detail-widgets/sub-issues/issues-list/root.tsx
Labels: ready_to_merge

#7086 [WEB-4133] Fix analytics release bugs
  apiserver/plane/app/views/analytic/advance.py
  web/core/components/analytics-v2/insight-table/root.tsx
  web/core/components/analytics-v2/overview/active-projects.tsx
  web/core/components/analytics-v2/work-items/priority-chart.tsx
  web/core/components/analytics-v2/work-items/workitems-insight-table.tsx
Labels: ready_to_merge

#7080 [WEB-4115] fix: update issue count status query to handle null values
  apiserver/plane/space/views/issue.py
Labels: ready_to_merge

#7114 [WEB-2403] fix: alignment of project states in collapsed view
  web/core/components/issues/issue-layouts/kanban/default.tsx
  web/core/components/issues/issue-layouts/kanban/headers/group-by-card.tsx
Labels: 🌐frontend, 🌟improvement, ready to merge

#7115 [WEB-4166] chore: projects app sidebar accessibility
  packages/i18n/src/constants/language.ts
  packages/i18n/src/locales/cs/accessibility.json
  packages/i18n/src/locales/de/accessibility.json
  packages/i18n/src/locales/en/accessibility.json
  packages/i18n/src/locales/en/translations.json
  packages/i18n/src/locales/es/accessibility.json
  packages/i18n/src/locales/fr/accessibility.json
  packages/i18n/src/locales/id/accessibility.json
  packages/i18n/src/locales/it/accessibility.json
  packages/i18n/src/locales/ja/accessibility.json
  packages/i18n/src/locales/ko/accessibility.json
  packages/i18n/src/locales/pl/accessibility.json
  packages/i18n/src/locales/pt-BR/accessibility.json
  packages/i18n/src/locales/ro/accessibility.json
  packages/i18n/src/locales/ru/accessibility.json
  packages/i18n/src/locales/sk/accessibility.json
  packages/i18n/src/locales/tr-TR/accessibility.json
  packages/i18n/src/locales/ua/accessibility.json
  packages/i18n/src/locales/vi-VN/accessibility.json
  packages/i18n/src/locales/zh-CN/accessibility.json
  packages/i18n/src/locales/zh-TW/accessibility.json
  packages/i18n/src/store/index.ts
  packages/ui/src/avatar/avatar.tsx
  packages/ui/src/dropdowns/custom-menu.tsx
  packages/ui/src/dropdowns/helper.tsx
  web/app/(all)/[workspaceSlug]/(projects)/extended-sidebar.tsx
  web/ce/components/workspace/edition-badge.tsx
  web/ce/components/workspace/sidebar/app-search.tsx
  web/ce/components/workspace/sidebar/extended-sidebar-item.tsx
  web/ce/components/workspace/sidebar/sidebar-item.tsx
  web/ce/constants/sidebar-favorites.ts
  web/core/components/workspace/logo.tsx
  web/core/components/workspace/sidebar/dropdown.tsx
  web/core/components/workspace/sidebar/favorites/favorite-folder.tsx
  web/core/components/workspace/sidebar/favorites/favorite-items/common/favorite-item-quick-action.tsx
  web/core/components/workspace/sidebar/favorites/favorites-menu.tsx
  web/core/components/workspace/sidebar/favorites/new-fav-folder.tsx
  web/core/components/workspace/sidebar/help-section.tsx
  web/core/components/workspace/sidebar/projects-list-item.tsx
  web/core/components/workspace/sidebar/projects-list.tsx
  web/core/components/workspace/sidebar/quick-actions.tsx
  web/core/components/workspace/sidebar/sidebar-menu-items.tsx
  web/core/store/theme.store.ts
Labels: 🌐frontend, 🌟improvement, ready to merge

#7129 fix: Optimize image uploads in Editor
  package.json
  packages/editor/src/core/extensions/custom-image/components/image-block.tsx
  packages/editor/src/core/extensions/custom-image/components/image-node.tsx
  packages/editor/src/core/extensions/custom-image/components/image-uploader.tsx
  packages/editor/src/core/hooks/use-file-upload.ts
Labels: 🐛bug, 🌐frontend, ✍️editor, ready to merge

#7126 [WEB-3863] fix: links error handling
  web/core/store/issue/issue-details/link.store.ts
Labels: ready to merge

#7117 [WEB-4172] feat: Crawl work item links for title and favicon
  apiserver/plane/app/views/issue/link.py
  apiserver/plane/bgtasks/work_item_link_task.py
  web/core/components/issues/issue-detail/links/link-item.tsx
Labels: 🌟improvement, ready to merge

#7140 [WIKI-181] chore: asset check endpoint added
  apiserver/plane/app/urls/asset.py
  apiserver/plane/app/views/__init__.py
  apiserver/plane/app/views/asset/v2.py
  packages/editor/src/core/types/config.ts
  space/helpers/editor.helper.ts
  web/core/hooks/editor/use-editor-config.ts
  web/core/services/file.service.ts
Labels: 🌐frontend, ⚙️backend, ready to merge

#7144 [WIKI-399] fix: add favorite action to page header
  web/core/components/pages/header/actions.tsx
Labels: 🌐frontend, pages, ready to merge
